## @file
# Sources
#

SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

#
# Include sub-makefiles.
#
include $(PATH_SUB_CURRENT)/initdll/Makefile.kmk
include $(PATH_SUB_CURRENT)/libwrap/Makefile.kmk
include $(PATH_SUB_CURRENT)/guidlib/Makefile.kmk
include $(PATH_SUB_CURRENT)/kernel32/Makefile.kmk

include $(FILE_KBUILD_SUB_FOOTER)
