LANGUAGE LANG_KOREAN, SUBLANG_DEFAULT

SYSMENU MENU LOADONCALL MOVEABLE DISCARDABLE
{
 MENUITEM "º¹±Í(&R)", 61728
 MENUITEM "ÀÌµ¿(&M)", 61456
 MENUITEM "Å©±â º¯°æ(&S)", 61440
 MENUITEM "¾ÆÀÌÄÜ Ç¥½Ã(&N)", 61472
 MENUITEM "ÀüÃ¼ È­¸é Ç¥½Ã(&M)", 61488
 MENUITEM SEPARATOR
 MENUITEM "´Ý±â(&C)\tAlt-F4", 61536
 MENUITEM SEPARATOR
 MENUITEM "ÀÛ¾÷ ÀüÈ¯(&W) ...\tCtrl-Esc", 61744
 MENUITEM SEPARATOR
 MENUITEM "¿ÍÀÎ¿¡ °üÇÏ¿© ...", 61761
}

SYSMENUWARP MENU LOADONCALL MOVEABLE DISCARDABLE
{
 MENUITEM "º¹Í(&R)\tAlt-F5", 61728
 MENUITEM "ÀÌ¿(&M)\tAlt-F7", 61456
 MENUITEM "Åâ º¯°æ(&S)\tAlt-F8", 61440
 MENUITEM "ÆÀÌÄÜ ÇÃ(&N)\tAlt-F9", 61472
 MENUITEM "ÀüÃ È¸é ÇÃ(&M)\tAlt-F10", 61488
 MENUITEM SEPARATOR
 MENUITEM "Ýâ(&C)\tAlt-F4", 61536
 MENUITEM SEPARATOR
 MENUITEM "ÀÛ÷ ÀüÈ¯(&W) ...\tCtrl-Esc", 61744
 MENUITEM SEPARATOR
 MENUITEM "¿ÍÀÎ¿¡ °üÇÏ¿ ...", 61761
}

EDITMENU MENU LOADONCALL MOVEABLE DISCARDABLE
{
	POPUP ""
	BEGIN
		MENUITEM "½ÇÇà Ãë¼Ò(&U)", EM_UNDO
		MENUITEM SEPARATOR
		MENUITEM "Àß¶ó³»±â(&T)", WM_CUT
		MENUITEM "º¹»ç(&C)", WM_COPY
		MENUITEM "ºÙ¿©³Ö±â(&P)", WM_PASTE
		MENUITEM "»èÁ¦(&D)", WM_CLEAR
		MENUITEM SEPARATOR
		MENUITEM "ÀüÃ¼ ¼±ÅÃ(&A)", EM_SETSEL
	END
}

MSGBOX DIALOG 100, 80, 216, 168
STYLE DS_SYSMODAL | DS_MODALFRAME | WS_POPUP | WS_VISIBLE | WS_CAPTION | WS_SYSMENU
BEGIN
	ICON "", 1088, 8, 20, 16, 16, WS_CHILD | WS_VISIBLE
	LTEXT "", 100, 32, 4, 176, 48, WS_CHILD | WS_VISIBLE | WS_GROUP
	PUSHBUTTON "È®ÀÎ(&O)", 1, 16, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "Ãë¼Ò(&C)", 2, 64, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "Áß´Ü(&A)", 3, 112, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "Àç½Ãµµ(&R)", 4, 160, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "¹«½Ã(&I)", 5, 208, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "¿¹(&Y)", 6, 256, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "¾Æ´Ï¿À(&N)", 7, 304, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
END

