LANGUAGE LANG_KOREAN, SUBLANG_DEFAULT

SYSMENU MENU LOADONCALL MOVEABLE DISCARDABLE
{
 MENUITEM "∫π±Õ(&R)", 61728
 MENUITEM "¿Ãµø(&M)", 61456
 MENUITEM "≈©±‚ ∫Ø∞Ê(&S)", 61440
 MENUITEM "æ∆¿Ãƒ‹ «•Ω√(&N)", 61472
 MENUITEM "¿¸√º »≠∏È «•Ω√(&M)", 61488
 MENUITEM SEPARATOR
 MENUITEM "¥›±‚(&C)\tAlt-F4", 61536
 MENUITEM SEPARATOR
 MENUITEM "¿€æ˜ ¿¸»Ø(&W) ...\tCtrl-Esc", 61744
}

SYSMENUWARP MENU LOADONCALL MOVEABLE DISCARDABLE
{
 MENUITEM "∫πÕ(&R)\tAlt-F5", 61728
 MENUITEM "¿Ãø(&M)\tAlt-F7", 61456
 MENUITEM "≈‚ ∫Ø∞Ê(&S)\tAlt-F8", 61440
 MENUITEM "∆¿Ãƒ‹ «√(&N)\tAlt-F9", 61472
 MENUITEM "¿¸√ »∏È «√(&M)\tAlt-F10", 61488
 MENUITEM SEPARATOR
 MENUITEM "›‚(&C)\tAlt-F4", 61536
 MENUITEM SEPARATOR
 MENUITEM "¿€˜ ¿¸»Ø(&W) ...\tCtrl-Esc", 61744
}

EDITMENU MENU LOADONCALL MOVEABLE DISCARDABLE
{
	POPUP ""
	BEGIN
		MENUITEM "Ω««‡ √Îº“(&U)", EM_UNDO
		MENUITEM SEPARATOR
		MENUITEM "¿ﬂ∂Û≥ª±‚(&T)", WM_CUT
		MENUITEM "∫πªÁ(&C)", WM_COPY
		MENUITEM "∫Ÿø©≥÷±‚(&P)", WM_PASTE
		MENUITEM "ªË¡¶(&D)", WM_CLEAR
		MENUITEM SEPARATOR
		MENUITEM "¿¸√º º±≈√(&A)", EM_SETSEL
	END
}

MSGBOX DIALOG 100, 80, 216, 168
STYLE DS_SYSMODAL | DS_MODALFRAME | WS_POPUP | WS_VISIBLE | WS_CAPTION | WS_SYSMENU
BEGIN
	ICON "", 1088, 8, 20, 16, 16, WS_CHILD | WS_VISIBLE
	LTEXT "", 100, 32, 4, 176, 48, WS_CHILD | WS_VISIBLE | WS_GROUP
	PUSHBUTTON "»Æ¿Œ(&O)", 1, 16, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "√Îº“(&C)", 2, 64, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "¡ﬂ¥‹(&A)", 3, 112, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "¿ÁΩ√µµ(&R)", 4, 160, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "π´Ω√(&I)", 5, 208, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "øπ(&Y)", 6, 256, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
	PUSHBUTTON "æ∆¥œø¿(&N)", 7, 304, 56, 40, 14, WS_CHILD | WS_VISIBLE | WS_TABSTOP
END

