# $Id: Makefile,v 1.1 2002-06-19 00:37:28 bird Exp $

#
# Main script for the CUI part.
#

# Include the setup.mak
PATH_ROOT = ..\..
!include $(PATH_ROOT)\$(BUILD_SETUP_MAK)

# Target Config
TARGET_MODE = EMPTY

# Subdirs to process.
POSTMAKEFILES = \
    doxygen.mak \

# Include the process rulez.
!include $(MAKE_INCLUDE_PROCESS)


