# $Id: makefile,v 1.8 2000-12-03 00:26:11 bird Exp $

#
# Odin32 API
#
#       main glide makefile
#


#
# Common tools macros. (MAKE_CMD)
#
!include ../../../makefile.inc


# Dummy all rule - nmake without target will make all targets of the first rule.
all_: all


# All, Lib, Clean and Dep rules.
$(COMMONRULES):
    $(DODIRS) "cvg sst1" $(MAKE_CMD) $@

