FX_EXE = 1

include "\glide\3dfxos2.mak"

OBJS =	3DF.OBJ         CLAMP.OBJ       DEQUANT.OBJ     DIFFUSE.OBJ     GLDUTIL.OBJ \
	MIPMAP.OBJ      NCC.OBJ         NCCNNET.OBJ     PAL256.OBJ      PPM.OBJ \
	QUANTIZE.OBJ    READ.OBJ        RESAMPLE.OBJ    RGT.OBJ         TEXUSLIB.OBJ \
	TGA.OBJ         UTIL.OBJ        VIEW.OBJ        WRITE.OBJ

all: $(OBJS)

clean:
        del *.obj
        del *.dll
        del *.lib
