include "\glide\3dfxos2.mak"

OBJS =	CPUDTECT.OBJ    DDGUMP.OBJ      DIGLIDE.OBJ     DIGUTEX.OBJ     DISST.OBJ \
	DITEX.OBJ       FXBLDNO.OBJ     G3DF.OBJ        GAA.OBJ         GBANNER.OBJ \
	GDRAW.OBJ       GERROR.OBJ      GGLIDE.OBJ      GLFB.OBJ        GMOVIE.OBJ \
	GPCI.OBJ        GSPLASH.OBJ     GSST.OBJ        GTEX.OBJ        GTEXDL.OBJ \
	GU.OBJ          GUCLIP.OBJ      GUMP.OBJ        GUTEX.OBJ       GXDRAW.OBJ \
	P6FENCE.OBJ     FIFO.OBJ

all: $(OBJS)

clean:
        del *.obj

