<?php

require "cvs.php3";
require "stilovi.php3";

/*
 * Parse argument(s)
 */
if (isset($sFile))
{
    $sOperation = "viewfile";
    if (!isset($sRevision))
        $sRevision = "";
    $sTitle = substr($sFile, 0, -2);
}
else if (isset($sDir))
{
    $sOperation = "viewdir";
    $sTitle = ($sDir == "." || $sDir =="") ? "root" : $sDir;
    $iSortColumn = (!isset($iSortColumn) || $iSortColumn == "")  ?
                        0 : $iSortColumn = @(int)$iSortColumn;
}
else
{   /* default action: */
    $sOperation = "viewdir";
    $sDir = ".";
    $sTitle = "root";
    $iSortColumn = 0;
}


/*
 * Odin32 look.
 */
require "01-PreTitle.php3";
echo "Odin32 CVS: ", $sTitle;
require "02-PostTitle.php3";

require "03-MainTableBeg.php3";
require "04-ColumnOne.php3";

require "05-ColumnTwoHeader.php3";
echo "Odin32 CVS: ", $sTitle;
require "06-ColumnTwoHeader2.php3";


/*
 *
 */

/*
 * Do the requested operation...
 */
switch ($sOperation)
{
    case "viewfile":
    {
        $obj = new CVSFile($sFile, 0);
        if ($obj && $obj->fOk)
        {
            $obj->PrintRevision($sRevision);
            //$obj->DumpInfo();
        }
        else
        { //error - complain
            echo "<p><i>An error occured while creating file object for $sFile.</i>";
            if ($obj)
                echo "<br><i>".$obj->sError."<br>";
        }
        break;
    }

    case "viewdir":
    {
        ListDirectory($sDir, $iSortColumn);
        break;
    }

    default:
        echo "IPE";
}


/*
 * Finish off the column
 */
require "07-ColumnTwoFooter.php3";

if (1)
{
    require "08-News.php3";
    /*
    require "09-ContentsTitle.php3";

    TocBeg();
    TocEnd();

    */
    require "10-EndOfContent.php3";
    require "11-NetlabsContact.php3";

    $Kada=date ("j M Y", filemtime(__file__));
    require "12-OdinBanner.php3";
}
else
{
    echo "</td>\n</tr></table>\n";
    echo "</td>\n</tr></table>\n";
}
require "13-Closing.php3";


?>
