<?php
$Title ="The Odin32 API Database";

require "stilovi.php3";
require "Odin32DBHelpers.php3";

/*
 * Connect to database
 */
$db = mysql_connect("127.0.0.1", "root", "");
$rc = mysql_select_db("odin32", $db);


/*
 * Global Variables
 */
$iRefcode       = -1;                   /* Reference number. (< 0 is all members in the category) */
$sCategory      = "";                   /* Category name for internal use (equal to table name). */
$sCategoryName  = "";                   /* Category name for presentation. */
$fNoData        = 0;                    /* Flag which is set if refcode don't give matches in the DB. */


/*
 * What are we up to? We'll parse the input parameter (if any) to find out.
 */
if (isset($dllrefcode))
{   /* DLLs by refcode */
    $sCategory      = "dll";
    $sCategoryName  = "Dll";
    if ($dllrefcode != "")
        $iRefcode = (int)$dllrefcode;
    $fFunctions = (isset($fFunctions)   && $fFunctions  != '0');
    $fFiles     = (isset($fFiles)       && $fFiles      != '0');
    $fAPIGroups = (isset($fAPIGroups)   && $fAPIGroups  != '0');
    $fAuthors   = (isset($fAuthors)     && $fAuthors    != '0');
    $fSortByState=(isset($fSortByState) && $fSortByState!= '0');
}
else if (isset($filerefcode))
{   /* Files by refcode */
    $sCategory      = "file";
    $sCategoryName  = "File";
    if ($filerefcode != "")
        $iRefcode = (int)$filerefcode;
    $fFunctions = (isset($fFunctions)   && $fFunctions  != '0');
    $fAPIGroups = (isset($fAPIGroups)   && $fAPIGroups  != '0');
    $fAuthors   = (isset($fAuthors)     && $fAuthors    != '0');
    $fSortByState=(isset($fSortByState) && $fSortByState!= '0');
}
else if (isset($functionrefcode))
{   /* Functions by refcode */
    $sCategory      = "function";
    $sCategoryName  = "Function";
    if ($functionrefcode != "")
        $iRefcode = (int)$functionrefcode;
}
else if (isset($apigrouprefcode))
{   /* Api Group by refcode */
    $sCategory      = "apigroup";
    $sCategoryName  = "API Group";
    if ($apigrouprefcode != "")
        $iRefcode = (int)$apigrouprefcode;
    $fFunctions = (isset($fFunctions)   && $fFunctions  != '0');
    $fFiles     = (isset($fFiles)       && $fFiles      != '0');
    $fAuthors   = (isset($fAuthors)     && $fAuthors    != '0');
    $fSortByState=(isset($fSortByState) && $fSortByState!= '0');
}
else if (isset($authorrefcode))
{   /* Author by refcode */
    $sCategory      = "author";
    $sCategoryName  = "Author";
    if ($authorrefcode != "")
        $iRefcode = (int)$authorrefcode;
    $fDlls      = (isset($fDlls)        && $fDlls  != '0');
    $fFunctions = (isset($fFunctions)   && $fFunctions  != '0');
    $fFiles     = (isset($fFiles)       && $fFiles      != '0');
    $fAPIGroups = (isset($fAPIGroups)   && $fAPIGroups  != '0');
    $fSortByState=(isset($fSortByState) && $fSortByState!= '0');
    if (!(isset($authordll) && $authordll != "" && @(int)$authordll >= 0))
        $authordll = -1;
} /* else: initial page */


/*
 * Get name of the item we're to display data on.
 */
if ($iRefcode < 0)
    $sName = "All"; //FIXME
else
{
    $sql = sprintf("SELECT name FROM %s WHERE refcode = %d",
                   $sCategory, $iRefcode);
    $result = mysql_query($sql, $db);
    if (@mysql_num_rows($result) > 0 &&
        ($aName = @mysql_fetch_row($result))
        )
    {
        $sName = $aName[0];
    }
    else
    {
        $fNoData = 1;
        $sName = "!Invalid Refcode!";
    }
    @mysql_free_result($result);
}

require "01-PreTitle.php3";
echo $Title." - ".$sCategoryName.": ".$sName;
require "02-PostTitle.php3";

require "03-MainTableBeg.php3";
require "04-ColumnOne.php3";

require "05-ColumnTwoHeader.php3";
echo $Title."<br>".$sCategoryName.": ".$sName;
require "06-ColumnTwoHeader2.php3";


/*
 * Init the contents array.
 */
$aContent = array();


TekstBeg();
if (!$fNoData)
{
    switch ($sCategory)
    {
        case "dll":
            {
            Odin32DBDllInfo($aContent, $db, $iRefcode, $fFunctions, $fFiles, $fAPIGroups, $fAuthors, $fSortByState);
            break;
            }

        case "file":
            {
            Odin32DBFileInfo($aContent, $db, $iRefcode, $fFunctions, $fAPIGroups, $fAuthors, $fSortByState);
            break;
            }

        case "function":
            {
            Odin32DBFunctionInfo($aContent, $db, $iRefcode);
            break;
            }

        case "apigroup":
            {
            Odin32DBAPIGroupInfo(&$aContent, $db, $iRefcode, $fFunctions, $fFiles, $fAuthors, $fSortByState);
            break;
            }

        case "author":
            {
            Odin32DBAuthorInfo($aContent, $db, $iRefcode, $fDlls, $fFunctions, $fFiles, $fAPIGroups, $fSortByState, $authordll);
            break;
            }

        default:
            echo "!IPE!"; //FIXME
    }
}
else
    echo "Sorry, but there is not data available!";

TekstEnd();

require "07-ColumnTwoFooter.php3";
require "08-News.php3";
require "09-ContentsTitle.php3";

DBWriteContents($aContent);

require "10-EndOfContent.php3";
require "11-NetlabsContact.php3";

$Kada=date ("j M Y", filemtime(__file__));
require "12-OdinBanner.php3";

require "13-Closing.php3";
?>

