# $Id: Makefile,v 1.1 2002-04-16 00:07:00 bird Exp $
#
# GetDriveType.exe makefile.
#
# Copyright (c) 2002 knut st. osmundsen (bird@anduin.net)
#
# Project Odin Software License can be found in LICENSE.TXT
#
#


#
# Pre Setup Config.
#


#
# Include Setup.
#
PATH_ROOT=..\..\..
!include $(PATH_ROOT)\make\setup.mak

#
# Post Setup Config
#
TARGET_NAME = kernel32_testcase_empty
TARGET_MODE = EMPTY


#
# Makefiles
#
POSTMAKEFILES = \
    GetDriveType.mak



#
# Include Processing Rules.
#
!include $(MAKE_INCLUDE_PROCESS)

