# $Id: Makefile,v 1.2 2002-06-19 02:14:49 bird Exp $

#
# Main script for the CUI part.
#

#
# TODO:
#  - Run all testcases nomatter who's failing.
#  - Do proper logging of the results.
#

# Include the setup.mak
PATH_ROOT = ..\..
!include $(PATH_ROOT)\$(BUILD_SETUP_MAK)

# Target Config
TARGET_MODE = EMPTY

# Subdirs to process.
POSTMAKEFILES = \
    doxygen.mak \

# Include the process rulez.
!include $(MAKE_INCLUDE_PROCESS)


