# $Id: Makefile,v 1.1 2002-05-16 11:36:59 bird Exp $

#
# Stub file in case someone wanna do the testcases
# by including make in the big make process.
#


#
# Load the build setup
#
PATH_ROOT=..
!include $(PATH_ROOT)\make\setup.mak

#
# Target config.
#
TARGET_MODE = EMPTY


#
# Load the processing rules
#
!include $(MAKE_INCLUDE_PROCESS)

