/* $Id: SymDB.c,v 1.2 2000-02-27 12:37:52 bird Exp $
*
* Autogenerated kernel symbol database.
*
* Copyright (c) 2000 knut st. osmundsen (knut.stange.osmundsen@pmsc.no)
*
* Project Odin Software License can be found in LICENSE.TXT
*
*/
#define INCL_NOPMAPI
#define INCL_NOBASEAPI
#include <os2.h>
#include "probkrnl.h"

KRNLDBENTRY aKrnlSymDB[] =
{
    { /* 14039RS.SYM */
        14039, 'R', TRUE, 15,
        {
            {14, 0x00008390}, /* _ldrRead */
            {14, 0x00061530}, /* _ldrOpen */
            {14, 0x000628d0}, /* _ldrClose */
            {14, 0x000629b5}, /* _LDRQAppType */
            {14, 0x0005eae0}, /* _ldrEnum32bitRelRecs */
            {14, 0x00005268}, /* _IOSftOpen */
            {14, 0x00005b61}, /* _IOSftClose */
            {14, 0x00005c5c}, /* _IOSftTransPath */
            {14, 0x00005740}, /* _IOSftReadAt */
            {14, 0x00005747}, /* _IOSftWriteAt */
            {14, 0x00005d86}, /* _SftFileSize */
            {14, 0x0005cec0}, /* _VMAllocMem */
            {14, 0x0004ce4b}, /* _VMGetOwner */
            {14, 0x0006ca7e}, /* g_tkExecPgm */
            {11, 0x00009e10}, /* f_FuStrLenZ */
            {11, 0x00009d90}, /* f_FuStrLen */
            {11, 0x00009fb9}, /* f_FuBuff */
        }
    },
    { /* 14039RU.SYM */
        14039, 'R', FALSE, 14,
        {
            {13, 0x000070e4}, /* _ldrRead */
            {13, 0x000577d0}, /* _ldrOpen */
            {13, 0x00058aa0}, /* _ldrClose */
            {13, 0x00058b85}, /* _LDRQAppType */
            {13, 0x00055060}, /* _ldrEnum32bitRelRecs */
            {13, 0x00004598}, /* _IOSftOpen */
            {13, 0x00004df4}, /* _IOSftClose */
            {13, 0x00004ecd}, /* _IOSftTransPath */
            {13, 0x00004a2c}, /* _IOSftReadAt */
            {13, 0x00004a33}, /* _IOSftWriteAt */
            {13, 0x00004fe6}, /* _SftFileSize */
            {13, 0x00053620}, /* _VMAllocMem */
            {13, 0x00042dcb}, /* _VMGetOwner */
            {13, 0x00061dde}, /* g_tkExecPgm */
            { 9, 0x0000e640}, /* f_FuStrLenZ */
            { 9, 0x0000e5f6}, /* f_FuStrLen */
            { 9, 0x0000e738}, /* f_FuBuff */
        }
    },
    { /* 8255RS.SYM */
        8255, 'R', TRUE, 15,
        {
            {14, 0x0000b434}, /* _ldrRead */
            {14, 0x00045838}, /* _ldrOpen */
            {14, 0x00046234}, /* _ldrClose */
            {14, 0x00046284}, /* _LDRQAppType */
            {14, 0x00043d70}, /* _ldrEnum32bitRelRecs */
            {14, 0x000049d4}, /* _IOSftOpen */
            {14, 0x00004f52}, /* _IOSftClose */
            {14, 0x00005009}, /* _IOSftTransPath */
            {14, 0x00004c9a}, /* _IOSftReadAt */
            {14, 0x00004e63}, /* _IOSftWriteAt */
            {14, 0x00005133}, /* _SftFileSize */
            {14, 0x00041964}, /* _VMAllocMem */
            {14, 0x00026624}, /* _VMGetOwner */
            {14, 0x0004f84e}, /* g_tkExecPgm */
            {11, 0x0000a168}, /* f_FuStrLenZ */
            {11, 0x0000a0e8}, /* f_FuStrLen */
            {11, 0x0000a311}, /* f_FuBuff */
        }
    },
    { /* 8255RU.SYM */
        8255, 'R', FALSE, 13,
        {
            {12, 0x0000932c}, /* _ldrRead */
            {12, 0x0003a00c}, /* _ldrOpen */
            {12, 0x0003a890}, /* _ldrClose */
            {12, 0x0003a8e0}, /* _LDRQAppType */
            {12, 0x0003822c}, /* _ldrEnum32bitRelRecs */
            {12, 0x000034a0}, /* _IOSftOpen */
            {12, 0x0000390c}, /* _IOSftClose */
            {12, 0x000039a1}, /* _IOSftTransPath */
            {12, 0x0000375a}, /* _IOSftReadAt */
            {12, 0x00003761}, /* _IOSftWriteAt */
            {12, 0x00003aba}, /* _SftFileSize */
            {12, 0x00036588}, /* _VMAllocMem */
            {12, 0x0001ccde}, /* _VMGetOwner */
            {12, 0x0004265e}, /* g_tkExecPgm */
            { 9, 0x0000e124}, /* f_FuStrLenZ */
            { 9, 0x0000e0da}, /* f_FuStrLen */
            { 9, 0x0000e218}, /* f_FuBuff */
        }
    },
    { /* 8256RS.SYM */
        8256, 'R', TRUE, 15,
        {
            {14, 0x0000b434}, /* _ldrRead */
            {14, 0x00045a50}, /* _ldrOpen */
            {14, 0x0004644c}, /* _ldrClose */
            {14, 0x0004649c}, /* _LDRQAppType */
            {14, 0x00043f84}, /* _ldrEnum32bitRelRecs */
            {14, 0x000049d4}, /* _IOSftOpen */
            {14, 0x00004f52}, /* _IOSftClose */
            {14, 0x00005009}, /* _IOSftTransPath */
            {14, 0x00004c9a}, /* _IOSftReadAt */
            {14, 0x00004e63}, /* _IOSftWriteAt */
            {14, 0x00005133}, /* _SftFileSize */
            {14, 0x00041b78}, /* _VMAllocMem */
            {14, 0x00026800}, /* _VMGetOwner */
            {14, 0x0004fb4a}, /* g_tkExecPgm */
            {11, 0x0000a168}, /* f_FuStrLenZ */
            {11, 0x0000a0e8}, /* f_FuStrLen */
            {11, 0x0000a311}, /* f_FuBuff */
        }
    },
    { /* 8256RU.SYM */
        8256, 'R', FALSE, 13,
        {
            {12, 0x0000932c}, /* _ldrRead */
            {12, 0x00039ff8}, /* _ldrOpen */
            {12, 0x0003a87c}, /* _ldrClose */
            {12, 0x0003a8cc}, /* _LDRQAppType */
            {12, 0x00038218}, /* _ldrEnum32bitRelRecs */
            {12, 0x000034a0}, /* _IOSftOpen */
            {12, 0x0000390c}, /* _IOSftClose */
            {12, 0x000039a1}, /* _IOSftTransPath */
            {12, 0x0000375a}, /* _IOSftReadAt */
            {12, 0x00003761}, /* _IOSftWriteAt */
            {12, 0x00003aba}, /* _SftFileSize */
            {12, 0x00036574}, /* _VMAllocMem */
            {12, 0x0001ccde}, /* _VMGetOwner */
            {12, 0x00042632}, /* g_tkExecPgm */
            { 9, 0x0000e124}, /* f_FuStrLenZ */
            { 9, 0x0000e0da}, /* f_FuStrLen */
            { 9, 0x0000e218}, /* f_FuBuff */
        }
    },
    { /* 8257RS.SYM */
        8257, 'R', TRUE, 15,
        {
            {14, 0x0000b434}, /* _ldrRead */
            {14, 0x000459a0}, /* _ldrOpen */
            {14, 0x00046398}, /* _ldrClose */
            {14, 0x000463e8}, /* _LDRQAppType */
            {14, 0x00043ed4}, /* _ldrEnum32bitRelRecs */
            {14, 0x000049d4}, /* _IOSftOpen */
            {14, 0x00004f52}, /* _IOSftClose */
            {14, 0x00005009}, /* _IOSftTransPath */
            {14, 0x00004c9a}, /* _IOSftReadAt */
            {14, 0x00004e63}, /* _IOSftWriteAt */
            {14, 0x00005133}, /* _SftFileSize */
            {14, 0x00041ac4}, /* _VMAllocMem */
            {14, 0x000266f8}, /* _VMGetOwner */
            {14, 0x0004fa96}, /* g_tkExecPgm */
            {11, 0x0000a168}, /* f_FuStrLenZ */
            {11, 0x0000a0e8}, /* f_FuStrLen */
            {11, 0x0000a311}, /* f_FuBuff */
        }
    },
    { /* 8257RU.SYM */
        8257, 'R', FALSE, 13,
        {
            {12, 0x0000932c}, /* _ldrRead */
            {12, 0x00039ff0}, /* _ldrOpen */
            {12, 0x0003a874}, /* _ldrClose */
            {12, 0x0003a8c4}, /* _LDRQAppType */
            {12, 0x00038210}, /* _ldrEnum32bitRelRecs */
            {12, 0x000034a0}, /* _IOSftOpen */
            {12, 0x0000390c}, /* _IOSftClose */
            {12, 0x000039a1}, /* _IOSftTransPath */
            {12, 0x0000375a}, /* _IOSftReadAt */
            {12, 0x00003761}, /* _IOSftWriteAt */
            {12, 0x00003aba}, /* _SftFileSize */
            {12, 0x00036564}, /* _VMAllocMem */
            {12, 0x0001ccd6}, /* _VMGetOwner */
            {12, 0x0004263e}, /* g_tkExecPgm */
            { 9, 0x0000e124}, /* f_FuStrLenZ */
            { 9, 0x0000e0da}, /* f_FuStrLen */
            { 9, 0x0000e218}, /* f_FuBuff */
        }
    },
    { /* 8258RS.SYM */
        8258, 'R', TRUE, 15,
        {
            {14, 0x0000bdd0}, /* _ldrRead */
            {14, 0x000464bc}, /* _ldrOpen */
            {14, 0x00046eb8}, /* _ldrClose */
            {14, 0x00046f08}, /* _LDRQAppType */
            {14, 0x000449b4}, /* _ldrEnum32bitRelRecs */
            {14, 0x0000526c}, /* _IOSftOpen */
            {14, 0x000057ea}, /* _IOSftClose */
            {14, 0x000058a1}, /* _IOSftTransPath */
            {14, 0x00005532}, /* _IOSftReadAt */
            {14, 0x000056fb}, /* _IOSftWriteAt */
            {14, 0x000059cb}, /* _SftFileSize */
            {14, 0x000425a4}, /* _VMAllocMem */
            {14, 0x000271aa}, /* _VMGetOwner */
            {14, 0x0005065e}, /* g_tkExecPgm */
            {11, 0x00009fdc}, /* f_FuStrLenZ */
            {11, 0x00009f5c}, /* f_FuStrLen */
            {11, 0x0000a185}, /* f_FuBuff */
        }
    },
    { /* 8258RU.SYM */
        8258, 'R', FALSE, 14,
        {
            {13, 0x000091a4}, /* _ldrRead */
            {13, 0x0003a580}, /* _ldrOpen */
            {13, 0x0003ae08}, /* _ldrClose */
            {13, 0x0003ae58}, /* _LDRQAppType */
            {13, 0x0003877c}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039a4}, /* _IOSftOpen */
            {13, 0x00003e10}, /* _IOSftClose */
            {13, 0x00003ea5}, /* _IOSftTransPath */
            {13, 0x00003c5e}, /* _IOSftReadAt */
            {13, 0x00003c65}, /* _IOSftWriteAt */
            {13, 0x00003fbe}, /* _SftFileSize */
            {13, 0x00036a48}, /* _VMAllocMem */
            {13, 0x0001d16a}, /* _VMGetOwner */
            {13, 0x00042d56}, /* g_tkExecPgm */
            { 9, 0x0000d794}, /* f_FuStrLenZ */
            { 9, 0x0000d74a}, /* f_FuStrLen */
            { 9, 0x0000d888}, /* f_FuBuff */
        }
    },
    { /* 8259RS.SYM */
        8259, 'R', TRUE, 15,
        {
            {14, 0x0000bdd0}, /* _ldrRead */
            {14, 0x000465c0}, /* _ldrOpen */
            {14, 0x00046fbc}, /* _ldrClose */
            {14, 0x0004700c}, /* _LDRQAppType */
            {14, 0x00044ab8}, /* _ldrEnum32bitRelRecs */
            {14, 0x0000526c}, /* _IOSftOpen */
            {14, 0x000057ea}, /* _IOSftClose */
            {14, 0x000058a1}, /* _IOSftTransPath */
            {14, 0x00005532}, /* _IOSftReadAt */
            {14, 0x000056fb}, /* _IOSftWriteAt */
            {14, 0x000059cb}, /* _SftFileSize */
            {14, 0x000426a8}, /* _VMAllocMem */
            {14, 0x000272ae}, /* _VMGetOwner */
            {14, 0x00050812}, /* g_tkExecPgm */
            {11, 0x00009fdc}, /* f_FuStrLenZ */
            {11, 0x00009f5c}, /* f_FuStrLen */
            {11, 0x0000a185}, /* f_FuBuff */
        }
    },
    { /* 8259RU.SYM */
        8259, 'R', FALSE, 14,
        {
            {13, 0x00009234}, /* _ldrRead */
            {13, 0x0003a608}, /* _ldrOpen */
            {13, 0x0003ae90}, /* _ldrClose */
            {13, 0x0003aee0}, /* _LDRQAppType */
            {13, 0x00038804}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039a4}, /* _IOSftOpen */
            {13, 0x00003e10}, /* _IOSftClose */
            {13, 0x00003ea5}, /* _IOSftTransPath */
            {13, 0x00003c5e}, /* _IOSftReadAt */
            {13, 0x00003c65}, /* _IOSftWriteAt */
            {13, 0x00003fbe}, /* _SftFileSize */
            {13, 0x00036ad0}, /* _VMAllocMem */
            {13, 0x0001d2de}, /* _VMGetOwner */
            {13, 0x00042de2}, /* g_tkExecPgm */
            { 9, 0x0000d7a4}, /* f_FuStrLenZ */
            { 9, 0x0000d75a}, /* f_FuStrLen */
            { 9, 0x0000d898}, /* f_FuBuff */
        }
    },
    { /* 8260RS.SYM */
        8260, 'R', TRUE, 15,
        {
            {14, 0x0000bdec}, /* _ldrRead */
            {14, 0x00046858}, /* _ldrOpen */
            {14, 0x00047254}, /* _ldrClose */
            {14, 0x000472a4}, /* _LDRQAppType */
            {14, 0x00044d50}, /* _ldrEnum32bitRelRecs */
            {14, 0x00005278}, /* _IOSftOpen */
            {14, 0x000057f6}, /* _IOSftClose */
            {14, 0x000058ad}, /* _IOSftTransPath */
            {14, 0x0000553e}, /* _IOSftReadAt */
            {14, 0x00005707}, /* _IOSftWriteAt */
            {14, 0x000059d7}, /* _SftFileSize */
            {14, 0x00042940}, /* _VMAllocMem */
            {14, 0x0002743a}, /* _VMGetOwner */
            {14, 0x00050b4a}, /* g_tkExecPgm */
            {11, 0x00009f7c}, /* f_FuStrLenZ */
            {11, 0x00009efc}, /* f_FuStrLen */
            {11, 0x0000a125}, /* f_FuBuff */
        }
    },
    { /* 8260RU.SYM */
        8260, 'R', FALSE, 14,
        {
            {13, 0x00009244}, /* _ldrRead */
            {13, 0x0003a618}, /* _ldrOpen */
            {13, 0x0003aea0}, /* _ldrClose */
            {13, 0x0003aef0}, /* _LDRQAppType */
            {13, 0x00038814}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039a4}, /* _IOSftOpen */
            {13, 0x00003e10}, /* _IOSftClose */
            {13, 0x00003ea5}, /* _IOSftTransPath */
            {13, 0x00003c5e}, /* _IOSftReadAt */
            {13, 0x00003c65}, /* _IOSftWriteAt */
            {13, 0x00003fbe}, /* _SftFileSize */
            {13, 0x00036ae0}, /* _VMAllocMem */
            {13, 0x0001d2ee}, /* _VMGetOwner */
            {13, 0x00042e8a}, /* g_tkExecPgm */
            { 9, 0x0000d7a4}, /* f_FuStrLenZ */
            { 9, 0x0000d75a}, /* f_FuStrLen */
            { 9, 0x0000d898}, /* f_FuBuff */
        }
    },
    { /* 8261RS.SYM */
        8261, 'R', TRUE, 15,
        {
            {14, 0x0000c1dc}, /* _ldrRead */
            {14, 0x0004a46c}, /* _ldrOpen */
            {14, 0x0004ae94}, /* _ldrClose */
            {14, 0x0004aee4}, /* _LDRQAppType */
            {14, 0x0004895c}, /* _ldrEnum32bitRelRecs */
            {14, 0x000053d8}, /* _IOSftOpen */
            {14, 0x000058b1}, /* _IOSftClose */
            {14, 0x00005968}, /* _IOSftTransPath */
            {14, 0x000056c8}, /* _IOSftReadAt */
            {14, 0x000056cf}, /* _IOSftWriteAt */
            {14, 0x00005a92}, /* _SftFileSize */
            {14, 0x0004654c}, /* _VMAllocMem */
            {14, 0x00027aa0}, /* _VMGetOwner */
            {14, 0x000547fe}, /* g_tkExecPgm */
            {11, 0x0000a158}, /* f_FuStrLenZ */
            {11, 0x0000a0d8}, /* f_FuStrLen */
            {11, 0x0000a301}, /* f_FuBuff */
        }
    },
    { /* 8261RU.SYM */
        8261, 'R', FALSE, 14,
        {
            {13, 0x00009294}, /* _ldrRead */
            {13, 0x0003a83c}, /* _ldrOpen */
            {13, 0x0003b0c8}, /* _ldrClose */
            {13, 0x0003b118}, /* _LDRQAppType */
            {13, 0x00038a24}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039f0}, /* _IOSftOpen */
            {13, 0x00003e5c}, /* _IOSftClose */
            {13, 0x00003ef1}, /* _IOSftTransPath */
            {13, 0x00003caa}, /* _IOSftReadAt */
            {13, 0x00003cb1}, /* _IOSftWriteAt */
            {13, 0x0000400a}, /* _SftFileSize */
            {13, 0x00036cf0}, /* _VMAllocMem */
            {13, 0x0001d2ee}, /* _VMGetOwner */
            {13, 0x0004315a}, /* g_tkExecPgm */
            { 9, 0x0000d7d0}, /* f_FuStrLenZ */
            { 9, 0x0000d786}, /* f_FuStrLen */
            { 9, 0x0000d8c4}, /* f_FuBuff */
        }
    },
    { /* 8262RS.SYM */
        8262, 'R', TRUE, 15,
        {
            {14, 0x0000c1dc}, /* _ldrRead */
            {14, 0x0004a36c}, /* _ldrOpen */
            {14, 0x0004ad94}, /* _ldrClose */
            {14, 0x0004ade4}, /* _LDRQAppType */
            {14, 0x0004885c}, /* _ldrEnum32bitRelRecs */
            {14, 0x000053d8}, /* _IOSftOpen */
            {14, 0x000058b1}, /* _IOSftClose */
            {14, 0x00005968}, /* _IOSftTransPath */
            {14, 0x000056c8}, /* _IOSftReadAt */
            {14, 0x000056cf}, /* _IOSftWriteAt */
            {14, 0x00005a92}, /* _SftFileSize */
            {14, 0x0004644c}, /* _VMAllocMem */
            {14, 0x000279a0}, /* _VMGetOwner */
            {14, 0x000546fe}, /* g_tkExecPgm */
            {11, 0x0000a15c}, /* f_FuStrLenZ */
            {11, 0x0000a0dc}, /* f_FuStrLen */
            {11, 0x0000a305}, /* f_FuBuff */
        }
    },
    { /* 8262RU.SYM */
        8262, 'R', FALSE, 14,
        {
            {13, 0x00009294}, /* _ldrRead */
            {13, 0x0003a758}, /* _ldrOpen */
            {13, 0x0003afe4}, /* _ldrClose */
            {13, 0x0003b034}, /* _LDRQAppType */
            {13, 0x00038940}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039f0}, /* _IOSftOpen */
            {13, 0x00003e5c}, /* _IOSftClose */
            {13, 0x00003ef1}, /* _IOSftTransPath */
            {13, 0x00003caa}, /* _IOSftReadAt */
            {13, 0x00003cb1}, /* _IOSftWriteAt */
            {13, 0x0000400a}, /* _SftFileSize */
            {13, 0x00036c0c}, /* _VMAllocMem */
            {13, 0x0001d20a}, /* _VMGetOwner */
            {13, 0x00043076}, /* g_tkExecPgm */
            { 9, 0x0000d7d4}, /* f_FuStrLenZ */
            { 9, 0x0000d78a}, /* f_FuStrLen */
            { 9, 0x0000d8c8}, /* f_FuBuff */
        }
    },
    { /* 8263RS.SYM */
        8263, 'R', TRUE, 15,
        {
            {14, 0x0000c250}, /* _ldrRead */
            {14, 0x0004a460}, /* _ldrOpen */
            {14, 0x0004ae88}, /* _ldrClose */
            {14, 0x0004aed8}, /* _LDRQAppType */
            {14, 0x00048944}, /* _ldrEnum32bitRelRecs */
            {14, 0x000053e0}, /* _IOSftOpen */
            {14, 0x000058b9}, /* _IOSftClose */
            {14, 0x00005970}, /* _IOSftTransPath */
            {14, 0x000056d0}, /* _IOSftReadAt */
            {14, 0x000056d7}, /* _IOSftWriteAt */
            {14, 0x00005a9a}, /* _SftFileSize */
            {14, 0x00046534}, /* _VMAllocMem */
            {14, 0x00027a14}, /* _VMGetOwner */
            {14, 0x000547a2}, /* g_tkExecPgm */
            {11, 0x0000a170}, /* f_FuStrLenZ */
            {11, 0x0000a0f0}, /* f_FuStrLen */
            {11, 0x0000a319}, /* f_FuBuff */
        }
    },
    { /* 8263RU.SYM */
        8263, 'R', FALSE, 14,
        {
            {13, 0x00009308}, /* _ldrRead */
            {13, 0x0003a8e0}, /* _ldrOpen */
            {13, 0x0003b16c}, /* _ldrClose */
            {13, 0x0003b1bc}, /* _LDRQAppType */
            {13, 0x00038ac0}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039f8}, /* _IOSftOpen */
            {13, 0x00003e64}, /* _IOSftClose */
            {13, 0x00003ef9}, /* _IOSftTransPath */
            {13, 0x00003cb2}, /* _IOSftReadAt */
            {13, 0x00003cb9}, /* _IOSftWriteAt */
            {13, 0x00004012}, /* _SftFileSize */
            {13, 0x00036d8c}, /* _VMAllocMem */
            {13, 0x0001d27e}, /* _VMGetOwner */
            {13, 0x0004321e}, /* g_tkExecPgm */
            { 9, 0x0000d7d4}, /* f_FuStrLenZ */
            { 9, 0x0000d78a}, /* f_FuStrLen */
            { 9, 0x0000d8c8}, /* f_FuBuff */
        }
    },
    { /* 8264RS.SYM */
        8264, 'R', TRUE, 15,
        {
            {14, 0x0000c250}, /* _ldrRead */
            {14, 0x0004a524}, /* _ldrOpen */
            {14, 0x0004af44}, /* _ldrClose */
            {14, 0x0004af94}, /* _LDRQAppType */
            {14, 0x00048a1c}, /* _ldrEnum32bitRelRecs */
            {14, 0x000053e0}, /* _IOSftOpen */
            {14, 0x000058b9}, /* _IOSftClose */
            {14, 0x00005970}, /* _IOSftTransPath */
            {14, 0x000056d0}, /* _IOSftReadAt */
            {14, 0x000056d7}, /* _IOSftWriteAt */
            {14, 0x00005a9a}, /* _SftFileSize */
            {14, 0x0004660c}, /* _VMAllocMem */
            {14, 0x000279f4}, /* _VMGetOwner */
            {14, 0x00054942}, /* g_tkExecPgm */
            {11, 0x0000a178}, /* f_FuStrLenZ */
            {11, 0x0000a0f8}, /* f_FuStrLen */
            {11, 0x0000a321}, /* f_FuBuff */
        }
    },
    { /* 8264RU.SYM */
        8264, 'R', FALSE, 14,
        {
            {13, 0x0000930c}, /* _ldrRead */
            {13, 0x0003aa94}, /* _ldrOpen */
            {13, 0x0003b318}, /* _ldrClose */
            {13, 0x0003b368}, /* _LDRQAppType */
            {13, 0x00038c88}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039fc}, /* _IOSftOpen */
            {13, 0x00003e68}, /* _IOSftClose */
            {13, 0x00003efd}, /* _IOSftTransPath */
            {13, 0x00003cb6}, /* _IOSftReadAt */
            {13, 0x00003cbd}, /* _IOSftWriteAt */
            {13, 0x00004016}, /* _SftFileSize */
            {13, 0x00036f54}, /* _VMAllocMem */
            {13, 0x0001d3a6}, /* _VMGetOwner */
            {13, 0x00043432}, /* g_tkExecPgm */
            { 9, 0x0000d7e0}, /* f_FuStrLenZ */
            { 9, 0x0000d796}, /* f_FuStrLen */
            { 9, 0x0000d8d4}, /* f_FuBuff */
        }
    },
    { /* 8265RS.SYM */
        8265, 'R', TRUE, 15,
        {
            {14, 0x0000c250}, /* _ldrRead */
            {14, 0x0004a5d4}, /* _ldrOpen */
            {14, 0x0004aff4}, /* _ldrClose */
            {14, 0x0004b044}, /* _LDRQAppType */
            {14, 0x00048ab8}, /* _ldrEnum32bitRelRecs */
            {14, 0x000053e0}, /* _IOSftOpen */
            {14, 0x000058b9}, /* _IOSftClose */
            {14, 0x00005970}, /* _IOSftTransPath */
            {14, 0x000056d0}, /* _IOSftReadAt */
            {14, 0x000056d7}, /* _IOSftWriteAt */
            {14, 0x00005a9a}, /* _SftFileSize */
            {14, 0x000466a8}, /* _VMAllocMem */
            {14, 0x00027a7c}, /* _VMGetOwner */
            {14, 0x000549e2}, /* g_tkExecPgm */
            {11, 0x0000a178}, /* f_FuStrLenZ */
            {11, 0x0000a0f8}, /* f_FuStrLen */
            {11, 0x0000a321}, /* f_FuBuff */
        }
    },
    { /* 8265RU.SYM */
        8265, 'R', FALSE, 14,
        {
            {13, 0x0000930c}, /* _ldrRead */
            {13, 0x0003a9b4}, /* _ldrOpen */
            {13, 0x0003b238}, /* _ldrClose */
            {13, 0x0003b288}, /* _LDRQAppType */
            {13, 0x00038b94}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039fc}, /* _IOSftOpen */
            {13, 0x00003e68}, /* _IOSftClose */
            {13, 0x00003efd}, /* _IOSftTransPath */
            {13, 0x00003cb6}, /* _IOSftReadAt */
            {13, 0x00003cbd}, /* _IOSftWriteAt */
            {13, 0x00004016}, /* _SftFileSize */
            {13, 0x00036e60}, /* _VMAllocMem */
            {13, 0x0001d2a6}, /* _VMGetOwner */
            {13, 0x00043352}, /* g_tkExecPgm */
            { 9, 0x0000d830}, /* f_FuStrLenZ */
            { 9, 0x0000d7e6}, /* f_FuStrLen */
            { 9, 0x0000d924}, /* f_FuBuff */
        }
    },
    { /* 9029RU.SYM */
        9029, 'R', FALSE, 13,
        {
            {12, 0x00009404}, /* _ldrRead */
            {12, 0x00039900}, /* _ldrOpen */
            {12, 0x0003a188}, /* _ldrClose */
            {12, 0x0003a1d8}, /* _LDRQAppType */
            {12, 0x00037bcc}, /* _ldrEnum32bitRelRecs */
            {12, 0x000034ec}, /* _IOSftOpen */
            {12, 0x00003992}, /* _IOSftClose */
            {12, 0x00003a39}, /* _IOSftTransPath */
            {12, 0x000037b3}, /* _IOSftReadAt */
            {12, 0x000037ba}, /* _IOSftWriteAt */
            {12, 0x00003b52}, /* _SftFileSize */
            {12, 0x00035ea0}, /* _VMAllocMem */
            {12, 0x0001c8f0}, /* _VMGetOwner */
            {12, 0x00041eb6}, /* g_tkExecPgm */
            { 9, 0x0000e594}, /* f_FuStrLenZ */
            { 9, 0x0000e54a}, /* f_FuStrLen */
            { 9, 0x0000e688}, /* f_FuBuff */
        }
    },
    { /* 9030RU.SYM */
        9030, 'R', FALSE, 14,
        {
            {13, 0x00009784}, /* _ldrRead */
            {13, 0x0003a114}, /* _ldrOpen */
            {13, 0x0003a99c}, /* _ldrClose */
            {13, 0x0003a9ec}, /* _LDRQAppType */
            {13, 0x0003831c}, /* _ldrEnum32bitRelRecs */
            {13, 0x0000388c}, /* _IOSftOpen */
            {13, 0x00003d32}, /* _IOSftClose */
            {13, 0x00003dd9}, /* _IOSftTransPath */
            {13, 0x00003b53}, /* _IOSftReadAt */
            {13, 0x00003b5a}, /* _IOSftWriteAt */
            {13, 0x00003ef2}, /* _SftFileSize */
            {13, 0x000365e8}, /* _VMAllocMem */
            {13, 0x0001d000}, /* _VMGetOwner */
            {13, 0x0004288a}, /* g_tkExecPgm */
            { 9, 0x0000db08}, /* f_FuStrLenZ */
            { 9, 0x0000dabe}, /* f_FuStrLen */
            { 9, 0x0000dbfc}, /* f_FuBuff */
        }
    },
    { /* 9031RU.SYM */
        9031, 'R', FALSE, 14,
        {
            {13, 0x00009814}, /* _ldrRead */
            {13, 0x0003a02c}, /* _ldrOpen */
            {13, 0x0003a8b0}, /* _ldrClose */
            {13, 0x0003a900}, /* _LDRQAppType */
            {13, 0x00038228}, /* _ldrEnum32bitRelRecs */
            {13, 0x0000388c}, /* _IOSftOpen */
            {13, 0x00003d32}, /* _IOSftClose */
            {13, 0x00003dd9}, /* _IOSftTransPath */
            {13, 0x00003b53}, /* _IOSftReadAt */
            {13, 0x00003b5a}, /* _IOSftWriteAt */
            {13, 0x00003ef2}, /* _SftFileSize */
            {13, 0x00036574}, /* _VMAllocMem */
            {13, 0x0001d09c}, /* _VMGetOwner */
            {13, 0x0004288a}, /* g_tkExecPgm */
            { 9, 0x0000db08}, /* f_FuStrLenZ */
            { 9, 0x0000dabe}, /* f_FuStrLen */
            { 9, 0x0000dbfc}, /* f_FuBuff */
        }
    },
    { /* 9032RU.SYM */
        9032, 'R', FALSE, 14,
        {
            {13, 0x00009814}, /* _ldrRead */
            {13, 0x0003a27c}, /* _ldrOpen */
            {13, 0x0003ab00}, /* _ldrClose */
            {13, 0x0003ab50}, /* _LDRQAppType */
            {13, 0x00038478}, /* _ldrEnum32bitRelRecs */
            {13, 0x0000388c}, /* _IOSftOpen */
            {13, 0x00003d32}, /* _IOSftClose */
            {13, 0x00003dd9}, /* _IOSftTransPath */
            {13, 0x00003b53}, /* _IOSftReadAt */
            {13, 0x00003b5a}, /* _IOSftWriteAt */
            {13, 0x00003ef2}, /* _SftFileSize */
            {13, 0x000367c4}, /* _VMAllocMem */
            {13, 0x0001d09a}, /* _VMGetOwner */
            {13, 0x00042b3a}, /* g_tkExecPgm */
            { 9, 0x0000db00}, /* f_FuStrLenZ */
            { 9, 0x0000dab6}, /* f_FuStrLen */
            { 9, 0x0000dbf4}, /* f_FuBuff */
        }
    },
    { /* 9033RU.SYM */
        9033, 'R', FALSE, 14,
        {
            {13, 0x00009824}, /* _ldrRead */
            {13, 0x0003a3c8}, /* _ldrOpen */
            {13, 0x0003ac54}, /* _ldrClose */
            {13, 0x0003aca4}, /* _LDRQAppType */
            {13, 0x000385b0}, /* _ldrEnum32bitRelRecs */
            {13, 0x0000388c}, /* _IOSftOpen */
            {13, 0x00003d32}, /* _IOSftClose */
            {13, 0x00003dd9}, /* _IOSftTransPath */
            {13, 0x00003b53}, /* _IOSftReadAt */
            {13, 0x00003b5a}, /* _IOSftWriteAt */
            {13, 0x00003ef2}, /* _SftFileSize */
            {13, 0x000368fc}, /* _VMAllocMem */
            {13, 0x0001d172}, /* _VMGetOwner */
            {13, 0x00042c8e}, /* g_tkExecPgm */
            { 9, 0x0000db30}, /* f_FuStrLenZ */
            { 9, 0x0000dae6}, /* f_FuStrLen */
            { 9, 0x0000dc24}, /* f_FuBuff */
        }
    },
    { /* 9034RU.SYM */
        9034, 'R', FALSE, 14,
        {
            {13, 0x00009368}, /* _ldrRead */
            {13, 0x0003a700}, /* _ldrOpen */
            {13, 0x0003af8c}, /* _ldrClose */
            {13, 0x0003afdc}, /* _LDRQAppType */
            {13, 0x000388e0}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039b0}, /* _IOSftOpen */
            {13, 0x00003e56}, /* _IOSftClose */
            {13, 0x00003efd}, /* _IOSftTransPath */
            {13, 0x00003c77}, /* _IOSftReadAt */
            {13, 0x00003c7e}, /* _IOSftWriteAt */
            {13, 0x00004016}, /* _SftFileSize */
            {13, 0x00036c2c}, /* _VMAllocMem */
            {13, 0x0001d2fa}, /* _VMGetOwner */
            {13, 0x00042fda}, /* g_tkExecPgm */
            { 9, 0x0000db44}, /* f_FuStrLenZ */
            { 9, 0x0000dafa}, /* f_FuStrLen */
            { 9, 0x0000dc38}, /* f_FuBuff */
        }
    },
    { /* 9035RU.SYM */
        9035, 'R', FALSE, 14,
        {
            {13, 0x00009368}, /* _ldrRead */
            {13, 0x0003a964}, /* _ldrOpen */
            {13, 0x0003b1e8}, /* _ldrClose */
            {13, 0x0003b238}, /* _LDRQAppType */
            {13, 0x00038b58}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039b0}, /* _IOSftOpen */
            {13, 0x00003e56}, /* _IOSftClose */
            {13, 0x00003efd}, /* _IOSftTransPath */
            {13, 0x00003c77}, /* _IOSftReadAt */
            {13, 0x00003c7e}, /* _IOSftWriteAt */
            {13, 0x00004016}, /* _SftFileSize */
            {13, 0x00036ea4}, /* _VMAllocMem */
            {13, 0x0001d436}, /* _VMGetOwner */
            {13, 0x0004324e}, /* g_tkExecPgm */
            { 9, 0x0000db44}, /* f_FuStrLenZ */
            { 9, 0x0000dafa}, /* f_FuStrLen */
            { 9, 0x0000dc38}, /* f_FuBuff */
        }
    },
    { /* 9036RU.SYM */
        9036, 'R', FALSE, 14,
        {
            {13, 0x000093b4}, /* _ldrRead */
            {13, 0x0003ab8c}, /* _ldrOpen */
            {13, 0x0003b410}, /* _ldrClose */
            {13, 0x0003b460}, /* _LDRQAppType */
            {13, 0x00038d6c}, /* _ldrEnum32bitRelRecs */
            {13, 0x000039fc}, /* _IOSftOpen */
            {13, 0x00003ea2}, /* _IOSftClose */
            {13, 0x00003f49}, /* _IOSftTransPath */
            {13, 0x00003cc3}, /* _IOSftReadAt */
            {13, 0x00003cca}, /* _IOSftWriteAt */
            {13, 0x00004062}, /* _SftFileSize */
            {13, 0x000370b8}, /* _VMAllocMem */
            {13, 0x0001d4ee}, /* _VMGetOwner */
            {13, 0x0004359e}, /* g_tkExecPgm */
            { 9, 0x0000db94}, /* f_FuStrLenZ */
            { 9, 0x0000db4a}, /* f_FuStrLen */
            { 9, 0x0000dc88}, /* f_FuBuff */
        }
    },
    { /* Terminating entry */
        0,0,0,0,
        {
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
            {0,0},
        }
    }
}; /* end of aKrnlSymDB[] */
