/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/ktk/tmp/odin/odin32xp/tools/wrc/lexyy.c,v 1.1 1999-09-08 19:34:08 sandervl Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 117
#define YY_END_OF_BUFFER 118
static yyconst short int yy_accept[346] =
    {   0,
        0,    0,   59,   59,    0,    0,    0,    0,    0,    0,
        0,    0,  107,  107,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,   22,    9,    9,    9,    9,   39,   39,
        0,    0,   29,   29,   33,   33,   34,   34,  118,  115,
      114,  113,  115,   81,  115,  100,  115,   49,   49,  111,
      115,  115,  115,   52,   52,   47,  115,   48,  114,  115,
       59,  114,   60,   59,   59,   59,   59,   59,   59,  116,
       62,   61,   95,   83,   82,   99,   80,   65,   64,  116,
      105,  103,  104,  101,  105,  107,  109,  108,    4,  116,

        4,    4,    8,    6,   14,   22,    9,   12,  116,  116,
       39,   38,   38,   38,   29,  116,   27,   25,   26,   29,
      116,   33,   30,   31,  116,   33,   37,   34,   36,   35,
      114,   56,   54,  106,  112,   49,   52,   49,   52,   52,
      111,   57,   55,   58,   63,   53,  114,    0,    0,    0,
        0,    0,    0,    0,    0,   59,   59,   59,   59,   59,
       59,   59,   59,    0,   61,   95,    0,   96,   94,   94,
       84,   86,   87,   88,   89,   90,   91,   92,   93,   94,
       80,    0,   77,   76,   76,   66,   68,   69,   70,   71,
       72,   73,   74,   75,   76,  103,  102,  107,  108,  108,

      110,    0,    0,    7,    6,   14,   22,    9,   10,    0,
       11,   39,    0,    0,    0,    0,    0,   29,   28,   29,
       33,   32,   33,   34,  112,   51,   50,    0,    0,    0,
        0,   15,    0,    0,    0,    0,   59,   59,   59,   59,
       59,   59,   59,   98,   97,   84,   86,    0,   79,   78,
       66,   68,    0,    3,    2,   10,   51,   50,    0,    0,
        0,    0,    0,   15,    0,    0,    0,    0,    0,    0,
       59,   59,   59,   59,   59,   59,   46,   84,   85,   66,
        0,    0,   18,   19,    0,    0,    0,    0,    0,   24,
        0,    0,   59,   41,   59,   59,   59,   59,   66,    0,

        0,   18,   19,   20,   21,   16,    0,    0,   24,    0,
       13,   59,   42,   59,   59,   59,   66,   67,    5,   20,
       21,   16,   17,    0,   23,   13,   59,   59,   59,   45,
       66,    5,   17,    1,   23,   59,   59,   43,    1,   59,
       59,   59,   44,   40,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    9,
       10,   11,    1,    1,    1,    1,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   26,   27,   26,   26,   28,   29,   30,   31,   32,
       26,   33,   34,   26,   35,   36,   26,   37,   26,   26,
        1,   38,    1,    1,   26,    1,   39,   40,   41,   42,

       43,   44,   45,   26,   46,   26,   26,   47,   48,   49,
       50,   51,   26,   52,   53,   54,   55,   56,   26,   57,
       26,   26,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    2,    3,    1,    4,    5,    1,    1,    6,    7,
        8,    9,   10,   10,   10,    5,    1,    1,   11,   10,
       10,   10,   10,   10,   10,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   10,   10,
       10,   10,   10,   10,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   14,    1,   14
    } ;

static yyconst short int yy_base[397] =
    {   0,
        0,   60,  119,  169,   17,   18,   42,   43,   46,   47,
      219,  262,   21,   22,   24,   37,  306,  366,  426,  486,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  626,  625,   79,   87,   89,   90,  624,  623,
      622,   28,   94,  127,  170,  324,   41,   92,  624, 1265,
      621, 1265,  604, 1265,  614, 1265,   24,  241,   98,    0,
      602,  601,  600,    0,  612, 1265,  557, 1265,   81,  113,
        0,  613, 1265,   10,   59,   75,   85,  100,  148,  609,
     1265, 1265,    0, 1265,  132,  542,    0, 1265,  136,  595,
     1265,  611, 1265, 1265,    0,    0, 1265,  146, 1265, 1265,

        0,    0, 1265,  603,    0,    0,    0, 1265,  166,  186,
        0, 1265,  101,  147,    0,  600, 1265, 1265, 1265,  130,
      182,    0, 1265, 1265,  596,  189, 1265,  604, 1265, 1265,
      603, 1265, 1265, 1265,    0,  191,    0,    0,  194,  640,
        0, 1265, 1265, 1265, 1265, 1265,  208,  295,  345,  561,
      177,   65,  557,  550,  552,    0,  165,  193,  180,  227,
      201,  224,  216,  592, 1265,    0,  269, 1265, 1265,  590,
      238,  266, 1265, 1265, 1265, 1265, 1265, 1265, 1265,    0,
        0,  287, 1265, 1265,  588,  280,  338, 1265, 1265, 1265,
     1265, 1265, 1265, 1265,    0,  590, 1265,    0,  224,  234,

     1265,  585,  570, 1265,  579,    0,    0,    0,    0,  297,
     1265,    0,  326,  343,  347,    6,  543,    0, 1265,  329,
        0, 1265,  337,  583,    0,  433,  301,  540,   43,  541,
      528,  160,  538,  529,  538,  534,  372,  371,  362,  376,
      377,  374,  379, 1265, 1265,  341,  344,    0, 1265, 1265,
      347,  392,    0,  570, 1265,    0,    0,    0,  528,  529,
      529,  525,  520,  567,  525,  525,  519,  522,  519,  520,
      428,  426,  417,  420,  432,  422,    0,  395, 1265,  441,
        0,  513,  559,  558,  515,  506,  510,  510,  497,    0,
      503,  506,  424,    0,  434,  429,  439,  442,  460,    0,

      506,  546,  541,  540,  533,  527,  479,  441,    0,  427,
      463,  440,    0,  484,  479,  485,  496, 1265,  421,  417,
      414,  413,  410,  368,    0,  396,  492,  493,  490,    0,
      502,  361,  294,  288,    0,  497,  491,    0,  271,  492,
      493,  498,    0,    0, 1265,  684,  698,  712,  726,  740,
      754,  768,  782,  796,  810,  824,  838,  852,  866,  880,
      894,  908,  922,  518,  936,  950,  964,  978,  992, 1006,
     1020,  213, 1034, 1048, 1062, 1076, 1085,  524, 1097, 1111,
     1125, 1139, 1153, 1166, 1180, 1194, 1208,  165,  159, 1222,
      143,  130,   29, 1236,   16, 1250

    } ;

static yyconst short int yy_def[397] =
    {   0,
      346,  346,  347,  347,  348,  348,  349,  349,  350,  350,
      351,  351,  352,  352,  353,  353,  354,  354,  355,  355,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  357,  357,  358,  358,  358,  358,  359,  359,
      360,  360,  361,  361,  362,  362,  363,  363,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  364,  364,  365,
      345,  345,  345,  364,  364,  345,  345,  345,  345,  345,
      366,  345,  345,  366,  366,  366,  366,  366,  366,  367,
      345,  345,  368,  345,  345,  369,  370,  345,  345,  371,
      345,  345,  345,  345,  372,  373,  345,  374,  345,  345,

      375,  376,  345,  377,  378,  379,  380,  345,  381,  345,
      382,  345,  345,  345,  383,  384,  345,  345,  345,  383,
      345,  385,  345,  345,  386,  385,  345,  345,  345,  345,
      345,  345,  345,  345,  387,  364,  364,  364,  364,  364,
      365,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  366,  366,  366,  366,  366,
      366,  366,  366,  367,  345,  368,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  388,
      370,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  389,  345,  345,  373,  374,  374,

      345,  375,  376,  345,  377,  378,  379,  380,  390,  345,
      345,  382,  345,  345,  345,  345,  345,  383,  345,  383,
      385,  345,  385,  345,  387,  364,  140,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  366,  366,  366,  366,
      366,  366,  366,  345,  345,  345,  345,  391,  345,  345,
      345,  345,  392,  375,  345,  390,  364,  364,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      366,  366,  366,  366,  366,  366,  366,  345,  345,  345,
      393,  345,  345,  345,  345,  345,  345,  345,  345,  394,
      345,  345,  366,  366,  366,  366,  366,  366,  345,  395,

      345,  345,  345,  345,  345,  345,  345,  345,  394,  345,
      345,  366,  366,  366,  366,  366,  345,  345,  345,  345,
      345,  345,  345,  345,  396,  345,  366,  366,  366,  366,
      345,  345,  345,  345,  396,  366,  366,  366,  345,  366,
      366,  366,  366,  366,    0,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345

    } ;

static yyconst short int yy_nxt[1326] =
    {   0,
       50,   51,   52,   53,   54,   50,   55,   56,   50,   50,
       50,   57,   58,   59,   59,   60,   61,   62,   63,   81,
       81,   82,   82,   97,   97,  318,  100,   65,  101,  113,
       52,   98,   98,  114,  134,  135,  157,   50,  300,  100,
      102,  101,  128,  129,   84,   84,   85,   85,   88,   88,
       89,   89,  229,  102,  230,  157,  130,   66,   67,   68,
       50,   69,   52,   53,   54,   70,   55,   56,   50,   50,
       50,   57,   58,   59,   59,   60,   61,   62,   63,   86,
       86,  108,  147,   90,   90,  158,  148,   65,  260,  108,
      109,  108,  108,  128,  129,  261,   52,   50,  109,  100,

      109,  109,  213,  159,  158,  116,  214,  130,  232,  117,
      136,  136,  136,  233,  149,  160,  110,   66,   67,   68,
       72,   52,  159,   73,  110,  138,  110,  110,  120,   52,
      161,  220,  121,  167,  160,  214,  168,  182,  116,  281,
      183,   74,  117,   75,  138,   76,   77,   78,  215,  161,
       79,  118,  279,  119,  150,  151,  200,  201,  152,  153,
       74,  264,   75,  154,   76,   77,   78,  155,  253,   79,
       72,   52,   52,   73,  248,  100,  134,  135,  123,  124,
      162,  125,  163,  215,  118,  100,  119,  210,  211,  216,
      223,   74,  217,   75,  214,   76,   77,   78,  237,  162,

       79,  265,  163,  136,  136,  136,  226,  226,  266,  147,
       74,  239,   75,  148,   76,   77,   78,  237,  138,   79,
       92,   93,  197,  229,  216,  230,   94,  217,  231,  238,
      239,   95,   95,   95,  345,  345,  241,  138,   95,   95,
       95,   95,   95,   95,  200,  201,  240,  242,  243,  238,
      246,  246,  247,  136,  136,  136,  241,   95,   95,   95,
       95,   95,   95,   92,   93,  240,  242,  243,  138,   94,
      167,  139,  339,  244,   95,   95,   95,  140,  247,  247,
      247,   95,   95,   95,   95,   95,   95,  138,  182,  339,
      139,  249,  251,  251,  252,  333,  149,  140,  210,  211,

       95,   95,   95,   95,   95,   95,  103,  103,  100,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  126,   52,  213,  258,  121,
      220,  214,  123,  124,  214,  125,  150,  151,  223,  100,
      152,  153,  214,  103,  215,  154,  149,  258,  215,  155,
      252,  252,  252,  278,  278,  247,  247,  247,  247,  280,
      280,  252,  332,  103,  103,  103,  103,  103,  100,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  216,  150,  151,  217,  216,
      152,  153,  217,  271,  272,  154,  273,  326,  274,  155,

      275,  276,  277,  103,  252,  252,  252,  247,  247,  247,
      334,  333,  271,  272,  322,  321,  273,  274,  320,  275,
      276,  277,  332,  103,  103,  103,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  226,  226,  293,  294,  295,
      296,  297,  298,  299,  299,  252,  312,  313,  314,  315,
      257,  316,  327,  100,  326,  325,  293,  294,  295,  296,
      297,  298,  317,  317,  252,  312,  313,  314,  315,  257,
      316,  327,  324,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,

      100,  100,  100,  100,  100,  328,  329,  330,  331,  331,
      252,  336,  337,  338,  252,  252,  252,  340,  341,  342,
      343,  344,  323,  100,  328,  329,  330,  137,  322,  137,
      336,  337,  338,  206,  321,  206,  340,  341,  342,  343,
      344,  320,  303,  100,  100,  100,  170,  302,  319,  311,
      310,  308,  307,  306,  171,  171,  172,  305,  304,  303,
      302,  301,  292,  291,  290,  289,  288,  287,  264,  286,
      285,  284,  283,  282,  254,  270,  269,  268,  267,  263,
      173,  174,  262,  259,  224,  175,  232,  204,  255,  254,
      176,  196,  250,  177,  245,  178,  165,  179,  180,  185,

      236,  235,  234,  228,  131,  224,  134,  186,  186,  187,
      134,  204,  196,  165,  131,  146,  145,  144,  143,  142,
      133,  132,  131,  345,   52,  100,  100,  100,  100,  345,
      345,  345,  345,  188,  189,  345,  345,  345,  190,  345,
      345,  345,  345,  191,  345,  345,  192,  345,  193,  345,
      194,  195,  227,  227,  227,  345,  345,  345,  345,  227,
      227,  227,  227,  227,  227,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  227,  227,
      227,  227,  227,  227,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   71,   71,

       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,  104,  104,  104,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  115,  115,  115,  115,  115,  115,

      115,  115,  115,  115,  115,  115,  115,  115,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  141,  141,  345,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      156,  345,  345,  345,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  164,  164,  345,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  166,  166,
      345,  345,  166,  166,  166,  166,  166,  166,  166,  166,
      345,  166,  169,  169,  169,  169,  169,  169,  169,  169,

      169,  169,  169,  169,  169,  169,  181,  181,  345,  345,
      181,  181,  181,  181,  181,  181,  181,  181,  345,  181,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  198,  198,  345,  198,  198,  198,
      198,  345,  198,  198,  198,  198,  198,  198,  199,  199,
      345,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  202,  202,  345,  202,  202,  202,  202,  202,
      202,  202,  345,  202,  202,  202,  203,  203,  345,  203,
      203,  203,  203,  203,  203,  203,  345,  203,  203,  203,
      205,  345,  345,  345,  205,  345,  205,  207,  207,  345,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  208,  208,  345,  208,  208,  208,  208,  208,  345,
      208,  208,  208,  345,  208,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  212,
      212,  345,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  218,  218,  345,  218,  345,  218,  218,
      218,  345,  218,  218,  218,  218,  219,  219,  345,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      221,  221,  345,  221,  345,  345,  345,  221,  345,  221,
      221,  221,  221,  221,  222,  222,  345,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  225,  225,
      345,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  256,  256,  345,  256,  256,  256,  256,  256,
      345,  256,  256,  256,  345,  256,  309,  309,  345,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      335,  335,  345,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,   49,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345
    } ;

static yyconst short int yy_chk[1326] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    5,    6,   13,   14,  395,   15,    1,   15,   42,
       42,   13,   14,   42,   57,   57,   74,    1,  393,   16,
       15,   16,   47,   47,    7,    8,    7,    8,    9,   10,
        9,   10,  216,   16,  216,   74,   47,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    7,
        8,   35,   69,    9,   10,   75,   69,    2,  229,   36,
       35,   37,   38,   48,   48,  229,   43,    2,   36,   43,

       37,   38,  113,   76,   75,   43,  113,   48,  152,   43,
       59,   59,   59,  152,   70,   77,   35,    2,    2,    2,
        3,    3,   76,    3,   36,   59,   37,   38,   44,   44,
       78,  120,   44,   85,   77,  120,   85,   89,   44,  392,
       89,    3,   44,    3,   59,    3,    3,    3,  114,   78,
        3,   43,  391,   43,   70,   70,   98,   98,   70,   70,
        3,  232,    3,   70,    3,    3,    3,   70,  389,    3,
        4,    4,   45,    4,  388,   45,  109,  109,   45,   45,
       79,   45,   79,  121,   44,   45,   44,  110,  110,  114,
      126,    4,  114,    4,  126,    4,    4,    4,  157,   79,

        4,  232,   79,  136,  136,  136,  139,  139,  232,  147,
        4,  159,    4,  147,    4,    4,    4,  157,  136,    4,
       11,   11,  372,  151,  121,  151,   11,  121,  151,  158,
      159,   11,   11,   11,  199,  199,  161,  136,   11,   11,
       11,   11,   11,   11,  200,  200,  160,  162,  163,  158,
      171,  171,  171,   58,   58,   58,  161,   11,   11,   11,
       11,   11,   11,   12,   12,  160,  162,  163,   58,   12,
      167,   58,  339,  167,   12,   12,   12,   58,  172,  172,
      172,   12,   12,   12,   12,   12,   12,   58,  182,  334,
       58,  182,  186,  186,  186,  333,  148,   58,  210,  210,

       12,   12,   12,   12,   12,   12,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   46,   46,  213,  227,   46,
      220,  213,   46,   46,  220,   46,  148,  148,  223,   46,
      148,  148,  223,   17,  214,  148,  149,  227,  215,  148,
      187,  187,  187,  246,  246,  246,  247,  247,  247,  251,
      251,  251,  332,   17,   17,   17,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,  214,  149,  149,  214,  215,
      149,  149,  215,  237,  238,  149,  239,  326,  240,  149,

      241,  242,  243,   18,  252,  252,  252,  278,  278,  278,
      324,  323,  237,  238,  322,  321,  239,  240,  320,  241,
      242,  243,  319,   18,   18,   18,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,  226,  226,  271,  272,  273,
      274,  275,  276,  280,  280,  280,  293,  295,  296,  297,
      226,  298,  312,   19,  311,  310,  271,  272,  273,  274,
      275,  276,  299,  299,  299,  293,  295,  296,  297,  226,
      298,  312,  308,   19,   19,   19,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,  314,  315,  316,  317,  317,
      317,  327,  328,  329,  331,  331,  331,  336,  337,  340,
      341,  342,  307,   20,  314,  315,  316,  364,  306,  364,
      327,  328,  329,  378,  305,  378,  336,  337,  340,  341,
      342,  304,  303,   20,   20,   20,   86,  302,  301,  292,
      291,  289,  288,  287,   86,   86,   86,  286,  285,  284,
      283,  282,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  254,  236,  235,  234,  233,  231,
       86,   86,  230,  228,  224,   86,  217,  205,  203,  202,
       86,  196,  185,   86,  170,   86,  164,   86,   86,   90,

      155,  154,  153,  150,  131,  128,  125,   90,   90,   90,
      116,  104,   92,   80,   72,   67,   65,   63,   62,   61,
       55,   53,   51,   49,   41,   40,   39,   34,   33,    0,
        0,    0,    0,   90,   90,    0,    0,    0,   90,    0,
        0,    0,    0,   90,    0,    0,   90,    0,   90,    0,
       90,   90,  140,  140,  140,    0,    0,    0,    0,  140,
      140,  140,  140,  140,  140,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  140,  140,
      140,  140,  140,  140,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  361,  361,  361,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  365,  365,    0,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      366,    0,    0,    0,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  367,  367,    0,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  368,  368,
        0,    0,  368,  368,  368,  368,  368,  368,  368,  368,
        0,  368,  369,  369,  369,  369,  369,  369,  369,  369,

      369,  369,  369,  369,  369,  369,  370,  370,    0,    0,
      370,  370,  370,  370,  370,  370,  370,  370,    0,  370,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  373,  373,    0,  373,  373,  373,
      373,    0,  373,  373,  373,  373,  373,  373,  374,  374,
        0,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  375,  375,    0,  375,  375,  375,  375,  375,
      375,  375,    0,  375,  375,  375,  376,  376,    0,  376,
      376,  376,  376,  376,  376,  376,    0,  376,  376,  376,
      377,    0,    0,    0,  377,    0,  377,  379,  379,    0,

      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  380,  380,    0,  380,  380,  380,  380,  380,    0,
      380,  380,  380,    0,  380,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  382,
      382,    0,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  383,  383,    0,  383,    0,  383,  383,
      383,    0,  383,  383,  383,  383,  384,  384,    0,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      385,  385,    0,  385,    0,    0,    0,  385,    0,  385,
      385,  385,  385,  385,  386,  386,    0,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  387,  387,
        0,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  390,  390,    0,  390,  390,  390,  390,  390,
        0,  390,  390,  390,    0,  390,  394,  394,    0,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      396,  396,    0,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "parser.l"
#define INITIAL 0
/* -*-C-*-
 *
 * Copyright 1994 Martin von Loewis
 * Copyright 1998 Bertho A. Stultiens (BS)
 *
 * 20-Jun-1998 BS	- Changed the filename conversion. Filenames are
 *			  case-sensitive inder *nix, but not under dos.
 *			  default behaviour is to convert to lower case.
 *			- All backslashes are converted to forward and
 *			  both single and double slash is recognized as
 *			  MS/Borland does.
 *			- Fixed a bug in 'yywf' case that prevented
 *			  double quoted names to be scanned propperly.
 *
 * 19-May-1998 BS	- Started to build a preprocessor.
 *			- Changed keyword processing completely to
 *			  table-lookups.
 *
 * 20-Apr-1998 BS	- Added ';' comment stripping
 *
 * 17-Apr-1998 BS	- Made the win32 keywords optional when compiling in
 *			  16bit mode
 *
 * 15-Apr-1998 BS	- Changed string handling to include escapes
 *			- Added unicode string handling (no codepage
 *			  translation though).
 *			- 'Borrowed' the main idea of string scanning from
 *			  the flex manual pages.
 *			- Added conditional handling of scanning depending
 *			  on the state of the parser. This was mainly required
 *			  to distinguish a file to load or raw data that
 *			  follows. MS's definition of filenames is rather
 *			  complex... It can be unquoted or double quoted. If
 *			  double quoted, then the '\\' char is not automatically
 *			  escaped according to Borland's rc compiler, but it
 *			  accepts both "\\path\\file.rc" and "\path\file.rc".
 *			  This makes life very hard! I go for the escaped
 *			  version, as this seems to be the documented way...
 *			- Single quoted strings are now parsed and converted
 *			  here.
 *			- Added comment stripping. The implementation is
 *			  'borrowed' from the flex manpages.
 *			- Rebuild string processing so that it may contain
 *			  escaped '\0'.
 */
/* Exclusive rules when looking for a filename */
#define yywf 1

#define yywf_s 2

/* Exclusive string handling */
#define yystr 3

/* Exclusive unicode string handling */
#define yylstr 4

/* Exclusive rcdata single quoted data handling */
#define yyrcd 5

/* Exclusive comment eating... */
#define comment 6

/* Preprocessor exclusives */
#define pp_incl 7

#define pp_def 8

#define pp_undef 9

#define pp_if 10

#define pp_ifdef 11

#define pp_ifndef 12

#define pp_elif 13

#define pp_else 14

#define pp_endif 15

#define pp_error 16

/* Set when accumulating #define's expansion text */
#define pp_def_s 17

/* Set when processing function type defines */
#define pp_ignore 18

/* Set when need to strip to eol */
#define pp_ignore_eol 19

/* Set when handling a false #if case */
#define pp_false 20

/* Set when stripping c-junk */
#define pp_strips 21

#define pp_stripp 22

#define pp_stripp_final 23

/*%option stack*/
#define YY_NEVER_INTERACTIVE 1
/*%option noyywrap */
/* Some shortcut definitions */
#line 90 "parser.l"

#if !defined(YY_FLEX_MAJOR_VERSION) || (1000 * YY_FLEX_MAJOR_VERSION + YY_FLEX_MINOR_VERSION < 2005)
#error Must use flex version 2.5.1 or higher (yy_scan_* routines are required).
#endif

/*#define LEX_DEBUG*/

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "wrc.h"
#include "utils.h"
#include "preproc.h"
#include "parser.h"
#include "newstruc.h"

#include "y.tab.h"

#define YY_USE_PROTOS
#define YY_NO_UNPUT

/* Always update the current character position within a line */
#define YY_USER_ACTION	char_number+=yyleng;

raw_data_t *new_raw_data(void);

void addcchar(char c);
void addwchar(short s);
string_t *get_buffered_cstring(void);
string_t *get_buffered_wstring(void);
string_t *make_string(char *s);
string_t *make_filename(char *s, int len);

int line_number = 1;		/* The current line */
int char_number = 1;		/* The current char pos within the line */
static char *cbuffer;		/* Buffers for string collection */
static int cbufidx;
static int cbufalloc = 0;
static short *wbuffer;
static int wbufidx;
static int wbufalloc = 0;
static int want_nl = 0;		/* Set when newline needs to go to parser */
static int want_ident = 0;	/* Set is #ifdef, #ifndef or defined is seen */
static int stripslevel = 0;	/* Count {} during pp_strips mode */
static int stripplevel = 0;	/* Count () during pp_strips mode */
static char *substtext = NULL;	/* Holds the substition text while getting a define */
static int cjunk_tagline;	/* Where did we start stripping (helps error tracking) */

#ifdef YY_USE_STACK
void push_to(int start)	{ yy_push_state(start); }
void pop_start(void)	{ yy_pop_state(start); }
#else
#define MAXSTARTSTACK	32
static int startstack[MAXSTARTSTACK];
static int startstackidx = 0;

void push_to(int start)
{
	if(yydebug)
		printf("push_to(%d): %d -> %d\n", line_number, YY_START, start);
	if(startstackidx >= MAXSTARTSTACK-1)
		internal_error(__FILE__, __LINE__, "Start condition stack overflow");
	startstack[startstackidx++] = YY_START;
	BEGIN(start);
}

void pop_start(void)
{
	if(yydebug)
		printf("pop_start(%d): %d <- %d\n", line_number, startstack[startstackidx-1], YY_START);
	if(startstackidx <= 0)
		internal_error(__FILE__, __LINE__, "Start condition stack underflow");
	--startstackidx;
	BEGIN(startstack[startstackidx]);
}
#endif


struct bufferstackentry {
	YY_BUFFER_STATE	bufferstate;	/* Buffer to switch back to */
	struct pp_entry	*define;	/* Points to expanding define
					   or NULL if handling includes
					 */
	int line_number;		/* Line that we were handling */
	int char_number;		/* The current position */
	char *filename;			/* Filename that we were handling */
};

#define MAXBUFFERSTACK 128
static struct bufferstackentry bufferstack[MAXBUFFERSTACK];
static int bufferstackidx = 0;

void push_buffer(YY_BUFFER_STATE buf, struct pp_entry *ppp, char *filename)
{
	if(yydebug)
		printf("push_buffer: %p %p %p\n", buf, ppp, filename);
	if(bufferstackidx >= MAXBUFFERSTACK-1)
		internal_error(__FILE__, __LINE__, "Buffer stack overflow");
	memset(&bufferstack[bufferstackidx], 0, sizeof(bufferstack[0]));
	bufferstack[bufferstackidx].bufferstate = buf;
	bufferstack[bufferstackidx].define = ppp;
	if(ppp)
		ppp->expanding = 1;
	else if(filename)
	{
		/* These will track the yyerror to the correct file and line */
		bufferstack[bufferstackidx].line_number = line_number;
		bufferstack[bufferstackidx].char_number = char_number;
		line_number = 1;
		char_number = 1;
		bufferstack[bufferstackidx].filename = input_name;
		input_name = filename;
	}
	else
		internal_error(__FILE__, __LINE__, "Pushing buffer without knowing where to go to");
	bufferstackidx++;
}

YY_BUFFER_STATE pop_buffer(void)
{
	if(bufferstackidx <= 0)
		return (YY_BUFFER_STATE)0;
	bufferstackidx--;
	if(bufferstack[bufferstackidx].define)
		bufferstack[bufferstackidx].define->expanding = 0;
	else
	{
		line_number = bufferstack[bufferstackidx].line_number;
		char_number = bufferstack[bufferstackidx].char_number;
		input_name = bufferstack[bufferstackidx].filename;
		fclose(yyin);
	}
	if(yydebug)
		printf("pop_buffer: %p %p (%d, %d) %p\n",
			bufferstack[bufferstackidx].bufferstate,
			bufferstack[bufferstackidx].define,
			bufferstack[bufferstackidx].line_number,
			bufferstack[bufferstackidx].char_number,
			bufferstack[bufferstackidx].filename);
	yy_switch_to_buffer(bufferstack[bufferstackidx].bufferstate);
	return bufferstack[bufferstackidx].bufferstate;
}

void do_include(char *name, int namelen)
{
	char *cpy = (char *)xmalloc(namelen);
	strcpy(cpy, name+1);	/* strip leading " or < */
	cpy[namelen-2] = '\0';	/* strip trailing " or > */
	if((yyin = open_include(cpy, name[0] == '"')) == NULL)
		yyerror("Unable to open include file %s", cpy);
	push_buffer(YY_CURRENT_BUFFER, NULL, cpy);
	yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
}


struct keyword {
	char	*keyword;
	int	token;
	int	isextension;
	int	needcase;
	int	alwayskeyword;
};

static struct keyword keywords[] = {
	{ "ACCELERATORS", ACCELERATORS, 0, 0, 0},
	{ "ALT", ALT, 0, 0, 0},
	{ "ASCII", ASCII, 0, 0, 0},
	{ "AUTO3STATE", AUTO3STATE, 1, 0, 0},
	{ "AUTOCHECKBOX", AUTOCHECKBOX, 1, 0, 0},
	{ "AUTORADIOBUTTON", AUTORADIOBUTTON, 1, 0, 0},
	{ "BEGIN", tBEGIN, 0, 0, 1},
	{ "BITMAP", tBITMAP, 0, 0, 0},
	{ "BLOCK", BLOCK, 0, 0, 1},
	{ "BUTTON", BUTTON, 1, 0, 0},
	{ "CAPTION", CAPTION, 0, 0, 0},
	{ "CHARACTERISTICS", CHARACTERISTICS, 1, 0, 0},
	{ "CHECKBOX", CHECKBOX, 0, 0, 0},
	{ "CHECKED", CHECKED, 0, 0, 0},
	{ "CLASS", CLASS, 0, 0, 0},
	{ "COMBOBOX", COMBOBOX, 0, 0, 0},
	{ "CONTROL", CONTROL, 0, 0, 0},
	{ "CTEXT", CTEXT, 0, 0, 0},
	{ "CURSOR", CURSOR, 0, 0, 0},
	{ "defined", tDEFINED, 0, 1, 1},
	{ "DEFPUSHBUTTON", DEFPUSHBUTTON, 0, 0, 1},
	{ "DIALOG", DIALOG, 0, 0, 0},
	{ "DIALOGEX", DIALOGEX, 1, 0, 0},
	{ "DISCARDABLE", DISCARDABLE, 0, 0, 0},
	{ "DLGINIT", DLGINIT, 0, 0, 0},
	{ "EDITTEXT", EDITTEXT, 0, 0, 0},
	{ "END", tEND, 0, 0, 1},
	{ "EXSTYLE", EXSTYLE, 0, 0, 0},
	{ "extern", tEXTERN, 0, 1, 1},
	{ "FILEFLAGS", FILEFLAGS, 0, 0, 0},
	{ "FILEFLAGSMASK", FILEFLAGSMASK, 0, 0, 0},
	{ "FILEOS", FILEOS, 0, 0, 0},
	{ "FILESUBTYPE", FILESUBTYPE, 0, 0, 0},
	{ "FILETYPE", FILETYPE, 0, 0, 0},
	{ "FILEVERSION", FILEVERSION, 0, 0, 0},
	{ "FIXED", tFIXED, 0, 0, 0},
	{ "FONT", FONT, 0, 0, 0},
	{ "GRAYED", GRAYED, 0, 0, 0},
	{ "GROUPBOX", GROUPBOX, 0, 0, 0},
	{ "HELP", HELP, 0, 0, 0},
	{ "ICON", ICON, 0, 0, 0},
	{ "IMPURE", IMPURE, 0, 0, 0},
	{ "INACTIVE", INACTIVE, 0, 0, 0},
	{ "LANGUAGE", LANGUAGE, 1, 0, 1},
	{ "LISTBOX", LISTBOX, 0, 0, 0},
	{ "LOADONCALL", LOADONCALL, 0, 0, 0},
	{ "LTEXT", LTEXT, 0, 0, 0},
	{ "MENU", MENU, 0, 0, 0},
	{ "MENUBARBREAK", MENUBARBREAK, 0, 0, 0},
	{ "MENUBREAK", MENUBREAK, 0, 0, 0},
	{ "MENUEX", MENUEX, 1, 0, 0},
	{ "MENUITEM", MENUITEM, 0, 0, 0},
	{ "MESSAGETABLE", MESSAGETABLE, 1, 0, 0},
	{ "MOVEABLE", MOVEABLE, 0, 0, 0},
	{ "NOINVERT", NOINVERT, 0, 0, 0},
	{ "NOT", NOT, 0, 0, 0},
	{ "POPUP", POPUP, 0, 0, 0},
	{ "PRELOAD", PRELOAD, 0, 0, 0},
	{ "PRODUCTVERSION", PRODUCTVERSION, 0, 0, 0},
	{ "PURE", tPURE, 0, 0, 0},
	{ "PUSHBUTTON", PUSHBUTTON, 0, 0, 0},
	{ "RADIOBUTTON", RADIOBUTTON, 0, 0, 0},
	{ "RCDATA", RCDATA, 0, 0, 0},
	{ "RTEXT", RTEXT, 0, 0, 0},
	{ "SCROLLBAR", SCROLLBAR, 0, 0, 0},
	{ "SEPARATOR", SEPARATOR, 0, 0, 0},
	{ "SHIFT", SHIFT, 0, 0, 0},
	{ "STATE3", STATE3, 1, 0, 0},
	{ "STRING", tSTRING, 0, 0, 0},
	{ "STRINGTABLE", STRINGTABLE, 0, 0, 1},
	{ "STYLE", STYLE, 0, 0, 0},
	{ "TOOLBAR", TOOLBAR, 1, 0, 0},
	{ "typedef", tTYPEDEF, 0, 1, 1},
	{ "VALUE", VALUE, 0, 0, 0},
	{ "VERSION", VERSION, 1, 0, 0},
	{ "VERSIONINFO", VERSIONINFO, 0, 0, 0},
	{ "VIRTKEY", VIRTKEY, 0, 0, 0}
};

#define NKEYWORDS	(sizeof(keywords)/sizeof(keywords[0]))
#define KWP(p)		((struct keyword *)(p))
int kw_cmp_func(const void *s1, const void *s2)
{
	int ret;
	ret = strcasecmp(KWP(s1)->keyword, KWP(s2)->keyword);
	if(!ret && (KWP(s1)->needcase || KWP(s2)->needcase))
		return strcmp(KWP(s1)->keyword, KWP(s2)->keyword);
	else
		return ret;
}

#define KW_BSEARCH
#define DO_SORT
struct keyword *iskeyword(char *kw)
{
	struct keyword *kwp;
	struct keyword key;
	key.keyword = kw;
	key.needcase = 0;
#ifdef DO_SORT
	{
		/* Make sure that it is sorted for bsearsh */
		static int sorted = 0;
		if(!sorted)
		{
			qsort(keywords, NKEYWORDS, sizeof(keywords[0]), kw_cmp_func);
			sorted = 1;
		}
	}
#endif
#ifdef KW_BSEARCH
	kwp = bsearch(&key, keywords, NKEYWORDS, sizeof(keywords[0]), kw_cmp_func);
#else
	{
		int i;
		for(i = 0; i < NKEYWORDS; i++)
		{
			if(!kw_cmp_func(&key, &keywords[i]))
				break;
		}
		if(i < NKEYWORDS)
			kwp = &keywords[i];
		else
			kwp = NULL;
	}
#endif

#ifdef LEX_DEBUG
	if(kwp && !strcmp(kwp->keyword, "LANGUAGE"))
		printf("Got Language\n");
#endif
	if(kwp == NULL || (kwp->isextension && !extensions))
		return NULL;
	else
		return kwp;
}

void add_to_substtext(char *text, int len)
{
	if(!substtext)
	{
		substtext = xstrdup(text);
	}
	else
	{
		substtext = (char *)xrealloc(substtext, strlen(substtext)+len+1);
		strcat(substtext, text);
	}
}

#line 1204 "lexyy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 410 "parser.l"

	/* #include handling */
#line 1357 "lexyy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 346 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1265 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 412 "parser.l"
push_to(pp_incl);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 413 "parser.l"
do_include(yytext, yyleng); pop_start();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 414 "parser.l"
do_include(yytext, yyleng); pop_start();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 415 "parser.l"
yyerror("Malformed #include");
	YY_BREAK
/* #define handling */
case 5:
YY_RULE_SETUP
#line 418 "parser.l"
push_to(pp_def);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 419 "parser.l"
{
				set_define(yytext);
				push_to(pp_def_s);
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 423 "parser.l"
push_to(pp_ignore); /* Ignore function-like defines for now*/
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 424 "parser.l"
yyerror("Malformed #define");
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 426 "parser.l"
{
			if(YY_START == pp_def_s)
				add_to_substtext(yytext, yyleng);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 430 "parser.l"
{ /* Comment is handled in normal handling */
			if(YY_START == pp_def_s)
				add_to_substtext(yytext, yyleng);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 434 "parser.l"
line_number++;	char_number = 1; /* Line continuation */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 435 "parser.l"
{
			if(YY_START == pp_def_s)
			{
				add_define(substtext ? substtext : "");
				free(substtext);
				substtext = NULL;
			}
			line_number++;
			char_number = 1;
			pop_start();
			pop_start();
		}
	YY_BREAK
/* #undef handling */
case 13:
YY_RULE_SETUP
#line 449 "parser.l"
push_to(pp_undef);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 450 "parser.l"
{
				del_define(yytext);
				pop_start();
				/*push_to(pp_ignore);*/
			}
	YY_BREAK
/* Conditional handling */
case 15:
YY_RULE_SETUP
#line 457 "parser.l"
{
			if(YY_START == pp_false)
			{
				if(yydebug)
					printf("(%d)#if ignored\n", line_number);
				push_if(0, 0, 1);
				push_to(pp_ignore_eol);
			}
			else
			{
				push_to(INITIAL);
				want_nl = 1;
				return tIF;
			}
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 472 "parser.l"
{
			if(YY_START == pp_false)
			{
				if(yydebug)
					printf("(%d)#ifdef ignored\n", line_number);
				push_if(0, 0, 1);
				push_to(pp_ignore_eol);
			}
			else
			{
				push_to(INITIAL);
				want_nl = 1;
				want_ident = 1;
				return tIFDEF;
			}
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 488 "parser.l"
{
			if(YY_START == pp_false)
			{
				if(yydebug)
					printf("(%d)#ifndef ignored\n", line_number);
				push_if(0, 0, 1);
				push_to(pp_ignore_eol);
			}
			else
			{
				push_to(INITIAL);
				want_nl = 1;
				want_ident = 1;
				return tIFNDEF;
			}
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 504 "parser.l"
{
			if(!isnevertrue_if())
			{
				push_to(INITIAL);
				want_nl = 1;
				return tELIF;
			}
			else if(YY_START == pp_false)
				push_to(pp_ignore_eol);
			if(yydebug)
				printf("(%d)#elif ignored\n", line_number);
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 516 "parser.l"
{
			if(!isnevertrue_if())
			{
				push_to(INITIAL);
				want_nl = 1;
				return tELSE;
			}
			if(yydebug)
				printf("(%d)#else ignored\n", line_number);
		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 526 "parser.l"
{
			if(!isnevertrue_if())
			{
				want_nl = 1;
				return tENDIF;
			}
			else
			{
				if(yydebug)
					printf("(%d)#endif ignored\n", line_number);
				pop_if();
			}
		}
	YY_BREAK
/* The error directive */
case 21:
YY_RULE_SETUP
#line 541 "parser.l"
push_to(pp_error);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 542 "parser.l"
yyerror("Error directive: %s", yytext);
	YY_BREAK
/* preprocessor junk */
case 23:
YY_RULE_SETUP
#line 545 "parser.l"
;	/* Ignore #pragma */
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 546 "parser.l"
;	/* Ignore #line */
	YY_BREAK
/* We'll get an error on malformed #xxx statements
  * by not recognising '#' at all. This helps tracking
  * preprocessor errors.
  */
/*^{ws}*#{ws}*			;	 Ignore # */
case 25:
YY_RULE_SETUP
#line 553 "parser.l"
stripslevel++;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 554 "parser.l"
stripslevel--;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 555 "parser.l"
if(!stripslevel) pop_start();
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 556 "parser.l"
; /* To catch comments */
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 557 "parser.l"
; /* Ignore rest */
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 559 "parser.l"
stripplevel++;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 560 "parser.l"
{
				stripplevel--;
				if(!stripplevel)
				{
					pop_start();
					push_to(pp_stripp_final);
				}
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 568 "parser.l"
; /* To catch comments */
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 569 "parser.l"
; /* Ignore rest */
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 571 "parser.l"
; /* Ignore */
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 572 "parser.l"
pop_start(); /* Kill the semicolon */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 573 "parser.l"
line_number++; char_number = 1; pop_start();
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 574 "parser.l"
yyless(0); pop_start();
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 576 "parser.l"
;	/* Ignore everything except #xxx during false #if state */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 578 "parser.l"
pop_start();
	YY_BREAK
/* These are special cases due to filename scanning */
case 40:
YY_RULE_SETUP
#line 581 "parser.l"
return DISCARDABLE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 582 "parser.l"
return tFIXED;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 583 "parser.l"
return IMPURE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 584 "parser.l"
return MOVEABLE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 585 "parser.l"
return LOADONCALL;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 586 "parser.l"
return PRELOAD;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 587 "parser.l"
return tPURE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 589 "parser.l"
return tBEGIN;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 590 "parser.l"
return tEND;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 592 "parser.l"
{ yylval.num = strtoul(yytext,  0, 10); return toupper(yytext[yyleng-1]) == 'L' ? LNUMBER : NUMBER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 593 "parser.l"
{ yylval.num = strtoul(yytext,  0, 16); return toupper(yytext[yyleng-1]) == 'L' ? LNUMBER : NUMBER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 594 "parser.l"
{ yylval.num = strtoul(yytext+2, 0, 8); return toupper(yytext[yyleng-1]) == 'L' ? LNUMBER : NUMBER; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 595 "parser.l"
{
				struct keyword *token;
				struct pp_entry *ppp;

				want_rscname = 0;
				
				if(want_ident)
				{
					/* Prevent preprocessor subst */
					want_ident = 0;
					yylval.str = make_string(yytext);
				#ifdef LEX_DEBUG
					printf("want IDENT (%s, %d, %d): <%s>\n", input_name, line_number, char_number, yytext);
				#endif
					return IDENT;
				}
				else if((ppp = pp_lookup(yytext)) != NULL)
				{
					/* Do preprocessor substitution,
					 * but expand only if macro is not
					 * already expanding.
					 */
					if(!ppp->expanding)
					{
				#ifdef LEX_DEBUG
						printf("expand IDENT (%s, %d, %d): <%s>\n", input_name, line_number, char_number, yytext);
				#endif
						push_buffer(YY_CURRENT_BUFFER, ppp, NULL);
						yy_scan_string(ppp->subst);
					}
				}
				else if((token = iskeyword(yytext)) != NULL
				  && !(!token->alwayskeyword && want_rscname))
				{
					switch(token->token)
					{
					case tDEFINED:
						want_ident = 1;
						break;
					/*case RCDATA:*/
					case CURSOR:
					case tBITMAP:
					case MESSAGETABLE:
					case DLGINIT:
						push_to(yywf);
						break;
					case FONT:
					case ICON:
						if(!indialog)
							push_to(yywf);
						break;
					case DIALOG:
					case DIALOGEX:
						indialog = 1;
						break;
					}
					return token->token;
				}
				else
				{
					yylval.str = make_string(yytext);
				#ifdef LEX_DEBUG
					printf("%s IDENT (%s, %d, %d): <%s>\n",
						want_rscname ? "rscname" : "just",
						input_name,
						line_number,
						char_number,
						yytext);
				#endif
					return IDENT;
				}
			}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 667 "parser.l"
return LOGOR;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 668 "parser.l"
return LOGAND;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 669 "parser.l"
return EQ;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 670 "parser.l"
return NE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 671 "parser.l"
return LTE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 672 "parser.l"
return GTE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 674 "parser.l"
{ pop_start(); yylval.str = make_filename(yytext, yyleng); return FILENAME; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 675 "parser.l"
push_to(yywf_s);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 676 "parser.l"
{ pop_start(); pop_start(); yylval.str = make_filename(yytext, yyleng-1); return FILENAME; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 677 "parser.l"
yyerror("Newline in filename");
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 679 "parser.l"
{
				push_to(yylstr);
				wbufidx = 0;
				if(!win32)
					yywarning("16bit resource contains unicode strings\n");
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 685 "parser.l"
{
				pop_start();
				yylval.str = get_buffered_wstring();
				return tSTRING;
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 690 "parser.l"
yyerror("Unterminated string");
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 691 "parser.l"
{ /* octal escape sequence */
				int result;
				result = strtol(yytext+1, 0, 8);
				if ( result > 0xffff )
					yyerror("Character constant out of range");
				addwchar((short)result);
			}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 698 "parser.l"
{  /* hex escape sequence */
				int result;
				result = strtol(yytext+2, 0, 16);
				addwchar((short)result);
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 703 "parser.l"
yyerror("Bad escape secuence");
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 704 "parser.l"
addwchar('\a');
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 705 "parser.l"
addwchar('\b');
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 706 "parser.l"
addwchar('\f');
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 707 "parser.l"
addwchar('\n');
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 708 "parser.l"
addwchar('\r');
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 709 "parser.l"
addwchar('\t');
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 710 "parser.l"
addwchar('\v');
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 711 "parser.l"
addwchar(yytext[1]);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 712 "parser.l"
addcchar('\"');		/* "bla""bla"  -> "bla\"bla" */
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 713 "parser.l"
addcchar('\"');		/* "bla\""bla" -> "bla\"bla" */
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 714 "parser.l"
;			/* "bla" "bla" -> "blabla" */
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 715 "parser.l"
{
				char *yptr = yytext;
				while(*yptr)	/* FIXME: codepage translation */
					addwchar(*yptr++ & 0xff);
			}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 721 "parser.l"
{
				push_to(yystr);
				cbufidx = 0;
			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 725 "parser.l"
{
				pop_start();
				yylval.str = get_buffered_cstring();
				return tSTRING;
			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 730 "parser.l"
yyerror("Unterminated string");
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 731 "parser.l"
{ /* octal escape sequence */
				int result;
				result = strtol(yytext+1, 0, 8);
				if ( result > 0xff )
					yyerror("Character constant out of range");
				addcchar((char)result);
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 738 "parser.l"
{  /* hex escape sequence */
				int result;
				result = strtol(yytext+2, 0, 16);
				addcchar((char)result);
			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 743 "parser.l"
yyerror("Bad escape secuence");
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 744 "parser.l"
addcchar('\a');
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 745 "parser.l"
addcchar('\b');
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 746 "parser.l"
addcchar('\f');
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 747 "parser.l"
addcchar('\n');
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 748 "parser.l"
addcchar('\r');
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 749 "parser.l"
addcchar('\t');
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 750 "parser.l"
addcchar('\v');
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 751 "parser.l"
addcchar(yytext[1]);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 752 "parser.l"
{
				char *yptr = yytext;
				while(*yptr)
					addcchar(*yptr++);
			}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 757 "parser.l"
addcchar('\"');		/* "bla""bla"   -> "bla\"bla" */
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 758 "parser.l"
addcchar('\"');		/* "bla\""bla"  -> "bla\"bla" */
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 759 "parser.l"
;			/* "bla" "bla"  -> "blabla" */
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 760 "parser.l"
yywarning("Matched %c");
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 763 "parser.l"
{
				push_to(yyrcd);
				cbufidx = 0;
			}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 767 "parser.l"
{
				pop_start();
				yylval.raw = new_raw_data();
				yylval.raw->size = cbufidx;
				yylval.raw->data = xmalloc(yylval.raw->size);
				memcpy(yylval.raw->data, cbuffer, yylval.raw->size);
				return RAWDATA;
			}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 775 "parser.l"
{
				int result;
				result = strtol(yytext, 0, 16);
				addcchar((char)result);
			}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 780 "parser.l"
;	/* Ignore space */
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 781 "parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 782 "parser.l"
yyerror("Malformed data-line");
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 784 "parser.l"
push_to(comment);	/* Eat comment */
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 785 "parser.l"
;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 786 "parser.l"
;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 787 "parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 788 "parser.l"
pop_start();
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 790 "parser.l"
; /* Eat comment */
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 791 "parser.l"
; /* Eat comment */
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 793 "parser.l"
{
				if(YY_START == yywf)
					pop_start();
				line_number++;
				char_number = 1;
				if(want_nl)
				{
					want_nl = 0;
					return tNL;
				}
			}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 804 "parser.l"
;	/* Eat whitespace */
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 806 "parser.l"
return yytext[0];
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(yywf):
case YY_STATE_EOF(yywf_s):
case YY_STATE_EOF(yystr):
case YY_STATE_EOF(yylstr):
case YY_STATE_EOF(yyrcd):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(pp_incl):
case YY_STATE_EOF(pp_def):
case YY_STATE_EOF(pp_undef):
case YY_STATE_EOF(pp_if):
case YY_STATE_EOF(pp_ifdef):
case YY_STATE_EOF(pp_ifndef):
case YY_STATE_EOF(pp_elif):
case YY_STATE_EOF(pp_else):
case YY_STATE_EOF(pp_endif):
case YY_STATE_EOF(pp_error):
case YY_STATE_EOF(pp_def_s):
case YY_STATE_EOF(pp_ignore):
case YY_STATE_EOF(pp_ignore_eol):
case YY_STATE_EOF(pp_false):
case YY_STATE_EOF(pp_strips):
case YY_STATE_EOF(pp_stripp):
case YY_STATE_EOF(pp_stripp_final):
#line 807 "parser.l"
{
				YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
				if(!pop_buffer())
                                {
					if(YY_START == pp_strips || YY_START == pp_stripp || YY_START == pp_stripp_final)
						yyerror("Unexpected end of file during c-junk scanning (started at %d)", cjunk_tagline);
					else
						yyterminate();
                                }
				yy_delete_buffer(b);
			}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 819 "parser.l"
{
				/* Catch all rule to find any unmatched text */
				if(*yytext == '\n')
				{
					line_number++;
					char_number = 1;
				}
				yywarning("Unmatched text '%c' (0x%02x) YY_START=%d",
					isprint(*yytext) ? *yytext : '.', *yytext, YY_START);
			}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 830 "parser.l"
ECHO;
	YY_BREAK
#line 2329 "lexyy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 346 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 346 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 345);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 830 "parser.l"


#ifndef yywrap
int yywrap(void)
{
#if 0
	if(bufferstackidx > 0)
	{
		return 0;
 	}
#endif
	return 1;
}
#endif

/* These dup functions copy the enclosed '\0' from
 * the resource string.
 */
void addcchar(char c)
{
	if(cbufidx >= cbufalloc)
	{
		cbufalloc += 1024;
		cbuffer = xrealloc(cbuffer, cbufalloc * sizeof(cbuffer[0]));
		if(cbufalloc > 65536)
			yywarning("Reallocating string buffer larger than 64kB");
	}
	cbuffer[cbufidx++] = c;
}

void addwchar(short s)
{
	if(wbufidx >= wbufalloc)
	{
		wbufalloc += 1024;
		wbuffer = xrealloc(wbuffer, wbufalloc * sizeof(wbuffer[0]));
		if(wbufalloc > 65536)
			yywarning("Reallocating wide string buffer larger than 64kB");
	}

	/*
	 * BS 08-Aug-1999 FIXME: The '& 0xff' is probably a bug, but I have
	 * not experienced it yet and I seem to remember that this was for
	 * a reason. But, as so many things you tend to forget why.
	 * I guess that there were problems due to the sign extension of
	 * shorts WRT chars (e.g. 0x80 becomes 0xff80 instead of 0x0080).
	 * This should then be fixed in the lexer calling the function.
	 */
	wbuffer[wbufidx++] = (short)(s & 0xff);
}

string_t *get_buffered_cstring(void)
{
	string_t *str = new_string();
	str->size = cbufidx;
	str->type = str_char;
	str->str.cstr = (char *)xmalloc(cbufidx+1);
	memcpy(str->str.cstr, cbuffer, cbufidx);
	str->str.cstr[cbufidx] = '\0';
/*	printf("got cstring \"%s\"\n", str->str.cstr); */
	return str;
}

string_t *get_buffered_wstring(void)
{
	string_t *str = new_string();
	str->size = wbufidx;
	str->type = str_unicode;
	str->str.wstr = (short *)xmalloc(2*(wbufidx+1));
	memcpy(str->str.wstr, wbuffer, wbufidx);
	str->str.wstr[wbufidx] = 0;
	return str;
}

string_t *make_string(char *s)
{
	string_t *str = new_string();
	str->size = strlen(s);
	str->type = str_char;
	str->str.cstr = (char *)xmalloc(str->size+1);
	memcpy(str->str.cstr, s, str->size+1);
	return str;
}

string_t *make_filename(char *s, int len)
{
	char *cptr;
	string_t *str = new_string();

	str->size = len;
	str->type = str_char;
	str->str.cstr = (char *)xmalloc(str->size+1);
	memcpy(str->str.cstr, s, str->size);
	str->str.cstr[str->size] = '\0';

	/* Remove escaped backslash and convert to forward */
	cptr = str->str.cstr;
	for(cptr = str->str.cstr; (cptr = strchr(cptr, '\\')) != NULL; cptr++)
	{
		if(cptr[1] == '\\')
		{
			memmove(cptr, cptr+1, strlen(cptr));
			str->size--;
		}
		*cptr = '/';
	}

	/* Convert to lower case. Seems to be reasonable to do */
	for(cptr = str->str.cstr; !leave_case && *cptr; cptr++)
	{
		*cptr = tolower(*cptr);
	}
	return str;
}

/* Called from the parser to signal filename request */
void set_yywf(void)
{
	push_to(yywf);
}

/* Called from the parser to signal preprocessor if case */
void set_pp_ignore(int state)
{
	if(state)
		push_to(pp_false);
	else
		pop_start();
}

/* Called from the parser to kill c-junk */
void strip_til_semicolon(void)
{
	cjunk_tagline = line_number;
	push_to(pp_strips);
}

void strip_til_parenthesis(void)
{
	cjunk_tagline = line_number;
	stripplevel = 1;	/* One scanned already */
	push_to(pp_stripp);
}


