# $Id: makefile,v 1.1 2001-11-19 12:32:25 sandervl Exp $

#
# Odin32 API
#
#       common.lib makefile
#


#
# Tell buildenvironmet to build an object library.
#
LIBTARGET = 1
EXETARGET = 1
PUBLICLIB = 1


#
# Compiler, tools, and interference rules.
#
!include ../../makefile.inc


#
# Object files. Prefix with OBJDIR and one space before the '\'.
#
OBJS = \
$(OBJDIR)\guid.obj 

#
# Target name - name of the library without extention and path.
#
TARGET  = guidlib


#
# Includes the common rules.
#
!include $(ODIN32_POST_INC)

