/* $Id: advapi32.h,v 1.7 2000-01-06 20:05:00 sandervl Exp $ */

/*
 * Win32 advanced API functions for OS/2
 *
 * 1998/06/12
 *
 * Copyright 1998 Sander van Leeuwen
 * Copyright 1998 Patrick Haller
 *
 *
 * Project Odin Software License can be found in LICENSE.TXT
 *
 */

#ifndef __ADVAPI32_H__
#define __ADVAPI32_H__

// IsTextUnicode
#define IS_TEXT_UNICODE_ASCII16               0x0001
#define IS_TEXT_UNICODE_REVERSE_ASCII16       0x0010

#define IS_TEXT_UNICODE_STATISTICS            0x0002
#define IS_TEXT_UNICODE_REVERSE_STATISTICS    0x0020

#define IS_TEXT_UNICODE_CONTROLS              0x0004
#define IS_TEXT_UNICODE_REVERSE_CONTROLS      0x0040

#define IS_TEXT_UNICODE_SIGNATURE             0x0008
#define IS_TEXT_UNICODE_REVERSE_SIGNATURE     0x0080

#define IS_TEXT_UNICODE_ILLEGAL_CHARS         0x0100
#define IS_TEXT_UNICODE_ODD_LENGTH            0x0200
#define IS_TEXT_UNICODE_DBCS_LEADBYTE         0x0400
#define IS_TEXT_UNICODE_NULL_BYTES            0x1000

#define IS_TEXT_UNICODE_UNICODE_MASK          0x000F
#define IS_TEXT_UNICODE_REVERSE_MASK          0x00F0
#define IS_TEXT_UNICODE_NOT_UNICODE_MASK      0x0F00
#define IS_TEXT_UNICODE_NOT_ASCII_MASK        0xF000


/*****************************************************************************
 * Prototypes                                                                *
 *****************************************************************************/

LONG      ODIN_INTERNAL ODIN_RegConnectRegistryA(LPCSTR,HKEY,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegConnectRegistryW(LPCWSTR,HKEY,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegEnumKeyExA(HKEY,DWORD,LPSTR,LPDWORD,LPDWORD,LPSTR,LPDWORD,LPFILETIME);
LONG      ODIN_INTERNAL ODIN_RegEnumKeyExW(HKEY,DWORD,LPWSTR,LPDWORD,LPDWORD,LPWSTR,LPDWORD,LPFILETIME);
LONG      ODIN_INTERNAL ODIN_RegGetKeySecurity(HKEY,SECURITY_INFORMATION,PSECURITY_DESCRIPTOR,LPDWORD);
LONG      ODIN_INTERNAL ODIN_RegLoadKeyA(HKEY,LPCSTR,LPCSTR);
LONG      ODIN_INTERNAL ODIN_RegLoadKeyW(HKEY,LPCWSTR,LPCWSTR);
LONG      ODIN_INTERNAL ODIN_RegNotifyChangeKeyValue(HKEY,BOOL,DWORD,HANDLE,BOOL);
LONG      ODIN_INTERNAL ODIN_RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegOpenKeyExA(HKEY,LPCSTR,DWORD,REGSAM,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegQueryInfoKeyW(HKEY,LPWSTR,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPFILETIME);
LONG      ODIN_INTERNAL ODIN_RegQueryInfoKeyA(HKEY,LPSTR,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPDWORD,LPFILETIME);
LONG      ODIN_INTERNAL ODIN_RegReplaceKeyA(HKEY,LPCSTR,LPCSTR,LPCSTR);
LONG      ODIN_INTERNAL ODIN_RegReplaceKeyW(HKEY,LPCWSTR,LPCWSTR,LPCWSTR);
LONG      ODIN_INTERNAL ODIN_RegRestoreKeyA(HKEY,LPCSTR,DWORD);
LONG      ODIN_INTERNAL ODIN_RegRestoreKeyW(HKEY,LPCWSTR,DWORD);
LONG      ODIN_INTERNAL ODIN_RegUnLoadKeyA(HKEY,LPCSTR);
LONG      ODIN_INTERNAL ODIN_RegUnLoadKeyW(HKEY,LPCWSTR);
LONG      ODIN_INTERNAL ODIN_RegCloseKey(HKEY);
LONG      ODIN_INTERNAL ODIN_RegFlushKey(HKEY);
LONG      ODIN_INTERNAL ODIN_RegCreateKeyA(HKEY,LPCSTR,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegCreateKeyW(HKEY,LPCWSTR,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegDeleteKeyA(HKEY,LPCSTR);
LONG      ODIN_INTERNAL ODIN_RegDeleteKeyW(HKEY,LPWSTR);
LONG      ODIN_INTERNAL ODIN_RegDeleteValueA(HKEY,LPSTR);
LONG      ODIN_INTERNAL ODIN_RegDeleteValueW(HKEY,LPWSTR);
LONG      ODIN_INTERNAL ODIN_RegEnumKeyA(HKEY,DWORD,LPSTR,DWORD);
LONG      ODIN_INTERNAL ODIN_RegEnumKeyW(HKEY,DWORD,LPWSTR,DWORD);
LONG      ODIN_INTERNAL ODIN_RegEnumValueA(HKEY,DWORD,LPSTR,LPDWORD,LPDWORD,LPDWORD,LPBYTE,LPDWORD);
LONG      ODIN_INTERNAL ODIN_RegEnumValueW(HKEY,DWORD,LPWSTR,LPDWORD,LPDWORD,LPDWORD,LPBYTE,LPDWORD);
LONG      ODIN_INTERNAL ODIN_RegOpenKeyA(HKEY,LPCSTR,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegOpenKeyW(HKEY,LPCWSTR,LPHKEY);
LONG      ODIN_INTERNAL ODIN_RegQueryValueA(HKEY,LPCSTR,LPSTR,LPLONG);
LONG      ODIN_INTERNAL ODIN_RegQueryValueW(HKEY,LPCWSTR,LPWSTR,LPLONG);
LONG      ODIN_INTERNAL ODIN_RegQueryValueExA(HKEY,LPSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD);
LONG      ODIN_INTERNAL ODIN_RegQueryValueExW(HKEY,LPWSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD);
LONG      ODIN_INTERNAL ODIN_RegSetValueA(HKEY,LPCSTR,DWORD,LPCSTR,DWORD);
LONG      ODIN_INTERNAL ODIN_RegSetValueW(HKEY,LPCWSTR,DWORD,LPCWSTR,DWORD);
LONG      ODIN_INTERNAL ODIN_RegSetValueExA(HKEY,LPSTR,DWORD,DWORD,LPBYTE,DWORD);
LONG      ODIN_INTERNAL ODIN_RegSetValueExW(HKEY,LPWSTR,DWORD,DWORD,LPBYTE,DWORD);
LONG      ODIN_INTERNAL ODIN_RegCreateKeyExA(HKEY,LPCSTR,DWORD,LPSTR,DWORD,REGSAM,LPSECURITY_ATTRIBUTES,PHKEY,LPDWORD);
LONG      ODIN_INTERNAL ODIN_RegCreateKeyExW(HKEY,LPCWSTR,DWORD,LPWSTR,DWORD,REGSAM,LPSECURITY_ATTRIBUTES,PHKEY,LPDWORD);

#ifdef USE_ODIN_REGISTRY_APIS
#define RegConnectRegistryA ODIN_RegConnectRegistryA
#define RegConnectRegistryW ODIN_RegConnectRegistryW
#define RegEnumKeyExA ODIN_RegEnumKeyExA
#define RegEnumKeyExW ODIN_RegEnumKeyExW
#define RegGetKeySecurity ODIN_RegGetKeySecurity
#define RegLoadKeyA ODIN_RegLoadKeyA
#define RegLoadKeyW ODIN_RegLoadKeyW
#define RegNotifyChangeKeyValue ODIN_RegNotifyChangeKeyValue
#define RegOpenKeyExW ODIN_RegOpenKeyExW
#define RegOpenKeyExA ODIN_RegOpenKeyExA
#define RegQueryInfoKeyW ODIN_RegQueryInfoKeyW
#define RegQueryInfoKeyA ODIN_RegQueryInfoKeyA
#define RegReplaceKeyA ODIN_RegReplaceKeyA
#define RegReplaceKeyW ODIN_RegReplaceKeyW
#define RegRestoreKeyA ODIN_RegRestoreKeyA
#define RegRestoreKeyW ODIN_RegRestoreKeyW
#define RegUnLoadKeyA ODIN_RegUnLoadKeyA
#define RegUnLoadKeyW ODIN_RegUnLoadKeyW
#define RegCloseKey ODIN_RegCloseKey
#define RegFlushKey ODIN_RegFlushKey
#define RegCreateKeyA ODIN_RegCreateKeyA
#define RegCreateKeyW ODIN_RegCreateKeyW
#define RegDeleteKeyA ODIN_RegDeleteKeyA
#define RegDeleteKeyW ODIN_RegDeleteKeyW
#define RegDeleteValueA ODIN_RegDeleteValueA
#define RegDeleteValueW ODIN_RegDeleteValueW
#define RegEnumKeyA ODIN_RegEnumKeyA
#define RegEnumKeyW ODIN_RegEnumKeyW
#define RegEnumValueA ODIN_RegEnumValueA
#define RegEnumValueW ODIN_RegEnumValueW
#define RegOpenKeyA ODIN_RegOpenKeyA
#define RegOpenKeyW ODIN_RegOpenKeyW
#define RegQueryValueA ODIN_RegQueryValueA
#define RegQueryValueW ODIN_RegQueryValueW
#define RegQueryValueExA ODIN_RegQueryValueExA
#define RegQueryValueExW ODIN_RegQueryValueExW
#define RegSetValueA ODIN_RegSetValueA
#define RegSetValueW ODIN_RegSetValueW
#define RegSetValueExA ODIN_RegSetValueExA
#define RegSetValueExW ODIN_RegSetValueExW
#define RegCreateKeyExA ODIN_RegCreateKeyExA
#define RegCreateKeyExW ODIN_RegCreateKeyExW
#endif

#endif
