/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/ktk/tmp/odin/2007/netlabs.cvs/odin32/tools/wrc/lexyy.c,v 1.2 2000-04-19 14:44:58 sandervl Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 124
#define YY_END_OF_BUFFER 125
static yyconst short int yy_accept[369] =
    {   0,
        0,    0,   66,   66,    0,    0,    0,    0,    0,    0,
        0,    0,  114,  114,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,   22,    9,    9,    9,    9,   46,   46,
        0,    0,   36,   36,   31,   31,   40,   40,   41,   41,
      125,  122,  121,  120,  122,   88,  122,  107,  122,   56,
       56,  118,  122,  122,  122,   59,   59,   54,  122,   55,
      121,  122,   66,  121,   67,   66,   66,   66,   66,   66,
       66,  123,   69,   68,  102,   90,   89,  106,   87,   72,
       71,  123,  112,  110,  111,  108,  112,  114,  116,  115,

        4,  123,    4,    4,    8,    6,   14,   22,    9,   12,
      123,  123,   46,   45,   45,   45,   36,  123,   34,   32,
       33,   36,  123,   31,  123,   29,   27,   28,   31,   40,
       37,   38,  123,   40,   44,   41,   43,   42,  121,   63,
       61,  113,  119,   56,   59,   56,   59,   59,  118,   64,
       62,   65,   70,   60,  121,    0,    0,    0,    0,    0,
        0,    0,    0,   66,   66,   66,   66,   66,   66,   66,
       66,    0,   68,  102,    0,  103,  101,  101,   91,   93,
       94,   95,   96,   97,   98,   99,  100,  101,   87,    0,
       84,   83,   83,   73,   75,   76,   77,   78,   79,   80,

       81,   82,   83,  110,  109,  114,  115,  115,  117,    0,
        0,    7,    6,   14,   22,    9,   10,    0,   11,   46,
        0,    0,    0,    0,    0,   36,   35,   36,    0,    0,
       31,   30,   31,   40,   39,   40,   41,  119,   58,   57,
        0,    0,    0,    0,    0,   15,    0,    0,    0,    0,
       66,   66,   66,   66,   66,   66,   66,  105,  104,   91,
       93,    0,   86,   85,   73,   75,    0,    3,    2,   10,
        0,   58,   57,    0,    0,    0,    0,    0,    0,   15,
        0,    0,    0,    0,    0,    0,   66,   66,   66,   66,
       66,   66,   53,   91,   92,   73,    0,    0,    0,   18,

       19,    0,    0,    0,    0,    0,    0,   26,    0,    0,
       66,   48,   66,   66,   66,   66,   73,    0,    0,    0,
       18,   19,   20,   21,   25,   16,    0,    0,   26,    0,
       13,   66,   49,   66,   66,   66,   73,   74,   23,    5,
       20,   21,   25,   16,   17,    0,   24,   13,   66,   66,
       66,   52,   73,   23,    5,   17,    1,   24,   66,   66,
       50,    1,   66,   66,   66,   51,   47,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    9,
       10,   11,    1,    1,    1,    1,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   26,   27,   26,   26,   28,   29,   30,   31,   32,
       26,   33,   34,   26,   35,   36,   26,   37,   26,   26,
        1,   38,    1,    1,   26,    1,   39,   40,   41,   42,

       43,   44,   45,   26,   46,   26,   26,   47,   48,   49,
       50,   51,   26,   52,   53,   54,   55,   56,   26,   57,
       26,   26,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    2,    3,    1,    4,    5,    1,    1,    6,    7,
        8,    9,   10,   10,   10,    5,    1,    1,   11,   10,
       10,   10,   10,   10,   10,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   10,   10,
       10,   10,   10,   10,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   14,    1,   14
    } ;

static yyconst short int yy_base[425] =
    {   0,
        0,   60,  119,  169,   17,   18,   42,   43,   46,   47,
      219,  262,   21,   22,   24,   37,  306,  366,  426,  486,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0, 1053, 1048,   79,   87,   89,   90, 1030, 1021,
     1020,   28,   94,  127,  120,  187,  323,  339,   41,   92,
     1005, 1334,  994, 1334,  977, 1334,  974, 1334,   24,  241,
      191,    0,  950,  949,  948,    0,  948, 1334,  619, 1334,
       81,  113,    0,  675, 1334,   10,   59,   83,   85,  103,
      174,  671, 1334, 1334,    0, 1334,  102,  542,    0, 1334,
      109,  595, 1334,  673, 1334, 1334,    0,    0, 1334,  126,

     1334, 1334,    0,    0, 1334,  665,    0,    0,    0, 1334,
      129,  147,    0, 1334,  107,  206,    0,  662, 1334, 1334,
     1334,  156,  246,    0,  661, 1334, 1334, 1334,  167,    0,
     1334, 1334,  660,  173, 1334,  668, 1334, 1334,  667, 1334,
     1334, 1334,    0,  253,    0,    0,  163,  640,    0, 1334,
     1334, 1334, 1334, 1334,  180,  344,  350,  625,  176,  139,
      621,  614,  610,    0,  157,  193,  163,  192,  215,  194,
      247,  653, 1334,    0,  325, 1334, 1334,  652,  281,  323,
     1334, 1334, 1334, 1334, 1334, 1334, 1334,    0,    0,  326,
     1334, 1334,  651,  343,  346, 1334, 1334, 1334, 1334, 1334,

     1334, 1334,    0,  648, 1334,    0,  224,  262, 1334,  643,
      627, 1334,  636,    0,    0,    0,    0,  351, 1334,    0,
      341,  360,  406,  363,   11,    0, 1334,  392,  412,  419,
        0, 1334,  407,    0, 1334,  414,  641,    0,  433,  372,
      598,   43,  599,  588,  595,  465,  596,  587,  594,  590,
      428,  430,  367,  433,  436,  478,  484, 1334, 1334,  463,
      468,    0, 1334, 1334,  496,  502,    0,  626, 1334,    0,
      578,    0,    0,  583,  584,  584,  580,  575,  575,  621,
      579,  579,  573,  576,  573,  574,  492,  490,  485,  488,
      500,  490,    0,  515, 1334,  520,    0,  566,  566,  612,

      611,  568,  559,  553,  561,  561,  546,    0,  549,  548,
      489,    0,  499,  513,  527,  529,  537,    0,  538,  546,
      586,  573,  534,  524,    0,  469,  424,  409,    0,  409,
      421,  530,    0,  532,  530,  536,  550, 1334,    0,  416,
      415,  387,    0,  386,  361,  307,    0,  338,  540,  541,
      542,    0,  556,    0,  332,  288,  277,    0,  553,  548,
        0,  244,  555,  556,  563,    0,    0, 1334,  684,  698,
      712,  726,  740,  754,  768,  782,  796,  810,  824,  838,
      852,  866,  880,  894,  908,  922,  936,  190,  950,  964,
      978,  992, 1006, 1020, 1034,  214, 1048, 1062, 1076, 1090,

     1099,  462, 1111, 1125, 1139, 1153, 1167, 1180, 1194, 1207,
     1221, 1235, 1249,  174,  147, 1263,  135,   93,   29, 1277,
       16, 1291, 1305, 1319
    } ;

static yyconst short int yy_def[425] =
    {   0,
      369,  369,  370,  370,  371,  371,  372,  372,  373,  373,
      374,  374,  375,  375,  376,  376,  377,  377,  378,  378,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  380,  380,  381,  381,  381,  381,  382,  382,
      383,  383,  384,  384,  385,  385,  386,  386,  387,  387,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  388,
      388,  389,  368,  368,  368,  388,  388,  368,  368,  368,
      368,  368,  390,  368,  368,  390,  390,  390,  390,  390,
      390,  391,  368,  368,  392,  368,  368,  393,  394,  368,
      368,  395,  368,  368,  368,  368,  396,  397,  368,  398,

      368,  368,  399,  400,  368,  401,  402,  403,  404,  368,
      405,  368,  406,  368,  368,  368,  407,  408,  368,  368,
      368,  407,  368,  409,  410,  368,  368,  368,  409,  411,
      368,  368,  412,  411,  368,  368,  368,  368,  368,  368,
      368,  368,  413,  388,  388,  388,  388,  388,  389,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  390,  390,  390,  390,  390,  390,  390,
      390,  391,  368,  392,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  414,  394,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  415,  368,  368,  397,  398,  398,  368,  399,
      400,  368,  401,  402,  403,  404,  416,  368,  368,  406,
      368,  368,  368,  368,  368,  407,  368,  407,  368,  368,
      409,  368,  409,  411,  368,  411,  368,  413,  388,  148,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      390,  390,  390,  390,  390,  390,  390,  368,  368,  368,
      368,  417,  368,  368,  368,  368,  418,  399,  368,  416,
      368,  388,  388,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  390,  390,  390,  390,
      390,  390,  390,  368,  368,  368,  419,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  420,  368,  368,
      390,  390,  390,  390,  390,  390,  368,  421,  368,  368,
      368,  368,  368,  368,  422,  368,  368,  368,  420,  368,
      368,  390,  390,  390,  390,  390,  368,  368,  423,  368,
      368,  368,  422,  368,  368,  368,  424,  368,  390,  390,
      390,  390,  368,  423,  368,  368,  368,  424,  390,  390,
      390,  368,  390,  390,  390,  390,  390,    0,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368
    } ;

static yyconst short int yy_nxt[1395] =
    {   0,
       52,   53,   54,   55,   56,   52,   57,   58,   52,   52,
       52,   59,   60,   61,   61,   62,   63,   64,   65,   83,
       83,   84,   84,   99,   99,  338,  102,   67,  103,  115,
       54,  100,  100,  116,  142,  143,  165,   52,  318,  102,
      104,  103,  136,  137,   86,   86,   87,   87,   90,   90,
       91,   91,  245,  104,  246,  165,  138,   68,   69,   70,
       52,   71,   54,   55,   56,   72,   57,   58,   52,   52,
       52,   59,   60,   61,   61,   62,   63,   64,   65,   88,
       88,  110,  155,   92,   92,  166,  156,   67,  275,  110,
      111,  110,  110,  136,  137,  276,   54,   52,  111,  102,

      111,  111,  297,  175,  166,  118,  176,  138,  221,  119,
      190,  167,  222,  191,  157,  168,  112,   68,   69,   70,
       74,   54,   54,   75,  112,  102,  112,  112,  122,   54,
      167,  125,  123,  169,  168,  126,  208,  209,  118,  142,
      143,   76,  119,   77,  295,   78,   79,   80,  218,  219,
       81,  120,  169,  121,  158,  159,  267,  228,  160,  161,
       76,  229,   77,  162,   78,   79,   80,  163,  233,   81,
       74,   54,  229,   75,  236,  239,  239,  127,  229,  128,
      245,  155,  246,  262,  120,  156,  121,  247,  129,   54,
      251,   76,  123,   77,  253,   78,   79,   80,  125,  145,

       81,  145,  126,  144,  144,  144,  170,  223,  171,  251,
       76,  254,   77,  253,   78,   79,   80,  256,  146,   81,
       94,   95,  242,  205,  243,  170,   96,  244,  171,  252,
      254,   97,   97,   97,  368,  368,  256,  146,   97,   97,
       97,   97,   97,   97,  127,  362,  128,  230,  224,  252,
      255,  225,  161,  144,  144,  144,  162,   97,   97,   97,
       97,   97,   97,   94,   95,  144,  144,  144,  146,   96,
      255,  147,  208,  209,   97,   97,   97,  148,  362,  257,
      146,   97,   97,   97,   97,   97,   97,  146,  159,  356,
      147,  225,  161,  260,  260,  261,  162,  148,  257,  146,

       97,   97,   97,   97,   97,   97,  105,  105,  102,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,   54,  175,  190,  102,  258,
      263,  131,  132,  355,  133,  261,  261,  261,  102,  348,
      134,   54,  221,  105,  123,  157,  222,  131,  132,  357,
      133,  157,  218,  219,  102,  265,  265,  266,  266,  266,
      266,  223,  356,  105,  105,  105,  105,  105,  102,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  158,  159,  344,  342,  160,
      161,  158,  159,  228,  162,  160,  161,  229,  163,  273,

      162,  289,  224,  105,  163,  225,  161,  223,  233,  242,
      162,  243,  229,  230,  271,  236,  341,  355,  273,  229,
      230,  289,  348,  105,  105,  105,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  239,  239,  347,  224,  287,
      346,  225,  161,  288,  159,  290,  162,  225,  161,  291,
      272,  159,  162,  102,  225,  161,  280,  345,  287,  162,
      344,  214,  288,  214,  290,  294,  294,  261,  291,  272,
      261,  261,  261,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,  102,  102,  292,  281,  293,  296,  296,
      266,  311,  312,  282,  266,  266,  266,  313,  314,  315,
      316,  332,  333,  102,  292,  342,  293,  261,  261,  261,
      311,  312,  317,  317,  266,  341,  313,  314,  315,  316,
      332,  333,  334,  102,  102,  102,  178,  335,  336,  337,
      337,  266,  349,  350,  179,  179,  180,  351,  352,  359,
      360,  334,  353,  353,  266,  361,  335,  336,  266,  266,
      266,  349,  350,  363,  322,  364,  351,  352,  359,  360,
      181,  182,  365,  366,  361,  183,  367,  321,  340,  339,
      184,  331,  363,  185,  364,  186,  330,  187,  188,  193,

      328,  365,  366,  327,  326,  367,  325,  194,  194,  195,
      324,  323,  322,  321,  320,  319,  310,  309,  308,  307,
      306,  305,  280,  304,  303,  302,  301,  300,  299,  298,
      268,  286,  285,  196,  197,  284,  283,  279,  198,  278,
      277,  274,  237,  199,  212,  269,  200,  268,  201,  204,
      202,  203,  240,  240,  240,  264,  259,  173,  250,  240,
      240,  240,  240,  240,  240,  249,  248,  241,  139,  237,
      142,  142,  142,  212,  204,  173,  139,  154,  240,  240,
      240,  240,  240,  240,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   73,   73,

       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  106,  106,  106,  106,

      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  117,  117,  117,  117,  117,  117,

      117,  117,  117,  117,  117,  117,  117,  117,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      149,  149,  153,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  164,  152,  151,  150,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  172,  172,
      141,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  174,  174,  140,  139,  174,  174,  174,  174,

      174,  174,  174,  174,  368,  174,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      189,  189,   54,  102,  189,  189,  189,  189,  189,  189,
      189,  189,  102,  189,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  206,  206,
      102,  206,  206,  206,  206,  102,  206,  206,  206,  206,
      206,  206,  207,  207,  368,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  210,  210,  368,  210,
      210,  210,  210,  210,  210,  210,  368,  210,  210,  210,
      211,  211,  368,  211,  211,  211,  211,  211,  211,  211,

      368,  211,  211,  211,  213,  368,  368,  368,  213,  368,
      213,  215,  215,  368,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  216,  216,  368,  216,  216,
      216,  216,  216,  368,  216,  216,  216,  368,  216,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  220,  220,  368,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  226,  226,  368,
      226,  368,  226,  226,  226,  368,  226,  226,  226,  226,
      227,  227,  368,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  231,  231,  368,  231,  368,  231,

      231,  231,  368,  231,  231,  231,  231,  232,  232,  368,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  234,  234,  368,  234,  368,  368,  368,  234,  368,
      234,  234,  234,  234,  234,  235,  235,  368,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  238,
      238,  368,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  270,  270,  368,  270,  270,  270,  270,
      270,  368,  270,  270,  270,  368,  270,  329,  329,  368,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  343,  343,  368,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  354,  354,  368,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  358,
      358,  368,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,   51,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368

    } ;

static yyconst short int yy_chk[1395] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    5,    6,   13,   14,  421,   15,    1,   15,   42,
       42,   13,   14,   42,   59,   59,   76,    1,  419,   16,
       15,   16,   49,   49,    7,    8,    7,    8,    9,   10,
        9,   10,  225,   16,  225,   76,   49,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    7,
        8,   35,   71,    9,   10,   77,   71,    2,  242,   36,
       35,   37,   38,   50,   50,  242,   43,    2,   36,   43,

       37,   38,  418,   87,   77,   43,   87,   50,  115,   43,
       91,   78,  115,   91,   72,   79,   35,    2,    2,    2,
        3,    3,   45,    3,   36,   45,   37,   38,   44,   44,
       78,   45,   44,   80,   79,   45,  100,  100,   44,  111,
      111,    3,   44,    3,  417,    3,    3,    3,  112,  112,
        3,   43,   80,   43,   72,   72,  415,  122,   72,   72,
        3,  122,    3,   72,    3,    3,    3,   72,  129,    3,
        4,    4,  129,    4,  134,  147,  147,   45,  134,   45,
      160,  155,  160,  414,   44,  155,   44,  160,   46,   46,
      165,    4,   46,    4,  167,    4,    4,    4,   46,  388,

        4,  388,   46,   61,   61,   61,   81,  116,   81,  165,
        4,  168,    4,  167,    4,    4,    4,  170,   61,    4,
       11,   11,  159,  396,  159,   81,   11,  159,   81,  166,
      168,   11,   11,   11,  207,  207,  170,   61,   11,   11,
       11,   11,   11,   11,   46,  362,   46,  123,  116,  166,
      169,  116,  116,   60,   60,   60,  116,   11,   11,   11,
       11,   11,   11,   12,   12,  144,  144,  144,   60,   12,
      169,   60,  208,  208,   12,   12,   12,   60,  357,  171,
      144,   12,   12,   12,   12,   12,   12,   60,  123,  356,
       60,  123,  123,  179,  179,  179,  123,   60,  171,  144,

       12,   12,   12,   12,   12,   12,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   47,  175,  190,   47,  175,
      190,   47,   47,  355,   47,  180,  180,  180,   47,  348,
       48,   48,  221,   17,   48,  156,  221,   48,   48,  346,
       48,  157,  218,  218,   48,  194,  194,  194,  195,  195,
      195,  222,  345,   17,   17,   17,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,  156,  156,  344,  342,  156,
      156,  157,  157,  228,  156,  157,  157,  228,  156,  240,

      157,  253,  222,   18,  157,  222,  222,  223,  233,  224,
      222,  224,  233,  229,  224,  236,  341,  340,  240,  236,
      230,  253,  331,   18,   18,   18,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,  239,  239,  330,  223,  251,
      328,  223,  223,  252,  229,  254,  223,  229,  229,  255,
      239,  230,  229,   19,  230,  230,  246,  327,  251,  230,
      326,  402,  252,  402,  254,  260,  260,  260,  255,  239,
      261,  261,  261,   19,   19,   19,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,  256,  246,  257,  265,  265,
      265,  287,  288,  246,  266,  266,  266,  289,  290,  291,
      292,  311,  313,   20,  256,  324,  257,  294,  294,  294,
      287,  288,  296,  296,  296,  323,  289,  290,  291,  292,
      311,  313,  314,   20,   20,   20,   88,  315,  316,  317,
      317,  317,  332,  334,   88,   88,   88,  335,  336,  349,
      350,  314,  337,  337,  337,  351,  315,  316,  353,  353,
      353,  332,  334,  359,  322,  360,  335,  336,  349,  350,
       88,   88,  363,  364,  351,   88,  365,  321,  320,  319,
       88,  310,  359,   88,  360,   88,  309,   88,   88,   92,

      307,  363,  364,  306,  305,  365,  304,   92,   92,   92,
      303,  302,  301,  300,  299,  298,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  271,
      268,  250,  249,   92,   92,  248,  247,  245,   92,  244,
      243,  241,  237,   92,  213,  211,   92,  210,   92,  204,
       92,   92,  148,  148,  148,  193,  178,  172,  163,  148,
      148,  148,  148,  148,  148,  162,  161,  158,  139,  136,
      133,  125,  118,  106,   94,   82,   74,   69,  148,  148,
      148,  148,  148,  148,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      389,  389,   67,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  390,   65,   64,   63,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  391,  391,
       57,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  392,  392,   55,   53,  392,  392,  392,  392,

      392,  392,  392,  392,   51,  392,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      394,  394,   41,   40,  394,  394,  394,  394,  394,  394,
      394,  394,   39,  394,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  397,  397,
       34,  397,  397,  397,  397,   33,  397,  397,  397,  397,
      397,  397,  398,  398,    0,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  399,  399,    0,  399,
      399,  399,  399,  399,  399,  399,    0,  399,  399,  399,
      400,  400,    0,  400,  400,  400,  400,  400,  400,  400,

        0,  400,  400,  400,  401,    0,    0,    0,  401,    0,
      401,  403,  403,    0,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  404,  404,    0,  404,  404,
      404,  404,  404,    0,  404,  404,  404,    0,  404,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  406,  406,    0,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  407,  407,    0,
      407,    0,  407,  407,  407,    0,  407,  407,  407,  407,
      408,  408,    0,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  409,  409,    0,  409,    0,  409,

      409,  409,    0,  409,  409,  409,  409,  410,  410,    0,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  411,  411,    0,  411,    0,    0,    0,  411,    0,
      411,  411,  411,  411,  411,  412,  412,    0,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  413,
      413,    0,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  416,  416,    0,  416,  416,  416,  416,
      416,    0,  416,  416,  416,    0,  416,  420,  420,    0,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  422,  422,    0,  422,  422,  422,  422,  422,  422,

      422,  422,  422,  422,  422,  423,  423,    0,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  424,
      424,    0,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "parser.l"
#define INITIAL 0
/* -*-C-*-
 *
 * Copyright 1994 Martin von Loewis
 * Copyright 1998 Bertho A. Stultiens (BS)
 *
 * 20-Jun-1998 BS	- Changed the filename conversion. Filenames are
 *			  case-sensitive inder *nix, but not under dos.
 *			  default behaviour is to convert to lower case.
 *			- All backslashes are converted to forward and
 *			  both single and double slash is recognized as
 *			  MS/Borland does.
 *			- Fixed a bug in 'yywf' case that prevented
 *			  double quoted names to be scanned propperly.
 *
 * 19-May-1998 BS	- Started to build a preprocessor.
 *			- Changed keyword processing completely to
 *			  table-lookups.
 *
 * 20-Apr-1998 BS	- Added ';' comment stripping
 *
 * 17-Apr-1998 BS	- Made the win32 keywords optional when compiling in
 *			  16bit mode
 *
 * 15-Apr-1998 BS	- Changed string handling to include escapes
 *			- Added unicode string handling (no codepage
 *			  translation though).
 *			- 'Borrowed' the main idea of string scanning from
 *			  the flex manual pages.
 *			- Added conditional handling of scanning depending
 *			  on the state of the parser. This was mainly required
 *			  to distinguish a file to load or raw data that
 *			  follows. MS's definition of filenames is rather
 *			  complex... It can be unquoted or double quoted. If
 *			  double quoted, then the '\\' char is not automatically
 *			  escaped according to Borland's rc compiler, but it
 *			  accepts both "\\path\\file.rc" and "\path\file.rc".
 *			  This makes life very hard! I go for the escaped
 *			  version, as this seems to be the documented way...
 *			- Single quoted strings are now parsed and converted
 *			  here.
 *			- Added comment stripping. The implementation is
 *			  'borrowed' from the flex manpages.
 *			- Rebuild string processing so that it may contain
 *			  escaped '\0'.
 */
/* Exclusive rules when looking for a filename */
#define yywf 1

#define yywf_s 2

/* Exclusive string handling */
#define yystr 3

/* Exclusive unicode string handling */
#define yylstr 4

/* Exclusive rcdata single quoted data handling */
#define yyrcd 5

/* Exclusive comment eating... */
#define comment 6

/* Preprocessor exclusives */
#define pp_incl 7

#define pp_def 8

#define pp_undef 9

#define pp_if 10

#define pp_ifdef 11

#define pp_ifndef 12

#define pp_elif 13

#define pp_else 14

#define pp_endif 15

#define pp_error 16

/* Set when accumulating #define's expansion text */
#define pp_def_s 17

/* Set when processing function type defines */
#define pp_ignore 18

/* Set when need to strip to eol */
#define pp_ignore_eol 19

/* Set when handling a false #if case */
#define pp_false 20

/* Set when stripping c-junk */
#define pp_stripe 21

#define pp_strips 22

#define pp_stripp 23

#define pp_stripp_final 24

/*%option stack*/
#define YY_NEVER_INTERACTIVE 1
/*%option noyywrap */
/* Some shortcut definitions */
#line 91 "parser.l"

#if !defined(YY_FLEX_MAJOR_VERSION) || (1000 * YY_FLEX_MAJOR_VERSION + YY_FLEX_MINOR_VERSION < 2005)
#error Must use flex version 2.5.1 or higher (yy_scan_* routines are required).
#endif

/*#define LEX_DEBUG*/

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "wrc.h"
#include "utils.h"
#include "preproc.h"
#include "parser.h"
#include "newstruc.h"

#include "y.tab.h"

#define YY_USE_PROTOS
#define YY_NO_UNPUT

/* Always update the current character position within a line */
#define YY_USER_ACTION	char_number+=yyleng;

raw_data_t *new_raw_data(void);

void addcchar(char c);
void addwchar(short s);
string_t *get_buffered_cstring(void);
string_t *get_buffered_wstring(void);
string_t *make_string(char *s);
string_t *make_filename(char *s, int len);

int line_number = 1;		/* The current line */
int char_number = 1;		/* The current char pos within the line */
static char *cbuffer;		/* Buffers for string collection */
static int cbufidx;
static int cbufalloc = 0;
static short *wbuffer;
static int wbufidx;
static int wbufalloc = 0;
static int want_nl = 0;		/* Set when newline needs to go to parser */
static int want_ident = 0;	/* Set is #ifdef, #ifndef or defined is seen */
static int stripslevel = 0;	/* Count {} during pp_strips/pp_stripe mode */
static int stripplevel = 0;	/* Count () during pp_strips mode */
static char *substtext = NULL;	/* Holds the substition text while getting a define */
static int cjunk_tagline;	/* Where did we start stripping (helps error tracking) */

#ifdef YY_USE_STACK
void push_to(int start)	{ yy_push_state(start); }
void pop_start(void)	{ yy_pop_state(start); }
#else
#define MAXSTARTSTACK	32
static int startstack[MAXSTARTSTACK];
static int startstackidx = 0;

void push_to(int start)
{
	if(yydebug)
		printf("push_to(%d): %d -> %d\n", line_number, YY_START, start);
	if(startstackidx >= MAXSTARTSTACK-1)
		internal_error(__FILE__, __LINE__, "Start condition stack overflow");
	startstack[startstackidx++] = YY_START;
	BEGIN(start);
}

void pop_start(void)
{
	if(yydebug)
		printf("pop_start(%d): %d <- %d\n", line_number, startstack[startstackidx-1], YY_START);
	if(startstackidx <= 0)
		internal_error(__FILE__, __LINE__, "Start condition stack underflow");
	--startstackidx;
	BEGIN(startstack[startstackidx]);
}
#endif


struct bufferstackentry {
	YY_BUFFER_STATE	bufferstate;	/* Buffer to switch back to */
	struct pp_entry	*define;	/* Points to expanding define
					   or NULL if handling includes
					 */
	int line_number;		/* Line that we were handling */
	int char_number;		/* The current position */
	char *filename;			/* Filename that we were handling */
};

#define MAXBUFFERSTACK 128
static struct bufferstackentry bufferstack[MAXBUFFERSTACK];
static int bufferstackidx = 0;

void push_buffer(YY_BUFFER_STATE buf, struct pp_entry *ppp, char *filename)
{
	if(yydebug)
		printf("push_buffer: %p %p %p\n", buf, ppp, filename);
	if(bufferstackidx >= MAXBUFFERSTACK-1)
		internal_error(__FILE__, __LINE__, "Buffer stack overflow");
	memset(&bufferstack[bufferstackidx], 0, sizeof(bufferstack[0]));
	bufferstack[bufferstackidx].bufferstate = buf;
	bufferstack[bufferstackidx].define = ppp;
	if(ppp)
		ppp->expanding = 1;
	else if(filename)
	{
		/* These will track the yyerror to the correct file and line */
		bufferstack[bufferstackidx].line_number = line_number;
		bufferstack[bufferstackidx].char_number = char_number;
		line_number = 1;
		char_number = 1;
		bufferstack[bufferstackidx].filename = input_name;
		input_name = filename;
	}
	else
		internal_error(__FILE__, __LINE__, "Pushing buffer without knowing where to go to");
	bufferstackidx++;
}

YY_BUFFER_STATE pop_buffer(void)
{
	if(bufferstackidx <= 0)
		return (YY_BUFFER_STATE)0;
	bufferstackidx--;
	if(bufferstack[bufferstackidx].define)
		bufferstack[bufferstackidx].define->expanding = 0;
	else
	{
		line_number = bufferstack[bufferstackidx].line_number;
		char_number = bufferstack[bufferstackidx].char_number;
		input_name = bufferstack[bufferstackidx].filename;
		fclose(yyin);
	}
	if(yydebug)
		printf("pop_buffer: %p %p (%d, %d) %p\n",
			bufferstack[bufferstackidx].bufferstate,
			bufferstack[bufferstackidx].define,
			bufferstack[bufferstackidx].line_number,
			bufferstack[bufferstackidx].char_number,
			bufferstack[bufferstackidx].filename);
	yy_switch_to_buffer(bufferstack[bufferstackidx].bufferstate);
	return bufferstack[bufferstackidx].bufferstate;
}

void do_include(char *name, int namelen)
{
	char *cpy = (char *)xmalloc(namelen);
	strcpy(cpy, name+1);	/* strip leading " or < */
	cpy[namelen-2] = '\0';	/* strip trailing " or > */
	if((yyin = open_include(cpy, name[0] == '"')) == NULL)
		yyerror("Unable to open include file %s", cpy);
	push_buffer(YY_CURRENT_BUFFER, NULL, cpy);
	yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
}


struct keyword {
	char	*keyword;
	int	token;
	int	isextension;
	int	needcase;
	int	alwayskeyword;
};

static struct keyword keywords[] = {
	{ "ACCELERATORS", ACCELERATORS, 0, 0, 0},
	{ "ALT", ALT, 0, 0, 0},
	{ "ASCII", ASCII, 0, 0, 0},
	{ "AUTO3STATE", AUTO3STATE, 1, 0, 0},
	{ "AUTOCHECKBOX", AUTOCHECKBOX, 1, 0, 0},
	{ "AUTORADIOBUTTON", AUTORADIOBUTTON, 1, 0, 0},
	{ "BEGIN", tBEGIN, 0, 0, 1},
	{ "BITMAP", tBITMAP, 0, 0, 0},
	{ "BLOCK", BLOCK, 0, 0, 1},
	{ "BUTTON", BUTTON, 1, 0, 0},
	{ "CAPTION", CAPTION, 0, 0, 0},
	{ "CHARACTERISTICS", CHARACTERISTICS, 1, 0, 0},
	{ "CHECKBOX", CHECKBOX, 0, 0, 0},
	{ "CHECKED", CHECKED, 0, 0, 0},
	{ "CLASS", CLASS, 0, 0, 0},
	{ "COMBOBOX", COMBOBOX, 0, 0, 0},
	{ "CONTROL", CONTROL, 0, 0, 0},
	{ "CTEXT", CTEXT, 0, 0, 0},
	{ "CURSOR", CURSOR, 0, 0, 0},
	{ "defined", tDEFINED, 0, 1, 1},
	{ "DEFPUSHBUTTON", DEFPUSHBUTTON, 0, 0, 1},
	{ "DIALOG", DIALOG, 0, 0, 0},
	{ "DIALOGEX", DIALOGEX, 1, 0, 0},
	{ "DISCARDABLE", DISCARDABLE, 0, 0, 0},
	{ "DLGINIT", DLGINIT, 0, 0, 0},
	{ "EDITTEXT", EDITTEXT, 0, 0, 0},
	{ "END", tEND, 0, 0, 1},
	{ "EXSTYLE", EXSTYLE, 0, 0, 0},
	{ "extern", tEXTERN, 0, 1, 1},
	{ "FILEFLAGS", FILEFLAGS, 0, 0, 0},
	{ "FILEFLAGSMASK", FILEFLAGSMASK, 0, 0, 0},
	{ "FILEOS", FILEOS, 0, 0, 0},
	{ "FILESUBTYPE", FILESUBTYPE, 0, 0, 0},
	{ "FILETYPE", FILETYPE, 0, 0, 0},
	{ "FILEVERSION", FILEVERSION, 0, 0, 0},
	{ "FIXED", tFIXED, 0, 0, 0},
	{ "FONT", FONT, 0, 0, 0},
	{ "GRAYED", GRAYED, 0, 0, 0},
	{ "GROUPBOX", GROUPBOX, 0, 0, 0},
	{ "HELP", HELP, 0, 0, 0},
	{ "ICON", ICON, 0, 0, 0},
	{ "IMPURE", IMPURE, 0, 0, 0},
	{ "INACTIVE", INACTIVE, 0, 0, 0},
	{ "LANGUAGE", LANGUAGE, 1, 0, 1},
	{ "LISTBOX", LISTBOX, 0, 0, 0},
	{ "LOADONCALL", LOADONCALL, 0, 0, 0},
	{ "LTEXT", LTEXT, 0, 0, 0},
	{ "MENU", MENU, 0, 0, 0},
	{ "MENUBARBREAK", MENUBARBREAK, 0, 0, 0},
	{ "MENUBREAK", MENUBREAK, 0, 0, 0},
	{ "MENUEX", MENUEX, 1, 0, 0},
	{ "MENUITEM", MENUITEM, 0, 0, 0},
	{ "MESSAGETABLE", MESSAGETABLE, 1, 0, 0},
	{ "MOVEABLE", MOVEABLE, 0, 0, 0},
	{ "NOINVERT", NOINVERT, 0, 0, 0},
	{ "NOT", NOT, 0, 0, 0},
	{ "POPUP", POPUP, 0, 0, 0},
	{ "PRELOAD", PRELOAD, 0, 0, 0},
	{ "PRODUCTVERSION", PRODUCTVERSION, 0, 0, 0},
	{ "PURE", tPURE, 0, 0, 0},
	{ "PUSHBUTTON", PUSHBUTTON, 0, 0, 0},
	{ "RADIOBUTTON", RADIOBUTTON, 0, 0, 0},
	{ "RCDATA", RCDATA, 0, 0, 0},
	{ "RTEXT", RTEXT, 0, 0, 0},
	{ "SCROLLBAR", SCROLLBAR, 0, 0, 0},
	{ "SEPARATOR", SEPARATOR, 0, 0, 0},
	{ "SHIFT", SHIFT, 0, 0, 0},
	{ "STATE3", STATE3, 1, 0, 0},
	{ "STRING", tSTRING, 0, 0, 0},
	{ "STRINGTABLE", STRINGTABLE, 0, 0, 1},
	{ "STYLE", STYLE, 0, 0, 0},
	{ "TOOLBAR", TOOLBAR, 1, 0, 0},
	{ "typedef", tTYPEDEF, 0, 1, 1},
	{ "VALUE", VALUE, 0, 0, 0},
	{ "VERSION", VERSION, 1, 0, 0},
	{ "VERSIONINFO", VERSIONINFO, 0, 0, 0},
	{ "VIRTKEY", VIRTKEY, 0, 0, 0}
};

#define NKEYWORDS	(sizeof(keywords)/sizeof(keywords[0]))
#define KWP(p)		((struct keyword *)(p))
int kw_cmp_func(const void *s1, const void *s2)
{
	int ret;
	ret = strcasecmp(KWP(s1)->keyword, KWP(s2)->keyword);
	if(!ret && (KWP(s1)->needcase || KWP(s2)->needcase))
		return strcmp(KWP(s1)->keyword, KWP(s2)->keyword);
	else
		return ret;
}

#define KW_BSEARCH
#define DO_SORT
struct keyword *iskeyword(char *kw)
{
	struct keyword *kwp;
	struct keyword key;
	key.keyword = kw;
	key.needcase = 0;
#ifdef DO_SORT
	{
		/* Make sure that it is sorted for bsearsh */
		static int sorted = 0;
		if(!sorted)
		{
			qsort(keywords, NKEYWORDS, sizeof(keywords[0]), kw_cmp_func);
			sorted = 1;
		}
	}
#endif
#ifdef KW_BSEARCH
	kwp = bsearch(&key, keywords, NKEYWORDS, sizeof(keywords[0]), kw_cmp_func);
#else
	{
		int i;
		for(i = 0; i < NKEYWORDS; i++)
		{
			if(!kw_cmp_func(&key, &keywords[i]))
				break;
		}
		if(i < NKEYWORDS)
			kwp = &keywords[i];
		else
			kwp = NULL;
	}
#endif

#ifdef LEX_DEBUG
	if(kwp && !strcmp(kwp->keyword, "LANGUAGE"))
		printf("Got Language\n");
#endif
	if(kwp == NULL || (kwp->isextension && !extensions))
		return NULL;
	else
		return kwp;
}

void add_to_substtext(char *text, int len)
{
	if(!substtext)
	{
		substtext = xstrdup(text);
	}
	else
	{
		substtext = (char *)xrealloc(substtext, strlen(substtext)+len+1);
		strcat(substtext, text);
	}
}

#line 1230 "lexyy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 411 "parser.l"

	/* #include handling */
#line 1383 "lexyy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1334 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 413 "parser.l"
push_to(pp_incl);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 414 "parser.l"
do_include(yytext, yyleng); pop_start();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 415 "parser.l"
do_include(yytext, yyleng); pop_start();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 416 "parser.l"
yyerror("Malformed #include");
	YY_BREAK
/* #define handling */
case 5:
YY_RULE_SETUP
#line 419 "parser.l"
push_to(pp_def);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 420 "parser.l"
{
				set_define(yytext);
				push_to(pp_def_s);
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 424 "parser.l"
push_to(pp_ignore); /* Ignore function-like defines for now*/
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 425 "parser.l"
yyerror("Malformed #define");
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 427 "parser.l"
{
			if(YY_START == pp_def_s)
				add_to_substtext(yytext, yyleng);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 431 "parser.l"
{ /* Comment is handled in normal handling */
			if(YY_START == pp_def_s)
				add_to_substtext(yytext, yyleng);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 435 "parser.l"
line_number++;	char_number = 1; /* Line continuation */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 436 "parser.l"
{
			if(YY_START == pp_def_s)
			{
				add_define(substtext ? substtext : "");
				free(substtext);
				substtext = NULL;
			}
			line_number++;
			char_number = 1;
			pop_start();
			pop_start();
		}
	YY_BREAK
/* #undef handling */
case 13:
YY_RULE_SETUP
#line 450 "parser.l"
push_to(pp_undef);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 451 "parser.l"
{
				del_define(yytext);
				pop_start();
				/*push_to(pp_ignore);*/
			}
	YY_BREAK
/* Conditional handling */
case 15:
YY_RULE_SETUP
#line 458 "parser.l"
{
			if(YY_START == pp_false)
			{
				if(yydebug)
					printf("(%d)#if ignored\n", line_number);
				push_if(0, 0, 1);
				push_to(pp_ignore_eol);
			}
			else
			{
				push_to(INITIAL);
				want_nl = 1;
				return tIF;
			}
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 473 "parser.l"
{
			if(YY_START == pp_false)
			{
				if(yydebug)
					printf("(%d)#ifdef ignored\n", line_number);
				push_if(0, 0, 1);
				push_to(pp_ignore_eol);
			}
			else
			{
				push_to(INITIAL);
				want_nl = 1;
				want_ident = 1;
				return tIFDEF;
			}
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 489 "parser.l"
{
			if(YY_START == pp_false)
			{
				if(yydebug)
					printf("(%d)#ifndef ignored\n", line_number);
				push_if(0, 0, 1);
				push_to(pp_ignore_eol);
			}
			else
			{
				push_to(INITIAL);
				want_nl = 1;
				want_ident = 1;
				return tIFNDEF;
			}
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 505 "parser.l"
{
			if(!isnevertrue_if())
			{
				push_to(INITIAL);
				want_nl = 1;
				return tELIF;
			}
			else if(YY_START == pp_false)
				push_to(pp_ignore_eol);
			if(yydebug)
				printf("(%d)#elif ignored\n", line_number);
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 517 "parser.l"
{
			if(!isnevertrue_if())
			{
				push_to(INITIAL);
				want_nl = 1;
				return tELSE;
			}
			if(yydebug)
				printf("(%d)#else ignored\n", line_number);
		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 527 "parser.l"
{
			if(!isnevertrue_if())
			{
				want_nl = 1;
				return tENDIF;
			}
			else
			{
				if(yydebug)
					printf("(%d)#endif ignored\n", line_number);
				pop_if();
			}
		}
	YY_BREAK
/* The error directive */
case 21:
YY_RULE_SETUP
#line 542 "parser.l"
push_to(pp_error);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 543 "parser.l"
yyerror("Error directive: %s", yytext);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 544 "parser.l"
{
			if(yydebug)
				printf("(%d)#error ignored\n", line_number);
		}
	YY_BREAK
/* preprocessor junk */
case 24:
YY_RULE_SETUP
#line 550 "parser.l"
;	/* Ignore #pragma */
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 551 "parser.l"
;	/* Ignore #ident */
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 552 "parser.l"
;	/* Ignore #line */
	YY_BREAK
/* We'll get an error on malformed #xxx statements
  * by not recognising '#' at all. This helps tracking
  * preprocessor errors.
  */
/*^{ws}*#{ws}*			;	 Ignore # */
case 27:
YY_RULE_SETUP
#line 559 "parser.l"
stripslevel++;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 560 "parser.l"
stripslevel--;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 561 "parser.l"
if(!stripslevel) pop_start();
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 562 "parser.l"
; /* To catch comments */
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 563 "parser.l"
; /* Ignore rest */
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 565 "parser.l"
stripslevel++;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 566 "parser.l"
{
			stripslevel--;
			if(!stripslevel) pop_start();
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 570 "parser.l"
if(!stripslevel) pop_start();
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 571 "parser.l"
; /* To catch comments */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 572 "parser.l"
; /* Ignore rest */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 574 "parser.l"
stripplevel++;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 575 "parser.l"
{
				stripplevel--;
				if(!stripplevel)
				{
					pop_start();
					push_to(pp_stripp_final);
				}
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 583 "parser.l"
; /* To catch comments */
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 584 "parser.l"
; /* Ignore rest */
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 586 "parser.l"
; /* Ignore */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 587 "parser.l"
pop_start(); /* Kill the semicolon */
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 588 "parser.l"
line_number++; char_number = 1; pop_start();
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 589 "parser.l"
yyless(0); pop_start();
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 591 "parser.l"
;	/* Ignore everything except #xxx during false #if state */
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 593 "parser.l"
pop_start();
	YY_BREAK
/* These are special cases due to filename scanning */
case 47:
YY_RULE_SETUP
#line 596 "parser.l"
return DISCARDABLE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 597 "parser.l"
return tFIXED;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 598 "parser.l"
return IMPURE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 599 "parser.l"
return MOVEABLE;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 600 "parser.l"
return LOADONCALL;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 601 "parser.l"
return PRELOAD;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 602 "parser.l"
return tPURE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 604 "parser.l"
return tBEGIN;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 605 "parser.l"
return tEND;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 607 "parser.l"
{ yylval.num = strtoul(yytext,  0, 10); return toupper(yytext[yyleng-1]) == 'L' ? LNUMBER : NUMBER; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 608 "parser.l"
{ yylval.num = strtoul(yytext,  0, 16); return toupper(yytext[yyleng-1]) == 'L' ? LNUMBER : NUMBER; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 609 "parser.l"
{ yylval.num = strtoul(yytext+2, 0, 8); return toupper(yytext[yyleng-1]) == 'L' ? LNUMBER : NUMBER; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 610 "parser.l"
{
				struct keyword *token;
				struct pp_entry *ppp;

				want_rscname = 0;
				
				if(want_ident)
				{
					/* Prevent preprocessor subst */
					want_ident = 0;
					yylval.str = make_string(yytext);
				#ifdef LEX_DEBUG
					printf("want IDENT (%s, %d, %d): <%s>\n", input_name, line_number, char_number, yytext);
				#endif
					return IDENT;
				}
				else if((ppp = pp_lookup(yytext)) != NULL)
				{
					/* Do preprocessor substitution,
					 * but expand only if macro is not
					 * already expanding.
					 */
					if(!ppp->expanding)
					{
				#ifdef LEX_DEBUG
						printf("expand IDENT (%s, %d, %d): <%s>\n", input_name, line_number, char_number, yytext);
				#endif
						push_buffer(YY_CURRENT_BUFFER, ppp, NULL);
						yy_scan_string(ppp->subst);
					}
				}
				else if((token = iskeyword(yytext)) != NULL
				  && !(!token->alwayskeyword && want_rscname))
				{
					switch(token->token)
					{
					case tDEFINED:
						want_ident = 1;
						break;
					/*case RCDATA:*/
					case CURSOR:
					case tBITMAP:
					case MESSAGETABLE:
					case DLGINIT:
						push_to(yywf);
						break;
					case FONT:
					case ICON:
						if(!indialog)
							push_to(yywf);
						break;
					case DIALOG:
					case DIALOGEX:
						indialog = 1;
						break;
					}
					return token->token;
				}
				else
				{
					yylval.str = make_string(yytext);
				#ifdef LEX_DEBUG
					printf("%s IDENT (%s, %d, %d): <%s>\n",
						want_rscname ? "rscname" : "just",
						input_name,
						line_number,
						char_number,
						yytext);
				#endif
					return IDENT;
				}
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 682 "parser.l"
return LOGOR;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 683 "parser.l"
return LOGAND;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 684 "parser.l"
return EQ;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 685 "parser.l"
return NE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 686 "parser.l"
return LTE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 687 "parser.l"
return GTE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 689 "parser.l"
{ pop_start(); yylval.str = make_filename(yytext, yyleng); return FILENAME; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 690 "parser.l"
push_to(yywf_s);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 691 "parser.l"
{ pop_start(); pop_start(); yylval.str = make_filename(yytext, yyleng-1); return FILENAME; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 692 "parser.l"
yyerror("Newline in filename");
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 694 "parser.l"
{
				push_to(yylstr);
				wbufidx = 0;
				if(!win32)
					yywarning("16bit resource contains unicode strings\n");
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 700 "parser.l"
{
				pop_start();
				yylval.str = get_buffered_wstring();
				return tSTRING;
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 705 "parser.l"
yyerror("Unterminated string");
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 706 "parser.l"
{ /* octal escape sequence */
				int result;
				result = strtol(yytext+1, 0, 8);
				if ( result > 0xffff )
					yyerror("Character constant out of range");
				addwchar((short)result);
			}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 713 "parser.l"
{  /* hex escape sequence */
				int result;
				result = strtol(yytext+2, 0, 16);
				addwchar((short)result);
			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 718 "parser.l"
yyerror("Bad escape secuence");
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 719 "parser.l"
addwchar('\a');
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 720 "parser.l"
addwchar('\b');
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 721 "parser.l"
addwchar('\f');
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 722 "parser.l"
addwchar('\n');
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 723 "parser.l"
addwchar('\r');
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 724 "parser.l"
addwchar('\t');
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 725 "parser.l"
addwchar('\v');
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 726 "parser.l"
addwchar(yytext[1]);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 727 "parser.l"
addcchar('\"');		/* "bla""bla"  -> "bla\"bla" */
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 728 "parser.l"
addcchar('\"');		/* "bla\""bla" -> "bla\"bla" */
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 729 "parser.l"
;			/* "bla" "bla" -> "blabla" */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 730 "parser.l"
{
				char *yptr = yytext;
				while(*yptr)	/* FIXME: codepage translation */
					addwchar(*yptr++ & 0xff);
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 736 "parser.l"
{
				push_to(yystr);
				cbufidx = 0;
			}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 740 "parser.l"
{
				pop_start();
				yylval.str = get_buffered_cstring();
				return tSTRING;
			}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 745 "parser.l"
yyerror("Unterminated string");
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 746 "parser.l"
{ /* octal escape sequence */
				int result;
				result = strtol(yytext+1, 0, 8);
				if ( result > 0xff )
					yyerror("Character constant out of range");
				addcchar((char)result);
			}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 753 "parser.l"
{  /* hex escape sequence */
				int result;
				result = strtol(yytext+2, 0, 16);
				addcchar((char)result);
			}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 758 "parser.l"
yyerror("Bad escape secuence");
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 759 "parser.l"
addcchar('\a');
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 760 "parser.l"
addcchar('\b');
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 761 "parser.l"
addcchar('\f');
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 762 "parser.l"
addcchar('\n');
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 763 "parser.l"
addcchar('\r');
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 764 "parser.l"
addcchar('\t');
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 765 "parser.l"
addcchar('\v');
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 766 "parser.l"
addcchar(yytext[1]);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 767 "parser.l"
{
				char *yptr = yytext;
				while(*yptr)
					addcchar(*yptr++);
			}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 772 "parser.l"
addcchar('\"');		/* "bla""bla"   -> "bla\"bla" */
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 773 "parser.l"
addcchar('\"');		/* "bla\""bla"  -> "bla\"bla" */
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 774 "parser.l"
;			/* "bla" "bla"  -> "blabla" */
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 775 "parser.l"
yywarning("Matched %c", *yytext);
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 778 "parser.l"
{
				push_to(yyrcd);
				cbufidx = 0;
			}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 782 "parser.l"
{
				pop_start();
				yylval.raw = new_raw_data();
				yylval.raw->size = cbufidx;
				yylval.raw->data = xmalloc(yylval.raw->size);
				memcpy(yylval.raw->data, cbuffer, yylval.raw->size);
				return RAWDATA;
			}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 790 "parser.l"
{
				int result;
				result = strtol(yytext, 0, 16);
				addcchar((char)result);
			}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 795 "parser.l"
;	/* Ignore space */
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 796 "parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 797 "parser.l"
yyerror("Malformed data-line");
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 799 "parser.l"
push_to(comment);	/* Eat comment */
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 800 "parser.l"
;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 801 "parser.l"
;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 802 "parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 803 "parser.l"
pop_start();
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 805 "parser.l"
; /* Eat comment */
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 806 "parser.l"
; /* Eat comment */
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 808 "parser.l"
{
				if(YY_START == yywf)
					pop_start();
				line_number++;
				char_number = 1;
				if(want_nl)
				{
					want_nl = 0;
					return tNL;
				}
			}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 819 "parser.l"
;	/* Eat whitespace */
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 821 "parser.l"
return yytext[0];
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(yywf):
case YY_STATE_EOF(yywf_s):
case YY_STATE_EOF(yystr):
case YY_STATE_EOF(yylstr):
case YY_STATE_EOF(yyrcd):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(pp_incl):
case YY_STATE_EOF(pp_def):
case YY_STATE_EOF(pp_undef):
case YY_STATE_EOF(pp_if):
case YY_STATE_EOF(pp_ifdef):
case YY_STATE_EOF(pp_ifndef):
case YY_STATE_EOF(pp_elif):
case YY_STATE_EOF(pp_else):
case YY_STATE_EOF(pp_endif):
case YY_STATE_EOF(pp_error):
case YY_STATE_EOF(pp_def_s):
case YY_STATE_EOF(pp_ignore):
case YY_STATE_EOF(pp_ignore_eol):
case YY_STATE_EOF(pp_false):
case YY_STATE_EOF(pp_stripe):
case YY_STATE_EOF(pp_strips):
case YY_STATE_EOF(pp_stripp):
case YY_STATE_EOF(pp_stripp_final):
#line 822 "parser.l"
{
				YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
				if(!pop_buffer())
                                {
					if(YY_START == pp_strips || YY_START == pp_stripe || YY_START == pp_stripp || YY_START == pp_stripp_final)
						yyerror("Unexpected end of file during c-junk scanning (started at %d)", cjunk_tagline);
					else
						yyterminate();
                                }
				yy_delete_buffer(b);
			}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 834 "parser.l"
{
				/* Catch all rule to find any unmatched text */
				if(*yytext == '\n')
				{
					line_number++;
					char_number = 1;
				}
				yywarning("Unmatched text '%c' (0x%02x) YY_START=%d stripslevel=%d",
					isprint(*yytext) ? *yytext : '.', *yytext, YY_START,stripslevel);
			}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 845 "parser.l"
ECHO;
	YY_BREAK
#line 2397 "lexyy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 368);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 845 "parser.l"


#ifndef yywrap
int yywrap(void)
{
#if 0
	if(bufferstackidx > 0)
	{
		return 0;
 	}
#endif
	return 1;
}
#endif

/* These dup functions copy the enclosed '\0' from
 * the resource string.
 */
void addcchar(char c)
{
	if(cbufidx >= cbufalloc)
	{
		cbufalloc += 1024;
		cbuffer = xrealloc(cbuffer, cbufalloc * sizeof(cbuffer[0]));
		if(cbufalloc > 65536)
			yywarning("Reallocating string buffer larger than 64kB");
	}
	cbuffer[cbufidx++] = c;
}

void addwchar(short s)
{
	if(wbufidx >= wbufalloc)
	{
		wbufalloc += 1024;
		wbuffer = xrealloc(wbuffer, wbufalloc * sizeof(wbuffer[0]));
		if(wbufalloc > 65536)
			yywarning("Reallocating wide string buffer larger than 64kB");
	}

	/*
	 * BS 08-Aug-1999 FIXME: The '& 0xff' is probably a bug, but I have
	 * not experienced it yet and I seem to remember that this was for
	 * a reason. But, as so many things you tend to forget why.
	 * I guess that there were problems due to the sign extension of
	 * shorts WRT chars (e.g. 0x80 becomes 0xff80 instead of 0x0080).
	 * This should then be fixed in the lexer calling the function.
	 */
	wbuffer[wbufidx++] = (short)(s & 0xff);
}

string_t *get_buffered_cstring(void)
{
	string_t *str = new_string();
	str->size = cbufidx;
	str->type = str_char;
	str->str.cstr = (char *)xmalloc(cbufidx+1);
	memcpy(str->str.cstr, cbuffer, cbufidx);
	str->str.cstr[cbufidx] = '\0';
/*	printf("got cstring \"%s\"\n", str->str.cstr); */
	return str;
}

string_t *get_buffered_wstring(void)
{
	string_t *str = new_string();
	str->size = wbufidx;
	str->type = str_unicode;
	str->str.wstr = (short *)xmalloc(2*(wbufidx+1));
	memcpy(str->str.wstr, wbuffer, wbufidx);
	str->str.wstr[wbufidx] = 0;
	return str;
}

string_t *make_string(char *s)
{
	string_t *str = new_string();
	str->size = strlen(s);
	str->type = str_char;
	str->str.cstr = (char *)xmalloc(str->size+1);
	memcpy(str->str.cstr, s, str->size+1);
	return str;
}

string_t *make_filename(char *s, int len)
{
	char *cptr;
	string_t *str = new_string();

	str->size = len;
	str->type = str_char;
	str->str.cstr = (char *)xmalloc(str->size+1);
	memcpy(str->str.cstr, s, str->size);
	str->str.cstr[str->size] = '\0';

	/* Remove escaped backslash and convert to forward */
	cptr = str->str.cstr;
	for(cptr = str->str.cstr; (cptr = strchr(cptr, '\\')) != NULL; cptr++)
	{
		if(cptr[1] == '\\')
		{
			memmove(cptr, cptr+1, strlen(cptr));
			str->size--;
		}
		*cptr = '/';
	}

	/* Convert to lower case. Seems to be reasonable to do */
	for(cptr = str->str.cstr; !leave_case && *cptr; cptr++)
	{
		*cptr = tolower(*cptr);
	}
	return str;
}

/* Called from the parser to signal filename request */
void set_yywf(void)
{
	push_to(yywf);
}

/* Called from the parser to signal preprocessor if case */
void set_pp_ignore(int state)
{
	if(state)
		push_to(pp_false);
	else
		pop_start();
}

/* Called from the parser to kill c-junk */
void strip_extern(void)
{
	cjunk_tagline = line_number;
	push_to(pp_stripe);
}

void strip_til_semicolon(void)
{
	cjunk_tagline = line_number;
	push_to(pp_strips);
}

void strip_til_parenthesis(void)
{
	cjunk_tagline = line_number;
	stripplevel = 1;	/* One scanned already */
	push_to(pp_stripp);
}

