C3DFXFLAGS = /DGLIDE_USE_C_TRISETUP /DFX_DLL_ENABLE /DMAPPL_OS2 /DPORTIO_DIRECT
CFLAGS     = $(CFLAGS) /Sp1 $(C3DFXFLAGS)

!IF "$(FX_DEBUG)" == "1"
C3DFXFLAGS = $(C3DFXFLAGS) /DGDB_INFO_ON /Ti
!endif

