#ifndef __SHELLICON_H__
#define __SHELLICON_H__

#define SHLICON_FILE		1
#define SHLICON_TEXTFILE	2
#define SHLICON_APPLICATION	3
#define SHLICON_FOLDER_OPEN	4
#define SHLICON_FOLDER_CLOSED	5
#define SHLICON_FLOPPY525	6
#define SHLICON_FLOPPY35	7
#define SHLICON_REMOVABLE_DISK	8
#define SHLICON_HARDDISK	9
#define SHLICON_NETDRIVE_CONN   10
#define SHLICON_NETDRIVE_DISCON 11
#define SHLICON_CDROM_DRIVE	12
#define SHLICON_RAMDRIVE	13
#define SHLICON_ENTIRENETWORK	14
#define SHLICON_NETWORK		15
#define SHLICON_NETWORK_COMP	16
#define SHLICON_PRINTER		17
#define SHLICON_NETWORK_PLACE	18
#define SHLICON_NETWORK_GROUP	19
#define SHLICON_PROGRAMS	20
#define SHLICON_RECENTDOCS	21
#define SHLICON_SETTINGS	22
#define SHLICON_SEARCH		23
#define SHLICON_HELP		24
#define SHLICON_RUN		25
#define SHLICON_SUSPEND		26
#define SHLICON_UNDOCK		27
#define SHLICON_SHUTDOWN	28
#define SHLICON_SHAREDRES	29
#define SHLICON_SHORTCUT	30
#define SHLICON_ARROW		31
#define SHLICON_TRASHCAN	32
#define SHLICON_TRASHCAN_FULL	33
#define SHLICON_DIALUP_FOLDER	34
#define SHLICON_DESKTOP		35
#define SHLICON_CONTROLPANEL	36
#define SHLICON_PROGRAMGROUP	37
#define SHLICON_PRINTER_FOLDER	38
#define SHLICON_FONT_FOLDER     39
#define SHLICON_LOGO		40
#define SHLICON_AUDIO_CD	41
#define SHLICON_TREE		42
#define SHLICON_COMPUTERS	43
#define SHLICON_FAVORITES	44
#define SHLICON_LOGOFF		45

//is actually present in explorer.exe..
#define SHLICON_MYCOMPUTER      999

#endif //__SHELLICON_H__
