# $Id: makefile,v 1.2 2001-10-24 10:55:36 achimha Exp $

#
# InnoTek OS/2 Presentation Manager Keyboard Hook
#
#       pmkbdhk.dll makefile
#


#
# Compiler, tools, and interference rules.
#
!include ../../makefile.inc


#
# Overrides.
#


#
# Object files. Prefix with OBJDIR and one space before the '\'.
#
OBJS = \
$(OBJDIR)\pmkbdhk.obj


#
# Libraries. One space before the '\'.
#
LIBS = \
OS2386.LIB \
$(RTLLIB)

#
# Target name - name of the dll without extention and path.
#
TARGET = pmkbdhk


#
# Includes the common rules.
#
!include $(ODIN32_POST_INC)

