/* 
 * A full version of os2wrap.h that prefixes all OS/2 type and constant
 * definitions with "os2_" which makes it possible to use the OS/2 APIs
 * from the same source files that use the Windows APIs.
 *
 * Project Odin Software License can be found in LICENSE.TXT
 */

#ifndef __OS2WRAP2_H__
#define __OS2WRAP2_H__

#ifdef WINVER
#error "os2wrap2.h must be included BEFORE any Windows include file!"
#endif

/*
   Redefine all OS/2 typedefs to those having the "os2_" prefix to avoid
   conflicts with Windows typedefs. The defines are generated with the following
   command on the respective OS/2 headers:

sed -nr \
  -e 's/^[[:space:]]*typedef[[:space:]]+struct[[:space:]]+_([A-Z_][A-Z1-9_]+)([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#define _\1 os2__\1\
#define \1 os2_\1/p' \
  -e 's/^[[:space:]]*typedef[[:space:]]+.+[[:space:]]+\**([A-Z_][A-Z1-9_]+)[[:space:]]*(\[.*\])?[[:space:]]*;([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#define \1 os2_\1/p' \
  -e 's/^[[:space:]]*#define[[:space:]]+((CONTEXT|CS|EH|EXCEPTION|HWND|WC|MB|WM|WS|RGN|RT|DT|SWP|TA)_([A-Z1-9_]+))[[:space:]]+.*$/#define \1 os2_\1/p' \

 */
#define INT os2_INT
#define UINT os2_UINT
#define APIRET os2_APIRET
#define BOOL os2_BOOL
#define PBOOL os2_PBOOL
#define BOOL32 os2_BOOL32
#define PBOOL32 os2_PBOOL32
#define CHAR os2_CHAR
#define PCHAR os2_PCHAR
#define BYTE os2_BYTE
#define PCH os2_PCH
#define PSZ os2_PSZ
#define PCCH os2_PCCH
#define PCSZ os2_PCSZ
#define BYTE os2_BYTE
#define PCH os2_PCH
#define PSZ os2_PSZ
#define PCCH os2_PCCH
#define PCSZ os2_PCSZ
#define PBYTE os2_PBYTE
#define UCHAR os2_UCHAR
#define PUCHAR os2_PUCHAR
#define SHORT os2_SHORT
#define PSHORT os2_PSHORT
#define USHORT os2_USHORT
#define PUSHORT os2_PUSHORT
#define LONG os2_LONG
#define PLONG os2_PLONG
#define ULONG os2_ULONG
#define PULONG os2_PULONG
#define LONGLONG os2_LONGLONG
#define PLONGLONG os2_PLONGLONG
#define ULONGLONG os2_ULONGLONG
#define PULONGLONG os2_PULONGLONG
#define _LONGLONG os2__LONGLONG
#define LONGLONG os2_LONGLONG
#define PLONGLONG os2_PLONGLONG
#define _ULONGLONG os2__ULONGLONG
#define ULONGLONG os2_ULONGLONG
#define PULONGLONG os2_PULONGLONG
#define PVOID os2_PVOID
#define PPVOID os2_PPVOID
#define CPVOID os2_CPVOID
#define STR8 os2_STR8
#define PSTR8 os2_PSTR8
#define STR16 os2_STR16
#define PSTR16 os2_PSTR16
#define STR32 os2_STR32
#define PSTR32 os2_PSTR32
#define STR64 os2_STR64
#define PSTR64 os2_PSTR64
#define SHANDLE os2_SHANDLE
#define LHANDLE os2_LHANDLE
#define HPIPE os2_HPIPE
#define PHPIPE os2_PHPIPE
#define HQUEUE os2_HQUEUE
#define PHQUEUE os2_PHQUEUE
#define HMODULE os2_HMODULE
#define PHMODULE os2_PHMODULE
#define HSEM os2_HSEM
#define PHSEM os2_PHSEM
#define HOBJECT os2_HOBJECT
#define PID os2_PID
#define PPID os2_PPID
#define TID os2_TID
#define PTID os2_PTID
#define PFN os2_PFN
#define PPFN os2_PPFN
#define SEL os2_SEL
#define PSEL os2_PSEL
#define HMTX os2_HMTX
#define PHMTX os2_PHMTX
#define HMUX os2_HMUX
#define PHMUX os2_PHMUX
#define _PANOSE os2__PANOSE
#define PANOSE os2_PANOSE
#define _FONTMETRICS os2__FONTMETRICS
#define FONTMETRICS os2_FONTMETRICS
#define PFONTMETRICS os2_PFONTMETRICS
#define _FATTRS os2__FATTRS
#define FATTRS os2_FATTRS
#define PFATTRS os2_PFATTRS
#define HFILE os2_HFILE
#define PHFILE os2_PHFILE
#define FHLOCK os2_FHLOCK
#define PFHLOCK os2_PFHLOCK
#define HDIR os2_HDIR
#define PHDIR os2_PHDIR
#define _FTIME os2__FTIME
#define FTIME os2_FTIME
#define _FTIME os2__FTIME
#define FTIME os2_FTIME
#define PFTIME os2_PFTIME
#define _FDATE os2__FDATE
#define FDATE os2_FDATE
#define _FDATE os2__FDATE
#define FDATE os2_FDATE
#define PFDATE os2_PFDATE
#define _FEA os2__FEA
#define FEA os2_FEA
#define PFEA os2_PFEA
#define _FEALIST os2__FEALIST
#define FEALIST os2_FEALIST
#define PFEALIST os2_PFEALIST
#define _GEA os2__GEA
#define GEA os2_GEA
#define PGEA os2_PGEA
#define _GEALIST os2__GEALIST
#define GEALIST os2_GEALIST
#define PGEALIST os2_PGEALIST
#define _EAOP os2__EAOP
#define EAOP os2_EAOP
#define PEAOP os2_PEAOP
#define _FEA2 os2__FEA2
#define FEA2 os2_FEA2
#define PFEA2 os2_PFEA2
#define _FEA2LIST os2__FEA2LIST
#define FEA2LIST os2_FEA2LIST
#define PFEA2LIST os2_PFEA2LIST
#define _GEA2 os2__GEA2
#define GEA2 os2_GEA2
#define PGEA2 os2_PGEA2
#define _GEA2LIST os2__GEA2LIST
#define GEA2LIST os2_GEA2LIST
#define PGEA2LIST os2_PGEA2LIST
#define _EAOP2 os2__EAOP2
#define EAOP2 os2_EAOP2
#define PEAOP2 os2_PEAOP2
#define _DENA1 os2__DENA1
#define DENA1 os2_DENA1
#define PDENA1 os2_PDENA1
#define DENA2 os2_DENA2
#define PDENA2 os2_PDENA2
#define _EASIZEBUF os2__EASIZEBUF
#define EASIZEBUF os2_EASIZEBUF
#define PEASIZEBUF os2_PEASIZEBUF
#define _ROUTENAMEBUF os2__ROUTENAMEBUF
#define ROUTENAMEBUF os2_ROUTENAMEBUF
#define PROUTENAMEBUF os2_PROUTENAMEBUF
#define _FSDTHREAD os2__FSDTHREAD
#define FSDTHREAD os2_FSDTHREAD
#define _FSDDAEMON os2__FSDDAEMON
#define FSDDAEMON os2_FSDDAEMON
#define _FILEFINDBUF os2__FILEFINDBUF
#define FILEFINDBUF os2_FILEFINDBUF
#define PFILEFINDBUF os2_PFILEFINDBUF
#define _FILEFINDBUF2 os2__FILEFINDBUF2
#define FILEFINDBUF2 os2_FILEFINDBUF2
#define PFILEFINDBUF2 os2_PFILEFINDBUF2
#define _FILEFINDBUF3 os2__FILEFINDBUF3
#define FILEFINDBUF3 os2_FILEFINDBUF3
#define PFILEFINDBUF3 os2_PFILEFINDBUF3
#define _FILEFINDBUF4 os2__FILEFINDBUF4
#define FILEFINDBUF4 os2_FILEFINDBUF4
#define PFILEFINDBUF4 os2_PFILEFINDBUF4
#define _FILEFINDBUF3L os2__FILEFINDBUF3L
#define FILEFINDBUF3L os2_FILEFINDBUF3L
#define PFILEFINDBUF3L os2_PFILEFINDBUF3L
#define _FILEFINDBUF4L os2__FILEFINDBUF4L
#define FILEFINDBUF4L os2_FILEFINDBUF4L
#define PFILEFINDBUF4L os2_PFILEFINDBUF4L
#define _FILELOCK os2__FILELOCK
#define FILELOCK os2_FILELOCK
#define PFILELOCK os2_PFILELOCK
#define _FILELOCKL os2__FILELOCKL
#define FILELOCKL os2_FILELOCKL
#define PFILELOCKL os2_PFILELOCKL
#define _FILESTATUS os2__FILESTATUS
#define FILESTATUS os2_FILESTATUS
#define PFILESTATUS os2_PFILESTATUS
#define _FILESTATUS2 os2__FILESTATUS2
#define FILESTATUS2 os2_FILESTATUS2
#define PFILESTATUS2 os2_PFILESTATUS2
#define _FILESTATUS3 os2__FILESTATUS3
#define FILESTATUS3 os2_FILESTATUS3
#define PFILESTATUS3 os2_PFILESTATUS3
#define _FILESTATUS4 os2__FILESTATUS4
#define FILESTATUS4 os2_FILESTATUS4
#define PFILESTATUS4 os2_PFILESTATUS4
#define _FILESTATUS3L os2__FILESTATUS3L
#define FILESTATUS3L os2_FILESTATUS3L
#define PFILESTATUS3L os2_PFILESTATUS3L
#define _FILESTATUS4L os2__FILESTATUS4L
#define FILESTATUS4L os2_FILESTATUS4L
#define PFILESTATUS4L os2_PFILESTATUS4L
#define _FSALLOCATE os2__FSALLOCATE
#define FSALLOCATE os2_FSALLOCATE
#define PFSALLOCATE os2_PFSALLOCATE
#define _FSQBUFFER os2__FSQBUFFER
#define FSQBUFFER os2_FSQBUFFER
#define PFSQBUFFER os2_PFSQBUFFER
#define _FSQBUFFER2 os2__FSQBUFFER2
#define FSQBUFFER2 os2_FSQBUFFER2
#define PFSQBUFFER2 os2_PFSQBUFFER2
#define _SPOOLATTACH os2__SPOOLATTACH
#define SPOOLATTACH os2_SPOOLATTACH
#define PSPOOLATTACH os2_PSPOOLATTACH
#define _VOLUMELABEL os2__VOLUMELABEL
#define VOLUMELABEL os2_VOLUMELABEL
#define PVOLUMELABEL os2_PVOLUMELABEL
#define _FSINFO os2__FSINFO
#define FSINFO os2_FSINFO
#define PFSINFO os2_PFSINFO
#define _LISTIO_CB os2__LISTIO_CB
#define LISTIO_CB os2_LISTIO_CB
#define PLISTIO os2_PLISTIO
#define _LISTIO_CBL os2__LISTIO_CBL
#define LISTIO_CBL os2_LISTIO_CBL
#define PLISTIOL os2_PLISTIOL
#define _DCBINFO os2__DCBINFO
#define DCBINFO os2_DCBINFO
#define PDCBINFO os2_PDCBINFO
#define _LINECONTROL os2__LINECONTROL
#define LINECONTROL os2_LINECONTROL
#define PLINECONTROL os2_PLINECONTROL
#define _MODEMSTATUS os2__MODEMSTATUS
#define MODEMSTATUS os2_MODEMSTATUS
#define PMODEMSTATUS os2_PMODEMSTATUS
#define _KBDTYPE os2__KBDTYPE
#define KBDTYPE os2_KBDTYPE
#define PKBDTYPE os2_PKBDTYPE
#define _RATEDELAY os2__RATEDELAY
#define RATEDELAY os2_RATEDELAY
#define PRATEDELAY os2_PRATEDELAY
#define _CODEPAGEINFO os2__CODEPAGEINFO
#define CODEPAGEINFO os2_CODEPAGEINFO
#define PCODEPAGEINFO os2_PCODEPAGEINFO
#define _CPID os2__CPID
#define CPID os2_CPID
#define PCPID os2_PCPID
#define _SHIFTSTATE os2__SHIFTSTATE
#define SHIFTSTATE os2_SHIFTSTATE
#define PSHIFTSTATE os2_PSHIFTSTATE
#define _HOTKEY os2__HOTKEY
#define HOTKEY os2_HOTKEY
#define PHOTKEY os2_PHOTKEY
#define _PTRDRAWFUNCTION os2__PTRDRAWFUNCTION
#define PTRDRAWFUNCTION os2_PTRDRAWFUNCTION
#define PPTRDRAWFUNCTION os2_PPTRDRAWFUNCTION
#define _PTRDRAWADDRESS os2__PTRDRAWADDRESS
#define PTRDRAWADDRESS os2_PTRDRAWADDRESS
#define PPTRDRAWADDRESS os2_PPTRDRAWADDRESS
#define _PTRDRAWDATA os2__PTRDRAWDATA
#define PTRDRAWDATA os2_PTRDRAWDATA
#define PPTRDRAWDATA os2_PPTRDRAWDATA
#define _TRACKLAYOUT os2__TRACKLAYOUT
#define TRACKLAYOUT os2_TRACKLAYOUT
#define PTRACKLAYOUT os2_PTRACKLAYOUT
#define _TRACKFORMAT os2__TRACKFORMAT
#define TRACKFORMAT os2_TRACKFORMAT
#define PTRACKFORMAT os2_PTRACKFORMAT
#define _BIOSPARAMETERBLOCK os2__BIOSPARAMETERBLOCK
#define BIOSPARAMETERBLOCK os2_BIOSPARAMETERBLOCK
#define PBIOSPARAMETERBLOCK os2_PBIOSPARAMETERBLOCK
#define _DEVICEPARAMETERBLOCK os2__DEVICEPARAMETERBLOCK
#define DEVICEPARAMETERBLOCK os2_DEVICEPARAMETERBLOCK
#define PDEVICEPARAMETERBLOCK os2_PDEVICEPARAMETERBLOCK
#define _MONITORPOSITION os2__MONITORPOSITION
#define MONITORPOSITION os2_MONITORPOSITION
#define PMONITORPOSITION os2_PMONITORPOSITION
#define _FRAME os2__FRAME
#define FRAME os2_FRAME
#define PFRAME os2_PFRAME
#define _LDTADDRINFO os2__LDTADDRINFO
#define LDTADDRINFO os2_LDTADDRINFO
#define PLDTADDRINFO os2_PLDTADDRINFO
#define _SCREENGROUP os2__SCREENGROUP
#define SCREENGROUP os2_SCREENGROUP
#define PSCREENGROUP os2_PSCREENGROUP
#define _RXQUEUE os2__RXQUEUE
#define RXQUEUE os2_RXQUEUE
#define PRXQUEUE os2_PRXQUEUE
#define _GETLINIOCTLDATA os2__GETLINIOCTLDATA
#define GETLINIOCTLDATA os2_GETLINIOCTLDATA
#define PGETLINIOCTLDATA os2_PGETLINIOCTLDATA
#define _BANKINFO os2__BANKINFO
#define BANKINFO os2_BANKINFO
#define _GLOBALIOCTLDATA os2__GLOBALIOCTLDATA
#define GLOBALIOCTLDATA os2_GLOBALIOCTLDATA
#define _OEMSVGAINFO os2__OEMSVGAINFO
#define OEMSVGAINFO os2_OEMSVGAINFO
#define _OEMINFO os2__OEMINFO
#define OEMINFO os2_OEMINFO
#define _GETGLOBALPACKET os2__GETGLOBALPACKET
#define GETGLOBALPACKET os2_GETGLOBALPACKET
#define _COUNTRYCODE os2__COUNTRYCODE
#define COUNTRYCODE os2_COUNTRYCODE
#define PCOUNTRYCODE os2_PCOUNTRYCODE
#define _COUNTRYINFO os2__COUNTRYINFO
#define COUNTRYINFO os2_COUNTRYINFO
#define PCOUNTRYINFO os2_PCOUNTRYINFO
#define RT_POINTER os2_RT_POINTER
#define RT_BITMAP os2_RT_BITMAP
#define RT_MENU os2_RT_MENU
#define RT_DIALOG os2_RT_DIALOG
#define RT_STRING os2_RT_STRING
#define RT_FONTDIR os2_RT_FONTDIR
#define RT_FONT os2_RT_FONT
#define RT_ACCELTABLE os2_RT_ACCELTABLE
#define RT_RCDATA os2_RT_RCDATA
#define RT_MESSAGE os2_RT_MESSAGE
#define RT_DLGINCLUDE os2_RT_DLGINCLUDE
#define RT_VKEYTBL os2_RT_VKEYTBL
#define RT_KEYTBL os2_RT_KEYTBL
#define RT_CHARTBL os2_RT_CHARTBL
#define RT_DISPLAYINFO os2_RT_DISPLAYINFO
#define RT_FKASHORT os2_RT_FKASHORT
#define RT_FKALONG os2_RT_FKALONG
#define RT_HELPTABLE os2_RT_HELPTABLE
#define RT_HELPSUBTABLE os2_RT_HELPSUBTABLE
#define RT_FDDIR os2_RT_FDDIR
#define RT_FD os2_RT_FD
#define RT_MAX os2_RT_MAX
#define RT_RESNAMES os2_RT_RESNAMES
#define _RESULTCODES os2__RESULTCODES
#define RESULTCODES os2_RESULTCODES
#define PRESULTCODES os2_PRESULTCODES
#define PTIB2 os2_PTIB2
#define PTIB os2_PTIB
#define PPIB os2_PPIB
#define PFNTHREAD os2_PFNTHREAD
#define PFNEXITLIST os2_PFNEXITLIST
#define _MPAFFINITY os2__MPAFFINITY
#define MPAFFINITY os2_MPAFFINITY
#define PMPAFFINITY os2_PMPAFFINITY
#define _THREADCREATE os2__THREADCREATE
#define THREADCREATE os2_THREADCREATE
#define PTHREADCREATE os2_PTHREADCREATE
#define _STARTDATA os2__STARTDATA
#define STARTDATA os2_STARTDATA
#define PSTARTDATA os2_PSTARTDATA
#define _STATUSDATA os2__STATUSDATA
#define STATUSDATA os2_STATUSDATA
#define PSTATUSDATA os2_PSTATUSDATA
#define HEV os2_HEV
#define PHEV os2_PHEV
#define _PSEMRECORD os2__PSEMRECORD
#define PSEMRECORD os2_PSEMRECORD
#define PSEMRECORD os2_PSEMRECORD
#define _AVAILDATA os2__AVAILDATA
#define AVAILDATA os2_AVAILDATA
#define PAVAILDATA os2_PAVAILDATA
#define _PIPEINFO os2__PIPEINFO
#define PIPEINFO os2_PIPEINFO
#define PPIPEINFO os2_PPIPEINFO
#define _PIPESEMSTATE os2__PIPESEMSTATE
#define PIPESEMSTATE os2_PIPESEMSTATE
#define PPIPESEMSTATE os2_PPIPESEMSTATE
#define _REQUESTDATA os2__REQUESTDATA
#define REQUESTDATA os2_REQUESTDATA
#define PREQUESTDATA os2_PREQUESTDATA
#define CONTEXT_CONTROL os2_CONTEXT_CONTROL
#define CONTEXT_INTEGER os2_CONTEXT_INTEGER
#define CONTEXT_SEGMENTS os2_CONTEXT_SEGMENTS
#define CONTEXT_FLOATING_POINT os2_CONTEXT_FLOATING_POINT
#define CONTEXT_FULL os2_CONTEXT_FULL
#define EH_NONCONTINUABLE os2_EH_NONCONTINUABLE
#define EH_UNWINDING os2_EH_UNWINDING
#define EH_EXIT_UNWIND os2_EH_EXIT_UNWIND
#define EH_STACK_INVALID os2_EH_STACK_INVALID
#define EH_NESTED_CALL os2_EH_NESTED_CALL
#define PFPREG os2_PFPREG
#define _CONTEXT os2__CONTEXT
#define CONTEXT os2_CONTEXT
#define PCONTEXTRECORD os2_PCONTEXTRECORD
#define EXCEPTION_MAXIMUM_PARAMETERS os2_EXCEPTION_MAXIMUM_PARAMETERS
#define _EXCEPTIONREPORTRECORD os2__EXCEPTIONREPORTRECORD
#define EXCEPTIONREPORTRECORD os2_EXCEPTIONREPORTRECORD
#define PEXCEPTIONREPORTRECORD os2_PEXCEPTIONREPORTRECORD
#define ERR os2_ERR
#define _EXCEPTIONREGISTRATIONRECORD os2__EXCEPTIONREGISTRATIONRECORD
#define EXCEPTIONREGISTRATIONRECORD os2_EXCEPTIONREGISTRATIONRECORD
#define PEXCEPTIONREGISTRATIONRECORD os2_PEXCEPTIONREGISTRATIONRECORD
#define _DATETIME os2__DATETIME
#define DATETIME os2_DATETIME
#define PDATETIME os2_PDATETIME
#define HTIMER os2_HTIMER
#define PHTIMER os2_PHTIMER
#define _QWORD os2__QWORD
#define QWORD os2_QWORD
#define PQWORD os2_PQWORD
#define _QSGREC os2__QSGREC
#define QSGREC os2_QSGREC
#define _QSTREC os2__QSTREC
#define QSTREC os2_QSTREC
#define _QSPREC os2__QSPREC
#define QSPREC os2_QSPREC
#define _QSS16REC os2__QSS16REC
#define QSS16REC os2_QSS16REC
#define _QSS16HEADREC os2__QSS16HEADREC
#define QSS16HEADREC os2_QSS16HEADREC
#define _QSMREC os2__QSMREC
#define QSMREC os2_QSMREC
#define _QSOPENQ os2__QSOPENQ
#define QSOPENQ os2_QSOPENQ
#define _QSEVENT os2__QSEVENT
#define QSEVENT os2_QSEVENT
#define _QSMUTEX os2__QSMUTEX
#define QSMUTEX os2_QSMUTEX
#define _QSMUX os2__QSMUX
#define QSMUX os2_QSMUX
#define _QSS32REC os2__QSS32REC
#define QSS32REC os2_QSS32REC
#define _QSLOBJREC os2__QSLOBJREC
#define QSLOBJREC os2_QSLOBJREC
#define _QSLREC os2__QSLREC
#define QSLREC os2_QSLREC
#define _QSEXLREC os2__QSEXLREC
#define QSEXLREC os2_QSEXLREC
#define _QSSFT os2__QSSFT
#define QSSFT os2_QSSFT
#define _QSFREC os2__QSFREC
#define QSFREC os2_QSFREC
#define _QSPTRREC os2__QSPTRREC
#define QSPTRREC os2_QSPTRREC
#define SGID os2_SGID
#define HVDD os2_HVDD
#define PHVDD os2_PHVDD
#define HSPINLOCK os2_HSPINLOCK
#define PHSPINLOCK os2_PHSPINLOCK
#define _RXSTRING os2__RXSTRING
#define RXSTRING os2_RXSTRING
#define PRXSTRING os2_PRXSTRING
#define _RXSYSEXIT os2__RXSYSEXIT
#define RXSYSEXIT os2_RXSYSEXIT
#define PRXSYSEXIT os2_PRXSYSEXIT
#define _SHVBLOCK os2__SHVBLOCK
#define SHVBLOCK os2_SHVBLOCK
#define PSHVBLOCK os2_PSHVBLOCK
#define PEXIT os2_PEXIT
#define _RXFNC_FLAGS os2__RXFNC_FLAGS
#define RXFNC_FLAGS os2_RXFNC_FLAGS
#define _RXFNCCAL_PARM os2__RXFNCCAL_PARM
#define RXFNCCAL_PARM os2_RXFNCCAL_PARM
#define _RXCMD_FLAGS os2__RXCMD_FLAGS
#define RXCMD_FLAGS os2_RXCMD_FLAGS
#define _RXCMDHST_PARM os2__RXCMDHST_PARM
#define RXCMDHST_PARM os2_RXCMDHST_PARM
#define _RXMSQPLL_PARM os2__RXMSQPLL_PARM
#define RXMSQPLL_PARM os2_RXMSQPLL_PARM
#define _RXMSQ_FLAGS os2__RXMSQ_FLAGS
#define RXMSQ_FLAGS os2_RXMSQ_FLAGS
#define _RXMSQPSH_PARM os2__RXMSQPSH_PARM
#define RXMSQPSH_PARM os2_RXMSQPSH_PARM
#define _RXMSQSIZ_PARM os2__RXMSQSIZ_PARM
#define RXMSQSIZ_PARM os2_RXMSQSIZ_PARM
#define _RXMSQNAM_PARM os2__RXMSQNAM_PARM
#define RXMSQNAM_PARM os2_RXMSQNAM_PARM
#define _RXSIOSAY_PARM os2__RXSIOSAY_PARM
#define RXSIOSAY_PARM os2_RXSIOSAY_PARM
#define _RXSIOTRC_PARM os2__RXSIOTRC_PARM
#define RXSIOTRC_PARM os2_RXSIOTRC_PARM
#define _RXSIOTRD_PARM os2__RXSIOTRD_PARM
#define RXSIOTRD_PARM os2_RXSIOTRD_PARM
#define _RXSIODR_PARM os2__RXSIODR_PARM
#define RXSIODR_PARM os2_RXSIODR_PARM
#define _RXHLT_FLAGS os2__RXHLT_FLAGS
#define RXHLT_FLAGS os2_RXHLT_FLAGS
#define _RXHLTTST_PARM os2__RXHLTTST_PARM
#define RXHLTTST_PARM os2_RXHLTTST_PARM
#define _RXTRC_FLAGS os2__RXTRC_FLAGS
#define RXTRC_FLAGS os2_RXTRC_FLAGS
#define _RXTRCTST_PARM os2__RXTRCTST_PARM
#define RXTRCTST_PARM os2_RXTRCTST_PARM
#define WM_DBCSFIRST os2_WM_DBCSFIRST
#define WM_DBCSLAST os2_WM_DBCSLAST
#define WC_FRAME os2_WC_FRAME
#define WC_COMBOBOX os2_WC_COMBOBOX
#define WC_BUTTON os2_WC_BUTTON
#define WC_MENU os2_WC_MENU
#define WC_STATIC os2_WC_STATIC
#define WC_ENTRYFIELD os2_WC_ENTRYFIELD
#define WC_LISTBOX os2_WC_LISTBOX
#define WC_SCROLLBAR os2_WC_SCROLLBAR
#define WC_TITLEBAR os2_WC_TITLEBAR
#define WC_MLE os2_WC_MLE
#define WC_APPSTAT os2_WC_APPSTAT
#define WC_KBDSTAT os2_WC_KBDSTAT
#define WC_PECIC os2_WC_PECIC
#define WC_DBE_KKPOPUP os2_WC_DBE_KKPOPUP
#define WC_SPINBUTTON os2_WC_SPINBUTTON
#define WC_CONTAINER os2_WC_CONTAINER
#define WC_SLIDER os2_WC_SLIDER
#define WC_VALUESET os2_WC_VALUESET
#define WC_NOTEBOOK os2_WC_NOTEBOOK
#define WC_PENFIRST os2_WC_PENFIRST
#define WC_PENLAST os2_WC_PENLAST
#define WC_MMPMFIRST os2_WC_MMPMFIRST
#define WC_CIRCULARSLIDER os2_WC_CIRCULARSLIDER
#define WC_MMPMLAST os2_WC_MMPMLAST
#define WS_VISIBLE os2_WS_VISIBLE
#define WS_DISABLED os2_WS_DISABLED
#define WS_CLIPCHILDREN os2_WS_CLIPCHILDREN
#define WS_CLIPSIBLINGS os2_WS_CLIPSIBLINGS
#define WS_PARENTCLIP os2_WS_PARENTCLIP
#define WS_SAVEBITS os2_WS_SAVEBITS
#define WS_SYNCPAINT os2_WS_SYNCPAINT
#define WS_MINIMIZED os2_WS_MINIMIZED
#define WS_MAXIMIZED os2_WS_MAXIMIZED
#define WS_ANIMATE os2_WS_ANIMATE
#define WS_GROUP os2_WS_GROUP
#define WS_TABSTOP os2_WS_TABSTOP
#define WS_MULTISELECT os2_WS_MULTISELECT
#define CS_MOVENOTIFY os2_CS_MOVENOTIFY
#define CS_SIZEREDRAW os2_CS_SIZEREDRAW
#define CS_HITTEST os2_CS_HITTEST
#define CS_PUBLIC os2_CS_PUBLIC
#define CS_FRAME os2_CS_FRAME
#define CS_CLIPCHILDREN os2_CS_CLIPCHILDREN
#define CS_CLIPSIBLINGS os2_CS_CLIPSIBLINGS
#define CS_PARENTCLIP os2_CS_PARENTCLIP
#define CS_SAVEBITS os2_CS_SAVEBITS
#define CS_SYNCPAINT os2_CS_SYNCPAINT
#define DT_LEFT os2_DT_LEFT
#define DT_QUERYEXTENT os2_DT_QUERYEXTENT
#define DT_UNDERSCORE os2_DT_UNDERSCORE
#define DT_STRIKEOUT os2_DT_STRIKEOUT
#define DT_TEXTATTRS os2_DT_TEXTATTRS
#define DT_EXTERNALLEADING os2_DT_EXTERNALLEADING
#define DT_CENTER os2_DT_CENTER
#define DT_RIGHT os2_DT_RIGHT
#define DT_TOP os2_DT_TOP
#define DT_VCENTER os2_DT_VCENTER
#define DT_BOTTOM os2_DT_BOTTOM
#define DT_HALFTONE os2_DT_HALFTONE
#define DT_MNEMONIC os2_DT_MNEMONIC
#define DT_WORDBREAK os2_DT_WORDBREAK
#define DT_ERASERECT os2_DT_ERASERECT
#define SWP_SIZE os2_SWP_SIZE
#define SWP_MOVE os2_SWP_MOVE
#define SWP_ZORDER os2_SWP_ZORDER
#define SWP_SHOW os2_SWP_SHOW
#define SWP_HIDE os2_SWP_HIDE
#define SWP_NOREDRAW os2_SWP_NOREDRAW
#define SWP_NOADJUST os2_SWP_NOADJUST
#define SWP_ACTIVATE os2_SWP_ACTIVATE
#define SWP_DEACTIVATE os2_SWP_DEACTIVATE
#define SWP_EXTSTATECHANGE os2_SWP_EXTSTATECHANGE
#define SWP_MINIMIZE os2_SWP_MINIMIZE
#define SWP_MAXIMIZE os2_SWP_MAXIMIZE
#define SWP_RESTORE os2_SWP_RESTORE
#define SWP_FOCUSACTIVATE os2_SWP_FOCUSACTIVATE
#define SWP_FOCUSDEACTIVATE os2_SWP_FOCUSDEACTIVATE
#define SWP_NOAUTOCLOSE os2_SWP_NOAUTOCLOSE
#define HWND_DESKTOP os2_HWND_DESKTOP
#define HWND_OBJECT os2_HWND_OBJECT
#define HWND_TOP os2_HWND_TOP
#define HWND_BOTTOM os2_HWND_BOTTOM
#define HWND_THREADCAPTURE os2_HWND_THREADCAPTURE
#define HACCEL os2_HACCEL
#define HRGN os2_HRGN
#define PHRGN os2_PHRGN
#define MRESULT os2_MRESULT
#define PMRESULT os2_PMRESULT
#define MPARAM os2_MPARAM
#define PMPARAM os2_PMPARAM
#define HPOINTER os2_HPOINTER
#define HLIB os2_HLIB
#define PHLIB os2_PHLIB
#define COLOR os2_COLOR
#define PCOLOR os2_PCOLOR
#define HAB os2_HAB
#define PHAB os2_PHAB
#define HPS os2_HPS
#define PHPS os2_PHPS
#define HDC os2_HDC
#define PHDC os2_PHDC
#define HWND os2_HWND
#define PHWND os2_PHWND
#define HMQ os2_HMQ
#define HPAL os2_HPAL
#define PHPAL os2_PHPAL
#define HBITMAP os2_HBITMAP
#define PHBITMAP os2_PHBITMAP
#define ERRORID os2_ERRORID
#define PERRORID os2_PERRORID
#define PFNWP os2_PFNWP
#define _POINTL os2__POINTL
#define POINTL os2_POINTL
#define PPOINTL os2_PPOINTL
#define _POINTS os2__POINTS
#define POINTS os2_POINTS
#define PPOINTS os2_PPOINTS
#define _RECTL os2__RECTL
#define RECTL os2_RECTL
#define PRECTL os2_PRECTL
#define WM_NULL os2_WM_NULL
#define WM_CREATE os2_WM_CREATE
#define WM_DESTROY os2_WM_DESTROY
#define WM_ENABLE os2_WM_ENABLE
#define WM_SHOW os2_WM_SHOW
#define WM_MOVE os2_WM_MOVE
#define WM_SIZE os2_WM_SIZE
#define WM_ADJUSTWINDOWPOS os2_WM_ADJUSTWINDOWPOS
#define WM_CALCVALIDRECTS os2_WM_CALCVALIDRECTS
#define WM_SETWINDOWPARAMS os2_WM_SETWINDOWPARAMS
#define WM_QUERYWINDOWPARAMS os2_WM_QUERYWINDOWPARAMS
#define WM_HITTEST os2_WM_HITTEST
#define WM_ACTIVATE os2_WM_ACTIVATE
#define WM_SETFOCUS os2_WM_SETFOCUS
#define WM_SETSELECTION os2_WM_SETSELECTION
#define WM_PPAINT os2_WM_PPAINT
#define WM_PSETFOCUS os2_WM_PSETFOCUS
#define WM_PSYSCOLORCHANGE os2_WM_PSYSCOLORCHANGE
#define WM_PSIZE os2_WM_PSIZE
#define WM_PACTIVATE os2_WM_PACTIVATE
#define WM_PCONTROL os2_WM_PCONTROL
#define WM_COMMAND os2_WM_COMMAND
#define WM_SYSCOMMAND os2_WM_SYSCOMMAND
#define WM_HELP os2_WM_HELP
#define WM_PAINT os2_WM_PAINT
#define WM_TIMER os2_WM_TIMER
#define WM_SEM1 os2_WM_SEM1
#define WM_SEM2 os2_WM_SEM2
#define WM_SEM3 os2_WM_SEM3
#define WM_SEM4 os2_WM_SEM4
#define WM_CLOSE os2_WM_CLOSE
#define WM_QUIT os2_WM_QUIT
#define WM_SYSCOLORCHANGE os2_WM_SYSCOLORCHANGE
#define WM_SYSVALUECHANGED os2_WM_SYSVALUECHANGED
#define WM_APPTERMINATENOTIFY os2_WM_APPTERMINATENOTIFY
#define WM_PRESPARAMCHANGED os2_WM_PRESPARAMCHANGED
#define WM_CONTROL os2_WM_CONTROL
#define WM_VSCROLL os2_WM_VSCROLL
#define WM_HSCROLL os2_WM_HSCROLL
#define WM_INITMENU os2_WM_INITMENU
#define WM_MENUSELECT os2_WM_MENUSELECT
#define WM_MENUEND os2_WM_MENUEND
#define WM_DRAWITEM os2_WM_DRAWITEM
#define WM_MEASUREITEM os2_WM_MEASUREITEM
#define WM_CONTROLPOINTER os2_WM_CONTROLPOINTER
#define WM_QUERYDLGCODE os2_WM_QUERYDLGCODE
#define WM_INITDLG os2_WM_INITDLG
#define WM_SUBSTITUTESTRING os2_WM_SUBSTITUTESTRING
#define WM_MATCHMNEMONIC os2_WM_MATCHMNEMONIC
#define WM_SAVEAPPLICATION os2_WM_SAVEAPPLICATION
#define WM_HELPBASE os2_WM_HELPBASE
#define WM_HELPTOP os2_WM_HELPTOP
#define WM_USER os2_WM_USER
#define _QMSG os2__QMSG
#define QMSG os2_QMSG
#define PQMSG os2_PQMSG
#define _COMMANDMSG os2__COMMANDMSG
#define COMMANDMSG os2_COMMANDMSG
#define PCMDMSG os2_PCMDMSG
#define _MQINFO os2__MQINFO
#define MQINFO os2_MQINFO
#define PMQINFO os2_PMQINFO
#define _SWP os2__SWP
#define SWP os2_SWP
#define PSWP os2_PSWP
#define _ICONINFO os2__ICONINFO
#define ICONINFO os2_ICONINFO
#define PICONINFO os2_PICONINFO
#define _FRAMECDATA os2__FRAMECDATA
#define FRAMECDATA os2_FRAMECDATA
#define PFRAMECDATA os2_PFRAMECDATA
#define WM_FLASHWINDOW os2_WM_FLASHWINDOW
#define WM_FORMATFRAME os2_WM_FORMATFRAME
#define WM_UPDATEFRAME os2_WM_UPDATEFRAME
#define WM_FOCUSCHANGE os2_WM_FOCUSCHANGE
#define WM_SETBORDERSIZE os2_WM_SETBORDERSIZE
#define WM_TRACKFRAME os2_WM_TRACKFRAME
#define WM_MINMAXFRAME os2_WM_MINMAXFRAME
#define WM_SETICON os2_WM_SETICON
#define WM_QUERYICON os2_WM_QUERYICON
#define WM_SETACCELTABLE os2_WM_SETACCELTABLE
#define WM_QUERYACCELTABLE os2_WM_QUERYACCELTABLE
#define WM_TRANSLATEACCEL os2_WM_TRANSLATEACCEL
#define WM_QUERYTRACKINFO os2_WM_QUERYTRACKINFO
#define WM_QUERYBORDERSIZE os2_WM_QUERYBORDERSIZE
#define WM_NEXTMENU os2_WM_NEXTMENU
#define WM_ERASEBACKGROUND os2_WM_ERASEBACKGROUND
#define WM_QUERYFRAMEINFO os2_WM_QUERYFRAMEINFO
#define WM_QUERYFOCUSCHAIN os2_WM_QUERYFOCUSCHAIN
#define WM_OWNERPOSCHANGE os2_WM_OWNERPOSCHANGE
#define WM_CALCFRAMERECT os2_WM_CALCFRAMERECT
#define WM_WINDOWPOSCHANGED os2_WM_WINDOWPOSCHANGED
#define WM_ADJUSTFRAMEPOS os2_WM_ADJUSTFRAMEPOS
#define WM_QUERYFRAMECTLCOUNT os2_WM_QUERYFRAMECTLCOUNT
#define WM_QUERYHELPINFO os2_WM_QUERYHELPINFO
#define WM_SETHELPINFO os2_WM_SETHELPINFO
#define WM_ERROR os2_WM_ERROR
#define WM_REALIZEPALETTE os2_WM_REALIZEPALETTE
#define HSAVEWP os2_HSAVEWP
#define _QVERSDATA os2__QVERSDATA
#define QVERSDATA os2_QVERSDATA
#define PQVERSDATA os2_PQVERSDATA
#define WM_QUERYCONVERTPOS os2_WM_QUERYCONVERTPOS
#define _CLASSINFO os2__CLASSINFO
#define CLASSINFO os2_CLASSINFO
#define PCLASSINFO os2_PCLASSINFO
#define _CREATESTRUCT os2__CREATESTRUCT
#define CREATESTRUCT os2_CREATESTRUCT
#define PCREATESTRUCT os2_PCREATESTRUCT
#define HENUM os2_HENUM
#define _ACCEL os2__ACCEL
#define ACCEL os2_ACCEL
#define PACCEL os2_PACCEL
#define _ACCELTABLE os2__ACCELTABLE
#define ACCELTABLE os2_ACCELTABLE
#define PACCELTABLE os2_PACCELTABLE
#define HATOMTBL os2_HATOMTBL
#define ATOM os2_ATOM
#define _BTNCDATA os2__BTNCDATA
#define BTNCDATA os2_BTNCDATA
#define PBTNCDATA os2_PBTNCDATA
#define _USERBUTTON os2__USERBUTTON
#define USERBUTTON os2_USERBUTTON
#define PUSERBUTTON os2_PUSERBUTTON
#define WM_RENDERFMT os2_WM_RENDERFMT
#define WM_RENDERALLFMTS os2_WM_RENDERALLFMTS
#define WM_DESTROYCLIPBOARD os2_WM_DESTROYCLIPBOARD
#define WM_PAINTCLIPBOARD os2_WM_PAINTCLIPBOARD
#define WM_SIZECLIPBOARD os2_WM_SIZECLIPBOARD
#define WM_HSCROLLCLIPBOARD os2_WM_HSCROLLCLIPBOARD
#define WM_VSCROLLCLIPBOARD os2_WM_VSCROLLCLIPBOARD
#define WM_DRAWCLIPBOARD os2_WM_DRAWCLIPBOARD
#define _CPTEXT os2__CPTEXT
#define CPTEXT os2_CPTEXT
#define PCPTEXT os2_PCPTEXT
#define _MFP os2__MFP
#define MFP os2_MFP
#define PMFP os2_PMFP
#define WM_DDE_FIRST os2_WM_DDE_FIRST
#define WM_DDE_INITIATE os2_WM_DDE_INITIATE
#define WM_DDE_REQUEST os2_WM_DDE_REQUEST
#define WM_DDE_ACK os2_WM_DDE_ACK
#define WM_DDE_DATA os2_WM_DDE_DATA
#define WM_DDE_ADVISE os2_WM_DDE_ADVISE
#define WM_DDE_UNADVISE os2_WM_DDE_UNADVISE
#define WM_DDE_POKE os2_WM_DDE_POKE
#define WM_DDE_EXECUTE os2_WM_DDE_EXECUTE
#define WM_DDE_TERMINATE os2_WM_DDE_TERMINATE
#define WM_DDE_INITIATEACK os2_WM_DDE_INITIATEACK
#define WM_DDE_LAST os2_WM_DDE_LAST
#define _CONVCONTEXT os2__CONVCONTEXT
#define CONVCONTEXT os2_CONVCONTEXT
#define PCONVCONTEXT os2_PCONVCONTEXT
#define _DDEINIT os2__DDEINIT
#define DDEINIT os2_DDEINIT
#define PDDEINIT os2_PDDEINIT
#define _DDESTRUCT os2__DDESTRUCT
#define DDESTRUCT os2_DDESTRUCT
#define PDDESTRUCT os2_PDDESTRUCT
#define _CURSORINFO os2__CURSORINFO
#define CURSORINFO os2_CURSORINFO
#define PCURSORINFO os2_PCURSORINFO
#define _DESKTOP os2__DESKTOP
#define DESKTOP os2_DESKTOP
#define PDESKTOP os2_PDESKTOP
#define MB_OK os2_MB_OK
#define MB_OKCANCEL os2_MB_OKCANCEL
#define MB_RETRYCANCEL os2_MB_RETRYCANCEL
#define MB_ABORTRETRYIGNORE os2_MB_ABORTRETRYIGNORE
#define MB_YESNO os2_MB_YESNO
#define MB_YESNOCANCEL os2_MB_YESNOCANCEL
#define MB_CANCEL os2_MB_CANCEL
#define MB_ENTER os2_MB_ENTER
#define MB_ENTERCANCEL os2_MB_ENTERCANCEL
#define MB_NOICON os2_MB_NOICON
#define MB_CUANOTIFICATION os2_MB_CUANOTIFICATION
#define MB_ICONQUESTION os2_MB_ICONQUESTION
#define MB_ICONEXCLAMATION os2_MB_ICONEXCLAMATION
#define MB_CUAWARNING os2_MB_CUAWARNING
#define MB_ICONASTERISK os2_MB_ICONASTERISK
#define MB_ICONHAND os2_MB_ICONHAND
#define MB_CUACRITICAL os2_MB_CUACRITICAL
#define MB_QUERY os2_MB_QUERY
#define MB_WARNING os2_MB_WARNING
#define MB_INFORMATION os2_MB_INFORMATION
#define MB_CRITICAL os2_MB_CRITICAL
#define MB_ERROR os2_MB_ERROR
#define MB_CUSTOMICON os2_MB_CUSTOMICON
#define MB_DEFBUTTON1 os2_MB_DEFBUTTON1
#define MB_DEFBUTTON2 os2_MB_DEFBUTTON2
#define MB_DEFBUTTON3 os2_MB_DEFBUTTON3
#define MB_APPLMODAL os2_MB_APPLMODAL
#define MB_SYSTEMMODAL os2_MB_SYSTEMMODAL
#define MB_HELP os2_MB_HELP
#define MB_MOVEABLE os2_MB_MOVEABLE
#define MB_NONMODAL os2_MB_NONMODAL
#define _MB2D os2__MB2D
#define MB2D os2_MB2D
#define PMB2D os2_PMB2D
#define _MB2INFO os2__MB2INFO
#define MB2INFO os2_MB2INFO
#define PMB2INFO os2_PMB2INFO
#define _DLGTITEM os2__DLGTITEM
#define DLGTITEM os2_DLGTITEM
#define PDLGTITEM os2_PDLGTITEM
#define _DLGTEMPLATE os2__DLGTEMPLATE
#define DLGTEMPLATE os2_DLGTEMPLATE
#define PDLGTEMPLATE os2_PDLGTEMPLATE
#define _COMBOCDATA os2__COMBOCDATA
#define COMBOCDATA os2_COMBOCDATA
#define PCOMBOCDATA os2_PCOMBOCDATA
#define _ENTRYFDATA os2__ENTRYFDATA
#define ENTRYFDATA os2_ENTRYFDATA
#define PENTRYFDATA os2_PENTRYFDATA
#define _ERRINFO os2__ERRINFO
#define ERRINFO os2_ERRINFO
#define PERRINFO os2_PERRINFO
#define _SMHSTRUCT os2__SMHSTRUCT
#define SMHSTRUCT os2_SMHSTRUCT
#define PSMHSTRUCT os2_PSMHSTRUCT
#define WM_MOUSEFIRST os2_WM_MOUSEFIRST
#define WM_MOUSEMOVE os2_WM_MOUSEMOVE
#define WM_BUTTONCLICKFIRST os2_WM_BUTTONCLICKFIRST
#define WM_BUTTON1DOWN os2_WM_BUTTON1DOWN
#define WM_BUTTON1UP os2_WM_BUTTON1UP
#define WM_BUTTON1DBLCLK os2_WM_BUTTON1DBLCLK
#define WM_BUTTON2DOWN os2_WM_BUTTON2DOWN
#define WM_BUTTON2UP os2_WM_BUTTON2UP
#define WM_BUTTON2DBLCLK os2_WM_BUTTON2DBLCLK
#define WM_BUTTON3DOWN os2_WM_BUTTON3DOWN
#define WM_BUTTON3UP os2_WM_BUTTON3UP
#define WM_BUTTON3DBLCLK os2_WM_BUTTON3DBLCLK
#define WM_BUTTONCLICKLAST os2_WM_BUTTONCLICKLAST
#define WM_MOUSELAST os2_WM_MOUSELAST
#define WM_CHAR os2_WM_CHAR
#define WM_VIOCHAR os2_WM_VIOCHAR
#define WM_JOURNALNOTIFY os2_WM_JOURNALNOTIFY
#define WM_MOUSEMAP os2_WM_MOUSEMAP
#define WM_VRNDISABLED os2_WM_VRNDISABLED
#define WM_VRNENABLED os2_WM_VRNENABLED
#define WM_EXTMOUSEFIRST os2_WM_EXTMOUSEFIRST
#define WM_CHORD os2_WM_CHORD
#define WM_BUTTON1MOTIONSTART os2_WM_BUTTON1MOTIONSTART
#define WM_BUTTON1MOTIONEND os2_WM_BUTTON1MOTIONEND
#define WM_BUTTON1CLICK os2_WM_BUTTON1CLICK
#define WM_BUTTON2MOTIONSTART os2_WM_BUTTON2MOTIONSTART
#define WM_BUTTON2MOTIONEND os2_WM_BUTTON2MOTIONEND
#define WM_BUTTON2CLICK os2_WM_BUTTON2CLICK
#define WM_BUTTON3MOTIONSTART os2_WM_BUTTON3MOTIONSTART
#define WM_BUTTON3MOTIONEND os2_WM_BUTTON3MOTIONEND
#define WM_BUTTON3CLICK os2_WM_BUTTON3CLICK
#define WM_EXTMOUSELAST os2_WM_EXTMOUSELAST
#define WM_MOUSETRANSLATEFIRST os2_WM_MOUSETRANSLATEFIRST
#define WM_BEGINDRAG os2_WM_BEGINDRAG
#define WM_ENDDRAG os2_WM_ENDDRAG
#define WM_SINGLESELECT os2_WM_SINGLESELECT
#define WM_OPEN os2_WM_OPEN
#define WM_CONTEXTMENU os2_WM_CONTEXTMENU
#define WM_CONTEXTHELP os2_WM_CONTEXTHELP
#define WM_TEXTEDIT os2_WM_TEXTEDIT
#define WM_BEGINSELECT os2_WM_BEGINSELECT
#define WM_ENDSELECT os2_WM_ENDSELECT
#define WM_MOUSETRANSLATELAST os2_WM_MOUSETRANSLATELAST
#define WM_PICKUP os2_WM_PICKUP
#define WM_PENFIRST os2_WM_PENFIRST
#define WM_PENLAST os2_WM_PENLAST
#define WM_MMPMFIRST os2_WM_MMPMFIRST
#define WM_MMPMLAST os2_WM_MMPMLAST
#define WM_BIDI_FIRST os2_WM_BIDI_FIRST
#define WM_BIDI_LAST os2_WM_BIDI_LAST
#define _CHARMSG os2__CHARMSG
#define CHARMSG os2_CHARMSG
#define PCHRMSG os2_PCHRMSG
#define _MOUSEMSG os2__MOUSEMSG
#define MOUSEMSG os2_MOUSEMSG
#define PMSEMSG os2_PMSEMSG
#define _LBOXINFO os2__LBOXINFO
#define LBOXINFO os2_LBOXINFO
#define PLBOXINFO os2_PLBOXINFO
#define _MENUITEM os2__MENUITEM
#define MENUITEM os2_MENUITEM
#define PMENUITEM os2_PMENUITEM
#define LPMT os2_LPMT
#define _OWNERITEM os2__OWNERITEM
#define OWNERITEM os2_OWNERITEM
#define POWNERITEM os2_POWNERITEM
#define _WNDPARAMS os2__WNDPARAMS
#define WNDPARAMS os2_WNDPARAMS
#define PWNDPARAMS os2_PWNDPARAMS
#define _POINTERINFO os2__POINTERINFO
#define POINTERINFO os2_POINTERINFO
#define PPOINTERINFO os2_PPOINTERINFO
#define _SBCDATA os2__SBCDATA
#define SBCDATA os2_SBCDATA
#define PSBCDATA os2_PSBCDATA
#define WM_MSGBOXINIT os2_WM_MSGBOXINIT
#define WM_MSGBOXDISMISS os2_WM_MSGBOXDISMISS
#define WM_CTLCOLORCHANGE os2_WM_CTLCOLORCHANGE
#define WM_QUERYCTLTYPE os2_WM_QUERYCTLTYPE
#define _CTLCOLOR os2__CTLCOLOR
#define CTLCOLOR os2_CTLCOLOR
#define PCTLCOLOR os2_PCTLCOLOR
#define _PARAM os2__PARAM
#define PARAM os2_PARAM
#define NPPARAM os2_NPPARAM
#define PPARAM os2_PPARAM
#define _PRESPARAMS os2__PRESPARAMS
#define PRESPARAMS os2_PRESPARAMS
#define NPPRESPARAMS os2_NPPRESPARAMS
#define PPRESPARAMS os2_PPRESPARAMS
#define _TRACKINFO os2__TRACKINFO
#define TRACKINFO os2_TRACKINFO
#define PTRACKINFO os2_PTRACKINFO
#define IPT os2_IPT
#define PIPT os2_PIPT
#define PIX os2_PIX
#define LINE os2_LINE
#define _FORMATRECT os2__FORMATRECT
#define FORMATRECT os2_FORMATRECT
#define PFORMATRECT os2_PFORMATRECT
#define _MLECTLDATA os2__MLECTLDATA
#define MLECTLDATA os2_MLECTLDATA
#define PMLECTLDATA os2_PMLECTLDATA
#define _MLEOVERFLOW os2__MLEOVERFLOW
#define MLEOVERFLOW os2_MLEOVERFLOW
#define POVERFLOW os2_POVERFLOW
#define _MLEMARGSTRUCT os2__MLEMARGSTRUCT
#define MLEMARGSTRUCT os2_MLEMARGSTRUCT
#define PMARGSTRUCT os2_PMARGSTRUCT
#define _SEARCH os2__SEARCH
#define SEARCH os2_SEARCH
#define PMLE_SEARCHDATA os2_PMLE_SEARCHDATA
#define TA_NORMAL_HORIZ os2_TA_NORMAL_HORIZ
#define TA_LEFT os2_TA_LEFT
#define TA_CENTER os2_TA_CENTER
#define TA_RIGHT os2_TA_RIGHT
#define TA_STANDARD_HORIZ os2_TA_STANDARD_HORIZ
#define TA_NORMAL_VERT os2_TA_NORMAL_VERT
#define TA_TOP os2_TA_TOP
#define TA_HALF os2_TA_HALF
#define TA_BASE os2_TA_BASE
#define TA_BOTTOM os2_TA_BOTTOM
#define TA_STANDARD_VERT os2_TA_STANDARD_VERT
#define RGN_ERROR os2_RGN_ERROR
#define RGN_NULL os2_RGN_NULL
#define RGN_RECT os2_RGN_RECT
#define RGN_COMPLEX os2_RGN_COMPLEX
#define PBUNDLE os2_PBUNDLE
#define FIXED os2_FIXED
#define PFIXED os2_PFIXED
#define HMF os2_HMF
#define PHMF os2_PHMF
#define _SIZEL os2__SIZEL
#define SIZEL os2_SIZEL
#define PSIZEL os2_PSIZEL
#define _RGNRECT os2__RGNRECT
#define RGNRECT os2_RGNRECT
#define PRGNRECT os2_PRGNRECT
#define _MATRIXLF os2__MATRIXLF
#define MATRIXLF os2_MATRIXLF
#define PMATRIXLF os2_PMATRIXLF
#define _ARCPARAMS os2__ARCPARAMS
#define ARCPARAMS os2_ARCPARAMS
#define PARCPARAMS os2_PARCPARAMS
#define _SIZEF os2__SIZEF
#define SIZEF os2_SIZEF
#define PSIZEF os2_PSIZEF
#define _POLYGON os2__POLYGON
#define POLYGON os2_POLYGON
#define PPOLYGON os2_PPOLYGON
#define _POLYSET os2__POLYSET
#define POLYSET os2_POLYSET
#define PPOLYSET os2_PPOLYSET
#define _GRADIENTL os2__GRADIENTL
#define GRADIENTL os2_GRADIENTL
#define PGRADIENTL os2_PGRADIENTL
#define _KERNINGPAIRS os2__KERNINGPAIRS
#define KERNINGPAIRS os2_KERNINGPAIRS
#define PKERNINGPAIRS os2_PKERNINGPAIRS
#define _FACENAMEDESC os2__FACENAMEDESC
#define FACENAMEDESC os2_FACENAMEDESC
#define PFACENAMEDESC os2_PFACENAMEDESC
#define FFDESCS os2_FFDESCS
#define PFFDESCS os2_PFFDESCS
#define _FFDESCS2 os2__FFDESCS2
#define FFDESCS2 os2_FFDESCS2
#define PFFDESCS2 os2_PFFDESCS2
#define _LINEBUNDLE os2__LINEBUNDLE
#define LINEBUNDLE os2_LINEBUNDLE
#define PLINEBUNDLE os2_PLINEBUNDLE
#define _CHARBUNDLE os2__CHARBUNDLE
#define CHARBUNDLE os2_CHARBUNDLE
#define PCHARBUNDLE os2_PCHARBUNDLE
#define _MARKERBUNDLE os2__MARKERBUNDLE
#define MARKERBUNDLE os2_MARKERBUNDLE
#define PMARKERBUNDLE os2_PMARKERBUNDLE
#define _AREABUNDLE os2__AREABUNDLE
#define AREABUNDLE os2_AREABUNDLE
#define PAREABUNDLE os2_PAREABUNDLE
#define _IMAGEBUNDLE os2__IMAGEBUNDLE
#define IMAGEBUNDLE os2_IMAGEBUNDLE
#define PIMAGEBUNDLE os2_PIMAGEBUNDLE
#define _RGB os2__RGB
#define RGB os2_RGB
#define _RGB2 os2__RGB2
#define RGB2 os2_RGB2
#define PRGB2 os2_PRGB2
#define _BITMAPINFOHEADER os2__BITMAPINFOHEADER
#define BITMAPINFOHEADER os2_BITMAPINFOHEADER
#define PBITMAPINFOHEADER os2_PBITMAPINFOHEADER
#define _BITMAPINFO os2__BITMAPINFO
#define BITMAPINFO os2_BITMAPINFO
#define PBITMAPINFO os2_PBITMAPINFO
#define _BITMAPINFO2 os2__BITMAPINFO2
#define BITMAPINFO2 os2_BITMAPINFO2
#define PBITMAPINFO2 os2_PBITMAPINFO2
#define _BITMAPINFOHEADER2 os2__BITMAPINFOHEADER2
#define BITMAPINFOHEADER2 os2_BITMAPINFOHEADER2
#define PBITMAPINFOHEADER2 os2_PBITMAPINFOHEADER2
#define _BITMAPFILEHEADER os2__BITMAPFILEHEADER
#define BITMAPFILEHEADER os2_BITMAPFILEHEADER
#define PBITMAPFILEHEADER os2_PBITMAPFILEHEADER
#define _BITMAPARRAYFILEHEADER os2__BITMAPARRAYFILEHEADER
#define BITMAPARRAYFILEHEADER os2_BITMAPARRAYFILEHEADER
#define PBITMAPARRAYFILEHEADER os2_PBITMAPARRAYFILEHEADER
#define _BITMAPFILEHEADER2 os2__BITMAPFILEHEADER2
#define BITMAPFILEHEADER2 os2_BITMAPFILEHEADER2
#define PBITMAPFILEHEADER2 os2_PBITMAPFILEHEADER2
#define _BITMAPARRAYFILEHEADER2 os2__BITMAPARRAYFILEHEADER2
#define BITMAPARRAYFILEHEADER2 os2_BITMAPARRAYFILEHEADER2
#define PBITMAPARRAYFILEHEADER2 os2_PBITMAPARRAYFILEHEADER2
#define PDEVOPENDATA os2_PDEVOPENDATA
#define _DRIVDATA os2__DRIVDATA
#define DRIVDATA os2_DRIVDATA
#define PDRIVDATA os2_PDRIVDATA
#define _DEVOPENSTRUC os2__DEVOPENSTRUC
#define DEVOPENSTRUC os2_DEVOPENSTRUC
#define PDEVOPENSTRUC os2_PDEVOPENSTRUC
#define _ESCMODE os2__ESCMODE
#define ESCMODE os2_ESCMODE
#define PESCMODE os2_PESCMODE
#define _VIOSIZECOUNT os2__VIOSIZECOUNT
#define VIOSIZECOUNT os2_VIOSIZECOUNT
#define PVIOSIZECOUNT os2_PVIOSIZECOUNT
#define _VIOFONTCELLSIZE os2__VIOFONTCELLSIZE
#define VIOFONTCELLSIZE os2_VIOFONTCELLSIZE
#define PVIOFONTCELLSIZE os2_PVIOFONTCELLSIZE
#define _SFACTORS os2__SFACTORS
#define SFACTORS os2_SFACTORS
#define PSFACTORS os2_PSFACTORS
#define _BANDRECT os2__BANDRECT
#define BANDRECT os2_BANDRECT
#define PBANDRECT os2_PBANDRECT
#define _HCINFO os2__HCINFO
#define HCINFO os2_HCINFO
#define PHCINFO os2_PHCINFO
#define HSWITCH os2_HSWITCH
#define PHSWITCH os2_PHSWITCH
#define HPROGRAM os2_HPROGRAM
#define PHPROGRAM os2_PHPROGRAM
#define HINI os2_HINI
#define PHINI os2_PHINI
#define HAPP os2_HAPP
#define _PRFPROFILE os2__PRFPROFILE
#define PRFPROFILE os2_PRFPROFILE
#define PPRFPROFILE os2_PPRFPROFILE
#define PROGCATEGORY os2_PROGCATEGORY
#define PPROGCATEGORY os2_PPROGCATEGORY
#define _HPROGARRAY os2__HPROGARRAY
#define HPROGARRAY os2_HPROGARRAY
#define PHPROGARRAY os2_PHPROGARRAY
#define _PROGTYPE os2__PROGTYPE
#define PROGTYPE os2_PROGTYPE
#define PPROGTYPE os2_PPROGTYPE
#define _PROGTITLE os2__PROGTITLE
#define PROGTITLE os2_PROGTITLE
#define PPROGTITLE os2_PPROGTITLE
#define _PROGDETAILS os2__PROGDETAILS
#define PROGDETAILS os2_PROGDETAILS
#define PPROGDETAILS os2_PPROGDETAILS
#define _SWCNTRL os2__SWCNTRL
#define SWCNTRL os2_SWCNTRL
#define PSWCNTRL os2_PSWCNTRL
#define _SWENTRY os2__SWENTRY
#define SWENTRY os2_SWENTRY
#define PSWENTRY os2_PSWENTRY
#define _SWBLOCK os2__SWBLOCK
#define SWBLOCK os2_SWBLOCK
#define PSWBLOCK os2_PSWBLOCK
#define APSZ os2_APSZ
#define PAPSZ os2_PAPSZ
#define _FILEDLG os2__FILEDLG
#define FILEDLG os2_FILEDLG
#define PFILEDLG os2_PFILEDLG
#define _FONTDLG os2__FONTDLG
#define FONTDLG os2_FONTDLG
#define PFONTDLG os2_PFONTDLG
#define _STYLECHANGE os2__STYLECHANGE
#define STYLECHANGE os2_STYLECHANGE
#define PSTYLECHANGE os2_PSTYLECHANGE
#define _SPBCDATA os2__SPBCDATA
#define SPBCDATA os2_SPBCDATA
#define PSPBCDATA os2_PSPBCDATA
#define _SLDCDATA os2__SLDCDATA
#define SLDCDATA os2_SLDCDATA
#define PSLDCDATA os2_PSLDCDATA
#define _CSBITMAPDATA os2__CSBITMAPDATA
#define CSBITMAPDATA os2_CSBITMAPDATA
#define PCSBITMAPDATA os2_PCSBITMAPDATA
#define _BOOKTEXT os2__BOOKTEXT
#define BOOKTEXT os2_BOOKTEXT
#define PBOOKTEXT os2_PBOOKTEXT
#define _NOTEBOOKBUTTON os2__NOTEBOOKBUTTON
#define NOTEBOOKBUTTON os2_NOTEBOOKBUTTON
#define PNOTEBOOKBUTTON os2_PNOTEBOOKBUTTON
#define _DELETENOTIFY os2__DELETENOTIFY
#define DELETENOTIFY os2_DELETENOTIFY
#define PDELETENOTIFY os2_PDELETENOTIFY
#define _PAGESELECTNOTIFY os2__PAGESELECTNOTIFY
#define PAGESELECTNOTIFY os2_PAGESELECTNOTIFY
#define PPAGESELECTNOTIFY os2_PPAGESELECTNOTIFY
#define _BOOKPAGEINFO os2__BOOKPAGEINFO
#define BOOKPAGEINFO os2_BOOKPAGEINFO
#define PBOOKPAGEINFO os2_PBOOKPAGEINFO
#define WM_DRAGFIRST os2_WM_DRAGFIRST
#define WM_DRAGLAST os2_WM_DRAGLAST
#define HSTR os2_HSTR
#define _DRAGIMAGE os2__DRAGIMAGE
#define DRAGIMAGE os2_DRAGIMAGE
#define PDRAGIMAGE os2_PDRAGIMAGE
#define _DRAGINFO os2__DRAGINFO
#define DRAGINFO os2_DRAGINFO
#define PDRAGINFO os2_PDRAGINFO
#define _DRAGITEM os2__DRAGITEM
#define DRAGITEM os2_DRAGITEM
#define PDRAGITEM os2_PDRAGITEM
#define _DRAGTRANSFER os2__DRAGTRANSFER
#define DRAGTRANSFER os2_DRAGTRANSFER
#define PDRAGTRANSFER os2_PDRAGTRANSFER
#define _RENDERFILE os2__RENDERFILE
#define RENDERFILE os2_RENDERFILE
#define PRENDERFILE os2_PRENDERFILE
#define _VSCDATA os2__VSCDATA
#define VSCDATA os2_VSCDATA
#define PVSCDATA os2_PVSCDATA
#define _VSDRAGINIT os2__VSDRAGINIT
#define VSDRAGINIT os2_VSDRAGINIT
#define PVSDRAGINIT os2_PVSDRAGINIT
#define _VSDRAGINFO os2__VSDRAGINFO
#define VSDRAGINFO os2_VSDRAGINFO
#define PVSDRAGINFO os2_PVSDRAGINFO
#define _VSTEXT os2__VSTEXT
#define VSTEXT os2_VSTEXT
#define PVSTEXT os2_PVSTEXT
#define _TREEITEMDESC os2__TREEITEMDESC
#define TREEITEMDESC os2_TREEITEMDESC
#define PTREEITEMDESC os2_PTREEITEMDESC
#define _FIELDINFO os2__FIELDINFO
#define FIELDINFO os2_FIELDINFO
#define PFIELDINFO os2_PFIELDINFO
#define _RECORDCORE os2__RECORDCORE
#define RECORDCORE os2_RECORDCORE
#define PRECORDCORE os2_PRECORDCORE
#define _MINIRECORDCORE os2__MINIRECORDCORE
#define MINIRECORDCORE os2_MINIRECORDCORE
#define PMINIRECORDCORE os2_PMINIRECORDCORE
#define _TREEMOVE os2__TREEMOVE
#define TREEMOVE os2_TREEMOVE
#define PTREEMOVE os2_PTREEMOVE
#define _CNRINFO os2__CNRINFO
#define CNRINFO os2_CNRINFO
#define PCNRINFO os2_PCNRINFO
#define _GRIDSQUARE os2__GRIDSQUARE
#define GRIDSQUARE os2_GRIDSQUARE
#define PGRIDSQUARE os2_PGRIDSQUARE
#define _GRIDINFO os2__GRIDINFO
#define GRIDINFO os2_GRIDINFO
#define PGRIDINFO os2_PGRIDINFO
#define _CDATE os2__CDATE
#define CDATE os2_CDATE
#define PCDATE os2_PCDATE
#define _CTIME os2__CTIME
#define CTIME os2_CTIME
#define PCTIME os2_PCTIME
#define _CNRDRAGINIT os2__CNRDRAGINIT
#define CNRDRAGINIT os2_CNRDRAGINIT
#define PCNRDRAGINIT os2_PCNRDRAGINIT
#define _FIELDINFOINSERT os2__FIELDINFOINSERT
#define FIELDINFOINSERT os2_FIELDINFOINSERT
#define PFIELDINFOINSERT os2_PFIELDINFOINSERT
#define _RECORDINSERT os2__RECORDINSERT
#define RECORDINSERT os2_RECORDINSERT
#define PRECORDINSERT os2_PRECORDINSERT
#define _QUERYRECFROMRECT os2__QUERYRECFROMRECT
#define QUERYRECFROMRECT os2_QUERYRECFROMRECT
#define PQUERYRECFROMRECT os2_PQUERYRECFROMRECT
#define _QUERYRECORDRECT os2__QUERYRECORDRECT
#define QUERYRECORDRECT os2_QUERYRECORDRECT
#define PQUERYRECORDRECT os2_PQUERYRECORDRECT
#define _SEARCHSTRING os2__SEARCHSTRING
#define SEARCHSTRING os2_SEARCHSTRING
#define PSEARCHSTRING os2_PSEARCHSTRING
#define _CNRDRAGINFO os2__CNRDRAGINFO
#define CNRDRAGINFO os2_CNRDRAGINFO
#define PCNRDRAGINFO os2_PCNRDRAGINFO
#define _CNRLAZYDRAGINFO os2__CNRLAZYDRAGINFO
#define CNRLAZYDRAGINFO os2_CNRLAZYDRAGINFO
#define PCNRLAZYDRAGINFO os2_PCNRLAZYDRAGINFO
#define _NOTIFYRECORDEMPHASIS os2__NOTIFYRECORDEMPHASIS
#define NOTIFYRECORDEMPHASIS os2_NOTIFYRECORDEMPHASIS
#define PNOTIFYRECORDEMPHASIS os2_PNOTIFYRECORDEMPHASIS
#define _NOTIFYRECORDENTER os2__NOTIFYRECORDENTER
#define NOTIFYRECORDENTER os2_NOTIFYRECORDENTER
#define PNOTIFYRECORDENTER os2_PNOTIFYRECORDENTER
#define _NOTIFYDELTA os2__NOTIFYDELTA
#define NOTIFYDELTA os2_NOTIFYDELTA
#define PNOTIFYDELTA os2_PNOTIFYDELTA
#define _NOTIFYSCROLL os2__NOTIFYSCROLL
#define NOTIFYSCROLL os2_NOTIFYSCROLL
#define PNOTIFYSCROLL os2_PNOTIFYSCROLL
#define _CNREDITDATA os2__CNREDITDATA
#define CNREDITDATA os2_CNREDITDATA
#define PCNREDITDATA os2_PCNREDITDATA
#define _OWNERBACKGROUND os2__OWNERBACKGROUND
#define OWNERBACKGROUND os2_OWNERBACKGROUND
#define POWNERBACKGROUND os2_POWNERBACKGROUND
#define _CNRDRAWITEMINFO os2__CNRDRAWITEMINFO
#define CNRDRAWITEMINFO os2_CNRDRAWITEMINFO
#define PCNRDRAWITEMINFO os2_PCNRDRAWITEMINFO
#define _OBJCLASS os2__OBJCLASS
#define OBJCLASS os2_OBJCLASS
#define POBJCLASS os2_POBJCLASS
#define HSPL os2_HSPL
#define HSTD os2_HSTD
#define PHSTD os2_PHSTD
#define PQMOPENDATA os2_PQMOPENDATA
#define SPLERR os2_SPLERR
#define _SQPOPENDATA os2__SQPOPENDATA
#define SQPOPENDATA os2_SQPOPENDATA
#define PSQPOPENDATA os2_PSQPOPENDATA
#define _DRIVPROPS os2__DRIVPROPS
#define DRIVPROPS os2_DRIVPROPS
#define PDRIVPROPS os2_PDRIVPROPS
#define _PRINTERINFO os2__PRINTERINFO
#define PRINTERINFO os2_PRINTERINFO
#define PPRINTERINFO os2_PPRINTERINFO
#define _PRJINFO os2__PRJINFO
#define PRJINFO os2_PRJINFO
#define PPRJINFO os2_PPRJINFO
#define _PRJINFO2 os2__PRJINFO2
#define PRJINFO2 os2_PRJINFO2
#define PPRJINFO2 os2_PPRJINFO2
#define _PRJINFO3 os2__PRJINFO3
#define PRJINFO3 os2_PRJINFO3
#define PPRJINFO3 os2_PPRJINFO3
#define _PRJINFO4 os2__PRJINFO4
#define PRJINFO4 os2_PRJINFO4
#define PPRJINFO4 os2_PPRJINFO4
#define _PRDINFO os2__PRDINFO
#define PRDINFO os2_PRDINFO
#define PPRDINFO os2_PPRDINFO
#define _PRDINFO3 os2__PRDINFO3
#define PRDINFO3 os2_PRDINFO3
#define PPRDINFO3 os2_PPRDINFO3
#define _PRQINFO os2__PRQINFO
#define PRQINFO os2_PRQINFO
#define PPRQINFO os2_PPRQINFO
#define _PRQINFO3 os2__PRQINFO3
#define PRQINFO3 os2_PRQINFO3
#define PPRQINFO3 os2_PPRQINFO3
#define _PRQINFO6 os2__PRQINFO6
#define PRQINFO6 os2_PRQINFO6
#define PPRQINFO6 os2_PPRQINFO6
#define _PRIDINFO os2__PRIDINFO
#define PRIDINFO os2_PRIDINFO
#define PPRIDINFO os2_PPRIDINFO
#define _PRDRIVINFO os2__PRDRIVINFO
#define PRDRIVINFO os2_PRDRIVINFO
#define PPRDRIVINFO os2_PPRDRIVINFO
#define _PRDRIVINFO2 os2__PRDRIVINFO2
#define PRDRIVINFO2 os2_PRDRIVINFO2
#define PPRDRIVINFO2 os2_PPRDRIVINFO2
#define _PRQPROCINFO os2__PRQPROCINFO
#define PRQPROCINFO os2_PRQPROCINFO
#define PPRQPROCINFO os2_PPRQPROCINFO
#define _PRPORTINFO os2__PRPORTINFO
#define PRPORTINFO os2_PRPORTINFO
#define PPRPORTINFO os2_PPRPORTINFO
#define _PRPORTINFO1 os2__PRPORTINFO1
#define PRPORTINFO1 os2_PRPORTINFO1
#define PPRPORTINFO1 os2_PPRPORTINFO1
#define _PRPORTINFO2 os2__PRPORTINFO2
#define PRPORTINFO2 os2_PRPORTINFO2
#define PPRPORTINFO2 os2_PPRPORTINFO2
#define _QMJOBINFO os2__QMJOBINFO
#define QMJOBINFO os2_QMJOBINFO
#define PQMJOBINFO os2_PQMJOBINFO
#define HWND_PARENT os2_HWND_PARENT
#define HELPSUBTABLE os2_HELPSUBTABLE
#define PHELPSUBTABLE os2_PHELPSUBTABLE
#define _ACVP os2__ACVP
#define ACVP os2_ACVP
#define PACVP os2_PACVP
#define _HELPTABLE os2__HELPTABLE
#define HELPTABLE os2_HELPTABLE
#define PHELPTABLE os2_PHELPTABLE
#define _HELPINIT os2__HELPINIT
#define HELPINIT os2_HELPINIT
#define PHELPINIT os2_PHELPINIT
#define HDDF os2_HDDF
#define _FOCAMETRICS os2__FOCAMETRICS
#define FOCAMETRICS os2_FOCAMETRICS
#define PFOCAMETRICS os2_PFOCAMETRICS
#define _FONTFILEMETRICS os2__FONTFILEMETRICS
#define FONTFILEMETRICS os2_FONTFILEMETRICS
#define PFONTFILEMETRICS os2_PFONTFILEMETRICS
#define _FONTDEFINITIONHEADER os2__FONTDEFINITIONHEADER
#define FONTDEFINITIONHEADER os2_FONTDEFINITIONHEADER
#define PFONTDEFINITIONHEADER os2_PFONTDEFINITIONHEADER
#define _FONTSIGNATURE os2__FONTSIGNATURE
#define FONTSIGNATURE os2_FONTSIGNATURE
#define PFONTSIGNATURE os2_PFONTSIGNATURE
#define _ADDITIONALMETRICS os2__ADDITIONALMETRICS
#define ADDITIONALMETRICS os2_ADDITIONALMETRICS
#define PADDITIONALMETRICS os2_PADDITIONALMETRICS
#define _FOCAFONT os2__FOCAFONT
#define FOCAFONT os2_FOCAFONT
#define PFOCAFONT os2_PFOCAFONT
#define FOCAFONT32 os2_FOCAFONT32
#define PFOCAFONT32 os2_PFOCAFONT32
#define HVPS os2_HVPS
#define PHVPS os2_PHVPS
#define HMONITOR os2_HMONITOR
#define PHMONITOR os2_PHMONITOR
#define _MONIN os2__MONIN
#define MONIN os2_MONIN
#define PMONIN os2_PMONIN
#define _MONOUT os2__MONOUT
#define MONOUT os2_MONOUT
#define PMONOUT os2_PMONOUT
#define HKBD os2_HKBD
#define PHKBD os2_PHKBD
#define _KBDKEYINFO os2__KBDKEYINFO
#define KBDKEYINFO os2_KBDKEYINFO
#define PKBDKEYINFO os2_PKBDKEYINFO
#define _KBDINFO os2__KBDINFO
#define KBDINFO os2_KBDINFO
#define PKBDINFO os2_PKBDINFO
#define _KBDHWID os2__KBDHWID
#define KBDHWID os2_KBDHWID
#define PKBDHWID os2_PKBDHWID
#define _KBDTRANS os2__KBDTRANS
#define KBDTRANS os2_KBDTRANS
#define PKBDTRANS os2_PKBDTRANS
#define _STRINGINBUF os2__STRINGINBUF
#define STRINGINBUF os2_STRINGINBUF
#define PSTRINGINBUF os2_PSTRINGINBUF
#define HVIO os2_HVIO
#define PHVIO os2_PHVIO
#define _VIOMODEINFO os2__VIOMODEINFO
#define VIOMODEINFO os2_VIOMODEINFO
#define PVIOMODEINFO os2_PVIOMODEINFO
#define _VIOCONFIGINFO os2__VIOCONFIGINFO
#define VIOCONFIGINFO os2_VIOCONFIGINFO
#define PVIOCONFIGINFO os2_PVIOCONFIGINFO
#define _VIOPHYSBUF os2__VIOPHYSBUF
#define VIOPHYSBUF os2_VIOPHYSBUF
#define PVIOPHYSBUF os2_PVIOPHYSBUF
#define _VIOPALSTATE os2__VIOPALSTATE
#define VIOPALSTATE os2_VIOPALSTATE
#define PVIOPALSTATE os2_PVIOPALSTATE
#define _VIOOVERSCAN os2__VIOOVERSCAN
#define VIOOVERSCAN os2_VIOOVERSCAN
#define PVIOOVERSCAN os2_PVIOOVERSCAN
#define _VIOINTENSITY os2__VIOINTENSITY
#define VIOINTENSITY os2_VIOINTENSITY
#define PVIOINTENSITY os2_PVIOINTENSITY
#define _VIOCOLORREG os2__VIOCOLORREG
#define VIOCOLORREG os2_VIOCOLORREG
#define PVIOCOLORREG os2_PVIOCOLORREG
#define _VIOSETULINELOC os2__VIOSETULINELOC
#define VIOSETULINELOC os2_VIOSETULINELOC
#define PVIOSETULINELOC os2_PVIOSETULINELOC
#define _VIOSETTARGET os2__VIOSETTARGET
#define VIOSETTARGET os2_VIOSETTARGET
#define PVIOSETTARGET os2_PVIOSETTARGET
#define _VIOCURSORINFO os2__VIOCURSORINFO
#define VIOCURSORINFO os2_VIOCURSORINFO
#define PVIOCURSORINFO os2_PVIOCURSORINFO
#define _VIOFONTINFO os2__VIOFONTINFO
#define VIOFONTINFO os2_VIOFONTINFO
#define PVIOFONTINFO os2_PVIOFONTINFO
#define HMOU os2_HMOU
#define PHMOU os2_PHMOU
#define _MOUEVENTINFO os2__MOUEVENTINFO
#define MOUEVENTINFO os2_MOUEVENTINFO
#define PMOUEVENTINFO os2_PMOUEVENTINFO
#define _MOUQUEINFO os2__MOUQUEINFO
#define MOUQUEINFO os2_MOUQUEINFO
#define PMOUQUEINFO os2_PMOUQUEINFO
#define _PTRLOC os2__PTRLOC
#define PTRLOC os2_PTRLOC
#define PPTRLOC os2_PPTRLOC
#define _NOPTRRECT os2__NOPTRRECT
#define NOPTRRECT os2_NOPTRRECT
#define PNOPTRRECT os2_PNOPTRRECT
#define _PTRSHAPE os2__PTRSHAPE
#define PTRSHAPE os2_PTRSHAPE
#define PPTRSHAPE os2_PPTRSHAPE
#define _SCALEFACT os2__SCALEFACT
#define SCALEFACT os2_SCALEFACT
#define PSCALEFACT os2_PSCALEFACT
#define _THRESHOLD os2__THRESHOLD
#define THRESHOLD os2_THRESHOLD
#define PTHRESHOLD os2_PTHRESHOLD
#define _GINFOSEG os2__GINFOSEG
#define GINFOSEG os2_GINFOSEG
#define PGINFOSEG os2_PGINFOSEG
#define _LINFOSEG os2__LINFOSEG
#define LINFOSEG os2_LINFOSEG
#define PLINFOSEG os2_PLINFOSEG

/* Some manually added redefinitionis not caught by sed */
#define VOID os2_VOID
#define FIELDOFFSET os2_FIELDOFFSET
#define MAKETYPE os2_MAKETYPE
#define MAKEUSHORT os2_MAKEUSHORT
#define MAKESHORT os2_MAKESHORT
#define MAKEULONG os2_MAKEULONG
#define MAKELONG os2_MAKELONG
#define LOUCHAR os2_LOUCHAR
#define HIUCHAR os2_HIUCHAR
#define LOBYTE os2_LOBYTE
#define HIBYTE os2_HIBYTE
#define LOUSHORT os2_LOUSHORT
#define HIUSHORT os2_HIUSHORT
#define WINERR_BASE os2_WINERR_BASE
#define GPIERR_BASE os2_GPIERR_BASE
#define DEVERR_BASE os2_DEVERR_BASE
#define SPLERR_BASE os2_SPLERR_BASE
#define SEVERITY_NOERROR os2_SEVERITY_NOERROR
#define SEVERITY_WARNING os2_SEVERITY_WARNING
#define SEVERITY_ERROR os2_SEVERITY_ERROR
#define SEVERITY_SEVERE os2_SEVERITY_SEVERE
#define SEVERITY_UNRECOVERABLE os2_SEVERITY_UNRECOVERABLE
#define MAKE16P os2_MAKE16P
#define MAKEP os2_MAKEP
#define SELECTOROF os2_SELECTOROF
#define OFFSETOF os2_OFFSETOF
#define APIENTRY os2_APIENTRY
#define EXPENTRY os2_EXPENTRY

/* include the main OS/2 API wrapper */
#include <os2wrap.h>

/*
   Undefine all typedefs prefixed with "os2_" at the beginning. The command to
   generate this block is:

sed -nr \
  -e 's/^[[:space:]]*typedef[[:space:]]+struct[[:space:]]+_([A-Z_][A-Z1-9_]+)([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#undef _\1\
#undef \1/p' \
  -e 's/^[[:space:]]*typedef[[:space:]]+.+[[:space:]]+\**([A-Z_][A-Z1-9_]+)[[:space:]]*(\[.*\])?[[:space:]]*;([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#undef \1/p' \
  -e 's/^[[:space:]]*#define[[:space:]]+((CONTEXT|CS|EH|EXCEPTION|HWND|WC|MB|WM|WS|RGN|RT|DT|SWP|TA)_([A-Z1-9_]+))[[:space:]]+.*$/#undef \1/p' \

 */

#undef INT
#undef UINT
#undef APIRET
#undef BOOL
#undef PBOOL
#undef BOOL32
#undef PBOOL32
#undef CHAR
#undef PCHAR
#undef BYTE
#undef PCH
#undef PSZ
#undef PCCH
#undef PCSZ
#undef BYTE
#undef PCH
#undef PSZ
#undef PCCH
#undef PCSZ
#undef PBYTE
#undef UCHAR
#undef PUCHAR
#undef SHORT
#undef PSHORT
#undef USHORT
#undef PUSHORT
#undef LONG
#undef PLONG
#undef ULONG
#undef PULONG
#undef LONGLONG
#undef PLONGLONG
#undef ULONGLONG
#undef PULONGLONG
#undef _LONGLONG
#undef LONGLONG
#undef PLONGLONG
#undef _ULONGLONG
#undef ULONGLONG
#undef PULONGLONG
#undef PVOID
#undef PPVOID
#undef CPVOID
#undef STR8
#undef PSTR8
#undef STR16
#undef PSTR16
#undef STR32
#undef PSTR32
#undef STR64
#undef PSTR64
#undef SHANDLE
#undef LHANDLE
#undef HPIPE
#undef PHPIPE
#undef HQUEUE
#undef PHQUEUE
#undef HMODULE
#undef PHMODULE
#undef HSEM
#undef PHSEM
#undef HOBJECT
#undef PID
#undef PPID
#undef TID
#undef PTID
#undef PFN
#undef PPFN
#undef SEL
#undef PSEL
#undef HMTX
#undef PHMTX
#undef HMUX
#undef PHMUX
#undef _PANOSE
#undef PANOSE
#undef _FONTMETRICS
#undef FONTMETRICS
#undef PFONTMETRICS
#undef _FATTRS
#undef FATTRS
#undef PFATTRS
#undef HFILE
#undef PHFILE
#undef FHLOCK
#undef PFHLOCK
#undef HDIR
#undef PHDIR
#undef _FTIME
#undef FTIME
#undef _FTIME
#undef FTIME
#undef PFTIME
#undef _FDATE
#undef FDATE
#undef _FDATE
#undef FDATE
#undef PFDATE
#undef _FEA
#undef FEA
#undef PFEA
#undef _FEALIST
#undef FEALIST
#undef PFEALIST
#undef _GEA
#undef GEA
#undef PGEA
#undef _GEALIST
#undef GEALIST
#undef PGEALIST
#undef _EAOP
#undef EAOP
#undef PEAOP
#undef _FEA2
#undef FEA2
#undef PFEA2
#undef _FEA2LIST
#undef FEA2LIST
#undef PFEA2LIST
#undef _GEA2
#undef GEA2
#undef PGEA2
#undef _GEA2LIST
#undef GEA2LIST
#undef PGEA2LIST
#undef _EAOP2
#undef EAOP2
#undef PEAOP2
#undef _DENA1
#undef DENA1
#undef PDENA1
#undef DENA2
#undef PDENA2
#undef _EASIZEBUF
#undef EASIZEBUF
#undef PEASIZEBUF
#undef _ROUTENAMEBUF
#undef ROUTENAMEBUF
#undef PROUTENAMEBUF
#undef _FSDTHREAD
#undef FSDTHREAD
#undef _FSDDAEMON
#undef FSDDAEMON
#undef _FILEFINDBUF
#undef FILEFINDBUF
#undef PFILEFINDBUF
#undef _FILEFINDBUF2
#undef FILEFINDBUF2
#undef PFILEFINDBUF2
#undef _FILEFINDBUF3
#undef FILEFINDBUF3
#undef PFILEFINDBUF3
#undef _FILEFINDBUF4
#undef FILEFINDBUF4
#undef PFILEFINDBUF4
#undef _FILEFINDBUF3L
#undef FILEFINDBUF3L
#undef PFILEFINDBUF3L
#undef _FILEFINDBUF4L
#undef FILEFINDBUF4L
#undef PFILEFINDBUF4L
#undef _FILELOCK
#undef FILELOCK
#undef PFILELOCK
#undef _FILELOCKL
#undef FILELOCKL
#undef PFILELOCKL
#undef _FILESTATUS
#undef FILESTATUS
#undef PFILESTATUS
#undef _FILESTATUS2
#undef FILESTATUS2
#undef PFILESTATUS2
#undef _FILESTATUS3
#undef FILESTATUS3
#undef PFILESTATUS3
#undef _FILESTATUS4
#undef FILESTATUS4
#undef PFILESTATUS4
#undef _FILESTATUS3L
#undef FILESTATUS3L
#undef PFILESTATUS3L
#undef _FILESTATUS4L
#undef FILESTATUS4L
#undef PFILESTATUS4L
#undef _FSALLOCATE
#undef FSALLOCATE
#undef PFSALLOCATE
#undef _FSQBUFFER
#undef FSQBUFFER
#undef PFSQBUFFER
#undef _FSQBUFFER2
#undef FSQBUFFER2
#undef PFSQBUFFER2
#undef _SPOOLATTACH
#undef SPOOLATTACH
#undef PSPOOLATTACH
#undef _VOLUMELABEL
#undef VOLUMELABEL
#undef PVOLUMELABEL
#undef _FSINFO
#undef FSINFO
#undef PFSINFO
#undef _LISTIO_CB
#undef LISTIO_CB
#undef PLISTIO
#undef _LISTIO_CBL
#undef LISTIO_CBL
#undef PLISTIOL
#undef _DCBINFO
#undef DCBINFO
#undef PDCBINFO
#undef _LINECONTROL
#undef LINECONTROL
#undef PLINECONTROL
#undef _MODEMSTATUS
#undef MODEMSTATUS
#undef PMODEMSTATUS
#undef _KBDTYPE
#undef KBDTYPE
#undef PKBDTYPE
#undef _RATEDELAY
#undef RATEDELAY
#undef PRATEDELAY
#undef _CODEPAGEINFO
#undef CODEPAGEINFO
#undef PCODEPAGEINFO
#undef _CPID
#undef CPID
#undef PCPID
#undef _SHIFTSTATE
#undef SHIFTSTATE
#undef PSHIFTSTATE
#undef _HOTKEY
#undef HOTKEY
#undef PHOTKEY
#undef _PTRDRAWFUNCTION
#undef PTRDRAWFUNCTION
#undef PPTRDRAWFUNCTION
#undef _PTRDRAWADDRESS
#undef PTRDRAWADDRESS
#undef PPTRDRAWADDRESS
#undef _PTRDRAWDATA
#undef PTRDRAWDATA
#undef PPTRDRAWDATA
#undef _TRACKLAYOUT
#undef TRACKLAYOUT
#undef PTRACKLAYOUT
#undef _TRACKFORMAT
#undef TRACKFORMAT
#undef PTRACKFORMAT
#undef _BIOSPARAMETERBLOCK
#undef BIOSPARAMETERBLOCK
#undef PBIOSPARAMETERBLOCK
#undef _DEVICEPARAMETERBLOCK
#undef DEVICEPARAMETERBLOCK
#undef PDEVICEPARAMETERBLOCK
#undef _MONITORPOSITION
#undef MONITORPOSITION
#undef PMONITORPOSITION
#undef _FRAME
#undef FRAME
#undef PFRAME
#undef _LDTADDRINFO
#undef LDTADDRINFO
#undef PLDTADDRINFO
#undef _SCREENGROUP
#undef SCREENGROUP
#undef PSCREENGROUP
#undef _RXQUEUE
#undef RXQUEUE
#undef PRXQUEUE
#undef _GETLINIOCTLDATA
#undef GETLINIOCTLDATA
#undef PGETLINIOCTLDATA
#undef _BANKINFO
#undef BANKINFO
#undef _GLOBALIOCTLDATA
#undef GLOBALIOCTLDATA
#undef _OEMSVGAINFO
#undef OEMSVGAINFO
#undef _OEMINFO
#undef OEMINFO
#undef _GETGLOBALPACKET
#undef GETGLOBALPACKET
#undef _COUNTRYCODE
#undef COUNTRYCODE
#undef PCOUNTRYCODE
#undef _COUNTRYINFO
#undef COUNTRYINFO
#undef PCOUNTRYINFO
#undef RT_POINTER
#undef RT_BITMAP
#undef RT_MENU
#undef RT_DIALOG
#undef RT_STRING
#undef RT_FONTDIR
#undef RT_FONT
#undef RT_ACCELTABLE
#undef RT_RCDATA
#undef RT_MESSAGE
#undef RT_DLGINCLUDE
#undef RT_VKEYTBL
#undef RT_KEYTBL
#undef RT_CHARTBL
#undef RT_DISPLAYINFO
#undef RT_FKASHORT
#undef RT_FKALONG
#undef RT_HELPTABLE
#undef RT_HELPSUBTABLE
#undef RT_FDDIR
#undef RT_FD
#undef RT_MAX
#undef RT_RESNAMES
#undef _RESULTCODES
#undef RESULTCODES
#undef PRESULTCODES
#undef PTIB2
#undef PTIB
#undef PPIB
#undef PFNTHREAD
#undef PFNEXITLIST
#undef _MPAFFINITY
#undef MPAFFINITY
#undef PMPAFFINITY
#undef _THREADCREATE
#undef THREADCREATE
#undef PTHREADCREATE
#undef _STARTDATA
#undef STARTDATA
#undef PSTARTDATA
#undef _STATUSDATA
#undef STATUSDATA
#undef PSTATUSDATA
#undef HEV
#undef PHEV
#undef _PSEMRECORD
#undef PSEMRECORD
#undef PSEMRECORD
#undef _AVAILDATA
#undef AVAILDATA
#undef PAVAILDATA
#undef _PIPEINFO
#undef PIPEINFO
#undef PPIPEINFO
#undef _PIPESEMSTATE
#undef PIPESEMSTATE
#undef PPIPESEMSTATE
#undef _REQUESTDATA
#undef REQUESTDATA
#undef PREQUESTDATA
#undef CONTEXT_CONTROL
#undef CONTEXT_INTEGER
#undef CONTEXT_SEGMENTS
#undef CONTEXT_FLOATING_POINT
#undef CONTEXT_FULL
#undef EH_NONCONTINUABLE
#undef EH_UNWINDING
#undef EH_EXIT_UNWIND
#undef EH_STACK_INVALID
#undef EH_NESTED_CALL
#undef PFPREG
#undef _CONTEXT
#undef CONTEXT
#undef PCONTEXTRECORD
#undef EXCEPTION_MAXIMUM_PARAMETERS
#undef _EXCEPTIONREPORTRECORD
#undef EXCEPTIONREPORTRECORD
#undef PEXCEPTIONREPORTRECORD
#undef ERR
#undef _EXCEPTIONREGISTRATIONRECORD
#undef EXCEPTIONREGISTRATIONRECORD
#undef PEXCEPTIONREGISTRATIONRECORD
#undef _DATETIME
#undef DATETIME
#undef PDATETIME
#undef HTIMER
#undef PHTIMER
#undef _QWORD
#undef QWORD
#undef PQWORD
#undef _QSGREC
#undef QSGREC
#undef _QSTREC
#undef QSTREC
#undef _QSPREC
#undef QSPREC
#undef _QSS16REC
#undef QSS16REC
#undef _QSS16HEADREC
#undef QSS16HEADREC
#undef _QSMREC
#undef QSMREC
#undef _QSOPENQ
#undef QSOPENQ
#undef _QSEVENT
#undef QSEVENT
#undef _QSMUTEX
#undef QSMUTEX
#undef _QSMUX
#undef QSMUX
#undef _QSS32REC
#undef QSS32REC
#undef _QSLOBJREC
#undef QSLOBJREC
#undef _QSLREC
#undef QSLREC
#undef _QSEXLREC
#undef QSEXLREC
#undef _QSSFT
#undef QSSFT
#undef _QSFREC
#undef QSFREC
#undef _QSPTRREC
#undef QSPTRREC
#undef SGID
#undef HVDD
#undef PHVDD
#undef HSPINLOCK
#undef PHSPINLOCK
#undef _RXSTRING
#undef RXSTRING
#undef PRXSTRING
#undef _RXSYSEXIT
#undef RXSYSEXIT
#undef PRXSYSEXIT
#undef _SHVBLOCK
#undef SHVBLOCK
#undef PSHVBLOCK
#undef PEXIT
#undef _RXFNC_FLAGS
#undef RXFNC_FLAGS
#undef _RXFNCCAL_PARM
#undef RXFNCCAL_PARM
#undef _RXCMD_FLAGS
#undef RXCMD_FLAGS
#undef _RXCMDHST_PARM
#undef RXCMDHST_PARM
#undef _RXMSQPLL_PARM
#undef RXMSQPLL_PARM
#undef _RXMSQ_FLAGS
#undef RXMSQ_FLAGS
#undef _RXMSQPSH_PARM
#undef RXMSQPSH_PARM
#undef _RXMSQSIZ_PARM
#undef RXMSQSIZ_PARM
#undef _RXMSQNAM_PARM
#undef RXMSQNAM_PARM
#undef _RXSIOSAY_PARM
#undef RXSIOSAY_PARM
#undef _RXSIOTRC_PARM
#undef RXSIOTRC_PARM
#undef _RXSIOTRD_PARM
#undef RXSIOTRD_PARM
#undef _RXSIODR_PARM
#undef RXSIODR_PARM
#undef _RXHLT_FLAGS
#undef RXHLT_FLAGS
#undef _RXHLTTST_PARM
#undef RXHLTTST_PARM
#undef _RXTRC_FLAGS
#undef RXTRC_FLAGS
#undef _RXTRCTST_PARM
#undef RXTRCTST_PARM
#undef WM_DBCSFIRST
#undef WM_DBCSLAST
#undef WC_FRAME
#undef WC_COMBOBOX
#undef WC_BUTTON
#undef WC_MENU
#undef WC_STATIC
#undef WC_ENTRYFIELD
#undef WC_LISTBOX
#undef WC_SCROLLBAR
#undef WC_TITLEBAR
#undef WC_MLE
#undef WC_APPSTAT
#undef WC_KBDSTAT
#undef WC_PECIC
#undef WC_DBE_KKPOPUP
#undef WC_SPINBUTTON
#undef WC_CONTAINER
#undef WC_SLIDER
#undef WC_VALUESET
#undef WC_NOTEBOOK
#undef WC_PENFIRST
#undef WC_PENLAST
#undef WC_MMPMFIRST
#undef WC_CIRCULARSLIDER
#undef WC_MMPMLAST
#undef WS_VISIBLE
#undef WS_DISABLED
#undef WS_CLIPCHILDREN
#undef WS_CLIPSIBLINGS
#undef WS_PARENTCLIP
#undef WS_SAVEBITS
#undef WS_SYNCPAINT
#undef WS_MINIMIZED
#undef WS_MAXIMIZED
#undef WS_ANIMATE
#undef WS_GROUP
#undef WS_TABSTOP
#undef WS_MULTISELECT
#undef CS_MOVENOTIFY
#undef CS_SIZEREDRAW
#undef CS_HITTEST
#undef CS_PUBLIC
#undef CS_FRAME
#undef CS_CLIPCHILDREN
#undef CS_CLIPSIBLINGS
#undef CS_PARENTCLIP
#undef CS_SAVEBITS
#undef CS_SYNCPAINT
#undef DT_LEFT
#undef DT_QUERYEXTENT
#undef DT_UNDERSCORE
#undef DT_STRIKEOUT
#undef DT_TEXTATTRS
#undef DT_EXTERNALLEADING
#undef DT_CENTER
#undef DT_RIGHT
#undef DT_TOP
#undef DT_VCENTER
#undef DT_BOTTOM
#undef DT_HALFTONE
#undef DT_MNEMONIC
#undef DT_WORDBREAK
#undef DT_ERASERECT
#undef SWP_SIZE
#undef SWP_MOVE
#undef SWP_ZORDER
#undef SWP_SHOW
#undef SWP_HIDE
#undef SWP_NOREDRAW
#undef SWP_NOADJUST
#undef SWP_ACTIVATE
#undef SWP_DEACTIVATE
#undef SWP_EXTSTATECHANGE
#undef SWP_MINIMIZE
#undef SWP_MAXIMIZE
#undef SWP_RESTORE
#undef SWP_FOCUSACTIVATE
#undef SWP_FOCUSDEACTIVATE
#undef SWP_NOAUTOCLOSE
#undef HWND_DESKTOP
#undef HWND_OBJECT
#undef HWND_TOP
#undef HWND_BOTTOM
#undef HWND_THREADCAPTURE
#undef HACCEL
#undef HRGN
#undef PHRGN
#undef MRESULT
#undef PMRESULT
#undef MPARAM
#undef PMPARAM
#undef HPOINTER
#undef HLIB
#undef PHLIB
#undef COLOR
#undef PCOLOR
#undef HAB
#undef PHAB
#undef HPS
#undef PHPS
#undef HDC
#undef PHDC
#undef HWND
#undef PHWND
#undef HMQ
#undef HPAL
#undef PHPAL
#undef HBITMAP
#undef PHBITMAP
#undef ERRORID
#undef PERRORID
#undef PFNWP
#undef _POINTL
#undef POINTL
#undef PPOINTL
#undef _POINTS
#undef POINTS
#undef PPOINTS
#undef _RECTL
#undef RECTL
#undef PRECTL
#undef WM_NULL
#undef WM_CREATE
#undef WM_DESTROY
#undef WM_ENABLE
#undef WM_SHOW
#undef WM_MOVE
#undef WM_SIZE
#undef WM_ADJUSTWINDOWPOS
#undef WM_CALCVALIDRECTS
#undef WM_SETWINDOWPARAMS
#undef WM_QUERYWINDOWPARAMS
#undef WM_HITTEST
#undef WM_ACTIVATE
#undef WM_SETFOCUS
#undef WM_SETSELECTION
#undef WM_PPAINT
#undef WM_PSETFOCUS
#undef WM_PSYSCOLORCHANGE
#undef WM_PSIZE
#undef WM_PACTIVATE
#undef WM_PCONTROL
#undef WM_COMMAND
#undef WM_SYSCOMMAND
#undef WM_HELP
#undef WM_PAINT
#undef WM_TIMER
#undef WM_SEM1
#undef WM_SEM2
#undef WM_SEM3
#undef WM_SEM4
#undef WM_CLOSE
#undef WM_QUIT
#undef WM_SYSCOLORCHANGE
#undef WM_SYSVALUECHANGED
#undef WM_APPTERMINATENOTIFY
#undef WM_PRESPARAMCHANGED
#undef WM_CONTROL
#undef WM_VSCROLL
#undef WM_HSCROLL
#undef WM_INITMENU
#undef WM_MENUSELECT
#undef WM_MENUEND
#undef WM_DRAWITEM
#undef WM_MEASUREITEM
#undef WM_CONTROLPOINTER
#undef WM_QUERYDLGCODE
#undef WM_INITDLG
#undef WM_SUBSTITUTESTRING
#undef WM_MATCHMNEMONIC
#undef WM_SAVEAPPLICATION
#undef WM_HELPBASE
#undef WM_HELPTOP
#undef WM_USER
#undef _QMSG
#undef QMSG
#undef PQMSG
#undef _COMMANDMSG
#undef COMMANDMSG
#undef PCMDMSG
#undef _MQINFO
#undef MQINFO
#undef PMQINFO
#undef _SWP
#undef SWP
#undef PSWP
#undef _ICONINFO
#undef ICONINFO
#undef PICONINFO
#undef _FRAMECDATA
#undef FRAMECDATA
#undef PFRAMECDATA
#undef WM_FLASHWINDOW
#undef WM_FORMATFRAME
#undef WM_UPDATEFRAME
#undef WM_FOCUSCHANGE
#undef WM_SETBORDERSIZE
#undef WM_TRACKFRAME
#undef WM_MINMAXFRAME
#undef WM_SETICON
#undef WM_QUERYICON
#undef WM_SETACCELTABLE
#undef WM_QUERYACCELTABLE
#undef WM_TRANSLATEACCEL
#undef WM_QUERYTRACKINFO
#undef WM_QUERYBORDERSIZE
#undef WM_NEXTMENU
#undef WM_ERASEBACKGROUND
#undef WM_QUERYFRAMEINFO
#undef WM_QUERYFOCUSCHAIN
#undef WM_OWNERPOSCHANGE
#undef WM_CALCFRAMERECT
#undef WM_WINDOWPOSCHANGED
#undef WM_ADJUSTFRAMEPOS
#undef WM_QUERYFRAMECTLCOUNT
#undef WM_QUERYHELPINFO
#undef WM_SETHELPINFO
#undef WM_ERROR
#undef WM_REALIZEPALETTE
#undef HSAVEWP
#undef _QVERSDATA
#undef QVERSDATA
#undef PQVERSDATA
#undef WM_QUERYCONVERTPOS
#undef _CLASSINFO
#undef CLASSINFO
#undef PCLASSINFO
#undef _CREATESTRUCT
#undef CREATESTRUCT
#undef PCREATESTRUCT
#undef HENUM
#undef _ACCEL
#undef ACCEL
#undef PACCEL
#undef _ACCELTABLE
#undef ACCELTABLE
#undef PACCELTABLE
#undef HATOMTBL
#undef ATOM
#undef _BTNCDATA
#undef BTNCDATA
#undef PBTNCDATA
#undef _USERBUTTON
#undef USERBUTTON
#undef PUSERBUTTON
#undef WM_RENDERFMT
#undef WM_RENDERALLFMTS
#undef WM_DESTROYCLIPBOARD
#undef WM_PAINTCLIPBOARD
#undef WM_SIZECLIPBOARD
#undef WM_HSCROLLCLIPBOARD
#undef WM_VSCROLLCLIPBOARD
#undef WM_DRAWCLIPBOARD
#undef _CPTEXT
#undef CPTEXT
#undef PCPTEXT
#undef _MFP
#undef MFP
#undef PMFP
#undef WM_DDE_FIRST
#undef WM_DDE_INITIATE
#undef WM_DDE_REQUEST
#undef WM_DDE_ACK
#undef WM_DDE_DATA
#undef WM_DDE_ADVISE
#undef WM_DDE_UNADVISE
#undef WM_DDE_POKE
#undef WM_DDE_EXECUTE
#undef WM_DDE_TERMINATE
#undef WM_DDE_INITIATEACK
#undef WM_DDE_LAST
#undef _CONVCONTEXT
#undef CONVCONTEXT
#undef PCONVCONTEXT
#undef _DDEINIT
#undef DDEINIT
#undef PDDEINIT
#undef _DDESTRUCT
#undef DDESTRUCT
#undef PDDESTRUCT
#undef _CURSORINFO
#undef CURSORINFO
#undef PCURSORINFO
#undef _DESKTOP
#undef DESKTOP
#undef PDESKTOP
#undef MB_OK
#undef MB_OKCANCEL
#undef MB_RETRYCANCEL
#undef MB_ABORTRETRYIGNORE
#undef MB_YESNO
#undef MB_YESNOCANCEL
#undef MB_CANCEL
#undef MB_ENTER
#undef MB_ENTERCANCEL
#undef MB_NOICON
#undef MB_CUANOTIFICATION
#undef MB_ICONQUESTION
#undef MB_ICONEXCLAMATION
#undef MB_CUAWARNING
#undef MB_ICONASTERISK
#undef MB_ICONHAND
#undef MB_CUACRITICAL
#undef MB_QUERY
#undef MB_WARNING
#undef MB_INFORMATION
#undef MB_CRITICAL
#undef MB_ERROR
#undef MB_CUSTOMICON
#undef MB_DEFBUTTON1
#undef MB_DEFBUTTON2
#undef MB_DEFBUTTON3
#undef MB_APPLMODAL
#undef MB_SYSTEMMODAL
#undef MB_HELP
#undef MB_MOVEABLE
#undef MB_NONMODAL
#undef _MB2D
#undef MB2D
#undef PMB2D
#undef _MB2INFO
#undef MB2INFO
#undef PMB2INFO
#undef _DLGTITEM
#undef DLGTITEM
#undef PDLGTITEM
#undef _DLGTEMPLATE
#undef DLGTEMPLATE
#undef PDLGTEMPLATE
#undef _COMBOCDATA
#undef COMBOCDATA
#undef PCOMBOCDATA
#undef _ENTRYFDATA
#undef ENTRYFDATA
#undef PENTRYFDATA
#undef _ERRINFO
#undef ERRINFO
#undef PERRINFO
#undef _SMHSTRUCT
#undef SMHSTRUCT
#undef PSMHSTRUCT
#undef WM_MOUSEFIRST
#undef WM_MOUSEMOVE
#undef WM_BUTTONCLICKFIRST
#undef WM_BUTTON1DOWN
#undef WM_BUTTON1UP
#undef WM_BUTTON1DBLCLK
#undef WM_BUTTON2DOWN
#undef WM_BUTTON2UP
#undef WM_BUTTON2DBLCLK
#undef WM_BUTTON3DOWN
#undef WM_BUTTON3UP
#undef WM_BUTTON3DBLCLK
#undef WM_BUTTONCLICKLAST
#undef WM_MOUSELAST
#undef WM_CHAR
#undef WM_VIOCHAR
#undef WM_JOURNALNOTIFY
#undef WM_MOUSEMAP
#undef WM_VRNDISABLED
#undef WM_VRNENABLED
#undef WM_EXTMOUSEFIRST
#undef WM_CHORD
#undef WM_BUTTON1MOTIONSTART
#undef WM_BUTTON1MOTIONEND
#undef WM_BUTTON1CLICK
#undef WM_BUTTON2MOTIONSTART
#undef WM_BUTTON2MOTIONEND
#undef WM_BUTTON2CLICK
#undef WM_BUTTON3MOTIONSTART
#undef WM_BUTTON3MOTIONEND
#undef WM_BUTTON3CLICK
#undef WM_EXTMOUSELAST
#undef WM_MOUSETRANSLATEFIRST
#undef WM_BEGINDRAG
#undef WM_ENDDRAG
#undef WM_SINGLESELECT
#undef WM_OPEN
#undef WM_CONTEXTMENU
#undef WM_CONTEXTHELP
#undef WM_TEXTEDIT
#undef WM_BEGINSELECT
#undef WM_ENDSELECT
#undef WM_MOUSETRANSLATELAST
#undef WM_PICKUP
#undef WM_PENFIRST
#undef WM_PENLAST
#undef WM_MMPMFIRST
#undef WM_MMPMLAST
#undef WM_BIDI_FIRST
#undef WM_BIDI_LAST
#undef _CHARMSG
#undef CHARMSG
#undef PCHRMSG
#undef _MOUSEMSG
#undef MOUSEMSG
#undef PMSEMSG
#undef _LBOXINFO
#undef LBOXINFO
#undef PLBOXINFO
#undef _MENUITEM
#undef MENUITEM
#undef PMENUITEM
#undef LPMT
#undef _OWNERITEM
#undef OWNERITEM
#undef POWNERITEM
#undef _WNDPARAMS
#undef WNDPARAMS
#undef PWNDPARAMS
#undef _POINTERINFO
#undef POINTERINFO
#undef PPOINTERINFO
#undef _SBCDATA
#undef SBCDATA
#undef PSBCDATA
#undef WM_MSGBOXINIT
#undef WM_MSGBOXDISMISS
#undef WM_CTLCOLORCHANGE
#undef WM_QUERYCTLTYPE
#undef _CTLCOLOR
#undef CTLCOLOR
#undef PCTLCOLOR
#undef _PARAM
#undef PARAM
#undef NPPARAM
#undef PPARAM
#undef _PRESPARAMS
#undef PRESPARAMS
#undef NPPRESPARAMS
#undef PPRESPARAMS
#undef _TRACKINFO
#undef TRACKINFO
#undef PTRACKINFO
#undef IPT
#undef PIPT
#undef PIX
#undef LINE
#undef _FORMATRECT
#undef FORMATRECT
#undef PFORMATRECT
#undef _MLECTLDATA
#undef MLECTLDATA
#undef PMLECTLDATA
#undef _MLEOVERFLOW
#undef MLEOVERFLOW
#undef POVERFLOW
#undef _MLEMARGSTRUCT
#undef MLEMARGSTRUCT
#undef PMARGSTRUCT
#undef _SEARCH
#undef SEARCH
#undef PMLE_SEARCHDATA
#undef TA_NORMAL_HORIZ
#undef TA_LEFT
#undef TA_CENTER
#undef TA_RIGHT
#undef TA_STANDARD_HORIZ
#undef TA_NORMAL_VERT
#undef TA_TOP
#undef TA_HALF
#undef TA_BASE
#undef TA_BOTTOM
#undef TA_STANDARD_VERT
#undef RGN_ERROR
#undef RGN_NULL
#undef RGN_RECT
#undef RGN_COMPLEX
#undef PBUNDLE
#undef FIXED
#undef PFIXED
#undef HMF
#undef PHMF
#undef _SIZEL
#undef SIZEL
#undef PSIZEL
#undef _RGNRECT
#undef RGNRECT
#undef PRGNRECT
#undef _MATRIXLF
#undef MATRIXLF
#undef PMATRIXLF
#undef _ARCPARAMS
#undef ARCPARAMS
#undef PARCPARAMS
#undef _SIZEF
#undef SIZEF
#undef PSIZEF
#undef _POLYGON
#undef POLYGON
#undef PPOLYGON
#undef _POLYSET
#undef POLYSET
#undef PPOLYSET
#undef _GRADIENTL
#undef GRADIENTL
#undef PGRADIENTL
#undef _KERNINGPAIRS
#undef KERNINGPAIRS
#undef PKERNINGPAIRS
#undef _FACENAMEDESC
#undef FACENAMEDESC
#undef PFACENAMEDESC
#undef FFDESCS
#undef PFFDESCS
#undef _FFDESCS2
#undef FFDESCS2
#undef PFFDESCS2
#undef _LINEBUNDLE
#undef LINEBUNDLE
#undef PLINEBUNDLE
#undef _CHARBUNDLE
#undef CHARBUNDLE
#undef PCHARBUNDLE
#undef _MARKERBUNDLE
#undef MARKERBUNDLE
#undef PMARKERBUNDLE
#undef _AREABUNDLE
#undef AREABUNDLE
#undef PAREABUNDLE
#undef _IMAGEBUNDLE
#undef IMAGEBUNDLE
#undef PIMAGEBUNDLE
#undef _RGB
#undef RGB
#undef _RGB2
#undef RGB2
#undef PRGB2
#undef _BITMAPINFOHEADER
#undef BITMAPINFOHEADER
#undef PBITMAPINFOHEADER
#undef _BITMAPINFO
#undef BITMAPINFO
#undef PBITMAPINFO
#undef _BITMAPINFO2
#undef BITMAPINFO2
#undef PBITMAPINFO2
#undef _BITMAPINFOHEADER2
#undef BITMAPINFOHEADER2
#undef PBITMAPINFOHEADER2
#undef _BITMAPFILEHEADER
#undef BITMAPFILEHEADER
#undef PBITMAPFILEHEADER
#undef _BITMAPARRAYFILEHEADER
#undef BITMAPARRAYFILEHEADER
#undef PBITMAPARRAYFILEHEADER
#undef _BITMAPFILEHEADER2
#undef BITMAPFILEHEADER2
#undef PBITMAPFILEHEADER2
#undef _BITMAPARRAYFILEHEADER2
#undef BITMAPARRAYFILEHEADER2
#undef PBITMAPARRAYFILEHEADER2
#undef PDEVOPENDATA
#undef _DRIVDATA
#undef DRIVDATA
#undef PDRIVDATA
#undef _DEVOPENSTRUC
#undef DEVOPENSTRUC
#undef PDEVOPENSTRUC
#undef _ESCMODE
#undef ESCMODE
#undef PESCMODE
#undef _VIOSIZECOUNT
#undef VIOSIZECOUNT
#undef PVIOSIZECOUNT
#undef _VIOFONTCELLSIZE
#undef VIOFONTCELLSIZE
#undef PVIOFONTCELLSIZE
#undef _SFACTORS
#undef SFACTORS
#undef PSFACTORS
#undef _BANDRECT
#undef BANDRECT
#undef PBANDRECT
#undef _HCINFO
#undef HCINFO
#undef PHCINFO
#undef HSWITCH
#undef PHSWITCH
#undef HPROGRAM
#undef PHPROGRAM
#undef HINI
#undef PHINI
#undef HAPP
#undef _PRFPROFILE
#undef PRFPROFILE
#undef PPRFPROFILE
#undef PROGCATEGORY
#undef PPROGCATEGORY
#undef _HPROGARRAY
#undef HPROGARRAY
#undef PHPROGARRAY
#undef _PROGTYPE
#undef PROGTYPE
#undef PPROGTYPE
#undef _PROGTITLE
#undef PROGTITLE
#undef PPROGTITLE
#undef _PROGDETAILS
#undef PROGDETAILS
#undef PPROGDETAILS
#undef _SWCNTRL
#undef SWCNTRL
#undef PSWCNTRL
#undef _SWENTRY
#undef SWENTRY
#undef PSWENTRY
#undef _SWBLOCK
#undef SWBLOCK
#undef PSWBLOCK
#undef APSZ
#undef PAPSZ
#undef _FILEDLG
#undef FILEDLG
#undef PFILEDLG
#undef _FONTDLG
#undef FONTDLG
#undef PFONTDLG
#undef _STYLECHANGE
#undef STYLECHANGE
#undef PSTYLECHANGE
#undef _SPBCDATA
#undef SPBCDATA
#undef PSPBCDATA
#undef _SLDCDATA
#undef SLDCDATA
#undef PSLDCDATA
#undef _CSBITMAPDATA
#undef CSBITMAPDATA
#undef PCSBITMAPDATA
#undef _BOOKTEXT
#undef BOOKTEXT
#undef PBOOKTEXT
#undef _NOTEBOOKBUTTON
#undef NOTEBOOKBUTTON
#undef PNOTEBOOKBUTTON
#undef _DELETENOTIFY
#undef DELETENOTIFY
#undef PDELETENOTIFY
#undef _PAGESELECTNOTIFY
#undef PAGESELECTNOTIFY
#undef PPAGESELECTNOTIFY
#undef _BOOKPAGEINFO
#undef BOOKPAGEINFO
#undef PBOOKPAGEINFO
#undef WM_DRAGFIRST
#undef WM_DRAGLAST
#undef HSTR
#undef _DRAGIMAGE
#undef DRAGIMAGE
#undef PDRAGIMAGE
#undef _DRAGINFO
#undef DRAGINFO
#undef PDRAGINFO
#undef _DRAGITEM
#undef DRAGITEM
#undef PDRAGITEM
#undef _DRAGTRANSFER
#undef DRAGTRANSFER
#undef PDRAGTRANSFER
#undef _RENDERFILE
#undef RENDERFILE
#undef PRENDERFILE
#undef _VSCDATA
#undef VSCDATA
#undef PVSCDATA
#undef _VSDRAGINIT
#undef VSDRAGINIT
#undef PVSDRAGINIT
#undef _VSDRAGINFO
#undef VSDRAGINFO
#undef PVSDRAGINFO
#undef _VSTEXT
#undef VSTEXT
#undef PVSTEXT
#undef _TREEITEMDESC
#undef TREEITEMDESC
#undef PTREEITEMDESC
#undef _FIELDINFO
#undef FIELDINFO
#undef PFIELDINFO
#undef _RECORDCORE
#undef RECORDCORE
#undef PRECORDCORE
#undef _MINIRECORDCORE
#undef MINIRECORDCORE
#undef PMINIRECORDCORE
#undef _TREEMOVE
#undef TREEMOVE
#undef PTREEMOVE
#undef _CNRINFO
#undef CNRINFO
#undef PCNRINFO
#undef _GRIDSQUARE
#undef GRIDSQUARE
#undef PGRIDSQUARE
#undef _GRIDINFO
#undef GRIDINFO
#undef PGRIDINFO
#undef _CDATE
#undef CDATE
#undef PCDATE
#undef _CTIME
#undef CTIME
#undef PCTIME
#undef _CNRDRAGINIT
#undef CNRDRAGINIT
#undef PCNRDRAGINIT
#undef _FIELDINFOINSERT
#undef FIELDINFOINSERT
#undef PFIELDINFOINSERT
#undef _RECORDINSERT
#undef RECORDINSERT
#undef PRECORDINSERT
#undef _QUERYRECFROMRECT
#undef QUERYRECFROMRECT
#undef PQUERYRECFROMRECT
#undef _QUERYRECORDRECT
#undef QUERYRECORDRECT
#undef PQUERYRECORDRECT
#undef _SEARCHSTRING
#undef SEARCHSTRING
#undef PSEARCHSTRING
#undef _CNRDRAGINFO
#undef CNRDRAGINFO
#undef PCNRDRAGINFO
#undef _CNRLAZYDRAGINFO
#undef CNRLAZYDRAGINFO
#undef PCNRLAZYDRAGINFO
#undef _NOTIFYRECORDEMPHASIS
#undef NOTIFYRECORDEMPHASIS
#undef PNOTIFYRECORDEMPHASIS
#undef _NOTIFYRECORDENTER
#undef NOTIFYRECORDENTER
#undef PNOTIFYRECORDENTER
#undef _NOTIFYDELTA
#undef NOTIFYDELTA
#undef PNOTIFYDELTA
#undef _NOTIFYSCROLL
#undef NOTIFYSCROLL
#undef PNOTIFYSCROLL
#undef _CNREDITDATA
#undef CNREDITDATA
#undef PCNREDITDATA
#undef _OWNERBACKGROUND
#undef OWNERBACKGROUND
#undef POWNERBACKGROUND
#undef _CNRDRAWITEMINFO
#undef CNRDRAWITEMINFO
#undef PCNRDRAWITEMINFO
#undef _OBJCLASS
#undef OBJCLASS
#undef POBJCLASS
#undef HSPL
#undef HSTD
#undef PHSTD
#undef PQMOPENDATA
#undef SPLERR
#undef _SQPOPENDATA
#undef SQPOPENDATA
#undef PSQPOPENDATA
#undef _DRIVPROPS
#undef DRIVPROPS
#undef PDRIVPROPS
#undef _PRINTERINFO
#undef PRINTERINFO
#undef PPRINTERINFO
#undef _PRJINFO
#undef PRJINFO
#undef PPRJINFO
#undef _PRJINFO2
#undef PRJINFO2
#undef PPRJINFO2
#undef _PRJINFO3
#undef PRJINFO3
#undef PPRJINFO3
#undef _PRJINFO4
#undef PRJINFO4
#undef PPRJINFO4
#undef _PRDINFO
#undef PRDINFO
#undef PPRDINFO
#undef _PRDINFO3
#undef PRDINFO3
#undef PPRDINFO3
#undef _PRQINFO
#undef PRQINFO
#undef PPRQINFO
#undef _PRQINFO3
#undef PRQINFO3
#undef PPRQINFO3
#undef _PRQINFO6
#undef PRQINFO6
#undef PPRQINFO6
#undef _PRIDINFO
#undef PRIDINFO
#undef PPRIDINFO
#undef _PRDRIVINFO
#undef PRDRIVINFO
#undef PPRDRIVINFO
#undef _PRDRIVINFO2
#undef PRDRIVINFO2
#undef PPRDRIVINFO2
#undef _PRQPROCINFO
#undef PRQPROCINFO
#undef PPRQPROCINFO
#undef _PRPORTINFO
#undef PRPORTINFO
#undef PPRPORTINFO
#undef _PRPORTINFO1
#undef PRPORTINFO1
#undef PPRPORTINFO1
#undef _PRPORTINFO2
#undef PRPORTINFO2
#undef PPRPORTINFO2
#undef _QMJOBINFO
#undef QMJOBINFO
#undef PQMJOBINFO
#undef HWND_PARENT
#undef HELPSUBTABLE
#undef PHELPSUBTABLE
#undef _ACVP
#undef ACVP
#undef PACVP
#undef _HELPTABLE
#undef HELPTABLE
#undef PHELPTABLE
#undef _HELPINIT
#undef HELPINIT
#undef PHELPINIT
#undef HDDF
#undef _FOCAMETRICS
#undef FOCAMETRICS
#undef PFOCAMETRICS
#undef _FONTFILEMETRICS
#undef FONTFILEMETRICS
#undef PFONTFILEMETRICS
#undef _FONTDEFINITIONHEADER
#undef FONTDEFINITIONHEADER
#undef PFONTDEFINITIONHEADER
#undef _FONTSIGNATURE
#undef FONTSIGNATURE
#undef PFONTSIGNATURE
#undef _ADDITIONALMETRICS
#undef ADDITIONALMETRICS
#undef PADDITIONALMETRICS
#undef _FOCAFONT
#undef FOCAFONT
#undef PFOCAFONT
#undef FOCAFONT32
#undef PFOCAFONT32
#undef HVPS
#undef PHVPS
#undef HMONITOR
#undef PHMONITOR
#undef _MONIN
#undef MONIN
#undef PMONIN
#undef _MONOUT
#undef MONOUT
#undef PMONOUT
#undef HKBD
#undef PHKBD
#undef _KBDKEYINFO
#undef KBDKEYINFO
#undef PKBDKEYINFO
#undef _KBDINFO
#undef KBDINFO
#undef PKBDINFO
#undef _KBDHWID
#undef KBDHWID
#undef PKBDHWID
#undef _KBDTRANS
#undef KBDTRANS
#undef PKBDTRANS
#undef _STRINGINBUF
#undef STRINGINBUF
#undef PSTRINGINBUF
#undef HVIO
#undef PHVIO
#undef _VIOMODEINFO
#undef VIOMODEINFO
#undef PVIOMODEINFO
#undef _VIOCONFIGINFO
#undef VIOCONFIGINFO
#undef PVIOCONFIGINFO
#undef _VIOPHYSBUF
#undef VIOPHYSBUF
#undef PVIOPHYSBUF
#undef _VIOPALSTATE
#undef VIOPALSTATE
#undef PVIOPALSTATE
#undef _VIOOVERSCAN
#undef VIOOVERSCAN
#undef PVIOOVERSCAN
#undef _VIOINTENSITY
#undef VIOINTENSITY
#undef PVIOINTENSITY
#undef _VIOCOLORREG
#undef VIOCOLORREG
#undef PVIOCOLORREG
#undef _VIOSETULINELOC
#undef VIOSETULINELOC
#undef PVIOSETULINELOC
#undef _VIOSETTARGET
#undef VIOSETTARGET
#undef PVIOSETTARGET
#undef _VIOCURSORINFO
#undef VIOCURSORINFO
#undef PVIOCURSORINFO
#undef _VIOFONTINFO
#undef VIOFONTINFO
#undef PVIOFONTINFO
#undef HMOU
#undef PHMOU
#undef _MOUEVENTINFO
#undef MOUEVENTINFO
#undef PMOUEVENTINFO
#undef _MOUQUEINFO
#undef MOUQUEINFO
#undef PMOUQUEINFO
#undef _PTRLOC
#undef PTRLOC
#undef PPTRLOC
#undef _NOPTRRECT
#undef NOPTRRECT
#undef PNOPTRRECT
#undef _PTRSHAPE
#undef PTRSHAPE
#undef PPTRSHAPE
#undef _SCALEFACT
#undef SCALEFACT
#undef PSCALEFACT
#undef _THRESHOLD
#undef THRESHOLD
#undef PTHRESHOLD
#undef _GINFOSEG
#undef GINFOSEG
#undef PGINFOSEG
#undef _LINFOSEG
#undef LINFOSEG
#undef PLINFOSEG

/* Some manually added redefinitionis not caught by sed */
#undef VOID
#undef FIELDOFFSET
#undef MAKETYPE
#undef MAKEUSHORT
#undef MAKESHORT
#undef MAKEULONG
#undef MAKELONG
#undef LOUCHAR
#undef HIUCHAR
#undef LOBYTE
#undef HIBYTE
#undef LOUSHORT
#undef HIUSHORT
#undef WINERR_BASE
#undef GPIERR_BASE
#undef DEVERR_BASE
#undef SPLERR_BASE
#undef SEVERITY_NOERROR
#undef SEVERITY_WARNING
#undef SEVERITY_ERROR
#undef SEVERITY_SEVERE
#undef SEVERITY_UNRECOVERABLE
#undef MAKE16P
#undef MAKEP
#undef SELECTOROF
#undef OFFSETOF
#undef APIENTRY
#undef EXPENTRY

#endif /* __OS2WRAP2_H__ */
