/* 
 * A full version of os2wrap.h that prefixes all OS/2 type and constant
 * definitions with "os2_" which makes it possible to use the OS/2 APIs
 * from the same source files that use the Windows APIs.
 *
 * Project Odin Software License can be found in LICENSE.TXT
 */

#ifndef __OS2WRAP2_H__
#define __OS2WRAP2_H__

#ifdef WINVER
#error "os2wrap2.h must be included BEFORE any Windows include file!"
#endif

/*
   Redefine all OS/2 typedefs to those having the "os2_" prefix to avoid
   conflicts with Windows typedefs. Also define "os2_" versions of all
   macros. The defines are generated with the following command on the
   respective OS/2 headers:

sed -nr '
{
  s/^[[:space:]]*typedef[[:space:]]+struct[[:space:]]+([A-Za-z_][A-Za-z0-9_]+)([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#define \1 os2_\1/p
  td
  s/^[[:space:]]*}[[:space:]]*([A-Z_][A-Z0-9_]+)[[:space:]]*;[[:space:]]*$/#define \1 os2_\1/p
  td
  s/^[[:space:]]*typedef[[:space:]]+.+[[:space:]]+\**([A-Z_][A-Z0-9_]+)[[:space:]]*(\[.*\])?[[:space:]]*;([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#define \1 os2_\1/p
  td
}
/^[[:space:]]*#define[[:space:]]+/ {
  :a;/\\$/{N;ba}
  s/([^A-Za-z0-9_])(MAKE[A-Z0-9]+)([^A-Za-z0-9_])/\1 \2 \3/g
  s/([^A-Za-z0-9_])(((CONTEXT|CS|DM|DT|EH|EXCEPTION|FDM|FNTM|HWND|MB|MIA|NP|QS|QSV|RGN|RT|SEM|SEVERITY|SIS|SV|SWP|TA|WC|WM|WS|(WIN|GPI|DEV|SPL)ERR)_([A-Z0-9_]+))|((P?VOID|(API|EXP)ENTRY|P(CMD|CHR|MSE)MSG|ERRORID|PCMDMSG|SEL|HWND|MPARAM|MRESULT|LHANDLE|SHANDLE|BOOL|(LO|HI|P)?U?(LONG|SHORT|CHAR|BYTE)|MPFROM[A-Z0-9]+|MAKE[A-Z0-9]+)([^A-Za-z0-9_])))/\1os2_\2/g
  tb;bd
  :b
  s/^[[:space:]]*#define[[:space:]]+(os2_)?([A-Za-z_][A-Za-z0-9_]+)[[:space:]]*(.*)/#define os2_\2 \3/p
}  
:d
'
 */
#define os2__THUNK_PASCAL_FUNCTION (FUN) os2_APIENTRY _16_##FUN
#define os2_MAKE16P (sel,off)   ((_far16ptr)((sel) << 16 | (off)))
#define os2_MAKEP (sel,off)     _libc_16to32 ( os2_MAKE16P  (sel, off))
#define os2_SELECTOROF (farptr) ((os2_SEL)((farptr) >> 16))
#define os2_OFFSETOF (farptr)   ((os2_USHORT)(farptr))
#define os2__THUNK_PTR_SIZE_OK (ptr,size) \
  (((os2_ULONG)(ptr) & ~0xffff) == (((os2_ULONG)(ptr) + (size) - 1) & ~0xffff))
#define os2_APIENTRY _System
#define os2_EXPENTRY _System
#define os2_VOID void
#define os2_NULLHANDLE ((os2_LHANDLE)0)
#define os2_NULLSHANDLE ((os2_SHANDLE)0)
#define INT os2_INT
#define UINT os2_UINT
#define APIRET os2_APIRET
#define BOOL os2_BOOL
#define PBOOL os2_PBOOL
#define BOOL32 os2_BOOL32
#define PBOOL32 os2_PBOOL32
#define CHAR os2_CHAR
#define PCHAR os2_PCHAR
#define BYTE os2_BYTE
#define PCH os2_PCH
#define PSZ os2_PSZ
#define PCCH os2_PCCH
#define PCSZ os2_PCSZ
#define BYTE os2_BYTE
#define PCH os2_PCH
#define PSZ os2_PSZ
#define PCCH os2_PCCH
#define PCSZ os2_PCSZ
#define PBYTE os2_PBYTE
#define UCHAR os2_UCHAR
#define PUCHAR os2_PUCHAR
#define SHORT os2_SHORT
#define PSHORT os2_PSHORT
#define USHORT os2_USHORT
#define PUSHORT os2_PUSHORT
#define LONG os2_LONG
#define PLONG os2_PLONG
#define ULONG os2_ULONG
#define PULONG os2_PULONG
#define LONGLONG os2_LONGLONG
#define PLONGLONG os2_PLONGLONG
#define ULONGLONG os2_ULONGLONG
#define PULONGLONG os2_PULONGLONG
#define _LONGLONG os2__LONGLONG
#define LONGLONG os2_LONGLONG
#define PLONGLONG os2_PLONGLONG
#define _ULONGLONG os2__ULONGLONG
#define ULONGLONG os2_ULONGLONG
#define PULONGLONG os2_PULONGLONG
#define PVOID os2_PVOID
#define PPVOID os2_PPVOID
#define CPVOID os2_CPVOID
#define STR8 os2_STR8
#define PSTR8 os2_PSTR8
#define STR16 os2_STR16
#define PSTR16 os2_PSTR16
#define STR32 os2_STR32
#define PSTR32 os2_PSTR32
#define STR64 os2_STR64
#define PSTR64 os2_PSTR64
#define SHANDLE os2_SHANDLE
#define LHANDLE os2_LHANDLE
#define HPIPE os2_HPIPE
#define PHPIPE os2_PHPIPE
#define HQUEUE os2_HQUEUE
#define PHQUEUE os2_PHQUEUE
#define HMODULE os2_HMODULE
#define PHMODULE os2_PHMODULE
#define HSEM os2_HSEM
#define PHSEM os2_PHSEM
#define HOBJECT os2_HOBJECT
#define PID os2_PID
#define PPID os2_PPID
#define TID os2_TID
#define PTID os2_PTID
#define PFN os2_PFN
#define PPFN os2_PPFN
#define SEL os2_SEL
#define PSEL os2_PSEL
#define HMTX os2_HMTX
#define PHMTX os2_PHMTX
#define HMUX os2_HMUX
#define PHMUX os2_PHMUX
#define os2_FIELDOFFSET (t,f)  ((os2_SHORT)&(((t *)0)->f))
#define os2_MAKETYPE (v,t)	  (*((t *)&v))
#define os2_MAKEUSHORT (l,h)	  (((os2_USHORT)(l)) | ((os2_USHORT)(h))<<8)
#define os2_MAKESHORT (l,h)	  ((os2_SHORT) os2_MAKEUSHORT (l, h))
#define os2_MAKEULONG (l,h)	  ((os2_ULONG)(((os2_USHORT)(l)) | ((os2_ULONG)((os2_USHORT)(h)))<<16))
#define os2_MAKELONG (l,h)	  ((os2_LONG) os2_MAKEULONG (l, h))
#define os2_LOUCHAR (w)	  ((os2_UCHAR)(w))
#define os2_HIUCHAR (w)	  ((os2_UCHAR)((os2_USHORT)(w)>>8))
#define os2_LOBYTE (x)	  os2_LOUCHAR(x)
#define os2_HIBYTE (x)	  os2_HIUCHAR(x)
#define os2_LOUSHORT (x)	  ((os2_USHORT)((os2_ULONG)(x)))
#define os2_HIUSHORT (x)	  ((os2_USHORT)((os2_ULONG)(x)>>16))
#define os2_WINERR_BASE 0x1000
#define os2_GPIERR_BASE 0x2000
#define os2_DEVERR_BASE 0x3000
#define os2_SPLERR_BASE 0x4000
#define os2_SEVERITY_NOERROR 0x0000
#define os2_SEVERITY_WARNING 0x0004
#define os2_SEVERITY_ERROR 0x0008
#define os2_SEVERITY_SEVERE 0x000c
#define os2_SEVERITY_UNRECOVERABLE 0x0010
#define _PANOSE os2__PANOSE
#define PANOSE os2_PANOSE
#define _FONTMETRICS os2__FONTMETRICS
#define FONTMETRICS os2_FONTMETRICS
#define PFONTMETRICS os2_PFONTMETRICS
#define _FATTRS os2__FATTRS
#define FATTRS os2_FATTRS
#define PFATTRS os2_PFATTRS
#define HFILE os2_HFILE
#define PHFILE os2_PHFILE
#define FHLOCK os2_FHLOCK
#define PFHLOCK os2_PFHLOCK
#define HDIR os2_HDIR
#define PHDIR os2_PHDIR
#define _FTIME os2__FTIME
#define FTIME os2_FTIME
#define _FTIME os2__FTIME
#define FTIME os2_FTIME
#define PFTIME os2_PFTIME
#define _FDATE os2__FDATE
#define FDATE os2_FDATE
#define _FDATE os2__FDATE
#define FDATE os2_FDATE
#define PFDATE os2_PFDATE
#define _FEA os2__FEA
#define FEA os2_FEA
#define PFEA os2_PFEA
#define _FEALIST os2__FEALIST
#define FEALIST os2_FEALIST
#define PFEALIST os2_PFEALIST
#define _GEA os2__GEA
#define GEA os2_GEA
#define PGEA os2_PGEA
#define _GEALIST os2__GEALIST
#define GEALIST os2_GEALIST
#define PGEALIST os2_PGEALIST
#define _EAOP os2__EAOP
#define EAOP os2_EAOP
#define PEAOP os2_PEAOP
#define _FEA2 os2__FEA2
#define FEA2 os2_FEA2
#define PFEA2 os2_PFEA2
#define _FEA2LIST os2__FEA2LIST
#define FEA2LIST os2_FEA2LIST
#define PFEA2LIST os2_PFEA2LIST
#define _GEA2 os2__GEA2
#define GEA2 os2_GEA2
#define PGEA2 os2_PGEA2
#define _GEA2LIST os2__GEA2LIST
#define GEA2LIST os2_GEA2LIST
#define PGEA2LIST os2_PGEA2LIST
#define _EAOP2 os2__EAOP2
#define EAOP2 os2_EAOP2
#define PEAOP2 os2_PEAOP2
#define _DENA1 os2__DENA1
#define DENA1 os2_DENA1
#define PDENA1 os2_PDENA1
#define DENA2 os2_DENA2
#define PDENA2 os2_PDENA2
#define _EASIZEBUF os2__EASIZEBUF
#define EASIZEBUF os2_EASIZEBUF
#define PEASIZEBUF os2_PEASIZEBUF
#define _ROUTENAMEBUF os2__ROUTENAMEBUF
#define ROUTENAMEBUF os2_ROUTENAMEBUF
#define PROUTENAMEBUF os2_PROUTENAMEBUF
#define _FSDTHREAD os2__FSDTHREAD
#define FSDTHREAD os2_FSDTHREAD
#define _FSDDAEMON os2__FSDDAEMON
#define FSDDAEMON os2_FSDDAEMON
#define _FILEFINDBUF os2__FILEFINDBUF
#define FILEFINDBUF os2_FILEFINDBUF
#define PFILEFINDBUF os2_PFILEFINDBUF
#define _FILEFINDBUF2 os2__FILEFINDBUF2
#define FILEFINDBUF2 os2_FILEFINDBUF2
#define PFILEFINDBUF2 os2_PFILEFINDBUF2
#define _FILEFINDBUF3 os2__FILEFINDBUF3
#define FILEFINDBUF3 os2_FILEFINDBUF3
#define PFILEFINDBUF3 os2_PFILEFINDBUF3
#define _FILEFINDBUF4 os2__FILEFINDBUF4
#define FILEFINDBUF4 os2_FILEFINDBUF4
#define PFILEFINDBUF4 os2_PFILEFINDBUF4
#define _FILEFINDBUF3L os2__FILEFINDBUF3L
#define FILEFINDBUF3L os2_FILEFINDBUF3L
#define PFILEFINDBUF3L os2_PFILEFINDBUF3L
#define _FILEFINDBUF4L os2__FILEFINDBUF4L
#define FILEFINDBUF4L os2_FILEFINDBUF4L
#define PFILEFINDBUF4L os2_PFILEFINDBUF4L
#define _FILELOCK os2__FILELOCK
#define FILELOCK os2_FILELOCK
#define PFILELOCK os2_PFILELOCK
#define _FILELOCKL os2__FILELOCKL
#define FILELOCKL os2_FILELOCKL
#define PFILELOCKL os2_PFILELOCKL
#define _FILESTATUS os2__FILESTATUS
#define FILESTATUS os2_FILESTATUS
#define PFILESTATUS os2_PFILESTATUS
#define _FILESTATUS2 os2__FILESTATUS2
#define FILESTATUS2 os2_FILESTATUS2
#define PFILESTATUS2 os2_PFILESTATUS2
#define _FILESTATUS3 os2__FILESTATUS3
#define FILESTATUS3 os2_FILESTATUS3
#define PFILESTATUS3 os2_PFILESTATUS3
#define _FILESTATUS4 os2__FILESTATUS4
#define FILESTATUS4 os2_FILESTATUS4
#define PFILESTATUS4 os2_PFILESTATUS4
#define _FILESTATUS3L os2__FILESTATUS3L
#define FILESTATUS3L os2_FILESTATUS3L
#define PFILESTATUS3L os2_PFILESTATUS3L
#define _FILESTATUS4L os2__FILESTATUS4L
#define FILESTATUS4L os2_FILESTATUS4L
#define PFILESTATUS4L os2_PFILESTATUS4L
#define _FSALLOCATE os2__FSALLOCATE
#define FSALLOCATE os2_FSALLOCATE
#define PFSALLOCATE os2_PFSALLOCATE
#define _FSQBUFFER os2__FSQBUFFER
#define FSQBUFFER os2_FSQBUFFER
#define PFSQBUFFER os2_PFSQBUFFER
#define _FSQBUFFER2 os2__FSQBUFFER2
#define FSQBUFFER2 os2_FSQBUFFER2
#define PFSQBUFFER2 os2_PFSQBUFFER2
#define _SPOOLATTACH os2__SPOOLATTACH
#define SPOOLATTACH os2_SPOOLATTACH
#define PSPOOLATTACH os2_PSPOOLATTACH
#define _VOLUMELABEL os2__VOLUMELABEL
#define VOLUMELABEL os2_VOLUMELABEL
#define PVOLUMELABEL os2_PVOLUMELABEL
#define _FSINFO os2__FSINFO
#define FSINFO os2_FSINFO
#define PFSINFO os2_PFSINFO
#define _LISTIO_CB os2__LISTIO_CB
#define LISTIO os2_LISTIO
#define PLISTIO os2_PLISTIO
#define _LISTIO_CBL os2__LISTIO_CBL
#define LISTIOL os2_LISTIOL
#define PLISTIOL os2_PLISTIOL
#define _DCBINFO os2__DCBINFO
#define DCBINFO os2_DCBINFO
#define PDCBINFO os2_PDCBINFO
#define _LINECONTROL os2__LINECONTROL
#define LINECONTROL os2_LINECONTROL
#define PLINECONTROL os2_PLINECONTROL
#define _MODEMSTATUS os2__MODEMSTATUS
#define MODEMSTATUS os2_MODEMSTATUS
#define PMODEMSTATUS os2_PMODEMSTATUS
#define _KBDTYPE os2__KBDTYPE
#define KBDTYPE os2_KBDTYPE
#define PKBDTYPE os2_PKBDTYPE
#define _RATEDELAY os2__RATEDELAY
#define RATEDELAY os2_RATEDELAY
#define PRATEDELAY os2_PRATEDELAY
#define _CODEPAGEINFO os2__CODEPAGEINFO
#define CODEPAGEINFO os2_CODEPAGEINFO
#define PCODEPAGEINFO os2_PCODEPAGEINFO
#define _CPID os2__CPID
#define CPID os2_CPID
#define PCPID os2_PCPID
#define _SHIFTSTATE os2__SHIFTSTATE
#define SHIFTSTATE os2_SHIFTSTATE
#define PSHIFTSTATE os2_PSHIFTSTATE
#define _HOTKEY os2__HOTKEY
#define HOTKEY os2_HOTKEY
#define PHOTKEY os2_PHOTKEY
#define _PTRDRAWFUNCTION os2__PTRDRAWFUNCTION
#define PTRDRAWFUNCTION os2_PTRDRAWFUNCTION
#define PPTRDRAWFUNCTION os2_PPTRDRAWFUNCTION
#define _PTRDRAWADDRESS os2__PTRDRAWADDRESS
#define PTRDRAWADDRESS os2_PTRDRAWADDRESS
#define PPTRDRAWADDRESS os2_PPTRDRAWADDRESS
#define _PTRDRAWDATA os2__PTRDRAWDATA
#define PTRDRAWDATA os2_PTRDRAWDATA
#define PPTRDRAWDATA os2_PPTRDRAWDATA
#define _TRACKLAYOUT os2__TRACKLAYOUT
#define TRACKLAYOUT os2_TRACKLAYOUT
#define PTRACKLAYOUT os2_PTRACKLAYOUT
#define _TRACKFORMAT os2__TRACKFORMAT
#define TRACKFORMAT os2_TRACKFORMAT
#define PTRACKFORMAT os2_PTRACKFORMAT
#define _BIOSPARAMETERBLOCK os2__BIOSPARAMETERBLOCK
#define BIOSPARAMETERBLOCK os2_BIOSPARAMETERBLOCK
#define PBIOSPARAMETERBLOCK os2_PBIOSPARAMETERBLOCK
#define _DEVICEPARAMETERBLOCK os2__DEVICEPARAMETERBLOCK
#define DEVICEPARAMETERBLOCK os2_DEVICEPARAMETERBLOCK
#define PDEVICEPARAMETERBLOCK os2_PDEVICEPARAMETERBLOCK
#define _MONITORPOSITION os2__MONITORPOSITION
#define MONITORPOSITION os2_MONITORPOSITION
#define PMONITORPOSITION os2_PMONITORPOSITION
#define _FRAME os2__FRAME
#define FRAME os2_FRAME
#define PFRAME os2_PFRAME
#define _LDTADDRINFO os2__LDTADDRINFO
#define LDTADDRINFO os2_LDTADDRINFO
#define PLDTADDRINFO os2_PLDTADDRINFO
#define _SCREENGROUP os2__SCREENGROUP
#define SCREENGROUP os2_SCREENGROUP
#define PSCREENGROUP os2_PSCREENGROUP
#define _RXQUEUE os2__RXQUEUE
#define RXQUEUE os2_RXQUEUE
#define PRXQUEUE os2_PRXQUEUE
#define _GETLINIOCTLDATA os2__GETLINIOCTLDATA
#define GETLINIOCTLDATA os2_GETLINIOCTLDATA
#define PGETLINIOCTLDATA os2_PGETLINIOCTLDATA
#define _BANKINFO os2__BANKINFO
#define BANKINFO os2_BANKINFO
#define _GLOBALIOCTLDATA os2__GLOBALIOCTLDATA
#define GLOBALIOCTLDATA os2_GLOBALIOCTLDATA
#define _OEMSVGAINFO os2__OEMSVGAINFO
#define OEMSVGAINFO os2_OEMSVGAINFO
#define _OEMINFO os2__OEMINFO
#define OEMINFO os2_OEMINFO
#define _GETGLOBALPACKET os2__GETGLOBALPACKET
#define GETGLOBALPACKET os2_GETGLOBALPACKET
#define _COUNTRYCODE os2__COUNTRYCODE
#define COUNTRYCODE os2_COUNTRYCODE
#define PCOUNTRYCODE os2_PCOUNTRYCODE
#define _COUNTRYINFO os2__COUNTRYINFO
#define COUNTRYINFO os2_COUNTRYINFO
#define PCOUNTRYINFO os2_PCOUNTRYINFO
#define os2_RT_POINTER 1
#define os2_RT_BITMAP 2
#define os2_RT_MENU 3
#define os2_RT_DIALOG 4
#define os2_RT_STRING 5
#define os2_RT_FONTDIR 6
#define os2_RT_FONT 7
#define os2_RT_ACCELTABLE 8
#define os2_RT_RCDATA 9
#define os2_RT_MESSAGE 10
#define os2_RT_DLGINCLUDE 11
#define os2_RT_VKEYTBL 12
#define os2_RT_KEYTBL 13
#define os2_RT_CHARTBL 14
#define os2_RT_DISPLAYINFO 15
#define os2_RT_FKASHORT 16
#define os2_RT_FKALONG 17
#define os2_RT_HELPTABLE 18
#define os2_RT_HELPSUBTABLE 19
#define os2_RT_FDDIR 20
#define os2_RT_FD 21
#define os2_RT_MAX 22
#define os2_RT_RESNAMES 255
#define _RESULTCODES os2__RESULTCODES
#define RESULTCODES os2_RESULTCODES
#define PRESULTCODES os2_PRESULTCODES
#define tib2_s os2_tib2_s
#define TIB2 os2_TIB2
#define PTIB2 os2_PTIB2
#define tib_s os2_tib_s
#define TIB os2_TIB
#define PTIB os2_PTIB
#define pib_s os2_pib_s
#define PIB os2_PIB
#define PPIB os2_PPIB
#define PFNTHREAD os2_PFNTHREAD
#define PFNEXITLIST os2_PFNEXITLIST
#define _MPAFFINITY os2__MPAFFINITY
#define MPAFFINITY os2_MPAFFINITY
#define PMPAFFINITY os2_PMPAFFINITY
#define _THREADCREATE os2__THREADCREATE
#define THREADCREATE os2_THREADCREATE
#define PTHREADCREATE os2_PTHREADCREATE
#define _STARTDATA os2__STARTDATA
#define STARTDATA os2_STARTDATA
#define PSTARTDATA os2_PSTARTDATA
#define _STATUSDATA os2__STATUSDATA
#define STATUSDATA os2_STATUSDATA
#define PSTATUSDATA os2_PSTATUSDATA
#define os2_SEM_INDEFINITE_WAIT ((os2_ULONG)-1)
#define os2_SEM_IMMEDIATE_RETURN 0
#define HEV os2_HEV
#define PHEV os2_PHEV
#define _PSEMRECORD os2__PSEMRECORD
#define SEMRECORD os2_SEMRECORD
#define PSEMRECORD os2_PSEMRECORD
#define os2_NP_INDEFINITE_WAIT ((os2_ULONG)-1)
#define os2_NP_DEFAULT_WAIT 0
#define os2_NP_STATE_DISCONNECTED 1
#define os2_NP_STATE_LISTENING 2
#define os2_NP_STATE_CONNECTED 3
#define os2_NP_STATE_CLOSING 4
#define os2_NP_ACCESS_INBOUND 0x0000
#define os2_NP_ACCESS_OUTBOUND 0x0001
#define os2_NP_ACCESS_DUPLEX 0x0002
#define os2_NP_INHERIT 0x0000
#define os2_NP_NOINHERIT 0x0080
#define os2_NP_WRITEBEHIND 0x0000
#define os2_NP_NOWRITEBEHIND 0x4000
#define os2_NP_READMODE_BYTE 0x0000
#define os2_NP_READMODE_MESSAGE 0x0100
#define os2_NP_TYPE_BYTE 0x0000
#define os2_NP_TYPE_MESSAGE 0x0400
#define os2_NP_END_CLIENT 0x0000
#define os2_NP_END_SERVER 0x4000
#define os2_NP_WAIT 0x0000
#define os2_NP_NOWAIT 0x8000
#define os2_NP_UNLIMITED_INSTANCES 0x00ff
#define os2_NP_NBLK os2_NP_NOWAIT
#define os2_NP_SERVER os2_NP_END_SERVER
#define os2_NP_WMESG os2_NP_TYPE_MESSAGE
#define os2_NP_RMESG os2_NP_READMODE_MESSAGE
#define os2_NP_ICOUNT 0x00ff
#define _AVAILDATA os2__AVAILDATA
#define AVAILDATA os2_AVAILDATA
#define PAVAILDATA os2_PAVAILDATA
#define _PIPEINFO os2__PIPEINFO
#define PIPEINFO os2_PIPEINFO
#define PPIPEINFO os2_PPIPEINFO
#define _PIPESEMSTATE os2__PIPESEMSTATE
#define PIPESEMSTATE os2_PIPESEMSTATE
#define PPIPESEMSTATE os2_PPIPESEMSTATE
#define _REQUESTDATA os2__REQUESTDATA
#define REQUESTDATA os2_REQUESTDATA
#define PREQUESTDATA os2_PREQUESTDATA
#define os2_CONTEXT_CONTROL 0x0001
#define os2_CONTEXT_INTEGER 0x0002
#define os2_CONTEXT_SEGMENTS 0x0004
#define os2_CONTEXT_FLOATING_POINT 0x0008
#define os2_CONTEXT_FULL (os2_CONTEXT_CONTROL | os2_CONTEXT_INTEGER | \
				  os2_CONTEXT_SEGMENTS | os2_CONTEXT_FLOATING_POINT)
#define os2_EH_NONCONTINUABLE 0x0001
#define os2_EH_UNWINDING 0x0002
#define os2_EH_EXIT_UNWIND 0x0004
#define os2_EH_STACK_INVALID 0x0008
#define os2_EH_NESTED_CALL 0x0010
#define _fpreg os2__fpreg
#define FPREG os2_FPREG
#define PFPREG os2_PFPREG
#define _CONTEXT os2__CONTEXT
#define CONTEXTRECORD os2_CONTEXTRECORD
#define PCONTEXTRECORD os2_PCONTEXTRECORD
#define os2_EXCEPTION_MAXIMUM_PARAMETERS 4
#define _EXCEPTIONREPORTRECORD os2__EXCEPTIONREPORTRECORD
#define EXCEPTIONREPORTRECORD os2_EXCEPTIONREPORTRECORD
#define PEXCEPTIONREPORTRECORD os2_PEXCEPTIONREPORTRECORD
#define ERR os2_ERR
#define _EXCEPTIONREGISTRATIONRECORD os2__EXCEPTIONREGISTRATIONRECORD
#define EXCEPTIONREGISTRATIONRECORD os2_EXCEPTIONREGISTRATIONRECORD
#define PEXCEPTIONREGISTRATIONRECORD os2_PEXCEPTIONREGISTRATIONRECORD
#define os2_QSV_MAX_PATH_LENGTH 1
#define os2_QSV_MAX_TEXT_SESSIONS 2
#define os2_QSV_MAX_PM_SESSIONS 3
#define os2_QSV_MAX_VDM_SESSIONS 4
#define os2_QSV_BOOT_DRIVE 5
#define os2_QSV_DYN_PRI_VARIATION 6
#define os2_QSV_MAX_WAIT 7
#define os2_QSV_MIN_SLICE 8
#define os2_QSV_MAX_SLICE 9
#define os2_QSV_PAGE_SIZE 10
#define os2_QSV_VERSION_MAJOR 11
#define os2_QSV_VERSION_MINOR 12
#define os2_QSV_VERSION_REVISION 13
#define os2_QSV_MS_COUNT 14
#define os2_QSV_TIME_LOW 15
#define os2_QSV_TIME_HIGH 16
#define os2_QSV_TOTPHYSMEM 17
#define os2_QSV_TOTRESMEM 18
#define os2_QSV_TOTAVAILMEM 19
#define os2_QSV_MAXPRMEM 20
#define os2_QSV_MAXSHMEM 21
#define os2_QSV_TIMER_INTERVAL 22
#define os2_QSV_MAX_COMP_LENGTH 23
#define os2_QSV_FOREGROUND_FS_SESSION 24
#define os2_QSV_FOREGROUND_PROCESS 25
#define os2_QSV_NUMPROCESSORS 26
#define os2_QSV_MAXHPRMEM 27
#define os2_QSV_MAXHSHMEM 28
#define os2_QSV_MAXPROCESSES 29
#define os2_QSV_VIRTUALADDRESSLIMIT 30
#define os2_QSV_INT10ENABLED 31
#define os2_QSV_MAX os2_QSV_INT10ENABLED
#define os2_SIS_MMIOADDR 0
#define os2_SIS_MEC_TABLE 1
#define os2_SIS_SYS_LOG 2
#define os2_SIS_PERF_MEC_TABLE 3
#define _DATETIME os2__DATETIME
#define DATETIME os2_DATETIME
#define PDATETIME os2_PDATETIME
#define HTIMER os2_HTIMER
#define PHTIMER os2_PHTIMER
#define os2_PADSHORT os2_USHORT pad_sh
#define os2_PADCHAR os2_UCHAR  pad_ch
#define os2_QS_PROCESS 0x0001
#define os2_QS_SEMAPHORE 0x0002
#define os2_QS_MTE 0x0004
#define os2_QS_FILESYS 0x0008
#define os2_QS_SHMEMORY 0x0010
#define os2_QS_DISK 0x0020
#define os2_QS_HWCONFIG 0x0040
#define os2_QS_NAMEDPIPE 0x0080
#define os2_QS_THREAD 0x0100
#define os2_QS_MODVER 0x0200
#define os2_QS_SUPPORTED (os2_QS_PROCESS|os2_QS_SEMAPHORE|os2_QS_MTE|os2_QS_FILESYS|os2_QS_SHMEMORY|os2_QS_MODVER)
#define os2_QS_END 0L
#define os2_QS_SYSSEM_WAITING 0x01
#define os2_QS_SYSSEM_MUXWAITING 0x02
#define os2_QS_SYSSEM_OWNER_DIED 0x04
#define os2_QS_SYSSEM_EXCLUSIVE 0x08
#define os2_QS_SYSSEM_NAME_CLEANUP 0x10
#define os2_QS_SYSSEM_THREAD_OWNER_DIED 0x20
#define os2_QS_SYSSEM_EXITLIST_OWNER 0x40
#define os2_QS_DC_SEM_SHARED 0x0001
#define os2_QS_DCMW_WAIT_ANY 0x0002
#define os2_QS_DCMW_WAIT_ALL 0x0004
#define os2_QS_DCM_MUTEX_SEM 0x0008
#define os2_QS_DCE_EVENT_SEM 0x0010
#define os2_QS_DCMW_MUX_SEM 0x0020
#define os2_QS_DC_SEM_PM 0x0040
#define os2_QS_DE_POSTED 0x0040
#define os2_QS_DM_OWNER_DIED 0x0080
#define os2_QS_DMW_MTX_MUX 0x0100
#define os2_QS_DHO_SEM_OPEN 0x0200
#define os2_QS_DE_16BIT_MW 0x0400
#define os2_QS_DCE_POSTONE 0x0800
#define os2_QS_DCE_AUTORESET 0x1000
#define _QWORD os2__QWORD
#define QWORD os2_QWORD
#define PQWORD os2_PQWORD
#define _QSGREC os2__QSGREC
#define QSGREC os2_QSGREC
#define _QSTREC os2__QSTREC
#define QSTREC os2_QSTREC
#define _QSPREC os2__QSPREC
#define QSPREC os2_QSPREC
#define _QSS16REC os2__QSS16REC
#define QSS16REC os2_QSS16REC
#define _QSS16HEADREC os2__QSS16HEADREC
#define QSS16HEADREC os2_QSS16HEADREC
#define _QSMREC os2__QSMREC
#define QSMREC os2_QSMREC
#define _QSOPENQ os2__QSOPENQ
#define QSOPENQ os2_QSOPENQ
#define _QSEVENT os2__QSEVENT
#define QSEVENT os2_QSEVENT
#define _QSMUTEX os2__QSMUTEX
#define QSMUTEX os2_QSMUTEX
#define _QSMUX os2__QSMUX
#define QSMUX os2_QSMUX
#define QSHUN os2_QSHUN
#define _QSS32REC os2__QSS32REC
#define QSS32REC os2_QSS32REC
#define _QSLOBJREC os2__QSLOBJREC
#define QSLOBJREC os2_QSLOBJREC
#define _QSLREC os2__QSLREC
#define QSLREC os2_QSLREC
#define _QSEXLREC os2__QSEXLREC
#define QSEXLREC os2_QSEXLREC
#define _QSSFT os2__QSSFT
#define QSSFT os2_QSSFT
#define _QSFREC os2__QSFREC
#define QSFREC os2_QSFREC
#define _QSPTRREC os2__QSPTRREC
#define QSPTRREC os2_QSPTRREC
#define SGID os2_SGID
#define HVDD os2_HVDD
#define PHVDD os2_PHVDD
#define HSPINLOCK os2_HSPINLOCK
#define PHSPINLOCK os2_PHSPINLOCK
#define _TStat os2__TStat
#define _uDB os2__uDB
#define os2_SIS_MMIOADDR 0
#define os2_SIS_MEC_TABLE 1
#define os2_SIS_SYS_LOG 2
#define os2_SIS_PERF_MEC_TABLE 3
#define _RXSTRING os2__RXSTRING
#define RXSTRING os2_RXSTRING
#define PRXSTRING os2_PRXSTRING
#define _RXSYSEXIT os2__RXSYSEXIT
#define RXSYSEXIT os2_RXSYSEXIT
#define PRXSYSEXIT os2_PRXSYSEXIT
#define os2_MAKERXSTRING (r,p,l) \
    ((r).strptr = (PCH)p, (r).strlength = (os2_ULONG)l)
#define _SHVBLOCK os2__SHVBLOCK
#define SHVBLOCK os2_SHVBLOCK
#define PSHVBLOCK os2_PSHVBLOCK
#define PEXIT os2_PEXIT
#define _RXFNC_FLAGS os2__RXFNC_FLAGS
#define RXFNC_FLAGS os2_RXFNC_FLAGS
#define _RXFNCCAL_PARM os2__RXFNCCAL_PARM
#define RXFNCCAL_PARM os2_RXFNCCAL_PARM
#define _RXCMD_FLAGS os2__RXCMD_FLAGS
#define RXCMD_FLAGS os2_RXCMD_FLAGS
#define _RXCMDHST_PARM os2__RXCMDHST_PARM
#define RXCMDHST_PARM os2_RXCMDHST_PARM
#define _RXMSQPLL_PARM os2__RXMSQPLL_PARM
#define RXMSQPLL_PARM os2_RXMSQPLL_PARM
#define _RXMSQ_FLAGS os2__RXMSQ_FLAGS
#define RXMSQ_FLAGS os2_RXMSQ_FLAGS
#define _RXMSQPSH_PARM os2__RXMSQPSH_PARM
#define RXMSQPSH_PARM os2_RXMSQPSH_PARM
#define _RXMSQSIZ_PARM os2__RXMSQSIZ_PARM
#define RXMSQSIZ_PARM os2_RXMSQSIZ_PARM
#define _RXMSQNAM_PARM os2__RXMSQNAM_PARM
#define RXMSQNAM_PARM os2_RXMSQNAM_PARM
#define _RXSIOSAY_PARM os2__RXSIOSAY_PARM
#define RXSIOSAY_PARM os2_RXSIOSAY_PARM
#define _RXSIOTRC_PARM os2__RXSIOTRC_PARM
#define RXSIOTRC_PARM os2_RXSIOTRC_PARM
#define _RXSIOTRD_PARM os2__RXSIOTRD_PARM
#define RXSIOTRD_PARM os2_RXSIOTRD_PARM
#define _RXSIODR_PARM os2__RXSIODR_PARM
#define RXSIODTR_PARM os2_RXSIODTR_PARM
#define _RXHLT_FLAGS os2__RXHLT_FLAGS
#define RXHLT_FLAGS os2_RXHLT_FLAGS
#define _RXHLTTST_PARM os2__RXHLTTST_PARM
#define RXHLTTST_PARM os2_RXHLTTST_PARM
#define _RXTRC_FLAGS os2__RXTRC_FLAGS
#define RXTRC_FLAGS os2_RXTRC_FLAGS
#define _RXTRCTST_PARM os2__RXTRCTST_PARM
#define RXTRCTST_PARM os2_RXTRCTST_PARM
#define os2_WM_DBCSFIRST 0x00b0
#define os2_WM_DBCSLAST 0x00cf
#define os2_WC_FRAME ((PSZ)0xffff0001)
#define os2_WC_COMBOBOX ((PSZ)0xffff0002)
#define os2_WC_BUTTON ((PSZ)0xffff0003)
#define os2_WC_MENU ((PSZ)0xffff0004)
#define os2_WC_STATIC ((PSZ)0xffff0005)
#define os2_WC_ENTRYFIELD ((PSZ)0xffff0006)
#define os2_WC_LISTBOX ((PSZ)0xffff0007)
#define os2_WC_SCROLLBAR ((PSZ)0xffff0008)
#define os2_WC_TITLEBAR ((PSZ)0xffff0009)
#define os2_WC_MLE ((PSZ)0xffff000a)
#define os2_WC_APPSTAT ((PSZ)0xffff0010)
#define os2_WC_KBDSTAT ((PSZ)0xffff0011)
#define os2_WC_PECIC ((PSZ)0xffff0012)
#define os2_WC_DBE_KKPOPUP ((PSZ)0xffff0013)
#define os2_WC_SPINBUTTON ((PSZ)0xffff0020)
#define os2_WC_CONTAINER ((PSZ)0xffff0025)
#define os2_WC_SLIDER ((PSZ)0xffff0026)
#define os2_WC_VALUESET ((PSZ)0xffff0027)
#define os2_WC_NOTEBOOK ((PSZ)0xffff0028)
#define os2_WC_PENFIRST ((PSZ)0xffff0029)
#define os2_WC_PENLAST ((PSZ)0xffff002c)
#define os2_WC_MMPMFIRST ((PSZ)0xffff0040)
#define os2_WC_CIRCULARSLIDER ((PSZ)0xffff0041)
#define os2_WC_MMPMLAST ((PSZ)0xffff004f)
#define os2_WS_VISIBLE 0x80000000
#define os2_WS_DISABLED 0x40000000
#define os2_WS_CLIPCHILDREN 0x20000000
#define os2_WS_CLIPSIBLINGS 0x10000000
#define os2_WS_PARENTCLIP 0x08000000
#define os2_WS_SAVEBITS 0x04000000
#define os2_WS_SYNCPAINT 0x02000000
#define os2_WS_MINIMIZED 0x01000000
#define os2_WS_MAXIMIZED 0x00800000
#define os2_WS_ANIMATE 0x00400000
#define os2_WS_GROUP 0x00010000
#define os2_WS_TABSTOP 0x00020000
#define os2_WS_MULTISELECT 0x00040000
#define os2_CS_MOVENOTIFY 0x00000001
#define os2_CS_SIZEREDRAW 0x00000004
#define os2_CS_HITTEST 0x00000008
#define os2_CS_PUBLIC 0x00000010
#define os2_CS_FRAME 0x00000020
#define os2_CS_CLIPCHILDREN 0x20000000
#define os2_CS_CLIPSIBLINGS 0x10000000
#define os2_CS_PARENTCLIP 0x08000000
#define os2_CS_SAVEBITS 0x04000000
#define os2_CS_SYNCPAINT 0x02000000
#define os2_DT_LEFT 0x00000000
#define os2_DT_QUERYEXTENT 0x00000002
#define os2_DT_UNDERSCORE 0x00000010
#define os2_DT_STRIKEOUT 0x00000020
#define os2_DT_TEXTATTRS 0x00000040
#define os2_DT_EXTERNALLEADING 0x00000080
#define os2_DT_CENTER 0x00000100
#define os2_DT_RIGHT 0x00000200
#define os2_DT_TOP 0x00000000
#define os2_DT_VCENTER 0x00000400
#define os2_DT_BOTTOM 0x00000800
#define os2_DT_HALFTONE 0x00001000
#define os2_DT_MNEMONIC 0x00002000
#define os2_DT_WORDBREAK 0x00004000
#define os2_DT_ERASERECT 0x00008000
#define os2_SWP_SIZE 0x0001
#define os2_SWP_MOVE 0x0002
#define os2_SWP_ZORDER 0x0004
#define os2_SWP_SHOW 0x0008
#define os2_SWP_HIDE 0x0010
#define os2_SWP_NOREDRAW 0x0020
#define os2_SWP_NOADJUST 0x0040
#define os2_SWP_ACTIVATE 0x0080
#define os2_SWP_DEACTIVATE 0x0100
#define os2_SWP_EXTSTATECHANGE 0x0200
#define os2_SWP_MINIMIZE 0x0400
#define os2_SWP_MAXIMIZE 0x0800
#define os2_SWP_RESTORE 0x1000
#define os2_SWP_FOCUSACTIVATE 0x2000
#define os2_SWP_FOCUSDEACTIVATE 0x4000
#define os2_SWP_NOAUTOCLOSE 0x8000
#define os2_HWND_DESKTOP ((os2_HWND)1)
#define os2_HWND_OBJECT ((os2_HWND)2)
#define os2_HWND_TOP ((os2_HWND)3)
#define os2_HWND_BOTTOM ((os2_HWND)4)
#define os2_HWND_THREADCAPTURE ((os2_HWND)5)
#define HACCEL os2_HACCEL
#define HRGN os2_HRGN
#define PHRGN os2_PHRGN
#define MRESULT os2_MRESULT
#define PMRESULT os2_PMRESULT
#define MPARAM os2_MPARAM
#define PMPARAM os2_PMPARAM
#define HPOINTER os2_HPOINTER
#define HLIB os2_HLIB
#define PHLIB os2_PHLIB
#define COLOR os2_COLOR
#define PCOLOR os2_PCOLOR
#define HAB os2_HAB
#define PHAB os2_PHAB
#define HPS os2_HPS
#define PHPS os2_PHPS
#define HDC os2_HDC
#define PHDC os2_PHDC
#define HWND os2_HWND
#define PHWND os2_PHWND
#define HMQ os2_HMQ
#define HPAL os2_HPAL
#define PHPAL os2_PHPAL
#define HBITMAP os2_HBITMAP
#define PHBITMAP os2_PHBITMAP
#define ERRORID os2_ERRORID
#define PERRORID os2_PERRORID
#define PFNWP os2_PFNWP
#define os2_ERRORIDERROR (errid)		(os2_LOUSHORT (errid))
#define os2_ERRORIDSEV (errid)		(os2_HIUSHORT (errid))
#define os2_MAKEERRORID (sev,error)		(os2_ERRORID)( os2_MAKEULONG  ((error), (sev)))
#define _POINTL os2__POINTL
#define POINTL os2_POINTL
#define PPOINTL os2_PPOINTL
#define _POINTS os2__POINTS
#define POINTS os2_POINTS
#define PPOINTS os2_PPOINTS
#define _RECTL os2__RECTL
#define RECTL os2_RECTL
#define PRECTL os2_PRECTL
#define os2_WM_NULL 0x0000
#define os2_WM_CREATE 0x0001
#define os2_WM_DESTROY 0x0002
#define os2_WM_ENABLE 0x0004
#define os2_WM_SHOW 0x0005
#define os2_WM_MOVE 0x0006
#define os2_WM_SIZE 0x0007
#define os2_WM_ADJUSTWINDOWPOS 0x0008
#define os2_WM_CALCVALIDRECTS 0x0009
#define os2_WM_SETWINDOWPARAMS 0x000a
#define os2_WM_QUERYWINDOWPARAMS 0x000b
#define os2_WM_HITTEST 0x000c
#define os2_WM_ACTIVATE 0x000d
#define os2_WM_SETFOCUS 0x000f
#define os2_WM_SETSELECTION 0x0010
#define os2_WM_PPAINT 0x0011
#define os2_WM_PSETFOCUS 0x0012
#define os2_WM_PSYSCOLORCHANGE 0x0013
#define os2_WM_PSIZE 0x0014
#define os2_WM_PACTIVATE 0x0015
#define os2_WM_PCONTROL 0x0016
#define os2_WM_COMMAND 0x0020
#define os2_WM_SYSCOMMAND 0x0021
#define os2_WM_HELP 0x0022
#define os2_WM_PAINT 0x0023
#define os2_WM_TIMER 0x0024
#define os2_WM_SEM1 0x0025
#define os2_WM_SEM2 0x0026
#define os2_WM_SEM3 0x0027
#define os2_WM_SEM4 0x0028
#define os2_WM_CLOSE 0x0029
#define os2_WM_QUIT 0x002a
#define os2_WM_SYSCOLORCHANGE 0x002b
#define os2_WM_SYSVALUECHANGED 0x002d
#define os2_WM_APPTERMINATENOTIFY 0x002e
#define os2_WM_PRESPARAMCHANGED 0x002f
#define os2_WM_CONTROL 0x0030
#define os2_WM_VSCROLL 0x0031
#define os2_WM_HSCROLL 0x0032
#define os2_WM_INITMENU 0x0033
#define os2_WM_MENUSELECT 0x0034
#define os2_WM_MENUEND 0x0035
#define os2_WM_DRAWITEM 0x0036
#define os2_WM_MEASUREITEM 0x0037
#define os2_WM_CONTROLPOINTER 0x0038
#define os2_WM_QUERYDLGCODE 0x003a
#define os2_WM_INITDLG 0x003b
#define os2_WM_SUBSTITUTESTRING 0x003c
#define os2_WM_MATCHMNEMONIC 0x003d
#define os2_WM_SAVEAPPLICATION 0x003e
#define os2_WM_HELPBASE 0x0f00
#define os2_WM_HELPTOP 0x0fff
#define os2_WM_USER 0x1000
#define _QMSG os2__QMSG
#define QMSG os2_QMSG
#define PQMSG os2_PQMSG
#define _COMMANDMSG os2__COMMANDMSG
#define CMDMSG os2_CMDMSG
#define PCMDMSG os2_PCMDMSG
#define _MQINFO os2__MQINFO
#define MQINFO os2_MQINFO
#define PMQINFO os2_PMQINFO
#define os2_COMMANDMSG (pmsg)	((os2_PCMDMSG)((os2_PBYTE)pmsg + sizeof (os2_ULONG)))
#define _SWP os2__SWP
#define SWP os2_SWP
#define PSWP os2_PSWP
#define _ICONINFO os2__ICONINFO
#define ICONINFO os2_ICONINFO
#define PICONINFO os2_PICONINFO
#define os2_MPVOID ((os2_MPARAM)0)
#define os2_MPFROMP (x)		((os2_MPARAM)((os2_ULONG)(x)))
#define os2_MPFROMHWND (x)		((os2_MPARAM)(os2_HWND)(x))
#define os2_MPFROMCHAR (x)		((os2_MPARAM)(os2_ULONG)(os2_USHORT)(x))
#define os2_MPFROMSHORT (x)		((os2_MPARAM)(os2_ULONG)(os2_USHORT)(x))
#define os2_MPFROM2SHORT (x1,x2)	((os2_MPARAM) os2_MAKELONG  (x1, x2))
#define os2_MPFROMSH2CH (s,c1,c2)	((os2_MPARAM) os2_MAKELONG  (s,  os2_MAKESHORT  (c1, c2)))
#define os2_MPFROMLONG (x)		((os2_MPARAM)(os2_ULONG)(x))
#define os2_PVOIDFROMMP (mp)		((os2_PVOID)(mp))
#define os2_HWNDFROMMP (mp)		((os2_HWND)(mp))
#define os2_CHAR1FROMMP (mp)		((os2_UCHAR)(os2_ULONG)(mp))
#define os2_CHAR2FROMMP (mp)		((os2_UCHAR)((os2_ULONG)mp >> 8))
#define os2_CHAR3FROMMP (mp)		((os2_UCHAR)((os2_ULONG)mp >> 16))
#define os2_CHAR4FROMMP (mp)		((os2_UCHAR)((os2_ULONG)mp >> 24))
#define os2_SHORT1FROMMP (mp)	((os2_USHORT)(os2_ULONG)(mp))
#define os2_SHORT2FROMMP (mp)	((os2_USHORT)((os2_ULONG)mp >> 16))
#define os2_LONGFROMMP (mp)		((os2_ULONG)(mp))
#define os2_MRFROMP (x)		((os2_MRESULT)(os2_PVOID)(x))
#define os2_MRFROMSHORT (x)		((os2_MRESULT)(os2_ULONG)(os2_USHORT)(x))
#define os2_MRFROM2SHORT (x1,x2)	((os2_MRESULT) os2_MAKELONG  (x1, x2))
#define os2_MRFROMLONG (x)		((os2_MRESULT)(os2_ULONG)(x))
#define os2_PVOIDFROMMR (mr)		((os2_VOID *)(mr))
#define os2_SHORT1FROMMR (mr)	((os2_USHORT)((os2_ULONG)mr))
#define os2_SHORT2FROMMR (mr)	((os2_USHORT)((os2_ULONG)mr >> 16))
#define os2_LONGFROMMR (mr)		((os2_ULONG)(mr))
#define _FRAMECDATA os2__FRAMECDATA
#define FRAMECDATA os2_FRAMECDATA
#define PFRAMECDATA os2_PFRAMECDATA
#define os2_WM_FLASHWINDOW 0x0040
#define os2_WM_FORMATFRAME 0x0041
#define os2_WM_UPDATEFRAME 0x0042
#define os2_WM_FOCUSCHANGE 0x0043
#define os2_WM_SETBORDERSIZE 0x0044
#define os2_WM_TRACKFRAME 0x0045
#define os2_WM_MINMAXFRAME 0x0046
#define os2_WM_SETICON 0x0047
#define os2_WM_QUERYICON 0x0048
#define os2_WM_SETACCELTABLE 0x0049
#define os2_WM_QUERYACCELTABLE 0x004a
#define os2_WM_TRANSLATEACCEL 0x004b
#define os2_WM_QUERYTRACKINFO 0x004c
#define os2_WM_QUERYBORDERSIZE 0x004d
#define os2_WM_NEXTMENU 0x004e
#define os2_WM_ERASEBACKGROUND 0x004f
#define os2_WM_QUERYFRAMEINFO 0x0050
#define os2_WM_QUERYFOCUSCHAIN 0x0051
#define os2_WM_OWNERPOSCHANGE 0x0052
#define os2_WM_CALCFRAMERECT 0x0053
#define os2_WM_WINDOWPOSCHANGED 0x0055
#define os2_WM_ADJUSTFRAMEPOS 0x0056
#define os2_WM_QUERYFRAMECTLCOUNT 0x0059
#define os2_WM_QUERYHELPINFO 0x005b
#define os2_WM_SETHELPINFO 0x005c
#define os2_WM_ERROR 0x005d
#define os2_WM_REALIZEPALETTE 0x005e
#define HSAVEWP os2_HSAVEWP
#define _QVERSDATA os2__QVERSDATA
#define QVERSDATA os2_QVERSDATA
#define PQVERSDATA os2_PQVERSDATA
#define os2_WM_QUERYCONVERTPOS 0x00b0
#define _CLASSINFO os2__CLASSINFO
#define CLASSINFO os2_CLASSINFO
#define PCLASSINFO os2_PCLASSINFO
#define _CREATESTRUCT os2__CREATESTRUCT
#define CREATESTRUCT os2_CREATESTRUCT
#define PCREATESTRUCT os2_PCREATESTRUCT
#define HENUM os2_HENUM
#define _ACCEL os2__ACCEL
#define ACCEL os2_ACCEL
#define PACCEL os2_PACCEL
#define _ACCELTABLE os2__ACCELTABLE
#define ACCELTABLE os2_ACCELTABLE
#define PACCELTABLE os2_PACCELTABLE
#define HATOMTBL os2_HATOMTBL
#define ATOM os2_ATOM
#define os2_MAKEINTATOM (x)		((PCH) os2_MAKEULONG  (x, 0xffff))
#define _BTNCDATA os2__BTNCDATA
#define BTNCDATA os2_BTNCDATA
#define PBTNCDATA os2_PBTNCDATA
#define _USERBUTTON os2__USERBUTTON
#define USERBUTTON os2_USERBUTTON
#define PUSERBUTTON os2_PUSERBUTTON
#define os2_WM_RENDERFMT 0x0060
#define os2_WM_RENDERALLFMTS 0x0061
#define os2_WM_DESTROYCLIPBOARD 0x0062
#define os2_WM_PAINTCLIPBOARD 0x0063
#define os2_WM_SIZECLIPBOARD 0x0064
#define os2_WM_HSCROLLCLIPBOARD 0x0065
#define os2_WM_VSCROLLCLIPBOARD 0x0066
#define os2_WM_DRAWCLIPBOARD 0x0067
#define _CPTEXT os2__CPTEXT
#define CPTEXT os2_CPTEXT
#define PCPTEXT os2_PCPTEXT
#define _MFP os2__MFP
#define MFP os2_MFP
#define PMFP os2_PMFP
#define os2_WM_DDE_FIRST 0x00a0
#define os2_WM_DDE_INITIATE 0x00a0
#define os2_WM_DDE_REQUEST 0x00a1
#define os2_WM_DDE_ACK 0x00a2
#define os2_WM_DDE_DATA 0x00a3
#define os2_WM_DDE_ADVISE 0x00a4
#define os2_WM_DDE_UNADVISE 0x00a5
#define os2_WM_DDE_POKE 0x00a6
#define os2_WM_DDE_EXECUTE 0x00a7
#define os2_WM_DDE_TERMINATE 0x00a8
#define os2_WM_DDE_INITIATEACK 0x00a9
#define os2_WM_DDE_LAST 0x00af
#define _CONVCONTEXT os2__CONVCONTEXT
#define CONVCONTEXT os2_CONVCONTEXT
#define PCONVCONTEXT os2_PCONVCONTEXT
#define _DDEINIT os2__DDEINIT
#define DDEINIT os2_DDEINIT
#define PDDEINIT os2_PDDEINIT
#define _DDESTRUCT os2__DDESTRUCT
#define DDESTRUCT os2_DDESTRUCT
#define PDDESTRUCT os2_PDDESTRUCT
#define os2_DDES_PABDATA (pddes) \
    (((os2_PBYTE)pddes) + ((PDDESTRUCT)pddes)->offabData)
#define os2_DDEI_PCONVCONTEXT (pddei) \
    ((PCONVCONTEXT)((os2_PBYTE)pddei + pddei->offConvContext))
#define _CURSORINFO os2__CURSORINFO
#define CURSORINFO os2_CURSORINFO
#define PCURSORINFO os2_PCURSORINFO
#define _DESKTOP os2__DESKTOP
#define DESKTOP os2_DESKTOP
#define PDESKTOP os2_PDESKTOP
#define os2_MB_OK 0x0000
#define os2_MB_OKCANCEL 0x0001
#define os2_MB_RETRYCANCEL 0x0002
#define os2_MB_ABORTRETRYIGNORE 0x0003
#define os2_MB_YESNO 0x0004
#define os2_MB_YESNOCANCEL 0x0005
#define os2_MB_CANCEL 0x0006
#define os2_MB_ENTER 0x0007
#define os2_MB_ENTERCANCEL 0x0008
#define os2_MB_NOICON 0x0000
#define os2_MB_CUANOTIFICATION 0x0000
#define os2_MB_ICONQUESTION 0x0010
#define os2_MB_ICONEXCLAMATION 0x0020
#define os2_MB_CUAWARNING 0x0020
#define os2_MB_ICONASTERISK 0x0030
#define os2_MB_ICONHAND 0x0040
#define os2_MB_CUACRITICAL 0x0040
#define os2_MB_QUERY os2_MB_ICONQUESTION
#define os2_MB_WARNING os2_MB_CUAWARNING
#define os2_MB_INFORMATION os2_MB_ICONASTERISK
#define os2_MB_CRITICAL os2_MB_CUACRITICAL
#define os2_MB_ERROR os2_MB_CRITICAL
#define os2_MB_CUSTOMICON 0x0080
#define os2_MB_DEFBUTTON1 0x0000
#define os2_MB_DEFBUTTON2 0x0100
#define os2_MB_DEFBUTTON3 0x0200
#define os2_MB_APPLMODAL 0x0000
#define os2_MB_SYSTEMMODAL 0x1000
#define os2_MB_HELP 0x2000
#define os2_MB_MOVEABLE 0x4000
#define os2_MB_NONMODAL 0x8000
#define _MB2D os2__MB2D
#define MB2D os2_MB2D
#define PMB2D os2_PMB2D
#define _MB2INFO os2__MB2INFO
#define MB2INFO os2_MB2INFO
#define PMB2INFO os2_PMB2INFO
#define os2_WinCheckButton (hwndDlg,id,usCheckState) \
    ((os2_ULONG)WinSendDlgItemMsg (hwndDlg, id, BM_SETCHECK, \
			       os2_MPFROMSHORT (usCheckState), (os2_MPARAM)NULL))
#define os2_WinIsControlEnabled (hwndDlg,id) \
    ((os2_BOOL)WinIsWindowEnabled (WinWindowFromID (hwndDlg, id)))
#define os2_WinQueryButtonCheckstate (hwndDlg,id) \
    ((os2_ULONG)WinSendDlgItemMsg (hwndDlg, id, BM_QUERYCHECK, \
			       (os2_MPARAM)NULL, (os2_MPARAM)NULL))
#define _DLGTITEM os2__DLGTITEM
#define DLGTITEM os2_DLGTITEM
#define PDLGTITEM os2_PDLGTITEM
#define _DLGTEMPLATE os2__DLGTEMPLATE
#define DLGTEMPLATE os2_DLGTEMPLATE
#define PDLGTEMPLATE os2_PDLGTEMPLATE
#define _COMBOCDATA os2__COMBOCDATA
#define COMBOCDATA os2_COMBOCDATA
#define PCOMBOCDATA os2_PCOMBOCDATA
#define _ENTRYFDATA os2__ENTRYFDATA
#define ENTRYFDATA os2_ENTRYFDATA
#define PENTRYFDATA os2_PENTRYFDATA
#define _ERRINFO os2__ERRINFO
#define ERRINFO os2_ERRINFO
#define PERRINFO os2_PERRINFO
#define _SMHSTRUCT os2__SMHSTRUCT
#define SMHSTRUCT os2_SMHSTRUCT
#define PSMHSTRUCT os2_PSMHSTRUCT
#define os2_WM_MOUSEFIRST 0x0070
#define os2_WM_MOUSEMOVE 0x0070
#define os2_WM_BUTTONCLICKFIRST 0x0071
#define os2_WM_BUTTON1DOWN 0x0071
#define os2_WM_BUTTON1UP 0x0072
#define os2_WM_BUTTON1DBLCLK 0x0073
#define os2_WM_BUTTON2DOWN 0x0074
#define os2_WM_BUTTON2UP 0x0075
#define os2_WM_BUTTON2DBLCLK 0x0076
#define os2_WM_BUTTON3DOWN 0x0077
#define os2_WM_BUTTON3UP 0x0078
#define os2_WM_BUTTON3DBLCLK 0x0079
#define os2_WM_BUTTONCLICKLAST 0x0079
#define os2_WM_MOUSELAST 0x0079
#define os2_WM_CHAR 0x007a
#define os2_WM_VIOCHAR 0x007b
#define os2_WM_JOURNALNOTIFY 0x007c
#define os2_WM_MOUSEMAP 0x007d
#define os2_WM_VRNDISABLED 0x007e
#define os2_WM_VRNENABLED 0x007f
#define os2_WM_EXTMOUSEFIRST 0x0410
#define os2_WM_CHORD 0x0410
#define os2_WM_BUTTON1MOTIONSTART 0x0411
#define os2_WM_BUTTON1MOTIONEND 0x0412
#define os2_WM_BUTTON1CLICK 0x0413
#define os2_WM_BUTTON2MOTIONSTART 0x0414
#define os2_WM_BUTTON2MOTIONEND 0x0415
#define os2_WM_BUTTON2CLICK 0x0416
#define os2_WM_BUTTON3MOTIONSTART 0x0417
#define os2_WM_BUTTON3MOTIONEND 0x0418
#define os2_WM_BUTTON3CLICK 0x0419
#define os2_WM_EXTMOUSELAST 0x0419
#define os2_WM_MOUSETRANSLATEFIRST 0x0420
#define os2_WM_BEGINDRAG 0x0420
#define os2_WM_ENDDRAG 0x0421
#define os2_WM_SINGLESELECT 0x0422
#define os2_WM_OPEN 0x0423
#define os2_WM_CONTEXTMENU 0x0424
#define os2_WM_CONTEXTHELP 0x0425
#define os2_WM_TEXTEDIT 0x0426
#define os2_WM_BEGINSELECT 0x0427
#define os2_WM_ENDSELECT 0x0428
#define os2_WM_MOUSETRANSLATELAST 0x0428
#define os2_WM_PICKUP 0x0429
#define os2_WM_PENFIRST 0x0481
#define os2_WM_PENLAST 0x049f
#define os2_WM_MMPMFIRST 0x0500
#define os2_WM_MMPMLAST 0x05ff
#define os2_WM_BIDI_FIRST 0x0bd0
#define os2_WM_BIDI_LAST 0x0bff
#define _CHARMSG os2__CHARMSG
#define CHRMSG os2_CHRMSG
#define PCHRMSG os2_PCHRMSG
#define _MOUSEMSG os2__MOUSEMSG
#define MSEMSG os2_MSEMSG
#define PMSEMSG os2_PMSEMSG
#define os2_CHARMSG (pmsg)		((os2_PCHRMSG)((os2_PBYTE)pmsg + sizeof (os2_ULONG)))
#define os2_MOUSEMSG (pmsg)		((os2_PMSEMSG)((os2_PBYTE)pmsg + sizeof (os2_ULONG)))
#define _LBOXINFO os2__LBOXINFO
#define LBOXINFO os2_LBOXINFO
#define PLBOXINFO os2_PLBOXINFO
#define os2_WinDeleteLboxItem (hwndLbox,index) \
    ((os2_LONG)WinSendMsg (hwndLbox, LM_DELETEITEM, os2_MPFROMLONG (index), \
		       (os2_MPARAM)NULL))
#define os2_WinInsertLboxItem (hwndLbox,index,psz) \
    ((os2_LONG)WinSendMsg (hwndLbox, LM_INSERTITEM, os2_MPFROMLONG(index), \
		       os2_MPFROMP (psz)))
#define os2_WinQueryLboxCount (hwndLbox) \
    ((os2_LONG)WinSendMsg (hwndLbox, LM_QUERYITEMCOUNT, (os2_MPARAM)NULL, \
		       (os2_MPARAM)NULL))
#define os2_WinQueryLboxItemText (hwndLbox,index,psz,cchMax) \
    ((os2_LONG)WinSendMsg (hwndLbox, LM_QUERYITEMTEXT, \
		       os2_MPFROM2SHORT((index), (cchMax)), os2_MPFROMP (psz)))
#define os2_WinQueryLboxItemTextLength (hwndLbox,index) \
    ((os2_SHORT)WinSendMsg (hwndLbox, LM_QUERYITEMTEXTLENGTH, \
			os2_MPFROMSHORT (index), (os2_MPARAM)NULL))
#define os2_WinQueryLboxSelectedItem (hwndLbox) \
    ((os2_LONG)WinSendMsg (hwndLbox, LM_QUERYSELECTION, os2_MPFROMLONG (LIT_FIRST), \
		       (os2_MPARAM)NULL))
#define os2_WinSetLboxItemText (hwndLbox,index,psz) \
    ((os2_BOOL)WinSendMsg (hwndLbox, LM_SETITEMTEXT, \
		       os2_MPFROMLONG (index), os2_MPFROMP (psz)))
#define os2_MIA_NODISMISS 0x0020
#define os2_MIA_FRAMED 0x1000
#define os2_MIA_CHECKED 0x2000
#define os2_MIA_DISABLED 0x4000
#define os2_MIA_HILITED 0x8000
#define _MENUITEM os2__MENUITEM
#define MENUITEM os2_MENUITEM
#define PMENUITEM os2_PMENUITEM
#define _mti os2__mti
#define MTI os2_MTI
#define _mt os2__mt
#define MT os2_MT
#define LPMT os2_LPMT
#define _OWNERITEM os2__OWNERITEM
#define OWNERITEM os2_OWNERITEM
#define POWNERITEM os2_POWNERITEM
#define os2_WinCheckMenuItem (hwndMenu,id,fcheck) \
    ((os2_BOOL)WinSendMsg (hwndMenu, MM_SETITEMATTR, \
		       os2_MPFROM2SHORT (id, TRUE), \
		       os2_MPFROM2SHORT (os2_MIA_CHECKED, \
				     ((os2_USHORT)(fcheck) ? os2_MIA_CHECKED : 0))))
#define os2_WinEnableMenuItem (hwndMenu,id,fEnable) \
    ((os2_BOOL)WinSendMsg (hwndMenu, MM_SETITEMATTR, os2_MPFROM2SHORT (id, TRUE), \
		       os2_MPFROM2SHORT (os2_MIA_DISABLED, \
				     ((os2_USHORT)(fEnable) ? 0 : os2_MIA_DISABLED))))
#define os2_WinIsMenuItemChecked (hwndMenu,id) \
    ((os2_BOOL)WinSendMsg (hwndMenu, MM_QUERYITEMATTR, \
		       os2_MPFROM2SHORT (id, TRUE), \
		       os2_MPFROMLONG (os2_MIA_CHECKED)))
#define os2_WinIsMenuItemEnabled (hwndMenu,id)  \
    (!(os2_BOOL)WinSendMsg (hwndMenu, MM_QUERYITEMATTR, \
			os2_MPFROM2SHORT (id, TRUE), \
			os2_MPFROMLONG (os2_MIA_DISABLED)))
#define os2_WinIsMenuItemValid (hwndMenu,id) \
    ((os2_BOOL)WinSendMsg (hwndMenu, MM_ISITEMVALID, \
		       os2_MPFROM2SHORT (id, TRUE), os2_MPFROMLONG (FALSE)))
#define os2_WinSetMenuItemText (hwndMenu,id,psz) \
    ((os2_BOOL)WinSendMsg (hwndMenu, MM_SETITEMTEXT, \
		       os2_MPFROMLONG (id), os2_MPFROMP (psz)))
#define os2_QS_KEY 0x0001
#define os2_QS_MOUSEBUTTON 0x0002
#define os2_QS_MOUSEMOVE 0x0004
#define os2_QS_MOUSE 0x0006
#define os2_QS_TIMER 0x0008
#define os2_QS_PAINT 0x0010
#define os2_QS_POSTMSG 0x0020
#define os2_QS_SEM1 0x0040
#define os2_QS_SEM2 0x0080
#define os2_QS_SEM3 0x0100
#define os2_QS_SEM4 0x0200
#define os2_QS_SENDMSG 0x0400
#define os2_QS_MSGINPUT 0x0800
#define _WNDPARAMS os2__WNDPARAMS
#define WNDPARAMS os2_WNDPARAMS
#define PWNDPARAMS os2_PWNDPARAMS
#define _POINTERINFO os2__POINTERINFO
#define POINTERINFO os2_POINTERINFO
#define PPOINTERINFO os2_PPOINTERINFO
#define _SBCDATA os2__SBCDATA
#define SBCDATA os2_SBCDATA
#define PSBCDATA os2_PSBCDATA
#define os2_WM_MSGBOXINIT 0x010e
#define os2_WM_MSGBOXDISMISS 0x010f
#define os2_SV_SWAPBUTTON 0
#define os2_SV_DBLCLKTIME 1
#define os2_SV_CXDBLCLK 2
#define os2_SV_CYDBLCLK 3
#define os2_SV_CXSIZEBORDER 4
#define os2_SV_CYSIZEBORDER 5
#define os2_SV_ALARM 6
#define os2_SV_CURSORRATE 9
#define os2_SV_FIRSTSCROLLRATE 10
#define os2_SV_SCROLLRATE 11
#define os2_SV_NUMBEREDLISTS 12
#define os2_SV_WARNINGFREQ 13
#define os2_SV_NOTEFREQ 14
#define os2_SV_ERRORFREQ 15
#define os2_SV_WARNINGDURATION 16
#define os2_SV_NOTEDURATION 17
#define os2_SV_ERRORDURATION 18
#define os2_SV_CXSCREEN 20
#define os2_SV_CYSCREEN 21
#define os2_SV_CXVSCROLL 22
#define os2_SV_CYHSCROLL 23
#define os2_SV_CYVSCROLLARROW 24
#define os2_SV_CXHSCROLLARROW 25
#define os2_SV_CXBORDER 26
#define os2_SV_CYBORDER 27
#define os2_SV_CXDLGFRAME 28
#define os2_SV_CYDLGFRAME 29
#define os2_SV_CYTITLEBAR 30
#define os2_SV_CYVSLIDER 31
#define os2_SV_CXHSLIDER 32
#define os2_SV_CXMINMAXBUTTON 33
#define os2_SV_CYMINMAXBUTTON 34
#define os2_SV_CYMENU 35
#define os2_SV_CXFULLSCREEN 36
#define os2_SV_CYFULLSCREEN 37
#define os2_SV_CXICON 38
#define os2_SV_CYICON 39
#define os2_SV_CXPOINTER 40
#define os2_SV_CYPOINTER 41
#define os2_SV_DEBUG 42
#define os2_SV_CMOUSEBUTTONS 43
#define os2_SV_CPOINTERBUTTONS 43
#define os2_SV_POINTERLEVEL 44
#define os2_SV_CURSORLEVEL 45
#define os2_SV_TRACKRECTLEVEL 46
#define os2_SV_CTIMERS 47
#define os2_SV_MOUSEPRESENT 48
#define os2_SV_CXBYTEALIGN 49
#define os2_SV_CXALIGN 49
#define os2_SV_CYBYTEALIGN 50
#define os2_SV_CYALIGN 50
#define os2_SV_DESKTOPWORKAREAYTOP 51
#define os2_SV_DESKTOPWORKAREAYBOTTOM 52
#define os2_SV_DESKTOPWORKAREAXRIGHT 53
#define os2_SV_DESKTOPWORKAREAXLEFT 54
#define os2_SV_NOTRESERVED 56
#define os2_SV_EXTRAKEYBEEP 57
#define os2_SV_SETLIGHTS 58
#define os2_SV_INSERTMODE 59
#define os2_SV_MENUROLLDOWNDELAY 64
#define os2_SV_MENUROLLUPDELAY 65
#define os2_SV_ALTMNEMONIC 66
#define os2_SV_TASKLISTMOUSEACCESS 67
#define os2_SV_CXICONTEXTWIDTH 68
#define os2_SV_CICONTEXTLINES 69
#define os2_SV_CHORDTIME 70
#define os2_SV_CXCHORD 71
#define os2_SV_CYCHORD 72
#define os2_SV_CXMOTIONSTART 73
#define os2_SV_CYMOTIONSTART 74
#define os2_SV_BEGINDRAG 75
#define os2_SV_ENDDRAG 76
#define os2_SV_SINGLESELECT 77
#define os2_SV_OPEN 78
#define os2_SV_CONTEXTMENU 79
#define os2_SV_CONTEXTHELP 80
#define os2_SV_TEXTEDIT 81
#define os2_SV_BEGINSELECT 82
#define os2_SV_ENDSELECT 83
#define os2_SV_BEGINDRAGKB 84
#define os2_SV_ENDDRAGKB 85
#define os2_SV_SELECTKB 86
#define os2_SV_OPENKB 87
#define os2_SV_CONTEXTMENUKB 88
#define os2_SV_CONTEXTHELPKB 89
#define os2_SV_TEXTEDITKB 90
#define os2_SV_BEGINSELECTKB 91
#define os2_SV_ENDSELECTKB 92
#define os2_SV_ANIMATION 93
#define os2_SV_ANIMATIONSPEED 94
#define os2_SV_MONOICONS 95
#define os2_SV_KBDALTERED 96
#define os2_SV_PRINTSCREEN 97
#define os2_SV_LOCKSTARTINPUT 98
#define os2_SV_DYNAMICDRAG 99
#define os2_SV_CSYSVALUES 100
#define os2_WM_CTLCOLORCHANGE 0x0129
#define os2_WM_QUERYCTLTYPE 0x0130 /*0x012a?*/
#define _CTLCOLOR os2__CTLCOLOR
#define CTLCOLOR os2_CTLCOLOR
#define PCTLCOLOR os2_PCTLCOLOR
#define _PARAM os2__PARAM
#define PARAM os2_PARAM
#define NPPARAM os2_NPPARAM
#define PPARAM os2_PPARAM
#define _PRESPARAMS os2__PRESPARAMS
#define PRESPARAMS os2_PRESPARAMS
#define NPPRESPARAMS os2_NPPRESPARAMS
#define PPRESPARAMS os2_PPRESPARAMS
#define _TRACKINFO os2__TRACKINFO
#define TRACKINFO os2_TRACKINFO
#define PTRACKINFO os2_PTRACKINFO
#define IPT os2_IPT
#define PIPT os2_PIPT
#define PIX os2_PIX
#define LINE os2_LINE
#define _FORMATRECT os2__FORMATRECT
#define MLEFORMATRECT os2_MLEFORMATRECT
#define PFORMATRECT os2_PFORMATRECT
#define _MLECTLDATA os2__MLECTLDATA
#define MLECTLDATA os2_MLECTLDATA
#define PMLECTLDATA os2_PMLECTLDATA
#define _MLEOVERFLOW os2__MLEOVERFLOW
#define MLEOVERFLOW os2_MLEOVERFLOW
#define POVERFLOW os2_POVERFLOW
#define _MLEMARGSTRUCT os2__MLEMARGSTRUCT
#define MLEMARGSTRUCT os2_MLEMARGSTRUCT
#define PMARGSTRUCT os2_PMARGSTRUCT
#define _SEARCH os2__SEARCH
#define MLE_SEARCHDATA os2_MLE_SEARCHDATA
#define PMLE_SEARCHDATA os2_PMLE_SEARCHDATA
#define os2_TA_NORMAL_HORIZ 0x0001
#define os2_TA_LEFT 0x0002
#define os2_TA_CENTER 0x0003
#define os2_TA_RIGHT 0x0004
#define os2_TA_STANDARD_HORIZ 0x0005
#define os2_TA_NORMAL_VERT 0x0100
#define os2_TA_TOP 0x0200
#define os2_TA_HALF 0x0300
#define os2_TA_BASE 0x0400
#define os2_TA_BOTTOM 0x0500
#define os2_TA_STANDARD_VERT 0x0600
#define os2_RGN_ERROR 0
#define os2_RGN_NULL 1
#define os2_RGN_RECT 2
#define os2_RGN_COMPLEX 3
#define PBUNDLE os2_PBUNDLE
#define FIXED os2_FIXED
#define PFIXED os2_PFIXED
#define HMF os2_HMF
#define PHMF os2_PHMF
#define _SIZEL os2__SIZEL
#define SIZEL os2_SIZEL
#define PSIZEL os2_PSIZEL
#define _RGNRECT os2__RGNRECT
#define RGNRECT os2_RGNRECT
#define PRGNRECT os2_PRGNRECT
#define _MATRIXLF os2__MATRIXLF
#define MATRIXLF os2_MATRIXLF
#define PMATRIXLF os2_PMATRIXLF
#define _ARCPARAMS os2__ARCPARAMS
#define ARCPARAMS os2_ARCPARAMS
#define PARCPARAMS os2_PARCPARAMS
#define _SIZEF os2__SIZEF
#define SIZEF os2_SIZEF
#define PSIZEF os2_PSIZEF
#define _POLYGON os2__POLYGON
#define POLYGON os2_POLYGON
#define PPOLYGON os2_PPOLYGON
#define _POLYSET os2__POLYSET
#define POLYSET os2_POLYSET
#define PPOLYSET os2_PPOLYSET
#define _GRADIENTL os2__GRADIENTL
#define GRADIENTL os2_GRADIENTL
#define PGRADIENTL os2_PGRADIENTL
#define _KERNINGPAIRS os2__KERNINGPAIRS
#define KERNINGPAIRS os2_KERNINGPAIRS
#define PKERNINGPAIRS os2_PKERNINGPAIRS
#define _FACENAMEDESC os2__FACENAMEDESC
#define FACENAMEDESC os2_FACENAMEDESC
#define PFACENAMEDESC os2_PFACENAMEDESC
#define FFDESCS os2_FFDESCS
#define PFFDESCS os2_PFFDESCS
#define _FFDESCS2 os2__FFDESCS2
#define FFDESCS2 os2_FFDESCS2
#define PFFDESCS2 os2_PFFDESCS2
#define _LINEBUNDLE os2__LINEBUNDLE
#define LINEBUNDLE os2_LINEBUNDLE
#define PLINEBUNDLE os2_PLINEBUNDLE
#define _CHARBUNDLE os2__CHARBUNDLE
#define CHARBUNDLE os2_CHARBUNDLE
#define PCHARBUNDLE os2_PCHARBUNDLE
#define _MARKERBUNDLE os2__MARKERBUNDLE
#define MARKERBUNDLE os2_MARKERBUNDLE
#define PMARKERBUNDLE os2_PMARKERBUNDLE
#define _AREABUNDLE os2__AREABUNDLE
#define AREABUNDLE os2_AREABUNDLE
#define PAREABUNDLE os2_PAREABUNDLE
#define _IMAGEBUNDLE os2__IMAGEBUNDLE
#define IMAGEBUNDLE os2_IMAGEBUNDLE
#define PIMAGEBUNDLE os2_PIMAGEBUNDLE
#define os2_MAKEFIXED (i,f)  os2_MAKELONG (f,i)
#define os2_FIXEDFRAC (fx)  (os2_LOUSHORT(fx))
#define os2_FIXEDINT (fx)   ((os2_SHORT)HIUSHORT(fx))
#define _RGB os2__RGB
#define RGB os2_RGB
#define _RGB2 os2__RGB2
#define RGB2 os2_RGB2
#define PRGB2 os2_PRGB2
#define _BITMAPINFOHEADER os2__BITMAPINFOHEADER
#define BITMAPINFOHEADER os2_BITMAPINFOHEADER
#define PBITMAPINFOHEADER os2_PBITMAPINFOHEADER
#define _BITMAPINFO os2__BITMAPINFO
#define BITMAPINFO os2_BITMAPINFO
#define PBITMAPINFO os2_PBITMAPINFO
#define _BITMAPINFO2 os2__BITMAPINFO2
#define BITMAPINFO2 os2_BITMAPINFO2
#define PBITMAPINFO2 os2_PBITMAPINFO2
#define _BITMAPINFOHEADER2 os2__BITMAPINFOHEADER2
#define BITMAPINFOHEADER2 os2_BITMAPINFOHEADER2
#define PBITMAPINFOHEADER2 os2_PBITMAPINFOHEADER2
#define _BITMAPFILEHEADER os2__BITMAPFILEHEADER
#define BITMAPFILEHEADER os2_BITMAPFILEHEADER
#define PBITMAPFILEHEADER os2_PBITMAPFILEHEADER
#define _BITMAPARRAYFILEHEADER os2__BITMAPARRAYFILEHEADER
#define BITMAPARRAYFILEHEADER os2_BITMAPARRAYFILEHEADER
#define PBITMAPARRAYFILEHEADER os2_PBITMAPARRAYFILEHEADER
#define _BITMAPFILEHEADER2 os2__BITMAPFILEHEADER2
#define BITMAPFILEHEADER2 os2_BITMAPFILEHEADER2
#define PBITMAPFILEHEADER2 os2_PBITMAPFILEHEADER2
#define _BITMAPARRAYFILEHEADER2 os2__BITMAPARRAYFILEHEADER2
#define BITMAPARRAYFILEHEADER2 os2_BITMAPARRAYFILEHEADER2
#define PBITMAPARRAYFILEHEADER2 os2_PBITMAPARRAYFILEHEADER2
#define os2_DM_ERROR 0
#define os2_DM_DRAW 1
#define os2_DM_RETAIN 2
#define os2_DM_DRAWANDRETAIN 3
#define PDEVOPENDATA os2_PDEVOPENDATA
#define _DRIVDATA os2__DRIVDATA
#define DRIVDATA os2_DRIVDATA
#define PDRIVDATA os2_PDRIVDATA
#define _DEVOPENSTRUC os2__DEVOPENSTRUC
#define DEVOPENSTRUC os2_DEVOPENSTRUC
#define PDEVOPENSTRUC os2_PDEVOPENSTRUC
#define _ESCMODE os2__ESCMODE
#define ESCMODE os2_ESCMODE
#define PESCMODE os2_PESCMODE
#define _VIOSIZECOUNT os2__VIOSIZECOUNT
#define VIOSIZECOUNT os2_VIOSIZECOUNT
#define PVIOSIZECOUNT os2_PVIOSIZECOUNT
#define _VIOFONTCELLSIZE os2__VIOFONTCELLSIZE
#define VIOFONTCELLSIZE os2_VIOFONTCELLSIZE
#define PVIOFONTCELLSIZE os2_PVIOFONTCELLSIZE
#define _SFACTORS os2__SFACTORS
#define SFACTORS os2_SFACTORS
#define PSFACTORS os2_PSFACTORS
#define _BANDRECT os2__BANDRECT
#define BANDRECT os2_BANDRECT
#define PBANDRECT os2_PBANDRECT
#define _HCINFO os2__HCINFO
#define HCINFO os2_HCINFO
#define PHCINFO os2_PHCINFO
#define HSWITCH os2_HSWITCH
#define PHSWITCH os2_PHSWITCH
#define HPROGRAM os2_HPROGRAM
#define PHPROGRAM os2_PHPROGRAM
#define HINI os2_HINI
#define PHINI os2_PHINI
#define HAPP os2_HAPP
#define _PRFPROFILE os2__PRFPROFILE
#define PRFPROFILE os2_PRFPROFILE
#define PPRFPROFILE os2_PPRFPROFILE
#define PROGCATEGORY os2_PROGCATEGORY
#define PPROGCATEGORY os2_PPROGCATEGORY
#define _HPROGARRAY os2__HPROGARRAY
#define HPROGARRAY os2_HPROGARRAY
#define PHPROGARRAY os2_PHPROGARRAY
#define _PROGTYPE os2__PROGTYPE
#define PROGTYPE os2_PROGTYPE
#define PPROGTYPE os2_PPROGTYPE
#define _PROGTITLE os2__PROGTITLE
#define PROGTITLE os2_PROGTITLE
#define PPROGTITLE os2_PPROGTITLE
#define _PROGDETAILS os2__PROGDETAILS
#define PROGDETAILS os2_PROGDETAILS
#define PPROGDETAILS os2_PPROGDETAILS
#define _SWCNTRL os2__SWCNTRL
#define SWCNTRL os2_SWCNTRL
#define PSWCNTRL os2_PSWCNTRL
#define _SWENTRY os2__SWENTRY
#define SWENTRY os2_SWENTRY
#define PSWENTRY os2_PSWENTRY
#define _SWBLOCK os2__SWBLOCK
#define SWBLOCK os2_SWBLOCK
#define PSWBLOCK os2_PSWBLOCK
#define os2_FDM_FILTER (os2_WM_USER+40)
#define os2_FDM_VALIDATE (os2_WM_USER+41)
#define os2_FDM_ERROR (os2_WM_USER+42)
#define APSZ os2_APSZ
#define PAPSZ os2_PAPSZ
#define _FILEDLG os2__FILEDLG
#define FILEDLG os2_FILEDLG
#define PFILEDLG os2_PFILEDLG
#define os2_FNTM_FACENAMECHANGED (os2_WM_USER+50)
#define os2_FNTM_POINTSIZECHANGED (os2_WM_USER+51)
#define os2_FNTM_STYLECHANGED (os2_WM_USER+52)
#define os2_FNTM_COLORCHANGED (os2_WM_USER+53)
#define os2_FNTM_UPDATEPREVIEW (os2_WM_USER+54)
#define os2_FNTM_FILTERLIST (os2_WM_USER+55)
#define _FONTDLG os2__FONTDLG
#define FONTDLG os2_FONTDLG
#define PFONTDLG os2_PFONTDLG
#define _STYLECHANGE os2__STYLECHANGE
#define STYLECHANGE os2_STYLECHANGE
#define PSTYLECHANGE os2_PSTYLECHANGE
#define _SPBCDATA os2__SPBCDATA
#define SPBCDATA os2_SPBCDATA
#define PSPBCDATA os2_PSPBCDATA
#define _SLDCDATA os2__SLDCDATA
#define SLDCDATA os2_SLDCDATA
#define PSLDCDATA os2_PSLDCDATA
#define _CSBITMAPDATA os2__CSBITMAPDATA
#define CSBITMAPDATA os2_CSBITMAPDATA
#define PCSBITMAPDATA os2_PCSBITMAPDATA
#define _BOOKTEXT os2__BOOKTEXT
#define BOOKTEXT os2_BOOKTEXT
#define PBOOKTEXT os2_PBOOKTEXT
#define _NOTEBOOKBUTTON os2__NOTEBOOKBUTTON
#define NOTEBOOKBUTTON os2_NOTEBOOKBUTTON
#define PNOTEBOOKBUTTON os2_PNOTEBOOKBUTTON
#define _DELETENOTIFY os2__DELETENOTIFY
#define DELETENOTIFY os2_DELETENOTIFY
#define PDELETENOTIFY os2_PDELETENOTIFY
#define _PAGESELECTNOTIFY os2__PAGESELECTNOTIFY
#define PAGESELECTNOTIFY os2_PAGESELECTNOTIFY
#define PPAGESELECTNOTIFY os2_PPAGESELECTNOTIFY
#define _BOOKPAGEINFO os2__BOOKPAGEINFO
#define BOOKPAGEINFO os2_BOOKPAGEINFO
#define PBOOKPAGEINFO os2_PBOOKPAGEINFO
#define os2_WM_DRAGFIRST 0x0310
#define os2_WM_DRAGLAST 0x032f
#define os2_DM_DROP 0x032f
#define os2_DM_DRAGOVER 0x032e
#define os2_DM_DRAGLEAVE 0x032d
#define os2_DM_DROPHELP 0x032c
#define os2_DM_ENDCONVERSATION 0x032b
#define os2_DM_PRINT 0x032a
#define os2_DM_RENDER 0x0329
#define os2_DM_RENDERCOMPLETE 0x0328
#define os2_DM_RENDERPREPARE 0x0327
#define os2_DM_DRAGFILECOMPLETE 0x0326
#define os2_DM_EMPHASIZETARGET 0x0325
#define os2_DM_DRAGERROR 0x0324
#define os2_DM_FILERENDERED 0x0323
#define os2_DM_RENDERFILE 0x0322
#define os2_DM_DRAGOVERNOTIFY 0x0321
#define os2_DM_PRINTOBJECT 0x0320
#define os2_DM_DISCARDOBJECT 0x031f
#define os2_DM_DROPNOTIFY 0x031e
#define HSTR os2_HSTR
#define _DRAGIMAGE os2__DRAGIMAGE
#define DRAGIMAGE os2_DRAGIMAGE
#define PDRAGIMAGE os2_PDRAGIMAGE
#define _DRAGINFO os2__DRAGINFO
#define DRAGINFO os2_DRAGINFO
#define PDRAGINFO os2_PDRAGINFO
#define _DRAGITEM os2__DRAGITEM
#define DRAGITEM os2_DRAGITEM
#define PDRAGITEM os2_PDRAGITEM
#define _DRAGTRANSFER os2__DRAGTRANSFER
#define DRAGTRANSFER os2_DRAGTRANSFER
#define PDRAGTRANSFER os2_PDRAGTRANSFER
#define _RENDERFILE os2__RENDERFILE
#define RENDERFILE os2_RENDERFILE
#define PRENDERFILE os2_PRENDERFILE
#define _VSCDATA os2__VSCDATA
#define VSCDATA os2_VSCDATA
#define PVSCDATA os2_PVSCDATA
#define _VSDRAGINIT os2__VSDRAGINIT
#define VSDRAGINIT os2_VSDRAGINIT
#define PVSDRAGINIT os2_PVSDRAGINIT
#define _VSDRAGINFO os2__VSDRAGINFO
#define VSDRAGINFO os2_VSDRAGINFO
#define PVSDRAGINFO os2_PVSDRAGINFO
#define _VSTEXT os2__VSTEXT
#define VSTEXT os2_VSTEXT
#define PVSTEXT os2_PVSTEXT
#define _TREEITEMDESC os2__TREEITEMDESC
#define TREEITEMDESC os2_TREEITEMDESC
#define PTREEITEMDESC os2_PTREEITEMDESC
#define _FIELDINFO os2__FIELDINFO
#define FIELDINFO os2_FIELDINFO
#define PFIELDINFO os2_PFIELDINFO
#define _RECORDCORE os2__RECORDCORE
#define RECORDCORE os2_RECORDCORE
#define PRECORDCORE os2_PRECORDCORE
#define _MINIRECORDCORE os2__MINIRECORDCORE
#define MINIRECORDCORE os2_MINIRECORDCORE
#define PMINIRECORDCORE os2_PMINIRECORDCORE
#define _TREEMOVE os2__TREEMOVE
#define TREEMOVE os2_TREEMOVE
#define PTREEMOVE os2_PTREEMOVE
#define _CNRINFO os2__CNRINFO
#define CNRINFO os2_CNRINFO
#define PCNRINFO os2_PCNRINFO
#define _GRIDSQUARE os2__GRIDSQUARE
#define GRIDSQUARE os2_GRIDSQUARE
#define PGRIDSQUARE os2_PGRIDSQUARE
#define _GRIDINFO os2__GRIDINFO
#define GRIDINFO os2_GRIDINFO
#define PGRIDINFO os2_PGRIDINFO
#define _CDATE os2__CDATE
#define CDATE os2_CDATE
#define PCDATE os2_PCDATE
#define _CTIME os2__CTIME
#define CTIME os2_CTIME
#define PCTIME os2_PCTIME
#define _CNRDRAGINIT os2__CNRDRAGINIT
#define CNRDRAGINIT os2_CNRDRAGINIT
#define PCNRDRAGINIT os2_PCNRDRAGINIT
#define _FIELDINFOINSERT os2__FIELDINFOINSERT
#define FIELDINFOINSERT os2_FIELDINFOINSERT
#define PFIELDINFOINSERT os2_PFIELDINFOINSERT
#define _RECORDINSERT os2__RECORDINSERT
#define RECORDINSERT os2_RECORDINSERT
#define PRECORDINSERT os2_PRECORDINSERT
#define _QUERYRECFROMRECT os2__QUERYRECFROMRECT
#define QUERYRECFROMRECT os2_QUERYRECFROMRECT
#define PQUERYRECFROMRECT os2_PQUERYRECFROMRECT
#define _QUERYRECORDRECT os2__QUERYRECORDRECT
#define QUERYRECORDRECT os2_QUERYRECORDRECT
#define PQUERYRECORDRECT os2_PQUERYRECORDRECT
#define _SEARCHSTRING os2__SEARCHSTRING
#define SEARCHSTRING os2_SEARCHSTRING
#define PSEARCHSTRING os2_PSEARCHSTRING
#define _CNRDRAGINFO os2__CNRDRAGINFO
#define CNRDRAGINFO os2_CNRDRAGINFO
#define PCNRDRAGINFO os2_PCNRDRAGINFO
#define _CNRLAZYDRAGINFO os2__CNRLAZYDRAGINFO
#define CNRLAZYDRAGINFO os2_CNRLAZYDRAGINFO
#define PCNRLAZYDRAGINFO os2_PCNRLAZYDRAGINFO
#define _NOTIFYRECORDEMPHASIS os2__NOTIFYRECORDEMPHASIS
#define NOTIFYRECORDEMPHASIS os2_NOTIFYRECORDEMPHASIS
#define PNOTIFYRECORDEMPHASIS os2_PNOTIFYRECORDEMPHASIS
#define _NOTIFYRECORDENTER os2__NOTIFYRECORDENTER
#define NOTIFYRECORDENTER os2_NOTIFYRECORDENTER
#define PNOTIFYRECORDENTER os2_PNOTIFYRECORDENTER
#define _NOTIFYDELTA os2__NOTIFYDELTA
#define NOTIFYDELTA os2_NOTIFYDELTA
#define PNOTIFYDELTA os2_PNOTIFYDELTA
#define _NOTIFYSCROLL os2__NOTIFYSCROLL
#define NOTIFYSCROLL os2_NOTIFYSCROLL
#define PNOTIFYSCROLL os2_PNOTIFYSCROLL
#define _CNREDITDATA os2__CNREDITDATA
#define CNREDITDATA os2_CNREDITDATA
#define PCNREDITDATA os2_PCNREDITDATA
#define _OWNERBACKGROUND os2__OWNERBACKGROUND
#define OWNERBACKGROUND os2_OWNERBACKGROUND
#define POWNERBACKGROUND os2_POWNERBACKGROUND
#define _CNRDRAWITEMINFO os2__CNRDRAWITEMINFO
#define CNRDRAWITEMINFO os2_CNRDRAWITEMINFO
#define PCNRDRAWITEMINFO os2_PCNRDRAWITEMINFO
#define _OBJCLASS os2__OBJCLASS
#define OBJCLASS os2_OBJCLASS
#define POBJCLASS os2_POBJCLASS
#define HSPL os2_HSPL
#define HSTD os2_HSTD
#define PHSTD os2_PHSTD
#define PQMOPENDATA os2_PQMOPENDATA
#define SPLERR os2_SPLERR
#define _SQPOPENDATA os2__SQPOPENDATA
#define SQPOPENDATA os2_SQPOPENDATA
#define PSQPOPENDATA os2_PSQPOPENDATA
#define _DRIVPROPS os2__DRIVPROPS
#define DRIVPROPS os2_DRIVPROPS
#define PDRIVPROPS os2_PDRIVPROPS
#define _PRINTERINFO os2__PRINTERINFO
#define PRINTERINFO os2_PRINTERINFO
#define PPRINTERINFO os2_PPRINTERINFO
#define _PRJINFO os2__PRJINFO
#define PRJINFO os2_PRJINFO
#define PPRJINFO os2_PPRJINFO
#define _PRJINFO2 os2__PRJINFO2
#define PRJINFO2 os2_PRJINFO2
#define PPRJINFO2 os2_PPRJINFO2
#define _PRJINFO3 os2__PRJINFO3
#define PRJINFO3 os2_PRJINFO3
#define PPRJINFO3 os2_PPRJINFO3
#define _PRJINFO4 os2__PRJINFO4
#define PRJINFO4 os2_PRJINFO4
#define PPRJINFO4 os2_PPRJINFO4
#define _PRDINFO os2__PRDINFO
#define PRDINFO os2_PRDINFO
#define PPRDINFO os2_PPRDINFO
#define _PRDINFO3 os2__PRDINFO3
#define PRDINFO3 os2_PRDINFO3
#define PPRDINFO3 os2_PPRDINFO3
#define _PRQINFO os2__PRQINFO
#define PRQINFO os2_PRQINFO
#define PPRQINFO os2_PPRQINFO
#define _PRQINFO3 os2__PRQINFO3
#define PRQINFO3 os2_PRQINFO3
#define PPRQINFO3 os2_PPRQINFO3
#define _PRQINFO6 os2__PRQINFO6
#define PRQINFO6 os2_PRQINFO6
#define PPRQINFO6 os2_PPRQINFO6
#define _PRIDINFO os2__PRIDINFO
#define PRIDINFO os2_PRIDINFO
#define PPRIDINFO os2_PPRIDINFO
#define _PRDRIVINFO os2__PRDRIVINFO
#define PRDRIVINFO os2_PRDRIVINFO
#define PPRDRIVINFO os2_PPRDRIVINFO
#define _PRDRIVINFO2 os2__PRDRIVINFO2
#define PRDRIVINFO2 os2_PRDRIVINFO2
#define PPRDRIVINFO2 os2_PPRDRIVINFO2
#define _PRQPROCINFO os2__PRQPROCINFO
#define PRQPROCINFO os2_PRQPROCINFO
#define PPRQPROCINFO os2_PPRQPROCINFO
#define _PRPORTINFO os2__PRPORTINFO
#define PRPORTINFO os2_PRPORTINFO
#define PPRPORTINFO os2_PPRPORTINFO
#define _PRPORTINFO1 os2__PRPORTINFO1
#define PRPORTINFO1 os2_PRPORTINFO1
#define PPRPORTINFO1 os2_PPRPORTINFO1
#define _PRPORTINFO2 os2__PRPORTINFO2
#define PRPORTINFO2 os2_PRPORTINFO2
#define PPRPORTINFO2 os2_PPRPORTINFO2
#define _QMJOBINFO os2__QMJOBINFO
#define QMJOBINFO os2_QMJOBINFO
#define PQMJOBINFO os2_PQMJOBINFO
#define os2_CTRL_PREVIOUS_ID ((os2_USHORT)0x0001)
#define os2_CTRL_SEARCH_ID ((os2_USHORT)0x0002)
#define os2_CTRL_PRINT_ID ((os2_USHORT)0x0003)
#define os2_CTRL_INDEX_ID ((os2_USHORT)0x0004)
#define os2_CTRL_CONTENTS_ID ((os2_USHORT)0x0005)
#define os2_CTRL_BACK_ID ((os2_USHORT)0x0006)
#define os2_CTRL_FORWARD_ID ((os2_USHORT)0x0007)
#define os2_CTRL_TUTORIAL_ID ((os2_USHORT)0x00ff)
#define os2_CTRL_USER_ID_BASE ((os2_USHORT)0x0101)
#define os2_HWND_PARENT (os2_HWND)NULL
#define HELPSUBTABLE os2_HELPSUBTABLE
#define PHELPSUBTABLE os2_PHELPSUBTABLE
#define _ACVP os2__ACVP
#define ACVP os2_ACVP
#define PACVP os2_PACVP
#define _HELPTABLE os2__HELPTABLE
#define HELPTABLE os2_HELPTABLE
#define PHELPTABLE os2_PHELPTABLE
#define _HELPINIT os2__HELPINIT
#define HELPINIT os2_HELPINIT
#define PHELPINIT os2_PHELPINIT
#define HDDF os2_HDDF
#define _FOCAMETRICS os2__FOCAMETRICS
#define FOCAMETRICS os2_FOCAMETRICS
#define PFOCAMETRICS os2_PFOCAMETRICS
#define _FONTFILEMETRICS os2__FONTFILEMETRICS
#define FONTFILEMETRICS os2_FONTFILEMETRICS
#define PFONTFILEMETRICS os2_PFONTFILEMETRICS
#define _FONTDEFINITIONHEADER os2__FONTDEFINITIONHEADER
#define FONTDEFINITIONHEADER os2_FONTDEFINITIONHEADER
#define PFONTDEFINITIONHEADER os2_PFONTDEFINITIONHEADER
#define _FONTSIGNATURE os2__FONTSIGNATURE
#define FONTSIGNATURE os2_FONTSIGNATURE
#define PFONTSIGNATURE os2_PFONTSIGNATURE
#define _ADDITIONALMETRICS os2__ADDITIONALMETRICS
#define ADDITIONALMETRICS os2_ADDITIONALMETRICS
#define PADDITIONALMETRICS os2_PADDITIONALMETRICS
#define _FOCAFONT os2__FOCAFONT
#define FOCAFONT os2_FOCAFONT
#define PFOCAFONT os2_PFOCAFONT
#define FOCAFONT32 os2_FOCAFONT32
#define PFOCAFONT32 os2_PFOCAFONT32
#define HVPS os2_HVPS
#define PHVPS os2_PHVPS
#define HMONITOR os2_HMONITOR
#define PHMONITOR os2_PHMONITOR
#define _MONIN os2__MONIN
#define MONIN os2_MONIN
#define PMONIN os2_PMONIN
#define _MONOUT os2__MONOUT
#define MONOUT os2_MONOUT
#define PMONOUT os2_PMONOUT
#define HKBD os2_HKBD
#define PHKBD os2_PHKBD
#define _KBDKEYINFO os2__KBDKEYINFO
#define KBDKEYINFO os2_KBDKEYINFO
#define PKBDKEYINFO os2_PKBDKEYINFO
#define _KBDINFO os2__KBDINFO
#define KBDINFO os2_KBDINFO
#define PKBDINFO os2_PKBDINFO
#define _KBDHWID os2__KBDHWID
#define KBDHWID os2_KBDHWID
#define PKBDHWID os2_PKBDHWID
#define _KBDTRANS os2__KBDTRANS
#define KBDTRANS os2_KBDTRANS
#define PKBDTRANS os2_PKBDTRANS
#define _STRINGINBUF os2__STRINGINBUF
#define STRINGINBUF os2_STRINGINBUF
#define PSTRINGINBUF os2_PSTRINGINBUF
#define HVIO os2_HVIO
#define PHVIO os2_PHVIO
#define _VIOMODEINFO os2__VIOMODEINFO
#define VIOMODEINFO os2_VIOMODEINFO
#define PVIOMODEINFO os2_PVIOMODEINFO
#define _VIOCONFIGINFO os2__VIOCONFIGINFO
#define VIOCONFIGINFO os2_VIOCONFIGINFO
#define PVIOCONFIGINFO os2_PVIOCONFIGINFO
#define _VIOPHYSBUF os2__VIOPHYSBUF
#define VIOPHYSBUF os2_VIOPHYSBUF
#define PVIOPHYSBUF os2_PVIOPHYSBUF
#define _VIOPALSTATE os2__VIOPALSTATE
#define VIOPALSTATE os2_VIOPALSTATE
#define PVIOPALSTATE os2_PVIOPALSTATE
#define _VIOOVERSCAN os2__VIOOVERSCAN
#define VIOOVERSCAN os2_VIOOVERSCAN
#define PVIOOVERSCAN os2_PVIOOVERSCAN
#define _VIOINTENSITY os2__VIOINTENSITY
#define VIOINTENSITY os2_VIOINTENSITY
#define PVIOINTENSITY os2_PVIOINTENSITY
#define _VIOCOLORREG os2__VIOCOLORREG
#define VIOCOLORREG os2_VIOCOLORREG
#define PVIOCOLORREG os2_PVIOCOLORREG
#define _VIOSETULINELOC os2__VIOSETULINELOC
#define VIOSETULINELOC os2_VIOSETULINELOC
#define PVIOSETULINELOC os2_PVIOSETULINELOC
#define _VIOSETTARGET os2__VIOSETTARGET
#define VIOSETTARGET os2_VIOSETTARGET
#define PVIOSETTARGET os2_PVIOSETTARGET
#define _VIOCURSORINFO os2__VIOCURSORINFO
#define VIOCURSORINFO os2_VIOCURSORINFO
#define PVIOCURSORINFO os2_PVIOCURSORINFO
#define _VIOFONTINFO os2__VIOFONTINFO
#define VIOFONTINFO os2_VIOFONTINFO
#define PVIOFONTINFO os2_PVIOFONTINFO
#define HMOU os2_HMOU
#define PHMOU os2_PHMOU
#define _MOUEVENTINFO os2__MOUEVENTINFO
#define MOUEVENTINFO os2_MOUEVENTINFO
#define PMOUEVENTINFO os2_PMOUEVENTINFO
#define _MOUQUEINFO os2__MOUQUEINFO
#define MOUQUEINFO os2_MOUQUEINFO
#define PMOUQUEINFO os2_PMOUQUEINFO
#define _PTRLOC os2__PTRLOC
#define PTRLOC os2_PTRLOC
#define PPTRLOC os2_PPTRLOC
#define _NOPTRRECT os2__NOPTRRECT
#define NOPTRRECT os2_NOPTRRECT
#define PNOPTRRECT os2_PNOPTRRECT
#define _PTRSHAPE os2__PTRSHAPE
#define PTRSHAPE os2_PTRSHAPE
#define PPTRSHAPE os2_PPTRSHAPE
#define _SCALEFACT os2__SCALEFACT
#define SCALEFACT os2_SCALEFACT
#define PSCALEFACT os2_PSCALEFACT
#define _THRESHOLD os2__THRESHOLD
#define THRESHOLD os2_THRESHOLD
#define PTHRESHOLD os2_PTHRESHOLD
#define _GINFOSEG os2__GINFOSEG
#define GINFOSEG os2_GINFOSEG
#define PGINFOSEG os2_PGINFOSEG
#define _LINFOSEG os2__LINFOSEG
#define LINFOSEG os2_LINFOSEG
#define PLINFOSEG os2_PLINFOSEG

/* include the main OS/2 API wrapper */
#include <os2wrap.h>

/*
   Undefine all typedefs prefixed with "os2_" at the beginning and original
   versions of macros. The command to generate this block is:

sed -nr '
{
  s/^[[:space:]]*typedef[[:space:]]+struct[[:space:]]+([A-Za-z_][A-Za-z0-9_]+)([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#undef \1/p
  td
  s/^[[:space:]]*}[[:space:]]*([A-Z_][A-Z0-9_]+)[[:space:]]*;[[:space:]]*$/#undef \1/p
  td
  s/^[[:space:]]*typedef[[:space:]]+.+[[:space:]]+\**([A-Z_][A-Z0-9_]+)[[:space:]]*(\[.*\])?[[:space:]]*;([[:space:]]*[/]\*.*\*[/])?[[:space:]]*$/#undef \1/p
  td
}
/^[[:space:]]*#define[[:space:]]+/ {
  :a;/\\$/{N;ba}
  s/([^A-Za-z0-9_])(MAKE[A-Z0-9]+)([^A-Za-z0-9_])/\1 \2 \3/g
  s/([^A-Za-z0-9_])(((CONTEXT|CS|DM|DT|EH|EXCEPTION|FDM|FNTM|HWND|MB|MIA|NP|QS|QSV|RGN|RT|SEM|SEVERITY|SIS|SV|SWP|TA|WC|WM|WS|(WIN|GPI|DEV|SPL)ERR)_([A-Z0-9_]+))|((P?VOID|(API|EXP)ENTRY|P(CMD|CHR|MSE)MSG|ERRORID|PCMDMSG|SEL|HWND|MPARAM|MRESULT|LHANDLE|SHANDLE|BOOL|(LO|HI|P)?U?(LONG|SHORT|CHAR|BYTE)|MPFROM[A-Z0-9]+|MAKE[A-Z0-9]+)([^A-Za-z0-9_])))/\1os2_\2/g
  tb;bd
  :b
  s/^[[:space:]]*#define[[:space:]]+(os2_)?([A-Za-z_][A-Za-z0-9_]+)[[:space:]]*(.*)/#undef \2/p
}  
:d
'
 */

#undef _THUNK_PASCAL_FUNCTION
#undef MAKE16P
#undef MAKEP
#undef SELECTOROF
#undef OFFSETOF
#undef _THUNK_PTR_SIZE_OK
#undef APIENTRY
#undef EXPENTRY
#undef VOID
#undef NULLHANDLE
#undef NULLSHANDLE
#undef INT
#undef UINT
#undef APIRET
#undef BOOL
#undef PBOOL
#undef BOOL32
#undef PBOOL32
#undef CHAR
#undef PCHAR
#undef BYTE
#undef PCH
#undef PSZ
#undef PCCH
#undef PCSZ
#undef BYTE
#undef PCH
#undef PSZ
#undef PCCH
#undef PCSZ
#undef PBYTE
#undef UCHAR
#undef PUCHAR
#undef SHORT
#undef PSHORT
#undef USHORT
#undef PUSHORT
#undef LONG
#undef PLONG
#undef ULONG
#undef PULONG
#undef LONGLONG
#undef PLONGLONG
#undef ULONGLONG
#undef PULONGLONG
#undef _LONGLONG
#undef LONGLONG
#undef PLONGLONG
#undef _ULONGLONG
#undef ULONGLONG
#undef PULONGLONG
#undef PVOID
#undef PPVOID
#undef CPVOID
#undef STR8
#undef PSTR8
#undef STR16
#undef PSTR16
#undef STR32
#undef PSTR32
#undef STR64
#undef PSTR64
#undef SHANDLE
#undef LHANDLE
#undef HPIPE
#undef PHPIPE
#undef HQUEUE
#undef PHQUEUE
#undef HMODULE
#undef PHMODULE
#undef HSEM
#undef PHSEM
#undef HOBJECT
#undef PID
#undef PPID
#undef TID
#undef PTID
#undef PFN
#undef PPFN
#undef SEL
#undef PSEL
#undef HMTX
#undef PHMTX
#undef HMUX
#undef PHMUX
#undef FIELDOFFSET
#undef MAKETYPE
#undef MAKEUSHORT
#undef MAKESHORT
#undef MAKEULONG
#undef MAKELONG
#undef LOUCHAR
#undef HIUCHAR
#undef LOBYTE
#undef HIBYTE
#undef LOUSHORT
#undef HIUSHORT
#undef WINERR_BASE
#undef GPIERR_BASE
#undef DEVERR_BASE
#undef SPLERR_BASE
#undef SEVERITY_NOERROR
#undef SEVERITY_WARNING
#undef SEVERITY_ERROR
#undef SEVERITY_SEVERE
#undef SEVERITY_UNRECOVERABLE
#undef _PANOSE
#undef PANOSE
#undef _FONTMETRICS
#undef FONTMETRICS
#undef PFONTMETRICS
#undef _FATTRS
#undef FATTRS
#undef PFATTRS
#undef HFILE
#undef PHFILE
#undef FHLOCK
#undef PFHLOCK
#undef HDIR
#undef PHDIR
#undef _FTIME
#undef FTIME
#undef _FTIME
#undef FTIME
#undef PFTIME
#undef _FDATE
#undef FDATE
#undef _FDATE
#undef FDATE
#undef PFDATE
#undef _FEA
#undef FEA
#undef PFEA
#undef _FEALIST
#undef FEALIST
#undef PFEALIST
#undef _GEA
#undef GEA
#undef PGEA
#undef _GEALIST
#undef GEALIST
#undef PGEALIST
#undef _EAOP
#undef EAOP
#undef PEAOP
#undef _FEA2
#undef FEA2
#undef PFEA2
#undef _FEA2LIST
#undef FEA2LIST
#undef PFEA2LIST
#undef _GEA2
#undef GEA2
#undef PGEA2
#undef _GEA2LIST
#undef GEA2LIST
#undef PGEA2LIST
#undef _EAOP2
#undef EAOP2
#undef PEAOP2
#undef _DENA1
#undef DENA1
#undef PDENA1
#undef DENA2
#undef PDENA2
#undef _EASIZEBUF
#undef EASIZEBUF
#undef PEASIZEBUF
#undef _ROUTENAMEBUF
#undef ROUTENAMEBUF
#undef PROUTENAMEBUF
#undef _FSDTHREAD
#undef FSDTHREAD
#undef _FSDDAEMON
#undef FSDDAEMON
#undef _FILEFINDBUF
#undef FILEFINDBUF
#undef PFILEFINDBUF
#undef _FILEFINDBUF2
#undef FILEFINDBUF2
#undef PFILEFINDBUF2
#undef _FILEFINDBUF3
#undef FILEFINDBUF3
#undef PFILEFINDBUF3
#undef _FILEFINDBUF4
#undef FILEFINDBUF4
#undef PFILEFINDBUF4
#undef _FILEFINDBUF3L
#undef FILEFINDBUF3L
#undef PFILEFINDBUF3L
#undef _FILEFINDBUF4L
#undef FILEFINDBUF4L
#undef PFILEFINDBUF4L
#undef _FILELOCK
#undef FILELOCK
#undef PFILELOCK
#undef _FILELOCKL
#undef FILELOCKL
#undef PFILELOCKL
#undef _FILESTATUS
#undef FILESTATUS
#undef PFILESTATUS
#undef _FILESTATUS2
#undef FILESTATUS2
#undef PFILESTATUS2
#undef _FILESTATUS3
#undef FILESTATUS3
#undef PFILESTATUS3
#undef _FILESTATUS4
#undef FILESTATUS4
#undef PFILESTATUS4
#undef _FILESTATUS3L
#undef FILESTATUS3L
#undef PFILESTATUS3L
#undef _FILESTATUS4L
#undef FILESTATUS4L
#undef PFILESTATUS4L
#undef _FSALLOCATE
#undef FSALLOCATE
#undef PFSALLOCATE
#undef _FSQBUFFER
#undef FSQBUFFER
#undef PFSQBUFFER
#undef _FSQBUFFER2
#undef FSQBUFFER2
#undef PFSQBUFFER2
#undef _SPOOLATTACH
#undef SPOOLATTACH
#undef PSPOOLATTACH
#undef _VOLUMELABEL
#undef VOLUMELABEL
#undef PVOLUMELABEL
#undef _FSINFO
#undef FSINFO
#undef PFSINFO
#undef _LISTIO_CB
#undef LISTIO
#undef PLISTIO
#undef _LISTIO_CBL
#undef LISTIOL
#undef PLISTIOL
#undef _DCBINFO
#undef DCBINFO
#undef PDCBINFO
#undef _LINECONTROL
#undef LINECONTROL
#undef PLINECONTROL
#undef _MODEMSTATUS
#undef MODEMSTATUS
#undef PMODEMSTATUS
#undef _KBDTYPE
#undef KBDTYPE
#undef PKBDTYPE
#undef _RATEDELAY
#undef RATEDELAY
#undef PRATEDELAY
#undef _CODEPAGEINFO
#undef CODEPAGEINFO
#undef PCODEPAGEINFO
#undef _CPID
#undef CPID
#undef PCPID
#undef _SHIFTSTATE
#undef SHIFTSTATE
#undef PSHIFTSTATE
#undef _HOTKEY
#undef HOTKEY
#undef PHOTKEY
#undef _PTRDRAWFUNCTION
#undef PTRDRAWFUNCTION
#undef PPTRDRAWFUNCTION
#undef _PTRDRAWADDRESS
#undef PTRDRAWADDRESS
#undef PPTRDRAWADDRESS
#undef _PTRDRAWDATA
#undef PTRDRAWDATA
#undef PPTRDRAWDATA
#undef _TRACKLAYOUT
#undef TRACKLAYOUT
#undef PTRACKLAYOUT
#undef _TRACKFORMAT
#undef TRACKFORMAT
#undef PTRACKFORMAT
#undef _BIOSPARAMETERBLOCK
#undef BIOSPARAMETERBLOCK
#undef PBIOSPARAMETERBLOCK
#undef _DEVICEPARAMETERBLOCK
#undef DEVICEPARAMETERBLOCK
#undef PDEVICEPARAMETERBLOCK
#undef _MONITORPOSITION
#undef MONITORPOSITION
#undef PMONITORPOSITION
#undef _FRAME
#undef FRAME
#undef PFRAME
#undef _LDTADDRINFO
#undef LDTADDRINFO
#undef PLDTADDRINFO
#undef _SCREENGROUP
#undef SCREENGROUP
#undef PSCREENGROUP
#undef _RXQUEUE
#undef RXQUEUE
#undef PRXQUEUE
#undef _GETLINIOCTLDATA
#undef GETLINIOCTLDATA
#undef PGETLINIOCTLDATA
#undef _BANKINFO
#undef BANKINFO
#undef _GLOBALIOCTLDATA
#undef GLOBALIOCTLDATA
#undef _OEMSVGAINFO
#undef OEMSVGAINFO
#undef _OEMINFO
#undef OEMINFO
#undef _GETGLOBALPACKET
#undef GETGLOBALPACKET
#undef _COUNTRYCODE
#undef COUNTRYCODE
#undef PCOUNTRYCODE
#undef _COUNTRYINFO
#undef COUNTRYINFO
#undef PCOUNTRYINFO
#undef RT_POINTER
#undef RT_BITMAP
#undef RT_MENU
#undef RT_DIALOG
#undef RT_STRING
#undef RT_FONTDIR
#undef RT_FONT
#undef RT_ACCELTABLE
#undef RT_RCDATA
#undef RT_MESSAGE
#undef RT_DLGINCLUDE
#undef RT_VKEYTBL
#undef RT_KEYTBL
#undef RT_CHARTBL
#undef RT_DISPLAYINFO
#undef RT_FKASHORT
#undef RT_FKALONG
#undef RT_HELPTABLE
#undef RT_HELPSUBTABLE
#undef RT_FDDIR
#undef RT_FD
#undef RT_MAX
#undef RT_RESNAMES
#undef _RESULTCODES
#undef RESULTCODES
#undef PRESULTCODES
#undef tib2_s
#undef TIB2
#undef PTIB2
#undef tib_s
#undef TIB
#undef PTIB
#undef pib_s
#undef PIB
#undef PPIB
#undef PFNTHREAD
#undef PFNEXITLIST
#undef _MPAFFINITY
#undef MPAFFINITY
#undef PMPAFFINITY
#undef _THREADCREATE
#undef THREADCREATE
#undef PTHREADCREATE
#undef _STARTDATA
#undef STARTDATA
#undef PSTARTDATA
#undef _STATUSDATA
#undef STATUSDATA
#undef PSTATUSDATA
#undef SEM_INDEFINITE_WAIT
#undef SEM_IMMEDIATE_RETURN
#undef HEV
#undef PHEV
#undef _PSEMRECORD
#undef SEMRECORD
#undef PSEMRECORD
#undef NP_INDEFINITE_WAIT
#undef NP_DEFAULT_WAIT
#undef NP_STATE_DISCONNECTED
#undef NP_STATE_LISTENING
#undef NP_STATE_CONNECTED
#undef NP_STATE_CLOSING
#undef NP_ACCESS_INBOUND
#undef NP_ACCESS_OUTBOUND
#undef NP_ACCESS_DUPLEX
#undef NP_INHERIT
#undef NP_NOINHERIT
#undef NP_WRITEBEHIND
#undef NP_NOWRITEBEHIND
#undef NP_READMODE_BYTE
#undef NP_READMODE_MESSAGE
#undef NP_TYPE_BYTE
#undef NP_TYPE_MESSAGE
#undef NP_END_CLIENT
#undef NP_END_SERVER
#undef NP_WAIT
#undef NP_NOWAIT
#undef NP_UNLIMITED_INSTANCES
#undef NP_NBLK
#undef NP_SERVER
#undef NP_WMESG
#undef NP_RMESG
#undef NP_ICOUNT
#undef _AVAILDATA
#undef AVAILDATA
#undef PAVAILDATA
#undef _PIPEINFO
#undef PIPEINFO
#undef PPIPEINFO
#undef _PIPESEMSTATE
#undef PIPESEMSTATE
#undef PPIPESEMSTATE
#undef _REQUESTDATA
#undef REQUESTDATA
#undef PREQUESTDATA
#undef CONTEXT_CONTROL
#undef CONTEXT_INTEGER
#undef CONTEXT_SEGMENTS
#undef CONTEXT_FLOATING_POINT
#undef CONTEXT_FULL
#undef EH_NONCONTINUABLE
#undef EH_UNWINDING
#undef EH_EXIT_UNWIND
#undef EH_STACK_INVALID
#undef EH_NESTED_CALL
#undef _fpreg
#undef FPREG
#undef PFPREG
#undef _CONTEXT
#undef CONTEXTRECORD
#undef PCONTEXTRECORD
#undef EXCEPTION_MAXIMUM_PARAMETERS
#undef _EXCEPTIONREPORTRECORD
#undef EXCEPTIONREPORTRECORD
#undef PEXCEPTIONREPORTRECORD
#undef ERR
#undef _EXCEPTIONREGISTRATIONRECORD
#undef EXCEPTIONREGISTRATIONRECORD
#undef PEXCEPTIONREGISTRATIONRECORD
#undef QSV_MAX_PATH_LENGTH
#undef QSV_MAX_TEXT_SESSIONS
#undef QSV_MAX_PM_SESSIONS
#undef QSV_MAX_VDM_SESSIONS
#undef QSV_BOOT_DRIVE
#undef QSV_DYN_PRI_VARIATION
#undef QSV_MAX_WAIT
#undef QSV_MIN_SLICE
#undef QSV_MAX_SLICE
#undef QSV_PAGE_SIZE
#undef QSV_VERSION_MAJOR
#undef QSV_VERSION_MINOR
#undef QSV_VERSION_REVISION
#undef QSV_MS_COUNT
#undef QSV_TIME_LOW
#undef QSV_TIME_HIGH
#undef QSV_TOTPHYSMEM
#undef QSV_TOTRESMEM
#undef QSV_TOTAVAILMEM
#undef QSV_MAXPRMEM
#undef QSV_MAXSHMEM
#undef QSV_TIMER_INTERVAL
#undef QSV_MAX_COMP_LENGTH
#undef QSV_FOREGROUND_FS_SESSION
#undef QSV_FOREGROUND_PROCESS
#undef QSV_NUMPROCESSORS
#undef QSV_MAXHPRMEM
#undef QSV_MAXHSHMEM
#undef QSV_MAXPROCESSES
#undef QSV_VIRTUALADDRESSLIMIT
#undef QSV_INT10ENABLED
#undef QSV_MAX
#undef SIS_MMIOADDR
#undef SIS_MEC_TABLE
#undef SIS_SYS_LOG
#undef SIS_PERF_MEC_TABLE
#undef _DATETIME
#undef DATETIME
#undef PDATETIME
#undef HTIMER
#undef PHTIMER
#undef PADSHORT
#undef PADCHAR
#undef QS_PROCESS
#undef QS_SEMAPHORE
#undef QS_MTE
#undef QS_FILESYS
#undef QS_SHMEMORY
#undef QS_DISK
#undef QS_HWCONFIG
#undef QS_NAMEDPIPE
#undef QS_THREAD
#undef QS_MODVER
#undef QS_SUPPORTED
#undef QS_END
#undef QS_SYSSEM_WAITING
#undef QS_SYSSEM_MUXWAITING
#undef QS_SYSSEM_OWNER_DIED
#undef QS_SYSSEM_EXCLUSIVE
#undef QS_SYSSEM_NAME_CLEANUP
#undef QS_SYSSEM_THREAD_OWNER_DIED
#undef QS_SYSSEM_EXITLIST_OWNER
#undef QS_DC_SEM_SHARED
#undef QS_DCMW_WAIT_ANY
#undef QS_DCMW_WAIT_ALL
#undef QS_DCM_MUTEX_SEM
#undef QS_DCE_EVENT_SEM
#undef QS_DCMW_MUX_SEM
#undef QS_DC_SEM_PM
#undef QS_DE_POSTED
#undef QS_DM_OWNER_DIED
#undef QS_DMW_MTX_MUX
#undef QS_DHO_SEM_OPEN
#undef QS_DE_16BIT_MW
#undef QS_DCE_POSTONE
#undef QS_DCE_AUTORESET
#undef _QWORD
#undef QWORD
#undef PQWORD
#undef _QSGREC
#undef QSGREC
#undef _QSTREC
#undef QSTREC
#undef _QSPREC
#undef QSPREC
#undef _QSS16REC
#undef QSS16REC
#undef _QSS16HEADREC
#undef QSS16HEADREC
#undef _QSMREC
#undef QSMREC
#undef _QSOPENQ
#undef QSOPENQ
#undef _QSEVENT
#undef QSEVENT
#undef _QSMUTEX
#undef QSMUTEX
#undef _QSMUX
#undef QSMUX
#undef QSHUN
#undef _QSS32REC
#undef QSS32REC
#undef _QSLOBJREC
#undef QSLOBJREC
#undef _QSLREC
#undef QSLREC
#undef _QSEXLREC
#undef QSEXLREC
#undef _QSSFT
#undef QSSFT
#undef _QSFREC
#undef QSFREC
#undef _QSPTRREC
#undef QSPTRREC
#undef SGID
#undef HVDD
#undef PHVDD
#undef HSPINLOCK
#undef PHSPINLOCK
#undef _TStat
#undef _uDB
#undef SIS_MMIOADDR
#undef SIS_MEC_TABLE
#undef SIS_SYS_LOG
#undef SIS_PERF_MEC_TABLE
#undef _RXSTRING
#undef RXSTRING
#undef PRXSTRING
#undef _RXSYSEXIT
#undef RXSYSEXIT
#undef PRXSYSEXIT
#undef MAKERXSTRING
#undef _SHVBLOCK
#undef SHVBLOCK
#undef PSHVBLOCK
#undef PEXIT
#undef _RXFNC_FLAGS
#undef RXFNC_FLAGS
#undef _RXFNCCAL_PARM
#undef RXFNCCAL_PARM
#undef _RXCMD_FLAGS
#undef RXCMD_FLAGS
#undef _RXCMDHST_PARM
#undef RXCMDHST_PARM
#undef _RXMSQPLL_PARM
#undef RXMSQPLL_PARM
#undef _RXMSQ_FLAGS
#undef RXMSQ_FLAGS
#undef _RXMSQPSH_PARM
#undef RXMSQPSH_PARM
#undef _RXMSQSIZ_PARM
#undef RXMSQSIZ_PARM
#undef _RXMSQNAM_PARM
#undef RXMSQNAM_PARM
#undef _RXSIOSAY_PARM
#undef RXSIOSAY_PARM
#undef _RXSIOTRC_PARM
#undef RXSIOTRC_PARM
#undef _RXSIOTRD_PARM
#undef RXSIOTRD_PARM
#undef _RXSIODR_PARM
#undef RXSIODTR_PARM
#undef _RXHLT_FLAGS
#undef RXHLT_FLAGS
#undef _RXHLTTST_PARM
#undef RXHLTTST_PARM
#undef _RXTRC_FLAGS
#undef RXTRC_FLAGS
#undef _RXTRCTST_PARM
#undef RXTRCTST_PARM
#undef WM_DBCSFIRST
#undef WM_DBCSLAST
#undef WC_FRAME
#undef WC_COMBOBOX
#undef WC_BUTTON
#undef WC_MENU
#undef WC_STATIC
#undef WC_ENTRYFIELD
#undef WC_LISTBOX
#undef WC_SCROLLBAR
#undef WC_TITLEBAR
#undef WC_MLE
#undef WC_APPSTAT
#undef WC_KBDSTAT
#undef WC_PECIC
#undef WC_DBE_KKPOPUP
#undef WC_SPINBUTTON
#undef WC_CONTAINER
#undef WC_SLIDER
#undef WC_VALUESET
#undef WC_NOTEBOOK
#undef WC_PENFIRST
#undef WC_PENLAST
#undef WC_MMPMFIRST
#undef WC_CIRCULARSLIDER
#undef WC_MMPMLAST
#undef WS_VISIBLE
#undef WS_DISABLED
#undef WS_CLIPCHILDREN
#undef WS_CLIPSIBLINGS
#undef WS_PARENTCLIP
#undef WS_SAVEBITS
#undef WS_SYNCPAINT
#undef WS_MINIMIZED
#undef WS_MAXIMIZED
#undef WS_ANIMATE
#undef WS_GROUP
#undef WS_TABSTOP
#undef WS_MULTISELECT
#undef CS_MOVENOTIFY
#undef CS_SIZEREDRAW
#undef CS_HITTEST
#undef CS_PUBLIC
#undef CS_FRAME
#undef CS_CLIPCHILDREN
#undef CS_CLIPSIBLINGS
#undef CS_PARENTCLIP
#undef CS_SAVEBITS
#undef CS_SYNCPAINT
#undef DT_LEFT
#undef DT_QUERYEXTENT
#undef DT_UNDERSCORE
#undef DT_STRIKEOUT
#undef DT_TEXTATTRS
#undef DT_EXTERNALLEADING
#undef DT_CENTER
#undef DT_RIGHT
#undef DT_TOP
#undef DT_VCENTER
#undef DT_BOTTOM
#undef DT_HALFTONE
#undef DT_MNEMONIC
#undef DT_WORDBREAK
#undef DT_ERASERECT
#undef SWP_SIZE
#undef SWP_MOVE
#undef SWP_ZORDER
#undef SWP_SHOW
#undef SWP_HIDE
#undef SWP_NOREDRAW
#undef SWP_NOADJUST
#undef SWP_ACTIVATE
#undef SWP_DEACTIVATE
#undef SWP_EXTSTATECHANGE
#undef SWP_MINIMIZE
#undef SWP_MAXIMIZE
#undef SWP_RESTORE
#undef SWP_FOCUSACTIVATE
#undef SWP_FOCUSDEACTIVATE
#undef SWP_NOAUTOCLOSE
#undef HWND_DESKTOP
#undef HWND_OBJECT
#undef HWND_TOP
#undef HWND_BOTTOM
#undef HWND_THREADCAPTURE
#undef HACCEL
#undef HRGN
#undef PHRGN
#undef MRESULT
#undef PMRESULT
#undef MPARAM
#undef PMPARAM
#undef HPOINTER
#undef HLIB
#undef PHLIB
#undef COLOR
#undef PCOLOR
#undef HAB
#undef PHAB
#undef HPS
#undef PHPS
#undef HDC
#undef PHDC
#undef HWND
#undef PHWND
#undef HMQ
#undef HPAL
#undef PHPAL
#undef HBITMAP
#undef PHBITMAP
#undef ERRORID
#undef PERRORID
#undef PFNWP
#undef ERRORIDERROR
#undef ERRORIDSEV
#undef MAKEERRORID
#undef _POINTL
#undef POINTL
#undef PPOINTL
#undef _POINTS
#undef POINTS
#undef PPOINTS
#undef _RECTL
#undef RECTL
#undef PRECTL
#undef WM_NULL
#undef WM_CREATE
#undef WM_DESTROY
#undef WM_ENABLE
#undef WM_SHOW
#undef WM_MOVE
#undef WM_SIZE
#undef WM_ADJUSTWINDOWPOS
#undef WM_CALCVALIDRECTS
#undef WM_SETWINDOWPARAMS
#undef WM_QUERYWINDOWPARAMS
#undef WM_HITTEST
#undef WM_ACTIVATE
#undef WM_SETFOCUS
#undef WM_SETSELECTION
#undef WM_PPAINT
#undef WM_PSETFOCUS
#undef WM_PSYSCOLORCHANGE
#undef WM_PSIZE
#undef WM_PACTIVATE
#undef WM_PCONTROL
#undef WM_COMMAND
#undef WM_SYSCOMMAND
#undef WM_HELP
#undef WM_PAINT
#undef WM_TIMER
#undef WM_SEM1
#undef WM_SEM2
#undef WM_SEM3
#undef WM_SEM4
#undef WM_CLOSE
#undef WM_QUIT
#undef WM_SYSCOLORCHANGE
#undef WM_SYSVALUECHANGED
#undef WM_APPTERMINATENOTIFY
#undef WM_PRESPARAMCHANGED
#undef WM_CONTROL
#undef WM_VSCROLL
#undef WM_HSCROLL
#undef WM_INITMENU
#undef WM_MENUSELECT
#undef WM_MENUEND
#undef WM_DRAWITEM
#undef WM_MEASUREITEM
#undef WM_CONTROLPOINTER
#undef WM_QUERYDLGCODE
#undef WM_INITDLG
#undef WM_SUBSTITUTESTRING
#undef WM_MATCHMNEMONIC
#undef WM_SAVEAPPLICATION
#undef WM_HELPBASE
#undef WM_HELPTOP
#undef WM_USER
#undef _QMSG
#undef QMSG
#undef PQMSG
#undef _COMMANDMSG
#undef CMDMSG
#undef PCMDMSG
#undef _MQINFO
#undef MQINFO
#undef PMQINFO
#undef COMMANDMSG
#undef _SWP
#undef SWP
#undef PSWP
#undef _ICONINFO
#undef ICONINFO
#undef PICONINFO
#undef MPVOID
#undef MPFROMP
#undef MPFROMHWND
#undef MPFROMCHAR
#undef MPFROMSHORT
#undef MPFROM2SHORT
#undef MPFROMSH2CH
#undef MPFROMLONG
#undef PVOIDFROMMP
#undef HWNDFROMMP
#undef CHAR1FROMMP
#undef CHAR2FROMMP
#undef CHAR3FROMMP
#undef CHAR4FROMMP
#undef SHORT1FROMMP
#undef SHORT2FROMMP
#undef LONGFROMMP
#undef MRFROMP
#undef MRFROMSHORT
#undef MRFROM2SHORT
#undef MRFROMLONG
#undef PVOIDFROMMR
#undef SHORT1FROMMR
#undef SHORT2FROMMR
#undef LONGFROMMR
#undef _FRAMECDATA
#undef FRAMECDATA
#undef PFRAMECDATA
#undef WM_FLASHWINDOW
#undef WM_FORMATFRAME
#undef WM_UPDATEFRAME
#undef WM_FOCUSCHANGE
#undef WM_SETBORDERSIZE
#undef WM_TRACKFRAME
#undef WM_MINMAXFRAME
#undef WM_SETICON
#undef WM_QUERYICON
#undef WM_SETACCELTABLE
#undef WM_QUERYACCELTABLE
#undef WM_TRANSLATEACCEL
#undef WM_QUERYTRACKINFO
#undef WM_QUERYBORDERSIZE
#undef WM_NEXTMENU
#undef WM_ERASEBACKGROUND
#undef WM_QUERYFRAMEINFO
#undef WM_QUERYFOCUSCHAIN
#undef WM_OWNERPOSCHANGE
#undef WM_CALCFRAMERECT
#undef WM_WINDOWPOSCHANGED
#undef WM_ADJUSTFRAMEPOS
#undef WM_QUERYFRAMECTLCOUNT
#undef WM_QUERYHELPINFO
#undef WM_SETHELPINFO
#undef WM_ERROR
#undef WM_REALIZEPALETTE
#undef HSAVEWP
#undef _QVERSDATA
#undef QVERSDATA
#undef PQVERSDATA
#undef WM_QUERYCONVERTPOS
#undef _CLASSINFO
#undef CLASSINFO
#undef PCLASSINFO
#undef _CREATESTRUCT
#undef CREATESTRUCT
#undef PCREATESTRUCT
#undef HENUM
#undef _ACCEL
#undef ACCEL
#undef PACCEL
#undef _ACCELTABLE
#undef ACCELTABLE
#undef PACCELTABLE
#undef HATOMTBL
#undef ATOM
#undef MAKEINTATOM
#undef _BTNCDATA
#undef BTNCDATA
#undef PBTNCDATA
#undef _USERBUTTON
#undef USERBUTTON
#undef PUSERBUTTON
#undef WM_RENDERFMT
#undef WM_RENDERALLFMTS
#undef WM_DESTROYCLIPBOARD
#undef WM_PAINTCLIPBOARD
#undef WM_SIZECLIPBOARD
#undef WM_HSCROLLCLIPBOARD
#undef WM_VSCROLLCLIPBOARD
#undef WM_DRAWCLIPBOARD
#undef _CPTEXT
#undef CPTEXT
#undef PCPTEXT
#undef _MFP
#undef MFP
#undef PMFP
#undef WM_DDE_FIRST
#undef WM_DDE_INITIATE
#undef WM_DDE_REQUEST
#undef WM_DDE_ACK
#undef WM_DDE_DATA
#undef WM_DDE_ADVISE
#undef WM_DDE_UNADVISE
#undef WM_DDE_POKE
#undef WM_DDE_EXECUTE
#undef WM_DDE_TERMINATE
#undef WM_DDE_INITIATEACK
#undef WM_DDE_LAST
#undef _CONVCONTEXT
#undef CONVCONTEXT
#undef PCONVCONTEXT
#undef _DDEINIT
#undef DDEINIT
#undef PDDEINIT
#undef _DDESTRUCT
#undef DDESTRUCT
#undef PDDESTRUCT
#undef DDES_PABDATA
#undef DDEI_PCONVCONTEXT
#undef _CURSORINFO
#undef CURSORINFO
#undef PCURSORINFO
#undef _DESKTOP
#undef DESKTOP
#undef PDESKTOP
#undef MB_OK
#undef MB_OKCANCEL
#undef MB_RETRYCANCEL
#undef MB_ABORTRETRYIGNORE
#undef MB_YESNO
#undef MB_YESNOCANCEL
#undef MB_CANCEL
#undef MB_ENTER
#undef MB_ENTERCANCEL
#undef MB_NOICON
#undef MB_CUANOTIFICATION
#undef MB_ICONQUESTION
#undef MB_ICONEXCLAMATION
#undef MB_CUAWARNING
#undef MB_ICONASTERISK
#undef MB_ICONHAND
#undef MB_CUACRITICAL
#undef MB_QUERY
#undef MB_WARNING
#undef MB_INFORMATION
#undef MB_CRITICAL
#undef MB_ERROR
#undef MB_CUSTOMICON
#undef MB_DEFBUTTON1
#undef MB_DEFBUTTON2
#undef MB_DEFBUTTON3
#undef MB_APPLMODAL
#undef MB_SYSTEMMODAL
#undef MB_HELP
#undef MB_MOVEABLE
#undef MB_NONMODAL
#undef _MB2D
#undef MB2D
#undef PMB2D
#undef _MB2INFO
#undef MB2INFO
#undef PMB2INFO
#undef WinCheckButton
#undef WinIsControlEnabled
#undef WinQueryButtonCheckstate
#undef _DLGTITEM
#undef DLGTITEM
#undef PDLGTITEM
#undef _DLGTEMPLATE
#undef DLGTEMPLATE
#undef PDLGTEMPLATE
#undef _COMBOCDATA
#undef COMBOCDATA
#undef PCOMBOCDATA
#undef _ENTRYFDATA
#undef ENTRYFDATA
#undef PENTRYFDATA
#undef _ERRINFO
#undef ERRINFO
#undef PERRINFO
#undef _SMHSTRUCT
#undef SMHSTRUCT
#undef PSMHSTRUCT
#undef WM_MOUSEFIRST
#undef WM_MOUSEMOVE
#undef WM_BUTTONCLICKFIRST
#undef WM_BUTTON1DOWN
#undef WM_BUTTON1UP
#undef WM_BUTTON1DBLCLK
#undef WM_BUTTON2DOWN
#undef WM_BUTTON2UP
#undef WM_BUTTON2DBLCLK
#undef WM_BUTTON3DOWN
#undef WM_BUTTON3UP
#undef WM_BUTTON3DBLCLK
#undef WM_BUTTONCLICKLAST
#undef WM_MOUSELAST
#undef WM_CHAR
#undef WM_VIOCHAR
#undef WM_JOURNALNOTIFY
#undef WM_MOUSEMAP
#undef WM_VRNDISABLED
#undef WM_VRNENABLED
#undef WM_EXTMOUSEFIRST
#undef WM_CHORD
#undef WM_BUTTON1MOTIONSTART
#undef WM_BUTTON1MOTIONEND
#undef WM_BUTTON1CLICK
#undef WM_BUTTON2MOTIONSTART
#undef WM_BUTTON2MOTIONEND
#undef WM_BUTTON2CLICK
#undef WM_BUTTON3MOTIONSTART
#undef WM_BUTTON3MOTIONEND
#undef WM_BUTTON3CLICK
#undef WM_EXTMOUSELAST
#undef WM_MOUSETRANSLATEFIRST
#undef WM_BEGINDRAG
#undef WM_ENDDRAG
#undef WM_SINGLESELECT
#undef WM_OPEN
#undef WM_CONTEXTMENU
#undef WM_CONTEXTHELP
#undef WM_TEXTEDIT
#undef WM_BEGINSELECT
#undef WM_ENDSELECT
#undef WM_MOUSETRANSLATELAST
#undef WM_PICKUP
#undef WM_PENFIRST
#undef WM_PENLAST
#undef WM_MMPMFIRST
#undef WM_MMPMLAST
#undef WM_BIDI_FIRST
#undef WM_BIDI_LAST
#undef _CHARMSG
#undef CHRMSG
#undef PCHRMSG
#undef _MOUSEMSG
#undef MSEMSG
#undef PMSEMSG
#undef CHARMSG
#undef MOUSEMSG
#undef _LBOXINFO
#undef LBOXINFO
#undef PLBOXINFO
#undef WinDeleteLboxItem
#undef WinInsertLboxItem
#undef WinQueryLboxCount
#undef WinQueryLboxItemText
#undef WinQueryLboxItemTextLength
#undef WinQueryLboxSelectedItem
#undef WinSetLboxItemText
#undef MIA_NODISMISS
#undef MIA_FRAMED
#undef MIA_CHECKED
#undef MIA_DISABLED
#undef MIA_HILITED
#undef _MENUITEM
#undef MENUITEM
#undef PMENUITEM
#undef _mti
#undef MTI
#undef _mt
#undef MT
#undef LPMT
#undef _OWNERITEM
#undef OWNERITEM
#undef POWNERITEM
#undef WinCheckMenuItem
#undef WinEnableMenuItem
#undef WinIsMenuItemChecked
#undef WinIsMenuItemEnabled
#undef WinIsMenuItemValid
#undef WinSetMenuItemText
#undef QS_KEY
#undef QS_MOUSEBUTTON
#undef QS_MOUSEMOVE
#undef QS_MOUSE
#undef QS_TIMER
#undef QS_PAINT
#undef QS_POSTMSG
#undef QS_SEM1
#undef QS_SEM2
#undef QS_SEM3
#undef QS_SEM4
#undef QS_SENDMSG
#undef QS_MSGINPUT
#undef _WNDPARAMS
#undef WNDPARAMS
#undef PWNDPARAMS
#undef _POINTERINFO
#undef POINTERINFO
#undef PPOINTERINFO
#undef _SBCDATA
#undef SBCDATA
#undef PSBCDATA
#undef WM_MSGBOXINIT
#undef WM_MSGBOXDISMISS
#undef SV_SWAPBUTTON
#undef SV_DBLCLKTIME
#undef SV_CXDBLCLK
#undef SV_CYDBLCLK
#undef SV_CXSIZEBORDER
#undef SV_CYSIZEBORDER
#undef SV_ALARM
#undef SV_CURSORRATE
#undef SV_FIRSTSCROLLRATE
#undef SV_SCROLLRATE
#undef SV_NUMBEREDLISTS
#undef SV_WARNINGFREQ
#undef SV_NOTEFREQ
#undef SV_ERRORFREQ
#undef SV_WARNINGDURATION
#undef SV_NOTEDURATION
#undef SV_ERRORDURATION
#undef SV_CXSCREEN
#undef SV_CYSCREEN
#undef SV_CXVSCROLL
#undef SV_CYHSCROLL
#undef SV_CYVSCROLLARROW
#undef SV_CXHSCROLLARROW
#undef SV_CXBORDER
#undef SV_CYBORDER
#undef SV_CXDLGFRAME
#undef SV_CYDLGFRAME
#undef SV_CYTITLEBAR
#undef SV_CYVSLIDER
#undef SV_CXHSLIDER
#undef SV_CXMINMAXBUTTON
#undef SV_CYMINMAXBUTTON
#undef SV_CYMENU
#undef SV_CXFULLSCREEN
#undef SV_CYFULLSCREEN
#undef SV_CXICON
#undef SV_CYICON
#undef SV_CXPOINTER
#undef SV_CYPOINTER
#undef SV_DEBUG
#undef SV_CMOUSEBUTTONS
#undef SV_CPOINTERBUTTONS
#undef SV_POINTERLEVEL
#undef SV_CURSORLEVEL
#undef SV_TRACKRECTLEVEL
#undef SV_CTIMERS
#undef SV_MOUSEPRESENT
#undef SV_CXBYTEALIGN
#undef SV_CXALIGN
#undef SV_CYBYTEALIGN
#undef SV_CYALIGN
#undef SV_DESKTOPWORKAREAYTOP
#undef SV_DESKTOPWORKAREAYBOTTOM
#undef SV_DESKTOPWORKAREAXRIGHT
#undef SV_DESKTOPWORKAREAXLEFT
#undef SV_NOTRESERVED
#undef SV_EXTRAKEYBEEP
#undef SV_SETLIGHTS
#undef SV_INSERTMODE
#undef SV_MENUROLLDOWNDELAY
#undef SV_MENUROLLUPDELAY
#undef SV_ALTMNEMONIC
#undef SV_TASKLISTMOUSEACCESS
#undef SV_CXICONTEXTWIDTH
#undef SV_CICONTEXTLINES
#undef SV_CHORDTIME
#undef SV_CXCHORD
#undef SV_CYCHORD
#undef SV_CXMOTIONSTART
#undef SV_CYMOTIONSTART
#undef SV_BEGINDRAG
#undef SV_ENDDRAG
#undef SV_SINGLESELECT
#undef SV_OPEN
#undef SV_CONTEXTMENU
#undef SV_CONTEXTHELP
#undef SV_TEXTEDIT
#undef SV_BEGINSELECT
#undef SV_ENDSELECT
#undef SV_BEGINDRAGKB
#undef SV_ENDDRAGKB
#undef SV_SELECTKB
#undef SV_OPENKB
#undef SV_CONTEXTMENUKB
#undef SV_CONTEXTHELPKB
#undef SV_TEXTEDITKB
#undef SV_BEGINSELECTKB
#undef SV_ENDSELECTKB
#undef SV_ANIMATION
#undef SV_ANIMATIONSPEED
#undef SV_MONOICONS
#undef SV_KBDALTERED
#undef SV_PRINTSCREEN
#undef SV_LOCKSTARTINPUT
#undef SV_DYNAMICDRAG
#undef SV_CSYSVALUES
#undef WM_CTLCOLORCHANGE
#undef WM_QUERYCTLTYPE
#undef _CTLCOLOR
#undef CTLCOLOR
#undef PCTLCOLOR
#undef _PARAM
#undef PARAM
#undef NPPARAM
#undef PPARAM
#undef _PRESPARAMS
#undef PRESPARAMS
#undef NPPRESPARAMS
#undef PPRESPARAMS
#undef _TRACKINFO
#undef TRACKINFO
#undef PTRACKINFO
#undef IPT
#undef PIPT
#undef PIX
#undef LINE
#undef _FORMATRECT
#undef MLEFORMATRECT
#undef PFORMATRECT
#undef _MLECTLDATA
#undef MLECTLDATA
#undef PMLECTLDATA
#undef _MLEOVERFLOW
#undef MLEOVERFLOW
#undef POVERFLOW
#undef _MLEMARGSTRUCT
#undef MLEMARGSTRUCT
#undef PMARGSTRUCT
#undef _SEARCH
#undef MLE_SEARCHDATA
#undef PMLE_SEARCHDATA
#undef TA_NORMAL_HORIZ
#undef TA_LEFT
#undef TA_CENTER
#undef TA_RIGHT
#undef TA_STANDARD_HORIZ
#undef TA_NORMAL_VERT
#undef TA_TOP
#undef TA_HALF
#undef TA_BASE
#undef TA_BOTTOM
#undef TA_STANDARD_VERT
#undef RGN_ERROR
#undef RGN_NULL
#undef RGN_RECT
#undef RGN_COMPLEX
#undef PBUNDLE
#undef FIXED
#undef PFIXED
#undef HMF
#undef PHMF
#undef _SIZEL
#undef SIZEL
#undef PSIZEL
#undef _RGNRECT
#undef RGNRECT
#undef PRGNRECT
#undef _MATRIXLF
#undef MATRIXLF
#undef PMATRIXLF
#undef _ARCPARAMS
#undef ARCPARAMS
#undef PARCPARAMS
#undef _SIZEF
#undef SIZEF
#undef PSIZEF
#undef _POLYGON
#undef POLYGON
#undef PPOLYGON
#undef _POLYSET
#undef POLYSET
#undef PPOLYSET
#undef _GRADIENTL
#undef GRADIENTL
#undef PGRADIENTL
#undef _KERNINGPAIRS
#undef KERNINGPAIRS
#undef PKERNINGPAIRS
#undef _FACENAMEDESC
#undef FACENAMEDESC
#undef PFACENAMEDESC
#undef FFDESCS
#undef PFFDESCS
#undef _FFDESCS2
#undef FFDESCS2
#undef PFFDESCS2
#undef _LINEBUNDLE
#undef LINEBUNDLE
#undef PLINEBUNDLE
#undef _CHARBUNDLE
#undef CHARBUNDLE
#undef PCHARBUNDLE
#undef _MARKERBUNDLE
#undef MARKERBUNDLE
#undef PMARKERBUNDLE
#undef _AREABUNDLE
#undef AREABUNDLE
#undef PAREABUNDLE
#undef _IMAGEBUNDLE
#undef IMAGEBUNDLE
#undef PIMAGEBUNDLE
#undef MAKEFIXED
#undef FIXEDFRAC
#undef FIXEDINT
#undef _RGB
#undef RGB
#undef _RGB2
#undef RGB2
#undef PRGB2
#undef _BITMAPINFOHEADER
#undef BITMAPINFOHEADER
#undef PBITMAPINFOHEADER
#undef _BITMAPINFO
#undef BITMAPINFO
#undef PBITMAPINFO
#undef _BITMAPINFO2
#undef BITMAPINFO2
#undef PBITMAPINFO2
#undef _BITMAPINFOHEADER2
#undef BITMAPINFOHEADER2
#undef PBITMAPINFOHEADER2
#undef _BITMAPFILEHEADER
#undef BITMAPFILEHEADER
#undef PBITMAPFILEHEADER
#undef _BITMAPARRAYFILEHEADER
#undef BITMAPARRAYFILEHEADER
#undef PBITMAPARRAYFILEHEADER
#undef _BITMAPFILEHEADER2
#undef BITMAPFILEHEADER2
#undef PBITMAPFILEHEADER2
#undef _BITMAPARRAYFILEHEADER2
#undef BITMAPARRAYFILEHEADER2
#undef PBITMAPARRAYFILEHEADER2
#undef DM_ERROR
#undef DM_DRAW
#undef DM_RETAIN
#undef DM_DRAWANDRETAIN
#undef PDEVOPENDATA
#undef _DRIVDATA
#undef DRIVDATA
#undef PDRIVDATA
#undef _DEVOPENSTRUC
#undef DEVOPENSTRUC
#undef PDEVOPENSTRUC
#undef _ESCMODE
#undef ESCMODE
#undef PESCMODE
#undef _VIOSIZECOUNT
#undef VIOSIZECOUNT
#undef PVIOSIZECOUNT
#undef _VIOFONTCELLSIZE
#undef VIOFONTCELLSIZE
#undef PVIOFONTCELLSIZE
#undef _SFACTORS
#undef SFACTORS
#undef PSFACTORS
#undef _BANDRECT
#undef BANDRECT
#undef PBANDRECT
#undef _HCINFO
#undef HCINFO
#undef PHCINFO
#undef HSWITCH
#undef PHSWITCH
#undef HPROGRAM
#undef PHPROGRAM
#undef HINI
#undef PHINI
#undef HAPP
#undef _PRFPROFILE
#undef PRFPROFILE
#undef PPRFPROFILE
#undef PROGCATEGORY
#undef PPROGCATEGORY
#undef _HPROGARRAY
#undef HPROGARRAY
#undef PHPROGARRAY
#undef _PROGTYPE
#undef PROGTYPE
#undef PPROGTYPE
#undef _PROGTITLE
#undef PROGTITLE
#undef PPROGTITLE
#undef _PROGDETAILS
#undef PROGDETAILS
#undef PPROGDETAILS
#undef _SWCNTRL
#undef SWCNTRL
#undef PSWCNTRL
#undef _SWENTRY
#undef SWENTRY
#undef PSWENTRY
#undef _SWBLOCK
#undef SWBLOCK
#undef PSWBLOCK
#undef FDM_FILTER
#undef FDM_VALIDATE
#undef FDM_ERROR
#undef APSZ
#undef PAPSZ
#undef _FILEDLG
#undef FILEDLG
#undef PFILEDLG
#undef FNTM_FACENAMECHANGED
#undef FNTM_POINTSIZECHANGED
#undef FNTM_STYLECHANGED
#undef FNTM_COLORCHANGED
#undef FNTM_UPDATEPREVIEW
#undef FNTM_FILTERLIST
#undef _FONTDLG
#undef FONTDLG
#undef PFONTDLG
#undef _STYLECHANGE
#undef STYLECHANGE
#undef PSTYLECHANGE
#undef _SPBCDATA
#undef SPBCDATA
#undef PSPBCDATA
#undef _SLDCDATA
#undef SLDCDATA
#undef PSLDCDATA
#undef _CSBITMAPDATA
#undef CSBITMAPDATA
#undef PCSBITMAPDATA
#undef _BOOKTEXT
#undef BOOKTEXT
#undef PBOOKTEXT
#undef _NOTEBOOKBUTTON
#undef NOTEBOOKBUTTON
#undef PNOTEBOOKBUTTON
#undef _DELETENOTIFY
#undef DELETENOTIFY
#undef PDELETENOTIFY
#undef _PAGESELECTNOTIFY
#undef PAGESELECTNOTIFY
#undef PPAGESELECTNOTIFY
#undef _BOOKPAGEINFO
#undef BOOKPAGEINFO
#undef PBOOKPAGEINFO
#undef WM_DRAGFIRST
#undef WM_DRAGLAST
#undef DM_DROP
#undef DM_DRAGOVER
#undef DM_DRAGLEAVE
#undef DM_DROPHELP
#undef DM_ENDCONVERSATION
#undef DM_PRINT
#undef DM_RENDER
#undef DM_RENDERCOMPLETE
#undef DM_RENDERPREPARE
#undef DM_DRAGFILECOMPLETE
#undef DM_EMPHASIZETARGET
#undef DM_DRAGERROR
#undef DM_FILERENDERED
#undef DM_RENDERFILE
#undef DM_DRAGOVERNOTIFY
#undef DM_PRINTOBJECT
#undef DM_DISCARDOBJECT
#undef DM_DROPNOTIFY
#undef HSTR
#undef _DRAGIMAGE
#undef DRAGIMAGE
#undef PDRAGIMAGE
#undef _DRAGINFO
#undef DRAGINFO
#undef PDRAGINFO
#undef _DRAGITEM
#undef DRAGITEM
#undef PDRAGITEM
#undef _DRAGTRANSFER
#undef DRAGTRANSFER
#undef PDRAGTRANSFER
#undef _RENDERFILE
#undef RENDERFILE
#undef PRENDERFILE
#undef _VSCDATA
#undef VSCDATA
#undef PVSCDATA
#undef _VSDRAGINIT
#undef VSDRAGINIT
#undef PVSDRAGINIT
#undef _VSDRAGINFO
#undef VSDRAGINFO
#undef PVSDRAGINFO
#undef _VSTEXT
#undef VSTEXT
#undef PVSTEXT
#undef _TREEITEMDESC
#undef TREEITEMDESC
#undef PTREEITEMDESC
#undef _FIELDINFO
#undef FIELDINFO
#undef PFIELDINFO
#undef _RECORDCORE
#undef RECORDCORE
#undef PRECORDCORE
#undef _MINIRECORDCORE
#undef MINIRECORDCORE
#undef PMINIRECORDCORE
#undef _TREEMOVE
#undef TREEMOVE
#undef PTREEMOVE
#undef _CNRINFO
#undef CNRINFO
#undef PCNRINFO
#undef _GRIDSQUARE
#undef GRIDSQUARE
#undef PGRIDSQUARE
#undef _GRIDINFO
#undef GRIDINFO
#undef PGRIDINFO
#undef _CDATE
#undef CDATE
#undef PCDATE
#undef _CTIME
#undef CTIME
#undef PCTIME
#undef _CNRDRAGINIT
#undef CNRDRAGINIT
#undef PCNRDRAGINIT
#undef _FIELDINFOINSERT
#undef FIELDINFOINSERT
#undef PFIELDINFOINSERT
#undef _RECORDINSERT
#undef RECORDINSERT
#undef PRECORDINSERT
#undef _QUERYRECFROMRECT
#undef QUERYRECFROMRECT
#undef PQUERYRECFROMRECT
#undef _QUERYRECORDRECT
#undef QUERYRECORDRECT
#undef PQUERYRECORDRECT
#undef _SEARCHSTRING
#undef SEARCHSTRING
#undef PSEARCHSTRING
#undef _CNRDRAGINFO
#undef CNRDRAGINFO
#undef PCNRDRAGINFO
#undef _CNRLAZYDRAGINFO
#undef CNRLAZYDRAGINFO
#undef PCNRLAZYDRAGINFO
#undef _NOTIFYRECORDEMPHASIS
#undef NOTIFYRECORDEMPHASIS
#undef PNOTIFYRECORDEMPHASIS
#undef _NOTIFYRECORDENTER
#undef NOTIFYRECORDENTER
#undef PNOTIFYRECORDENTER
#undef _NOTIFYDELTA
#undef NOTIFYDELTA
#undef PNOTIFYDELTA
#undef _NOTIFYSCROLL
#undef NOTIFYSCROLL
#undef PNOTIFYSCROLL
#undef _CNREDITDATA
#undef CNREDITDATA
#undef PCNREDITDATA
#undef _OWNERBACKGROUND
#undef OWNERBACKGROUND
#undef POWNERBACKGROUND
#undef _CNRDRAWITEMINFO
#undef CNRDRAWITEMINFO
#undef PCNRDRAWITEMINFO
#undef _OBJCLASS
#undef OBJCLASS
#undef POBJCLASS
#undef HSPL
#undef HSTD
#undef PHSTD
#undef PQMOPENDATA
#undef SPLERR
#undef _SQPOPENDATA
#undef SQPOPENDATA
#undef PSQPOPENDATA
#undef _DRIVPROPS
#undef DRIVPROPS
#undef PDRIVPROPS
#undef _PRINTERINFO
#undef PRINTERINFO
#undef PPRINTERINFO
#undef _PRJINFO
#undef PRJINFO
#undef PPRJINFO
#undef _PRJINFO2
#undef PRJINFO2
#undef PPRJINFO2
#undef _PRJINFO3
#undef PRJINFO3
#undef PPRJINFO3
#undef _PRJINFO4
#undef PRJINFO4
#undef PPRJINFO4
#undef _PRDINFO
#undef PRDINFO
#undef PPRDINFO
#undef _PRDINFO3
#undef PRDINFO3
#undef PPRDINFO3
#undef _PRQINFO
#undef PRQINFO
#undef PPRQINFO
#undef _PRQINFO3
#undef PRQINFO3
#undef PPRQINFO3
#undef _PRQINFO6
#undef PRQINFO6
#undef PPRQINFO6
#undef _PRIDINFO
#undef PRIDINFO
#undef PPRIDINFO
#undef _PRDRIVINFO
#undef PRDRIVINFO
#undef PPRDRIVINFO
#undef _PRDRIVINFO2
#undef PRDRIVINFO2
#undef PPRDRIVINFO2
#undef _PRQPROCINFO
#undef PRQPROCINFO
#undef PPRQPROCINFO
#undef _PRPORTINFO
#undef PRPORTINFO
#undef PPRPORTINFO
#undef _PRPORTINFO1
#undef PRPORTINFO1
#undef PPRPORTINFO1
#undef _PRPORTINFO2
#undef PRPORTINFO2
#undef PPRPORTINFO2
#undef _QMJOBINFO
#undef QMJOBINFO
#undef PQMJOBINFO
#undef CTRL_PREVIOUS_ID
#undef CTRL_SEARCH_ID
#undef CTRL_PRINT_ID
#undef CTRL_INDEX_ID
#undef CTRL_CONTENTS_ID
#undef CTRL_BACK_ID
#undef CTRL_FORWARD_ID
#undef CTRL_TUTORIAL_ID
#undef CTRL_USER_ID_BASE
#undef HWND_PARENT
#undef HELPSUBTABLE
#undef PHELPSUBTABLE
#undef _ACVP
#undef ACVP
#undef PACVP
#undef _HELPTABLE
#undef HELPTABLE
#undef PHELPTABLE
#undef _HELPINIT
#undef HELPINIT
#undef PHELPINIT
#undef HDDF
#undef _FOCAMETRICS
#undef FOCAMETRICS
#undef PFOCAMETRICS
#undef _FONTFILEMETRICS
#undef FONTFILEMETRICS
#undef PFONTFILEMETRICS
#undef _FONTDEFINITIONHEADER
#undef FONTDEFINITIONHEADER
#undef PFONTDEFINITIONHEADER
#undef _FONTSIGNATURE
#undef FONTSIGNATURE
#undef PFONTSIGNATURE
#undef _ADDITIONALMETRICS
#undef ADDITIONALMETRICS
#undef PADDITIONALMETRICS
#undef _FOCAFONT
#undef FOCAFONT
#undef PFOCAFONT
#undef FOCAFONT32
#undef PFOCAFONT32
#undef HVPS
#undef PHVPS
#undef HMONITOR
#undef PHMONITOR
#undef _MONIN
#undef MONIN
#undef PMONIN
#undef _MONOUT
#undef MONOUT
#undef PMONOUT
#undef HKBD
#undef PHKBD
#undef _KBDKEYINFO
#undef KBDKEYINFO
#undef PKBDKEYINFO
#undef _KBDINFO
#undef KBDINFO
#undef PKBDINFO
#undef _KBDHWID
#undef KBDHWID
#undef PKBDHWID
#undef _KBDTRANS
#undef KBDTRANS
#undef PKBDTRANS
#undef _STRINGINBUF
#undef STRINGINBUF
#undef PSTRINGINBUF
#undef HVIO
#undef PHVIO
#undef _VIOMODEINFO
#undef VIOMODEINFO
#undef PVIOMODEINFO
#undef _VIOCONFIGINFO
#undef VIOCONFIGINFO
#undef PVIOCONFIGINFO
#undef _VIOPHYSBUF
#undef VIOPHYSBUF
#undef PVIOPHYSBUF
#undef _VIOPALSTATE
#undef VIOPALSTATE
#undef PVIOPALSTATE
#undef _VIOOVERSCAN
#undef VIOOVERSCAN
#undef PVIOOVERSCAN
#undef _VIOINTENSITY
#undef VIOINTENSITY
#undef PVIOINTENSITY
#undef _VIOCOLORREG
#undef VIOCOLORREG
#undef PVIOCOLORREG
#undef _VIOSETULINELOC
#undef VIOSETULINELOC
#undef PVIOSETULINELOC
#undef _VIOSETTARGET
#undef VIOSETTARGET
#undef PVIOSETTARGET
#undef _VIOCURSORINFO
#undef VIOCURSORINFO
#undef PVIOCURSORINFO
#undef _VIOFONTINFO
#undef VIOFONTINFO
#undef PVIOFONTINFO
#undef HMOU
#undef PHMOU
#undef _MOUEVENTINFO
#undef MOUEVENTINFO
#undef PMOUEVENTINFO
#undef _MOUQUEINFO
#undef MOUQUEINFO
#undef PMOUQUEINFO
#undef _PTRLOC
#undef PTRLOC
#undef PPTRLOC
#undef _NOPTRRECT
#undef NOPTRRECT
#undef PNOPTRRECT
#undef _PTRSHAPE
#undef PTRSHAPE
#undef PPTRSHAPE
#undef _SCALEFACT
#undef SCALEFACT
#undef PSCALEFACT
#undef _THRESHOLD
#undef THRESHOLD
#undef PTHRESHOLD
#undef _GINFOSEG
#undef GINFOSEG
#undef PGINFOSEG
#undef _LINFOSEG
#undef LINFOSEG
#undef PLINFOSEG

#endif /* __OS2WRAP2_H__ */
