# $Id: Makefile,v 1.2 2002-06-26 07:11:03 sandervl Exp $
#
# Kernel32 Testcases Toplevel Makefile.
#
# Copyright (c) 2002 knut st. osmundsen (bird@anduin.net)
#
# Project Odin Software License can be found in LICENSE.TXT
#
#


#
# Pre Setup Config.
#


#
# Include Setup.
#
PATH_ROOT=..\..\..
!include $(PATH_ROOT)\$(BUILD_SETUP_MAK)


#
# Post Setup Config
#
TARGET_MODE = EMPTY


#
# Makefiles
#
POSTMAKEFILES = \
    GetDriveType.mak \
    ConsoleCtrlHandler.mak \
    MultiByteToWideChar.mak \


#
# Include Processing Rules.
#
!include $(MAKE_INCLUDE_PROCESS)

